### ISSUE TITLE
Add a safe-local property

### ISSUE THREAD

**Issue by Malabarba** [bbatsov/projectile#1002]
Could you add the following to `projectile-globally-ignored-directories`?

    :safe (lambda (x) (not (remq t (mapcar #'stringp x)))) 

I could fork, add it myself, and make a PR, but it'll probably take you 10 sec to do it yourself. :-)

**Comment by bbatsov** [comment]
For you - always. :-)

**Comment by Malabarba** [comment]
Thanks!
