### ISSUE TITLE
projectile-project-root is called often and is slow

### ISSUE THREAD

**Issue by aaronjensen** [bbatsov/projectile#1003]
Plenty of things call `projectile-project-root` against lists of files such as `projectile-ignored-directories`, `projectile-unignored-files`, etc. Because it is called so often, it is sensitive to performance issues. 

So far, I've found at least two performance issues. The first is from:

https://github.com/bbatsov/projectile/pull/929

if the `projectile-project-root` var is not set, `file-truename` (which is slow) will be called on `dir` every time `projectile-project-root` is invoked. This can be fixed by implementing the suggestion here: https://github.com/bbatsov/projectile/pull/929#discussion_r47745040

The second is that `file-exists-p` is slow as well and is called even if the cache is hit. One solution here would be to simply omit this check. Probably an ideal fix would be something like checking the project root once at the beginning of an operation instead of once (or more) for each file in a project.

**Comment by ibrahima** [comment]
Oh man, didn't realize I introduced a performance regression :( What functions should I test to see the regression? I didn't personally experience an issue myself. But it makes sense to remove the wrapper function if that's a performance issue. I just didn't like the idea of introducing a special case for this feature when there was a projectile-project-root-files-functions list to add to.

**Comment by Silex** [comment]
Most of the performance issues are usually TRAMP related... see https://github.com/bbatsov/projectile/issues/523 for example.

**Comment by aaronjensen** [comment]
@ibrahima It's a somewhat subtle pause coming from `projectile-current-project-files`. Here's a profile from me running it a few times. This comes from a fairly small directory with a `.projectile` in it.

```
                - projectile-current-project-files               1772  41%
                 - -mapcat                                       1711  40%
                  - mapcar                                       1711  40%
                   - #<compiled 0x444f465b>                      1711  40%
                    - projectile-dir-files                       1711  40%
                     - projectile-adjust-files                   1456  34%
                      - projectile-add-unignored                  923  21%
                       - projectile-remove-ignored                456  10%
                        - projectile-ignored-directories-rel                294   6%
                         - projectile-ignored-directories                279   6%
                          - -map                                  173   4%
                           - mapcar                               173   4%
                            - projectile-expand-root                173   4%
                             - projectile-project-root                173   4%
                              + file-truename                     146   3%
                              + file-exists-p                      18   0%
                          - projectile-unignored-directories                 61   1%
                           - projectile-project-unignored-directories                 61   1%
                            - projectile-project-unignored                 61   1%
                             - projectile-expand-paths                 31   0%
                              - projectile-project-root                 31   0%
                               + file-truename                     25   0%
                               + file-exists-p                      3   0%
                             + projectile-paths-to-ensure                 18   0%
                             + projectile-files-to-ensure                 12   0%
                          + projectile-project-ignored-directories                 45   1%
                         + projectile-make-relative-to-root                 15   0%
                        + projectile-ignored-files-rel                162   3%
                       + projectile-unignored-files-rel                378   8%
                       + projectile-unignored-directories-rel                 89   2%
                      + projectile-remove-ignored                 533  12%
                     + projectile-dir-files-external                240   5%
                     + projectile-project-root                     15   0%
                 - projectile-get-project-directories                 41   0%
                  + projectile-parse-dirconfig-file                 24   0%
                  + -map                                           17   0%
                 + projectile-sort-files                           20   0%
```

directory: 

```
$ tree -a
.
├── .projectile
├── acronym
│   ├── README.md
│   ├── acronym.exs
│   └── acronym_test.exs
├── anagram
│   ├── README.md
│   ├── anagram.exs
│   └── anagram_test.exs
├── bob
│   ├── README.md
│   ├── bob.exs
│   └── bob_test.exs
├── bracket-push
│   ├── README.md
│   ├── bracket_push.exs
│   └── bracket_push_test.exs
├── hello-world
│   ├── README.md
│   ├── hello_world.exs
│   └── hello_world_test.exs
├── list-ops
│   ├── README.md
│   ├── list_ops.exs
│   └── list_ops_test.exs
├── run-length-encoding
│   ├── README.md
│   ├── rle.exs
│   └── rle_test.exs
├── sublist
│   ├── README.md
│   ├── sublist.exs
│   └── sublist_test.exs
└── word-count
    ├── README.md
    ├── word_count.exs
    └── word_count_test.exs
```

**Comment by aaronjensen** [comment]
Hmm, the lag I'm experiencing may be related to persp-mode...

**Comment by aaronjensen** [comment]
Setting `persp-set-frame-buffer-predicate` to `nil` alleviates the lag.

Since this appears to be an issue only when `persp-mode` in in play, I'll leave it up to you all to decide how you'd like to proceed. I still don't understand the interplay, or even what `persp-set-frame-buffer-predicate` actually does, but that's not a projectile issue.

It still seems like projectile is doing too much work to determine the project root as often as it does, but it doesn't appear to have a terrible effect on my machine w/o `persp-mode`

**Comment by mbunkus** [comment]
I'm experiencing very, very slow operations over tramp (even on local network) if `projectile-global-mode` is on. I'm not using `persp-mode`, but of course I'm using tons of other stuff.

I'd like to investigate a bit further myself and provide more information for you but I need some pointers. How can I profile the time it takes like @aaronjensen has done? Thanks.

**Comment by bbatsov** [comment]
@mbunkus See https://www.gnu.org/software/emacs/manual/html_node/elisp/Profiling.html

**Comment by mbunkus** [comment]
@bbatsov Thanks. At the moment I cannot reproduce it, but the underlying Emacs has just been upgraded to v25.1, too. I'll profile and look further into it if I ever get it reproduced, but until then please ignore me :)

**Comment by fommil** [comment]
I also see this is slow on Windows with Emacs 25.1 (64 bit build). Seems to be a regression in GNU Emacs' performance for `file-truename` as it's pretty snappy on 24.5 (64 bit build).

```
- redisplay_internal (C function)                                   5  50%
 - eval                                                             5  50%
  - if                                                              5  50%
   - format                                                         5  50%
    - projectile-project-name                                       5  50%
     - projectile-project-root                                      5  50%
      - cl-some                                                     5  50%
       - #<compiled 0x3fba8ad>                                      5  50%
        - file-truename                                             5  50%
         - file-truename                                            5  50%
          - file-truename                                           4  40%
           - file-truename                                          3  30%
            + file-truename                                         2  20%
```

**Comment by alexmurray** [comment]
I notice projectile caches the project name as a buffer local variable to improve performance - can this be done also for `projectile-project-root` so that it is only calculated once and stored as buffer local for futher calls to `(projectile-project-root)` etc? This would likely resolve the performance a lot.

**Comment by alexmurray** [comment]
For me the changes in #1149 make a significant difference - especially when using things like [spaceline-all-the-icons](https://github.com/domtronn/spaceline-all-the-icons.el) which likes to call `(projectile-project-root)` multiple times during each redisplay - this patch makes a noticeable improvement to responsiveness etc. Would be great if anyone else on this issue could try and test it to see if it also helps them.
