### ISSUE TITLE
projectile-go-function custom is ignored

### ISSUE THREAD

**Issue by birkenfeld** [bbatsov/projectile#1007]
## Expected behavior

Customizing `projectile-go-function` calls the given function (in my case, one that always returns nil).

## Actual behavior

`projectile-go` is always used. Advicing projectile-go to always return nil works.

## Steps to reproduce the problem

```
(defun projectile-no-go () nil)
```
Customize `projectile-go-function` to be `projectile-no-go`.

### Projectile version information

20160420.1508

### Emacs version

25.1.50.1

### Operating system

GNU/Linux

**Comment by zhaojunz** [comment]
@bbatsov 

I am seeing the error when I try to use prelude recently
projectile.el:1875:39:Warning: reference to free variable
    `projectile-go-function'

If I remove this line, the error goes away. 

> (projectile-register-project-type 'go 'projectile-go-function "go build ./..." "go test ./...")

Thanks for looking at this.
