### ISSUE TITLE
Projectile, Helm and Magit

### ISSUE THREAD

**Issue by mattford63** [bbatsov/projectile#1010]
## Expected behavior

When I switch project with `C-c p p` then select via Helm hit tab and choose F3 "open project root in vc-dir" it should switch to magit repo.

## Actual behavior

It fails with 

```
Not inside a Git repository
```

or if all ready in a project just goes to its root rather than the selected.

## Steps to reproduce the problem

See expected behaviour

## Environment & Version information

Latest Helm from packages.

### Projectile version information
```
Projectile version: 20160507.1854
```
### Emacs version
```
GNU Emacs 24.5.1 (x86_64-redhat-linux-gnu, GTK+ Version 3.18.9)
 of 2016-04-11 on buildvm-25.phx2.fedoraproject.org
```
### Operating system

Fedora 23

**Comment by bbatsov** [comment]
This should be reported here https://github.com/bbatsov/helm-projectile
