### ISSUE TITLE
Switching projects does not include the current project

### ISSUE THREAD

**Issue by mfiano** [bbatsov/projectile#1016]
## Expected behavior

The list of projects to switch to should include the current project. My workflow includes C-c p p to open other files of the current project, but this seemed to have stopped working with an update.
## Actual behavior

When switching projects from a buffer of a file whose project is tracked, the list of projects to switch to does not include the project of the file in the buffer.
## Steps to reproduce the problem

C-c p p to switch to a project, and open a file. C-c p p again, and the same project is not listed.
### Projectile version information

```
Projectile version: MELPA projectile-20160526.832
```
### Emacs version

24.5.1
### Operating system

Linux

**Comment by bbatsov** [comment]
That's intentional. The assumption is that you'd never want to select the project you're already in - you can simply cancel the command to stay in it.

**Comment by bbatsov** [comment]
> My workflow includes C-c p p to open other files of the current project

Just use `C-c p f` instead.

**Comment by lepieru** [comment]
For my part, I don't like the idea to remove the current project from the project selection buffer. I often call `projectile-switch-project` when I am already in the project I am searching for, then I tell to myself "What?… oh ok".

To make it behaves as I prefer, I do this:

```emacs-lisp
(defun projectile-relevant-known-projects () projectile-known-projects)
(defun projectile-relevant-open-projects () projectile-open-projects)
```

**It seems risky** but it works for me.

**Comment by spatz** [comment]
>I often call projectile-switch-project when I am already in the project I am searching for, then I tell to myself "What?… oh ok".

I do the same. I fixed this by advising `projectile-switch-project` and replacing `projectile--remove-current-project` with `identity`, but that is a horrible hack.

Maybe place the current project last in the list? Then it's there if you search for it but it won't be the first suggestion.
