### ISSUE TITLE
Is there a way to jump to a test named the same way but in a different directory?

### ISSUE THREAD

**Issue by blaenk** [bbatsov/projectile#1019]
I've been looking through the code but it seems like the only way to influence the test file checker only considers the file base name. I'm currently in the situation where the project I'm working on arranges tests like this:
- src/some-file.js
- test/some-file.js

Is there any way to teach projectile about this?

**Comment by jordonbiondo** [comment]
I began work on supporting ember-cli projects and ran into this same issue. The structure of ember-cli projects are well defined and the interface lends itself well to other parts of projectile, but not test-implementation jumping.

I way to override the standard suffix/prefix matching behavior with something more full featured like a configurable hook would be great.

In ember you often have structures that look like this:

```md
- app
  - user
    - model.js
  - thing
    - model.js
- test
  - user
    - model-test.js
  - thing
    - model-test.js
```

These situations cause projectile to potentially jump to the wrong test file for a given implementation file if you added `-test` suffix support for the project type.

If we can agree on an approach to solve this issue, I'd be happy to work on a PR.

**Comment by Qquanwei** [comment]
+1
