### ISSUE TITLE
How to remove a project from cache?

### ISSUE THREAD

**Issue by sweord** [bbatsov/projectile#102]
For example: there are 3 projects e:/proj1, e:/proj2 e:/proj3 in projectile's cache file.

And e:/proj3 is removed for some resean. How can I remove it form projectiles project list?

Thanks.

**Comment by jgarvin** [comment]
This invalidates the one cache but AFAICT still doesn't remove it from the list you get when you press C-c p p. At least it doesn't without my having restarted emacs. I tried running M-x projectile-cleanup-known-projects after and my project still stays in the list.

**Comment by elatomo** [comment]
At least in v. `20180116.9`, you can remove unexisting projects with `projectile-cleanup-known-projects`:
```
projectile-cleanup-known-projects is an interactive autoloaded compiled Lisp
function in ‘projectile.el’.

(projectile-cleanup-known-projects)

Remove known projects that don’t exist anymore.

[back]
```
