### ISSUE TITLE
Share functionality with project.el in Emacs core

### ISSUE THREAD

**Issue by catern** [bbatsov/projectile#1027]
Emacs 25 will have a new basic project-management feature. https://github.com/emacs-mirror/emacs/blob/master/lisp/progmodes/project.el

Perhaps projectile should try to share variables and functions with project.el, so projectile and project.el are compatible?

**Comment by bbatsov** [comment]
This might happen down the road, but in general it's super low on my todo list. The Emacs core moves at a pretty slow pace and I don't really want to couple Projectile with it, unless I have a very strong motivation to do so. (and, of course this would mean we can't support older versions of Emacs)
