### ISSUE TITLE
ack support

### ISSUE THREAD

**Issue by marcowahl** [bbatsov/projectile#1030]
Hi!

Thanks for providing projectile!

It looks like support for ack has been dismissed in projectile. Is this intentional?  Will you include ack support again?

Best regards, Marco

Projectile version: 20160714.2338

**Comment by bbatsov** [comment]
There used to be ack support back in the day, but it was removed when the Emacs ack package disappeared. In general both `pt` and `ag` are much better than `ack`, so supporting it made little sense.

**Comment by marcowahl** [comment]
Ok, thanks.
