### ISSUE TITLE
projectile-find-file doesn't acknowledge overridden ignored files when in different subdirectory

### ISSUE THREAD

**Issue by samestep** [bbatsov/projectile#1037]
## Expected behavior

`projectile-find-file` (<kbd>C-c p f</kbd>) should list files that are ignored by `.gitignore` and overridden by `.projectile` using the bang prefix.
## Actual behavior

`projectile-find-file` doesn't list overridden ignored files when they are not in a subdirectory of the current directory. Interestingly, `projectile-find-file-in-known-projects` (<kbd>C-c p F</kbd>) doesn't have this problem.
## Steps to reproduce the problem

```
$ git init foo
$ cd foo
$ mkdir bar
$ echo 'Hello, world!' > bar/baz
$ echo '/bar/' > .gitignore
$ echo '!/bar/' > .projectile
$ mkdir qux
$ cd qux
$ emacs
C-c p f
```
### Projectile version information

```
Projectile version: 20160728.52
```
### Emacs version

24.5.1
### Operating system

Ubuntu 16.04.1 LTS

**Comment by krizex** [comment]
Same issue with me.
