### ISSUE TITLE
 `Aborting an helm session running in background` error from Helm-Projectile in Win 8

### ISSUE THREAD

**Issue by stephenwan** [bbatsov/projectile#1038]
I am encountering the `Aborting an helm session running in background` error when using `helm-projectile-switch-project` to open a `git` project. I have checked the existing issues and the only one that is similar to mine is #827 . But I have followed the procedures there already, and I should have the correct `find` ready for Emacs, as shown below. I haven't done any change to `projectile-generic-command`, whose value remains `"find . -type f -print0"`. 

![image](https://cloud.githubusercontent.com/assets/2305991/17393051/c03d7dbc-5a53-11e6-821c-3034b60ab58d.png)

There is no other information shown in the `*Message*` buffer. Is there any verbose toggle that I could switch on to get more error info? Or can someone give me some hints for troubleshooting? Thanks in advance.

### Projectile version information

Projectile version: 20160728.52

### Emacs version

GNU Emacs 24.5.1 (i686-pc-mingw32)

### Operating system

Windows 8.1 Enterprise

**Comment by bbatsov** [comment]
Please, report this issue here instead https://github.com/bbatsov/helm-projectile
