### ISSUE TITLE
projectile-test-project overwrites compile command

### ISSUE THREAD

**Issue by nickenchev** [bbatsov/projectile#1039]
## Expected behaviour

setting projectile-test-project should setup a separate command for running/testing the application
## Actual behaviour

setting "make run" as my command seems to be causing the "recompile" command to run the test command
## Steps to reproduce the problem

1) run "projectile-compile-project", set your make command
2) run "projectile-test-project", set your test command
3) run "recompile" it will not have your original command from "projectile-compile-project"
### Projectile version information

20160728.52
### Emacs version

24.5.1
### Operating system

OS X 10.11.5

**Comment by bbatsov** [comment]
Well this can be considered both a bug and feature, but I see your point. Recompile simply uses whatever the final compilation command was and projectile uses compile for a lot of tasks. Guess we can restore the old compilation command in some scenarios.

**Comment by nickenchev** [comment]
Hi, I'm was about to log another issue with a similar problem, and realized I had already logged it in 2016, except it was regarding the projectile-test-project command! Hah, I guess I should THANK you first for making this awesome package since I'm still using it daily!

Anyways, I'm looking for a way to use "projectile-run-project" without overriding my "compilation" command. I use projectile-run-gdb quite a bit, but often I want to be able to rapidly just run the executable I'm building WITHOUT gdb, especially when developing for Qt which loads a ton of DLLs and is a MUCH MUCH slower startup when debugging.

I'm seeing the same issue as was originally logged, I run the "projectile-compile-project" set my cmake --build command, and then if I "projectile-run-project" the command issued there overwrites my compile command. I work around this by alt tabbing to a terminal window and running without GDB there, but I'm curious if there's something that can be done about it. I know you said it could be considered a "feature", but I think if they interfere with each-other, I'd call that more of a bug, given that compiling and running your project will always have different commands.

Is the idea here that you're always compiling and running at the same time? So the assumption would be having the same command? This wouldn't work if you want to be able to run debug/no-debug at will.
