### ISSUE TITLE
helm-projectile-ag ignores .hgignore

### ISSUE THREAD

**Issue by d9k** [bbatsov/projectile#1040]
## Expected behavior

`helm-projectile-ag` must ignore files from .hgignore as `helm-ag` does (and as `helm-projectile-find-file` perfectly does too).

## Actual behavior

It doesn't ignore files excluded at project `.hgignore`, too many false positive hits.

## Steps to reproduce the problem

fragment of my `.hgignore` file:

```
regexp:^server/node_modules/.+
regexp:^\.idea
regexp:^\.\#
```

There would be false positive results from `server/node_modules`

## Environment & Version information

ag 0.31.0 from official ubuntu repo

### Projectile version information

version 20160728.52

### Emacs version

spacemacs 0.105.21 (emacs 24.5.1)

### Operating system

Kubuntu 16.04

**Comment by syohex** [comment]
You should report this issue to [helm-projectile](https://github.com/bbatsov/helm-projectile/issues) instead of here.

And does it work well on terminal emulator ? It looks ag does not work well with `.hgignore`(https://github.com/ggreer/the_silver_searcher/issues/799)

**Comment by d9k** [comment]
@syohex, thanks for hint!
As I stated, `helm-ag` works properly.
