### ISSUE TITLE
Not ignoring .DS_Store

### ISSUE THREAD

**Issue by dieggsy** [bbatsov/projectile#1041]
## Expected behavior

If `projectile-globally-ignored-files` is set to `("TAGS" ".DS_Store")`, `.DS_Store` files should not show up.
## Actual behavior

`projectile-globally-ignored-files` is set to `("TAGS" ".DS_Store")`, `.DS_Store` files still showing up.
## Steps to reproduce the problem

I simply did:
- `M-x customize-variable [ENTER]`
- `projectile-globally-ignored-files`
- `[INS]`
- `.DS_Store`
- `[ Apply and Save]`
- Restart Emacs
- Either `M-x helm-projectile-find-file` or `M-x projectile-find-file` [ENTER]
- Start typing `.DS_Store`, and I see matches for that file.
### Projectile version information

```
Projectile version: 20160728.52
```
### Emacs version

```
Emacs 24.5.1
```
### Operating system

```
OSX 10.11.6
```
## Screenshots

(This is using helm-projectile-find-file, but the files are not ignored with projectile-find-file either.)
<img width="642" alt="screen shot 2016-08-10 at 13 35 33" src="https://cloud.githubusercontent.com/assets/9020453/17569979/62b8e874-5eff-11e6-9c17-bef703c9dcf5.png">

<img width="547" alt="screen shot 2016-08-10 at 13 32 31" src="https://cloud.githubusercontent.com/assets/9020453/17569873/ebfc4262-5efe-11e6-83fd-4e0fb7858673.png">

**Comment by therockmandolinist** [comment]
Actually, perhaps this is a misunderstanding on my part? it is ignoring the highest-level .DS_Store file, though it would seem more intuitive to me that it would ignore all files matching that name.

**Comment by CestDiego** [comment]
Bump

**Comment by bbatsov** [comment]
Obviously this can be fixed (and the fix is likely going to be easy, as @therockmandolinist noticed the gist of the problem), but I'm quite busy (+ I'm recovering from a surgery right now). PRs welcome! :-)
