### ISSUE TITLE
projectile-regenerate-tags

### ISSUE THREAD

**Issue by mambolevis** [bbatsov/projectile#1049]
The following error message is generated when executing `projectile-regenerate-tags` 
```
projectile-regenerate-tags: ctags: invalid option -- ’e’
	Try ’ctags --help’ for a complete list of options.
```
I usually generate TAGS without any problem. That is the first time this error is shown. 
```
Projectile version: 20160830.138
```

### Emacs version

Emacs 25

### Operating system

*Windows 10*

**Comment by syohex** [comment]
I suppose you used Emacs's ctags. You should use Exuberant Ctags or Universal Ctags instead of it. (You need to set PATH or remove/move Emacs' ctags).

**Comment by mambolevis** [comment]
I got it. Now it is working.
Thanks a lot.

**Comment by syohex** [comment]
Can you close this issue ?
