### ISSUE TITLE
including git submodules, error when opening files

### ISSUE THREAD

**Issue by crucialfelix** [bbatsov/projectile#105]
Hello,

I have a project that has several git submodules

I added a .projectile file at the root but  C-c p f cannot find the files in the submodules.

I then tried added them to the .projectile file:   +/nsclasses etc

Projectile now finds them, but when it opens them the path is incorrect

```
nsclasses/nsclasses/fastadder/feeds/trulia.py
```

attempts to open:

```
nsclasses/fastadder/feeds/trulia.py
```

non-existant directory, opens as read-only blank buffer, flymake fails etc.

this is perhaps because the python package root is at

```
nsclasses/__init__.py
```

and maybe its reading the TAGS file ?

is there another better way that I should be adding submodules ?

many thanks, projectile is the missing tool for me to work quickly in emacs !

**Comment by dreamersdw** [comment]
If you use git 2.11+, you can set `projectile-git-command` with  the following value
`git ls-files -z -c  --recurse-submodules`

see https://stackoverflow.com/a/40311391
