### ISSUE TITLE
`projectile-before-switch-project-hook` expected default-directory behaviour has changed

### ISSUE THREAD

**Issue by john2x** [bbatsov/projectile#1056]
## Expected behavior

When switching projects, functions that are hooked to `projectile-before-switch-project-hook` had `default-directory` set to the target directory of `project-to-switch`.

## Actual behavior

With the changes introduced by https://github.com/bbatsov/projectile/commit/78ee7e36f94c88c2f2626350be441c31f884d60f, `projectile-before-switch-project-hook`'s behavior has changed. Functions using that hook now have `default-directory` set at the current/old value.

## Steps to reproduce the problem

Using [`nameframe-projectile-mode`](https://github.com/john2x/nameframe/blob/master/nameframe-projectile.el), switching to a project will create a frame with the incorrect name (since the target directory isn't available in `projectile-before-switch-project-hook` yet).

## Comments

1. Should `projectile-before-switch-project-hook`'s behaviour be reverted? (e.g. move it inside the `with-temp-buffer` form). 
2. Or should a new hook be introduced instead (e.g. something like `projectile-before-switch-project-hook-with-target-default-directory`). (See comments in #1005)

I can prepare a PR for either.

A workaround is possible by advising `projectile-switch-project-by-name` to set the necessary variable before the hook is triggered.

e.g.
```
(defun nameframe-projectile-switch-project-by-name (projectile-switch-project-by-name &rest args)
  (let* ((nameframe-projectile--project-to-switch (car args)))
    (apply projectile-switch-project-by-name args)))

(advice-add #'projectile-switch-project-by-name :around #'nameframe-projectile-switch-project-by-name)
```

### Projectile version information

```
Projectile version: 20160926.1133
```

### Emacs version

25.1

### Operating system

OS X 10.11

**Comment by bbatsov** [comment]
> When switching projects, functions that are hooked to projectile-before-switch-project-hook had default-directory set to the target directory of project-to-switch.

This was an oversight. The new behaviour is considered by me to be the correct one. It's natural to assume that in the before hook you'd have access to the current project dir, not the target one (there's an after hook for it).

**Comment by john2x** [comment]
Ah ok, understood. I'll stick with the workaround then.
