### ISSUE TITLE
projectile-find-file no longer lists submodule files

### ISSUE THREAD

**Issue by bsuh** [bbatsov/projectile#1058]
## Expected behavior

Submodule files are listed in `projectile-find-file`

## Actual behavior

Submodule files are not listed in `projectile-find-file`

## Steps to reproduce the problem

M-x projectile-find-file
Look for submodule files

### Projectile version information

Projectile 20160926.1133

### Emacs version

25.1.1

### Operating system

OS X 10.11

**Comment by bbatsov** [comment]
This caused the breakage - https://github.com/bbatsov/projectile/pull/1045

Not sure if @IvanMalison is working on a fix or if someone is expecting me to provide the fix. :-)

**Comment by IvanMalison** [comment]
@bbatsov I'll try to have a fix by the end of the weekendurl

**Comment by ambihelical** [comment]
Why not just revert the commit if the fix is not imminent?

**Comment by IvanMalison** [comment]
@ambihelical @bbatsov  I'm inclined to agree, though I would like to fix this, since it results in a dramatic speed up for me.

Dealing with the ssh case is somewhat tricky, I wasn't aware that shell-command-to-string actually handled that properly.

**Comment by bbatsov** [comment]
Commit reverted.
