### ISSUE TITLE
projectile-find-file no longer works over TRAMP

### ISSUE THREAD

**Issue by souvik1997** [bbatsov/projectile#1059]
## Expected behavior
projectile-find-file should list files in projects over TRAMP. Might be related to #1044 and #1045.

## Actual behavior

projectile-find-file returns with the error "Searching for program: No such file or directory: /sshx:$USER@$HOST:/usr/bin/git"

## Steps to reproduce the problem

Run projectile-find-file over TRAMP.

## Environment & Version information
Emacs 25.1 on OS X 10.12. Remote host is running Ubuntu 12.04.

### Projectile version information
```
Projectile 20160926.1133
```

This worked on projectile-20160921.902.

### Emacs version

Emacs 25.1.

### Operating system
macOS 10.12

**Comment by bbatsov** [comment]
Yeah, likely the issues are related. Let's wait for @IvanMalison's fix.

**Comment by bbatsov** [comment]
The problematic commit was reverted.
