### ISSUE TITLE
Can't open file via helm-projectile-find-file on cygwin/svn/spacemacs

### ISSUE THREAD

**Issue by zsoltika** [bbatsov/projectile#1061]
## Expected behavior

Issue `helm-projectile-find-file` in an `svn` repo, hit enter on an entry --> file gets opened.

## Actual behavior

(E.g.) the following file listing gets displayed:
![example file listing](https://i.imgur.com/JQnrUqy.png)

When hitting enter on the selected line an empty file/buffer gets created, named like '`<spaces>revision number<spaces>user....` 

## Steps to reproduce the problem

Install Cygwin, cygwin emacs-w32, latest cygwin svn, latest spacemacs master, latest packages.

#### System Info :computer:
- OS: cygwin
- Emacs: 25.1.1
- Spacemacs: 0.200.0
- Spacemacs branch: master (rev. e6357a5)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm auto-completion better-defaults emacs-lisp
      (git :variables git-gutter-use-fringe t)
      markdown org
      (shell :variables shell-default-height 30 shell-default-position 'bottom)
      spell-checking version-control html sql evil-snipe deft python dash smex ranger clojure)
```

### Projectile version information

Projectile 20160926.1133

### Emacs version

E.g. 25.1.1

### Operating system

Windows 10 (x64), with cygwin.

**Comment by bbatsov** [comment]
Please, resubmit this issue here https://github.com/bbatsov/helm-projectile
