### ISSUE TITLE
Fossil checkouts on Windows are not supported.

### ISSUE THREAD

**Issue by jaccarmac** [bbatsov/projectile#1063]
## Expected behavior

Projectile adds Fossil checkouts to its list of projects.

`projectile-find-file` in a Windows fossil checkout provides a list of files tracked by the repository.

## Actual behavior

Fossil checkouts on Windows are not added to the list.

`projectile-find-file` provides a list of files, but each name has a `^M` character appended to it.

## Steps to reproduce the problem

Use Projectile in a Fossil checkout on Windows.

### Projectile version information

```
Projectile version: 20160830.138
```

### Emacs version

25.1.1

### Operating system

Windows 10

**Comment by bbatsov** [comment]
Fixed by #1064.
