### ISSUE TITLE
projectile-project-name not returning current project name when called from projectile-after-switch-project-hook

### ISSUE THREAD

**Issue by njdan5691** [bbatsov/projectile#1067]
## Expected behavior

Would think that is should return the project name chosen from list supplied by C-c p p.
## Actual behavior

When switching projects with C-c p p projectile-project-name when called from projectile-after-switch-project-hook seems to return the previous project, the first time it's invoked it returns "-".
## Steps to reproduce the problem

```
(defun my-projectile-after-hook ()
  (message (concat "project:" (projectile-project-name))))

(add-hook 'projectile-after-switch-project-hook 'my-projectile-after-hook)
```

Just use C-c p p to switch back and forth between projects
### Projectile version information

```
 projectile-20161005.847
```
### Emacs version

Built from source.

```
GNU Emacs 25.1.2 (x86_64-unknown-linux-gnu, GTK+ Version 3.14.13)
 of 2016-08-06
Copyright (C) 2016 Free Software Foundation, Inc.
```
### Operating system

Centos 7

**Comment by leemhenson** [comment]
I see the same behaviour for `projectile-project-root` also.

**Comment by art-solopov** [comment]
The issue seems to be that the `default-directory` variable isn't actually set during the `after-switch-project` hook. The "workaround" would be to change the `projectile-switch-project-action` variable.

**Comment by bbatsov** [comment]
This is the relevant code:

```
(defun projectile-switch-project-by-name (project-to-switch &optional arg)
  "Switch to project by project name PROJECT-TO-SWITCH.
Invokes the command referenced by `projectile-switch-project-action' on switch.
With a prefix ARG invokes `projectile-commander' instead of
`projectile-switch-project-action.'"
  (let ((switch-project-action (if arg
                                   'projectile-commander
                                 projectile-switch-project-action)))
    (run-hooks 'projectile-before-switch-project-hook)
    ;; use a temporary buffer to load PROJECT-TO-SWITCH's dir-locals before calling SWITCH-PROJECT-ACTION
    (with-temp-buffer
      (let ((default-directory project-to-switch))
        (hack-dir-local-variables-non-file-buffer)
        (funcall switch-project-action)))
    (run-hooks 'projectile-after-switch-project-hook)))
```

Clearly when the after hook is invoked it happens after `switch-project-action`. @art-solopov `default-directory` is updated automatically.

**Comment by bbatsov** [comment]
I see that `default-directory` is wrong for some reason at hook invocation time, but that's like some wrapping function interfering with the binding. I'll look into this.

**Comment by bbatsov** [comment]
After some debugging I saw `with-temp-buffer` was messing things up. Should be working fine now.

**Comment by kaushalmodi** [comment]
I am still seeing this issue.

**Comment by kaushalmodi** [comment]
The issue is here.. debug code:

---

```el
(defun projectile-find-file (&optional arg)
  "Jump to a project's file using completion.
With a prefix ARG invalidates the cache first."
  (interactive "P")
  (projectile-maybe-invalidate-cache arg)
  (message "new prj root: %s" (projectile-project-root))
  (message "new prj name: %s" (projectile-project-name))
  (projectile-completing-read
   "Find file: "
   (projectile-current-project-files)
   :action `(lambda (file)
              (find-file (expand-file-name file ,(projectile-project-root)))
              (run-hooks 'projectile-find-file-hook))))
```

After `projectile-switch-project`, `(projectile-project-name)` shows the older project while `(projectile-project-root)` shows the new project correctly.

Whereas for the `projectile-find-file` prompt, `projectile-prepend-project-name` is used that uses `projectile-project-name`:

```el
(defun projectile-prepend-project-name (string)
  "Prepend the current project's name to STRING."
  (format "[%s] %s" (projectile-project-name) string))
```

**Comment by kaushalmodi** [comment]
This commit is the culprit: https://github.com/bbatsov/projectile/commit/65bc11e7c9ba5743a11ad24281beaa0bafb030ef

Overriding the `projectile-project-name` definition to the older self fixes this issue:

## older working definition

```el
(defun projectile-project-name ()
  "Return project name."
  (if projectile-project-name
      projectile-project-name
    (let ((project-root
           (condition-case nil
               (projectile-project-root)
             (error nil))))
      (if project-root
          (funcall projectile-project-name-function project-root)
        "-"))))
```

**Comment by kaushalmodi** [comment]
This also fixes the issue without having to revert the `projectile-project-name` definition:

```el
(add-hook 'projectile-before-switch-project-hook #'projectile-reset-cached-project-name)
```

@bbatsov Can you please add that to projectile.el? Thanks.

**Comment by raxod502** [comment]
@kaushalmodi That solution has the side effect of messing up the project name when you switch back to the buffer you were just in.

The real problem here is that I expected each buffer to only have one project name. However, `projectile-switch-project` has special behavior in that the project name is expected to be something other than what the current buffer's actual project name is.

Furthermore, I noticed an additional bug that occurs even if we revert `projectile-project-name` entirely: once you select a new project, the project name changes in the mode line as well as the minibuffer!

I think the most sensible solution is to add an additional variable that disables the caching system, and only bind it for the duration of calling `projectile-completing-read` the second time in `projectile-switch-project`. Give me a bit and I will try to make a pull request.

**Comment by kaushalmodi** [comment]
> That solution has the side effect of messing up the project name when you switch back to the buffer you were just in.

You are right!

> Furthermore, I noticed an additional bug that occurs even if we revert projectile-project-name entirely: once you select a new project, the project name changes in the mode line as well as the minibuffer!

I do not understand the problem stated.. "once you select a new project, the project name changes in the mode line as well as the minibuffer". If you are switching the project, of course the mode line will update to the new project in that window. Also the mini buffer has to show the new project's name.

**Comment by kaushalmodi** [comment]
For now, this works fine for me:

```el
    (defun projectile-project-name-old ()
      "Return project name."
      (if projectile-project-name
          projectile-project-name
        (let ((project-root
               (condition-case nil
                   (projectile-project-root)
                 (error nil))))
          (if project-root
              (funcall projectile-project-name-function project-root)
            "-"))))
    (advice-add 'projectile-project-name :override #'projectile-project-name-old)
```

**Comment by raxod502** [comment]
So I'm in the `projectile` project, thinking about switching to the `radian` project:

![image](https://cloud.githubusercontent.com/assets/6559064/21688311/94cdc5de-d329-11e6-80ad-6e22f14b00ba.png)

Once I select that project, the prompt in the minibuffer changed to `[radian]` as desired:

![image](https://cloud.githubusercontent.com/assets/6559064/21688349/c85b589e-d329-11e6-831a-e5c1acdd6ac2.png)

However, notice that the mode line has also changed to `[radian]` *even though I'm still visiting a file in the `projectile` project*!

I don't think it ever makes sense for the file name and the project name displayed in the mode line to be inconsistent. The project name displayed in the mode line should only change once I have actually selected a file from the other project.

@kaushalmodi Your code should produce the same effect as the version in my PR. That is, they both have the bug described above, but they both fix the issue you described previously.

**Comment by kaushalmodi** [comment]
Ah! Thanks for that explanation! Turns out I do show the current project in the mode line but in a different way.. I have the `smart-mode-line` package to do that for me. I disable the project name shown by projectile: `(setq projectile-mode-line "​P")`.

Here I am in `.emacs.d` project, thinking of switching to org project.
![image](https://cloud.githubusercontent.com/assets/3578197/21688597/78f8133e-d33b-11e6-94bf-dd72a0f1e769.png)

Here I have switched to `org` project, `projectile-find-file` is listing files from the switched project, but my mode line of the buffer from previous project is unaffected.

![image](https://cloud.githubusercontent.com/assets/3578197/21688643/9e60db56-d33b-11e6-8ef3-34ebb30eceb7.png)

**Comment by raxod502** [comment]
Perhaps `smart-mode-line` updates less often than the default mode line does (that is, at least once per second and often more).

I also disable the default Projectile project name, and add it back by just calling `projectile-project-name`—I think that should have the same effect:

![image](https://cloud.githubusercontent.com/assets/6559064/21688843/8964608e-d32b-11e6-9b70-5f39b6c516c4.png)

**Comment by kaushalmodi** [comment]
SML conservatively updates `mode-line-buffer-identification`, and the calls to `(projectile-project-name)` are made only in that. So that's why it helps.

It updates `mode-line-format` for other stuff, but calls to `(projectile-project-name)` are not made in that.

**Comment by kaushalmodi** [comment]
.. that's why probably I never saw any performance impact of the having projectile in the mode line. How about moving the projectile name update out of `mode-line-format`? Then there wouldn't be a need to cache the project name. :)

**Comment by raxod502** [comment]
How would I do that? Create a separate variable that contains the last known value of `(projectile-project-name)`, use that variable in the mode line, and then update it whenever `(projectile-project-name)` might change?

That seems like pretty much the same idea as a cache. (I don't want the project name to be displayed next to `buffer-file-name`.)

**Comment by kaushalmodi** [comment]
@raxod502 Thanks. The latest commit fixes this issue for me.
