### ISSUE TITLE
D language support (jump between implementation and test files)

### ISSUE THREAD

**Issue by antoniocorbibellot** [bbatsov/projectile#1071]
## Expected behavior

Toggle between implementation and test files in a D-language project.
## Actual behavior

I get the error: "Project type not supported!"
## Steps to reproduce the problem

create a file: src/myfile.d
create a test-file for it: src/test/myfileTest.d

Then try to jump between them via "C-c p t" and you get the error reported.
## Environment & Version information

Arch Linux
Emacs 25.1
### Projectile version information

projectile 20161008.47

**Comment by cydparser** [comment]
@antoniocorbibellot what does `M-: (projectile-project-type)` output when you are in a D buffer?

**Comment by antoniocorbibellot** [comment]
It says: make
