### ISSUE TITLE
Use behavior of rgrep/ag default string for projectile-grep/ag

### ISSUE THREAD

**Issue by laz2** [bbatsov/projectile#1078]
Cursor or selection on string "hello".

_rgrep/ag minibuffer_
`Search for (default hello):` <-- Field is empty

_projectile-grep/ag minibuffer_
`[project] Search for: hello` <-- Field isn't empty

If i want search with another string i must delete old. I see only one problem with this. If i want edit default search string i can not make that action. Is this good behavior? May i provide pull request?

**Comment by laz2** [comment]
Something like this:
* Cursor on symbol "hello":
`Search for (default hello):` <-- Cann't edit default
* Selection on symbol "hello":
`Search for: hello` <-- Can edit default

**Comment by laz2** [comment]
Is this good improvement or not?

**Comment by yauhen-l** [comment]
Vote for this change

**Comment by auvn** [comment]
+1

**Comment by iced** [comment]
+1

**Comment by laz2** [comment]
Any comments from maintainers? Is this good or not?

**Comment by bbatsov** [comment]
I'm fine with changing this. PR welcome. :-)

**Comment by laz2** [comment]
PR #1083. But in PR i always add symbol at cursor or selected region to default (input is always empty like in original behavior of rgrep/ag)
