### ISSUE TITLE
how to save cache info to per-project

### ISSUE THREAD

**Issue by windrg** [bbatsov/projectile#1079]
Hi,

I'd like to know if there's a way to save cache info to each project.
e.g - save its cache info in .projectile.

Could you please give me some hints or how-to?

**Comment by bbatsov** [comment]
That's not possible right now. Why do you want to move the cache there?

**Comment by andreas-marschke** [comment]
@windrg Have a look at this issue #1101 

@bbatsov Close as dupe?
