### ISSUE TITLE
Request adding a mode-icon

### ISSUE THREAD

**Issue by eflanigan00** [bbatsov/projectile#1086]
https://github.com/ryuslash/mode-icons

I filed a request and it should be easy to add if you pick an icon
https://github.com/ryuslash/mode-icons/issues/43

**Comment by bbatsov** [comment]
Unfortunately Projectile doesn't have a logo, so I'm not really sure what can be used as an icon there. I'm fine with the idea, but I can't really contribute anything to making this a reality.
