### ISSUE TITLE
projectile violates emacs key binding convention

### ISSUE THREAD

**Issue by retroj** [bbatsov/projectile#1087]
Hello.  Projectile binds its commands under the keymap 'C-c p' by default, and I just wanted to point out that this contradicts emacs conventions at outlined in the manual:

https://www.gnu.org/software/emacs/manual/html_node/elisp/Key-Binding-Conventions.html

> Don’t define C-c letter as a key in Lisp programs. Sequences consisting of C-c and a letter (either upper or lower case) are reserved for users; they are the only sequences reserved for users, so do not block them.
>
> Changing all the Emacs major modes to respect this convention was a lot of work; abandoning this convention would make that work go to waste, and inconvenience users. Please comply with it.

**Comment by bbatsov** [comment]
I'm well aware of this and it has been done intentionally for the sake of having a simple keybinding. This is configurable and people who dislike it can easily change it (e.g. to `C-c C-p`).
