### ISSUE TITLE
Cannot set terminal process group

### ISSUE THREAD

**Issue by arichiardi** [bbatsov/projectile#1097]
## Expected behavior

It should report only file entries.

## Actual behavior

It shows the output of bash interspersed with the files.

![2016-12-20-101249_728x76_scrot](https://cloud.githubusercontent.com/assets/1724788/21362359/e5756274-c69c-11e6-8c7d-5872d3c41a21.png)

## Steps to reproduce the problem

Just clean the projectile file cache and try to find a file with `helm-projectile-find-file`.
It is not clear if this is a helm problem or a projectile problem, but it looks like helm here is only displaying info, nothing more.

### Projectile version information

Latest commit on `master`, `0.15.0snapshot`

### Emacs version

GNU Emacs 24.5.1

### Operating system

Linux

**Comment by arichiardi** [comment]
I disabled the cache with `(projectile-enable-caching . nil)` in `.dir-locals.el` and I still have the problem.

**Comment by bbatsov** [comment]
I guess you don't know what's the command being executed when the shell error occurs?

**Comment by arichiardi** [comment]
Nope, is there a way to find out?

**Comment by sergeyklay** [comment]
@arichiardi Could you test with `(setq shell-command-switch "-lc")` ?

`-i` is for interactive, and `-c` tells bash to read whatever commands follow. I propose use `-l` instead of `-i` to avoid such issues.

`-l` means invoke login shells, so that `.profile` or `.bash_profile` is read.

For more see https://emacs.stackexchange.com/q/3447/16592

**Comment by arichiardi** [comment]
Will try out, thanks for the suggestion!

**Comment by ReneFroger** [comment]
@arichiardi 
See what the value is of `shell-command-switch`?

Perhaps you have declared `(set-variable 'shell-command-switch "-ic")` in your config? If so, try to comment that out and restart Emacs?
