### ISSUE TITLE
Not understanding how to use projectile + Running M-x doesn't give me access to "projectile-save-known-projects ()"

### ISSUE THREAD

**Issue by IanQS** [bbatsov/projectile#1102]
1) I can't seem to access "projectile-save-known-projects ()" when I run M-x. I'm assuming this has to do with the lack of ```;;;###autoload``` at the top of the function in the .el file. 

How do I get around this/ save my known projects list?

2) Could I get an idea of how I should be using projectile to manage my projects? Say I have two main folders: Research_A and Research_B. 

I add them by doing ```projectile-add-known-project``` but then I'm a little lost in them. Projectile provides a way for me to navigate and search through different projects easily right?

If it helps I'm intending to run this with perspectives.el so that 1) I can create new isolated "regions" (via perspectives) , and I can easily move around within them (via projectile)

**Comment by IanQS** [comment]
NVM, I found [tuhdo's guide](http://tuhdo.github.io/helm-projectile.html) which I'm going to read through right now. If I still don't understand I'll come back

**Comment by IanQS** [comment]
Nope, doesn't help me get an intuitive understanding. I'm definitely missing something. Why do I have to change the mode(projectile-mode) to add a folder to projectile? Isn't there some sort of add folder function that I could just use?

**Comment by raxod502** [comment]
You don't "manage" your projects with Projectile. You navigate through them.

Projects are automatically detected if they are under version control, or by a number of other heuristics. You can add an empty `.projectile` file to the project to force it to be recognized.

After you have visited a file in a project (presuming `projectile-mode` is enabled), you can always switch back to that project using `C-c p p`. You can switch to a file within the current project using `C-c p f`.

`projectile-mode` is a minor mode, not a major mode. Run `C-h m`, you will see that Emacs always has many minor modes enabled. They add all sorts of functionality.

You should probably read [this documentation](https://github.com/bbatsov/projectile/blob/master/doc/usage.md).
