### ISSUE TITLE
Can projectile-grep be generalized to use completing-read?

### ISSUE THREAD

**Issue by nickmccurdy** [bbatsov/projectile#1106]
I recently switched from `helm` (and `helm-projectile`) to `ivy`. I tried out a few `projectile` commands with the completion system set to `ivy` and got most of the commands to work very consistently with what I was used to, except that `projectile-grep` waits for `RET` without using `ivy`. This completed as expected when I was using `helm-projectile`, so it seems to me like the command isn't using `completing-read` (and `helm-projectile` has its own workaround).

I apologize if I'm missing something here, but would it be technically possible to add `completing-read` support directly to `projectile-grep` as with the other commands? Also, I have tried `counsel-projectile`, though it doesn't have `git grep` support yet.

**Comment by noorul** [comment]
This is one of the reasons why I am yet to move to counsel-projectile

**Comment by nickmccurdy** [comment]
I've been using `counsel-git-grep` instead, but it would be better to support this in projectile itself for completion library agnostic support, if possible.

**Comment by noorul** [comment]
I also use counsel-git-grep :)

**Comment by bbatsov** [comment]
@nickmccurdy What should it use `completing-read` for? There are no completion candidates when you start `projectile-grep`.
