### ISSUE TITLE
File System Notification Support

### ISSUE THREAD

**Issue by nordlow** [bbatsov/projectile#1108]
Emacs has recently gained integration with file notification services such as Linux's Inotify via functions `file-notify-.*`. Projectile should use these mechanisms for detecting modifications to both file and directory content changes to trigger updates to filename and tags lists etc.

**Comment by bbatsov** [comment]
That has been on my radar for a long time, but I have almost no time for Projectile these days. Hopefully someone will tackle this down the road.
