### ISSUE TITLE
Can't ignore global extension using .projectile 

### ISSUE THREAD

**Issue by humitos** [bbatsov/projectile#1109]
## Expected behavior

Ignore all the files matching a certain extension (for example `*.json`) in the whole project.

## Actual behavior

Only the ones from the project root directory are being ignored.

## Steps to reproduce the problem

1. create the following structure

```
[00:03] humitos: test-projectile> tree .
.
├── another-sub
│   └── file3.json
├── file.json
├── file.png
└── subdirectory
    └── file2.json

2 directories, 4 files
[00:10] humitos: test-projectile>
```

2. I want to ignore _all the *.json_ files, so I add this to my `.projectile` file

```
-*.json
```

### Projectile version information

Projectile version: 0.14  19fb9fa6590e1dc49afc3c8c5bd69cff6cf743a7

### Emacs version

GNU Emacs 26.0.50.2

### Operating system

Ubuntu 16.04

----

I tried with and without the `/` but none of them work as I expect.

![projectile-issue](https://cloud.githubusercontent.com/assets/244656/22320697/99595652-e35c-11e6-971e-c76d047d7f47.png)

**Comment by humitos** [comment]
Just tried with GNU Emacs 25.1.1 from http://mirror.cedia.org.ec/gnu/emacs/emacs-25.1.tar.xz compiled by myself, and I have the same issue.

**Comment by humitos** [comment]
Seems to be related to #740

**Comment by hankook** [comment]
@humitos I had the same problem on macOS, but I solved the problem by changing the indexing-method to 'native'.

**Comment by krzysztof-magosa** [comment]
Native is extremaly slow :(

**Comment by whirm** [comment]
I'd still like to have this fixed.

**Comment by whirm** [comment]
bump
