### ISSUE TITLE
Consider change default keybinding for switch project.

### ISSUE THREAD

**Issue by proofit404** [bbatsov/projectile#1114]
Hi,

Currently we need to type `C-c p p` to switch the project and `C-c p P` to test it. Personally I run tests much more frequently than I change projects. So I think it maybe convenient to run tests with `p` and jump with `P`.

Of course I can do this in my configuration what I already did. But its always better to discus your thought with maintainers.

Regards, Artem.

**Comment by bbatsov** [comment]
I don't want to change the project switching keybinding, but I'm open to the idea of coming up with a better keybinding for testing a project.

**Comment by proofit404** [comment]
How about `C-c p .`?

**Comment by bbatsov** [comment]
I can live with this provided other users are fine with the change as well.

**Comment by proofit404** [comment]
How we can prof that? Maybe running Twitter poll will give some highlights.
