### ISSUE TITLE
`projectile-globally-ignored-directories' only ignores top level directory.

### ISSUE THREAD

**Issue by introom** [bbatsov/projectile#1119]
for a directory named "build".
only /build will be ignored, not /foobar/build

this is related to issue: #1041

**Comment by skrech** [comment]
I'm using the last build from MELPA and the bug still persists. I'm trying to ignore all the __pycache__ directories, however, I'm working on a lot of small projects and the .projectile file is not feasible solution for me (although it works).

**Comment by ambihelical** [comment]
Seems similar to #733

**Comment by vincekd** [comment]
also experiencing this issue, and adding a `.projectile` file is not an option, as it is only used when the indexing method is native, which is too slow to use on a large code base. Either allowing `.projectile` files to work in alien mode or allowing `projectile-globally-ignored-directories` to use globs would work for me.

**Comment by vincekd** [comment]
I have submitted a pull request that resolves this issue by the second method stated above.

https://github.com/bbatsov/projectile/pull/1146

**Comment by skrech** [comment]
I've added "*/__pycache__" and "*__pycache__" to projectile-globally-ignored-directories and rescan the project with C-u C-c p-f and __pycache__ folders are still showing. I'm on Windows.

**Comment by vincekd** [comment]
do `*pycache/`

**Comment by skrech** [comment]
Unfortunately, that's not working either. :/

**Comment by vincekd** [comment]
probably file a new bug with the exact steps (including versions) to replicate your issue.
