### ISSUE TITLE
Projectile freezes over SSHFS

### ISSUE THREAD

**Issue by mtnmts** [bbatsov/projectile#1120]
Hello, I'm reporting a bug which is similar to https://github.com/bbatsov/projectile/issues/657, although it was claimed fixed on the bug report and closed, it seems to be happening on latest versions.

## Expected behavior

Emacs should edit files fine over SSHFS, vim/ls/etc do respond instantly over SSHFS, the remote machine is on the same LAN, RTT < 3ms on 1GB/s Infra.

## Actual behavior

Projectile causes Emacs to work extremely slow (nearly unresponsive i would say), disabling projectile makes emacs work as fast as on a local filesystem as far as i can tell, or applying the following configuration fix suggested in the previous bugfix.
`(setq projectile-file-exists-local-cache-expire (* 5 60)))`

## Steps to reproduce the problem

Vanilla emacs & Projectile, mount an sshfs (sshfs user@server:/remote/path /local/path/to/mount), navigate there/open file with Emacs with projectile enabled, Emacs will be stuck, disable projectile, things will fly.

### Projectile version information

Projectile Version:20160830.138 (Might not be completely latest, but the bug report is wayyyy older)

### Emacs version

GNU Emacs 25.1.1 - GTK Version 3.20.9 - Compiled 2016-10-13

### Operating system

Fedora 25

_Until When_

**Comment by bbatsov** [comment]
Your projectile version is pretty old, this was finally fixed just a few months ago.

**Comment by violetbaddley** [comment]
I'm having the same issue, with Projectile version 20170309.30, in GNU Emacs 25.2.1 (x86_64-apple-darwin16.4.0, Carbon Version 157 AppKit 1504.81)

**Comment by seagle0128** [comment]
Same issue here. I did profilers, and found `projectile-root-top-down` took huge CPU resources if the files were not in a vcs or a project. It's easy to reproduce, even on local local files via tramp. e.g. using root to open `/etc/passwd` via tramp.

**Comment by RainMark** [comment]
hi guys, i am having the same problem, it is fixed by enable the cache
https://github.com/syl20bnr/spacemacs/issues/4207#issuecomment-199951764
