### ISSUE TITLE
helm-projectile-grep on windows returns nothing and displays (wrong-type-argument stringp nil)

### ISSUE THREAD

**Issue by jamiltron** [bbatsov/projectile#1123]
Hello, when running helm-projectile-grep over a project in Windows 10 I get nothing back, even when searching over very common words such as 'function' that are in unignored files.

## Expected behavior

helm-projectile-grep returns a list of all occurrences of the word 'function' in a lua project.

## Actual behavior

Nothing is returned, and once I press enter I get the following message: `Error running timer 'helm-projectile-grep-or-ack' (wrong-type-argument stringp nil)` 

## Steps to reproduce the problem

Load a project on Windows 10, place cursor over common word, type `C-c p s g`, then press enter.

### Operating System

Windows 10 Enterprise 64 bit.

### Emacs
Emacs 25.1

### Packages
helm-projectile 20170202.1000

helm 20170309.105

projectile 20170309.30

**Comment by bbatsov** [comment]
Submit this here https://github.com/bbatsov/helm-projectile
