### ISSUE TITLE
projectile-grep fails on Windows 10

### ISSUE THREAD

**Issue by jamiltron** [bbatsov/projectile#1124]
Hello, I was having an issue with helm-projectile-grep, but thought I should try removing Helm and seeing if projectile-grep was able to run without issue. When running projectile-grep over a project in Windows 10 I get the following error:

```
-*- mode: grep; default-directory: "c:/work/" -*-
Grep started at Sat Mar 11 09:18:21

find . -type d "(" -path "*/{arch}" -o -path "*/_darcs" -o -path "*/_MTN" -o -path "*/.bzr" -o -path "*/.hg" -o -path "*/.git" -o -path "*/.svn" -o -path "*/.src" -o -path "*/MCVS" -o -path "*/CVS" -o -path "*/RCS" -o -path "*/SCCS" -o -path "*/.idea" -o -path "*/.ensime_cache" -o -path "*/.eunit" -o -path "*/.git" -o -path "*/.hg" -o -path "*/.fslckout" -o -path "*/_FOSSIL_" -o -path "*/.bzr" -o -path "*/_darcs" -o -path "*/.tox" -o -path "*/.svn" -o -path "*/.stack-work" ")" -prune -o ^"^!^" -type d "(" -name "TAGS" -o -name ".#*" -o -name "*.o" -o -name "*~" -o -name "*.bin" -o -name "*.bak" -o -name "*.obj" -o -name "*.map" -o -name "*.ico" -o -name "*.pif" -o -name "*.lnk" -o -name "*.a" -o -name "*.ln" -o -name "*.blg" -o -name "*.bbl" -o -name "*.dll" -o -name "*.drv" -o -name "*.vxd" -o -name "*.386" -o -name "*.elc" -o -name "*.lof" -o -name "*.glo" -o -name "*.idx" -o -name "*.lot" -o -name "*.fmt" -o -name "*.tfm" -o -name "*.class" -o -name "*.fas" -o -name "*.lib" -o -name "*.mem" -o -name "*.x86f" -o -name "*.sparcf" -o -name "*.dfsl" -o -name "*.pfsl" -o -name "*.d64fsl" -o -name "*.p64fsl" -o -name "*.lx64fsl" -o -name "*.lx32fsl" -o -name "*.dx64fsl" -o -name "*.dx32fsl" -o -name "*.fx64fsl" -o -name "*.fx32fsl" -o -name "*.sx64fsl" -o -name "*.sx32fsl" -o -name "*.wx64fsl" -o -name "*.wx32fsl" -o -name "*.fasl" -o -name "*.ufsl" -o -name "*.fsl" -o -name "*.dxl" -o -name "*.lo" -o -name "*.la" -o -name "*.gmo" -o -name "*.mo" -o -name "*.toc" -o -name "*.aux" -o -name "*.cp" -o -name "*.fn" -o -name "*.ky" -o -name "*.pg" -o -name "*.tp" -o -name "*.vr" -o -name "*.cps" -o -name "*.fns" -o -name "*.kys" -o -name "*.pgs" -o -name "*.tps" -o -name "*.vrs" -o -name "*.pyc" -o -name "*.pyo" ")" -prune -o  -type f "(" -iname "*" -o -iname ".*" ")" -exec grep -i -n "function" {} NUL ";"
FIND: Parameter format not correct

Grep exited abnormally with code 2 at Sat Mar 11 09:18:21
```

## Expected behavior

projectile-grep returns a list of all occurrences of the word 'function' in a lua project.

## Actual behavior

`Grep exited abnormally with code 2` proceeding the above error.

## Steps to reproduce the problem

Load a project on Windows 10, place cursor over common word, type C-c p s g, then press enter.

### Operating System

Windows 10 Enterprise 64 bit.

### Emacs

Emacs 25.1

### Packages

projectile 20170309.30

**Comment by jamiltron** [comment]
I should add that I have tried this with grep installed from GnuWin32 as well as grep from MinGW32, both fail with the same message.

**Comment by bbatsov** [comment]
Likely the grep command generated by Emacs is not compatible with the whatever version of `grep` you see to have. There's not much we can do about this - I'd suggest trying something like `pt` on Windows - it should work better than grep.

**Comment by tenpn** [comment]
is there a way to configure custom searchers like pt? I know ag and grep are bound by default.

**Comment by tenpn** [comment]
Oh just stumbled across projectile-pt. I'll rebind that over C-p p g.

**Comment by tenpn** [comment]
so steps:
- in a console, `choco install pt`
- in emacs,` package-install pt`
