### ISSUE TITLE
Projectile doesn't recognize it is in java project.

### ISSUE THREAD

**Issue by AnthonyJacob** [bbatsov/projectile#1126]
Projectile doesn't recognize it is in java project.

I am using the latest emacs and spacemacs.

**Comment by bbatsov** [comment]
What type of Java project?

**Comment by AnthonyJacob** [comment]
It doesn't contain anything apart from 

lib/library.jar
src/a/b/c/Main.java
src/a/b/d/Utils.java

**Comment by andreas-marschke** [comment]
You can remediate this by defining your own project type in your init.el using `projectile-register-project-type` have a look at the already defined list of project types in projectile.el fof some inspiration of how to do this.

**Comment by bbatsov** [comment]
Yep. Or you can just add `.projectile` to get some basic functionality working there. Not much more we can do about this - Projectile expects Java projects to have certain structure which this one simply doesn't.
