### ISSUE TITLE
projectile-find-file does not recognize git

### ISSUE THREAD

**Issue by duane** [bbatsov/projectile#1133]
## Expected behavior

`C-c p f` should open the `projectile-find-file` buffer.

## Actual behavior

It prints `fatal: Not a git repository (or any of the parent directories): .git`.

This happens, strangely, ONLY when inside of a git repository.

## Steps to reproduce the problem

To be honest, I'm not entirely sure how to replicate this problem reliably when not on my machine. I'm looking to debug the existing issue.

### Projectile version information

Projectile version: 20170106.606

### Emacs version

25.1.91.1

### Operating system

macOS 10.12.4

**Comment by ibeling** [comment]
I still have this problem, on ssh servers. @duane did you manage to solve it?
