### ISSUE TITLE
Pin projectile project? No auto-switching based on current buffer

### ISSUE THREAD

**Issue by habemus-papadum** [bbatsov/projectile#1143]
Hello, Is it possible to pin the projectile project to a specific directory and not have it auto switch based on the current buffer?  I have some use cases in which I am navigating into various locations, potentially via symlinks but I then want project-find-files, etc to work w/ respect to my original project regardless of whether the current buffer happens to be contained in different project-like folder.  Hope that is clear. 

Thanks, nehal

**Comment by raxod502** [comment]
This would be a nice feature. Note though that you may be able to achieve the same effect with regard to symlinks by not telling Emacs to follow them when finding a file. See `find-file-visit-truename`.

**Comment by cody-addison** [comment]
I would like to also request this feature. I common use case for me is to edit code, compile, then use eshell to run tests which exist outside the project. I think a good strategy would have a mode that doesn't change the project if the current buffer isn't associated with a project.
