### ISSUE TITLE
Deleted files are still shown in projectile-find-file

### ISSUE THREAD

**Issue by raxod502** [bbatsov/projectile#1148]
## Expected behavior

Suppose that I have a Git repository with some files committed to it. When I delete one of those files in my working directory, it should no longer show up in `projectile-find-file`.

## Actual behavior

All files in Git's index are shown in `projectile-find-file`. When I have renamed a file, this causes both the old path and the new path to show up in `projectile-find-file`. If the old path is listed earlier than the new path, this causes me to inadvertently re-create a file at the old path.

## Steps to reproduce the problem

```
$ mkdir example-git-repo
$ cd example-git-repo
$ git init
$ touch existing-file nonexistent-file
$ git add existing-file nonexistent-file
$ git commit -m "Add two files"
$ rm nonexistent-file
$ emacs -Q
M-x projectile-find-file
```

Observe that both `existing-file` and `nonexistent-file` are listed, whereas only `existing-file` should be listed.

```
$ git add nonexistent-file
$ emacs -Q
M-x projectile-find-file
```

Observe that `nonexistent-file` is no longer listed if its deletion is added to the index.

## Cause

This is because Projectile uses `git ls-files` in `projectile-git-command`, and `git ls-files` shows files in the index, not files in the working directory.

### Projectile version information

Revision 56e262dd3b5998d0dc6a590d06bc11058839c588, version 0.15.0snapshot.

### Emacs version

GNU Emacs 25.2.1 from `brew cask install emacs`.

### Operating system

```
                -/+:.           
               :++++.           
              /+++/.            OS: macOS Sierra 10.12.5 16F73 x86_64
      .:-::- .+/:-``.::-        Model: MacBookPro11,4
   .:/++++++/::::/++++++/:`     Kernel: 16.6.0
 .:///////////////////////:`    Uptime: 2 days, 8 hours, 4 mins
 ////////////////////////`      Packages: 203
-+++++++++++++++++++++++`       Shell: zsh 5.3.1
/++++++++++++++++++++++/        Resolution: 1440x900
/sssssssssssssssssssssss.       DE: Aqua
:ssssssssssssssssssssssss-      WM: Quartz Compositor
 osssssssssssssssssssssssso/`   Terminal: iTerm2
 `syyyyyyyyyyyyyyyyyyyyyyyy+`   Terminal Font: InputMono-Medium 12
  `ossssssssssssssssssssss/     CPU: Intel i7-4980HQ (8) @ 2.80GHz
    :ooooooooooooooooooo+.      GPU: Intel Iris Pro
     `:+oo+/:-..-:/+o+/-        Memory: 3607MiB / 16384MiB
```

**Comment by lfender6445** [comment]
Try `M-x projectile-invalidate-cache` to clear out deleted files

**Comment by raxod502** [comment]
@lfender6445 This makes no difference.

**Comment by vyorkin** [comment]
same problem, `projectile-invalidate-cache` doesn't help, restarting emacs doesn't help too,
the file disappears when I stage it with git (I mean `git add`)

**Comment by wladyslaws** [comment]
you have to do both, i.e. stage deletion with git along with cache invalidation afterwards

**Comment by raxod502** [comment]
This is not true, as far as I can tell from the tests I just did. If you haven't staged the deletion, then invalidating the cache does nothing—the file will be shown regardless. If you _have_ staged the deletion, then invalidating the cache also does nothing—the file will not be shown regardless.

**Comment by Andsbf** [comment]
commenting here just to keep track of it!

**Comment by raxod502** [comment]
@Andsbf There is a "subscribe to notifications" button that you can use to follow an issue without commenting.

**Comment by mmcnl** [comment]
Just confirming that this issue is still reproducible with the current version of projectile. As I (like the original poster) find the current behavior confusing, I'm curious if anyone has found any workaround?

**Comment by renatofdds** [comment]
This is still reproducible. I just found out about it using ```Projectile 2.1.0snapshot```. In the meantime as a workaround i set ```projectile-git-command``` to ```comm -23 <(git ls-files -co --exclude-standard | sort) <(git ls-files -d | sort) | tr '\n' '\0'```

**Comment by tagirb** [comment]
My workaround was to replace `git ls-files` with `fd`:
```
(setq projectile-git-command "fd . -0 --type f --hidden --color=never")
```
and also creating `~/.fdignore`:
```
**/.git/
```

**Comment by raxod502** [comment]
To my knowledge this is still a bug.

**Comment by raxod502** [comment]
Unless I am mistaken, nothing has changed with regard to this bug.

**Comment by bbatsov** [comment]
> This is because Projectile uses git ls-files in projectile-git-command, and git ls-files shows files in the index, not files in the working directory.

Yeah, that's true. 

Seems to me the simplest way to solve this would be to adjust the command in question, although I'm not sure what would be the optimal replacement.

**Comment by raxod502** [comment]
Relying on software such as `fd` might be an option, as suggested in https://github.com/bbatsov/projectile/issues/1148#issuecomment-555505464. I am not terribly familiar with the ecosystem of options, but I think it is likely that something suitable may exist.

**Comment by nilbacardit26** [comment]
Maybe that is a bit of track nowadays, but cleaning the tree by pushing the deleted files to git and then invalidating the cache solved the issue for me

**Comment by raxod502** [comment]
Correct, https://github.com/bbatsov/projectile/issues/1148#issuecomment-413901500 is still the best workaround.

**Comment by sergeyklay** [comment]
I found https://github.com/bbatsov/projectile/issues/1148#issuecomment-515270488 a suitable workaround for both Linux and macOS.

**Comment by raxod502** [comment]
Filed https://github.com/bbatsov/projectile/pull/1825 to solve this issue, and implemented https://github.com/radian-software/radian/commit/75e343469fbdb059ed39bbb80a2b019e93fa6890 to patch it in my Emacs configuration.
