### ISSUE TITLE
Add run, test-suffix, and test-prefix keys to included project types

### ISSUE THREAD

**Issue by nickmccurdy** [bbatsov/projectile#1155]
The built in project types only include the required arguments, build commands, and test commands. It would be useful to set more of these keys for as many project types as possible in a way that isn't too arbitrary.

**Comment by bbatsov** [comment]
Absolutely! I think this was discussed in the past as well. Should be trivial to add. PR welcome!

**Comment by miguelbernadi** [comment]
Isn't this already supported? https://www.projectile.mx/en/latest/projects/#adding-custom-project-types If so, the issue should be closed.
