### ISSUE TITLE
"you're not in a project" via the shell

### ISSUE THREAD

**Issue by fdr** [bbatsov/projectile#1157]
## Expected behavior

If I "cd" into a project directory, I was able to use projectile. I updated and this broke. Regrettably I do not know the old version, but I updated via `el-get` not long ago to try to get a fix for this bug in handling `.agignore` and it was not yet upstream: https://github.com/bbatsov/projectile/issues/987

## Actual behavior

Now, I get the `projectile-project-root: You’re not in a project` message.

## Steps to reproduce the problem

1. Start emacs
2. Use M-x shell
3. `cd` to a git repository
4. Attempt to use projectile search (or anything)

### Projectile version information

```
Projectile version: 0.15.0snapshot
```

### Emacs version

25.2.1

### Operating system

Fedora 26

**Comment by jellelicht** [comment]
This is also the case when using eshell

**Comment by bbatsov** [comment]
Seems we fixed this, but we forgot to close it.
