### ISSUE TITLE
projectile-find-file-in-directory issues

### ISSUE THREAD

**Issue by blaenk** [bbatsov/projectile#1158]
1. If the operation is canceled with C-g, `projectile-completing-read` yields `nil` which is then fed to `expand-file-name` which then emits a wrong type argument error.
2. The illusion of "being in" the target directory is broken by `projectile-cached-project-root`. If I call `projectile-find-file-in-directory` with some other projectile project A as the target directory, _from_ yet another projectile B directory, the illusion breaks down because asking for the projectile root yields B.

I was able to fix these things externally like so:

``` elisp
(defun my-edit-dots ()
  (interactive)
  (ignore-errors
    (let* ((target (getenv "DOTSPATH"))
           (projectile-cached-project-root target))
      (projectile-find-file-in-directory target))))
```

**Comment by bbatsov** [comment]
> The illusion of "being in" the target directory is broken by projectile-cached-project-root. If I call projectile-find-file-in-directory with some other projectile project A as the target directory, from yet another projectile B directory, the illusion breaks down because asking for the projectile root yields B.

This was removed in Projectile 1.1, btw. 

> If the operation is canceled with C-g, projectile-completing-read yields nil which is then fed to expand-file-name which then emits a wrong type argument error.

Yep, I guess we need to add some nil check there.
