### ISSUE TITLE
Can projectile-ag be configured to search multiple directories?

### ISSUE THREAD

**Issue by vonHabsi** [bbatsov/projectile#1161]
Can projectile-ag or projectile-grep search multiple directories?

I want to be able to search in mutliple projects whether any of them is open or not, similar to the way `projectile-find-file-in-known-projects` works.

There is a reddit discussion on it at - https://www.reddit.com/r/emacs/comments/6sl56y/how_can_projectileag_or_agproject_be_made_to/

**Comment by bbatsov** [comment]
Currently we don't have this, but it'd be trivial to implement.
