### ISSUE TITLE
Enabling flycheck in Org-mode when doing C-c ' is only possible when leaving projectile-require-project-root alone

### ISSUE THREAD

**Issue by hisnawi** [bbatsov/projectile#1163]
This is piggybacking on this issue:

https://github.com/flycheck/flycheck/issues/1301

Is there an explanation to why this would happen?

**Comment by hisnawi** [comment]
Any updates on this?

**Comment by bbatsov** [comment]
I'm not an org-mode user, so I don't really know what `C-c '` does to begin with (or is this something to do with `flycheck`?). I can't imagine interactions between projectile and some syntax checker, so some more details would be useful.

**Comment by hisnawi** [comment]
In org-mode C-' takes you to an org-src buffer where you can edit code, flycheck takes effect and shows the errors. When that projectile variable is set to nil flycheck start showing weird errors. When the variable is not touched flycheck doesn't do anything. But what I just noticed that flycheck doesn't even show errors. So I opted to just disable flycheck in org-mode files all together.
