### ISSUE TITLE
Cached values shouldn't be used when buffer-file-name nil (eg shell mode)

### ISSUE THREAD

**Issue by guillaumekoenig** [bbatsov/projectile#1171]
## Expected behavior
While cd'ing into different projects in shell mode, I expect C-c p p, C-c p f to show the name of the project I am currently into, along with its file (for the f binding).

## Actual behavior
Some other project name/files are displayed. They are the cached values of projectile-cached-buffer-file-name and projectile-cached-project-root. These were set the first time projectile bindings were issued in a project in that shell buffer, and not recomputed since (especially after cd'ing into a different project).

## Steps to reproduce the problem
Open shell buffer. cd into a project. First time name and files should match project cd'ed into. Now cd into a different project. Name and files reported by projectile are that of the first project and not that of the project newly cd'ed into.

### Projectile version information
```
Projectile 20170727.2351
```

### Proposed patch
Only use cached values if non nil (otherwise they match shell buffer's buffer-file-name nil value) :
```
--- a/projectile.el
+++ b/projectile.el
@@ -883,7 +883,8 @@
   ;; cl-subst to replace this 'none value with nil so a nil value is used
   ;; instead
   (or (cl-subst nil 'none
-                (or (and (equal projectile-cached-buffer-file-name buffer-file-name)
+                (or (and projectile-cached-buffer-file-name
+                         (equal projectile-cached-buffer-file-name buffer-file-name)
                          projectile-cached-project-root)
                     (progn
                       (setq projectile-cached-buffer-file-name buffer-file-name)
@@ -962,7 +963,8 @@
 (defun projectile-project-name ()
   "Return project name."
   (or projectile-project-name
-      (and (equal projectile-cached-buffer-file-name buffer-file-name)
+      (and projectile-cached-buffer-file-name
+           (equal projectile-cached-buffer-file-name buffer-file-name)
            projectile-cached-project-name)
       (progn
         (setq projectile-cached-buffer-file-name buffer-file-name)
```

**Comment by jellelicht** [comment]
This seems to be the issue reported at #1157
