### ISSUE TITLE
per-project-type configuration

### ISSUE THREAD

**Issue by Pitometsu** [bbatsov/projectile#1180]
E.g. I want to change `projectile-tags-command` for `haskell-stack` and `haskell-cabal` project types.

Now I just add to `haskell-mode-hook`

```elisp
  (eval-after-load 'projectile
    '(progn
       (setq-local projectile-tags-command "haskdogs")))

```

Is there any more convenient way to do it (not per-mode or per-project, but per project-type)?

**Comment by matthewbauer** [comment]
I've wanted something similar to this (that would work in any buffer with that project type). This is the closest I've come up with:

```
(add-hook 'projectile-mode-hook
          (lambda ()
            (when (and (not noninteractive)
                       (not (eq (aref (buffer-name) 0) ?\s))
                       (not (file-remote-p default-directory))
                       projectile-mode
                       (projectile-project-p)
                       (eq (projectile-project-type) 'my-project-type))
              (my-function))))
```

That will at least ensure you are being run in the right context (projectile-project-type can cause issues if run in connection buffers). Might be nice to have a true project type specific hook though.

**Comment by bbatsov** [comment]
The recommended way to do such changes is via `.dir-locals.el` https://www.gnu.org/software/emacs/manual/html_node/emacs/Directory-Variables.html
