### ISSUE TITLE
redisplay error on staring emacs 

### ISSUE THREAD

**Issue by kirk86** [bbatsov/projectile#1181]
Hi, I have emacs running using prelude and projectile. After the last update of packages I keep getting the following annoying error.

```
Error during redisplay: (eval (format " Projectile[%s(%s)]" (projectile-project-name) (projectile-project-type))) signaled (error "You’re not in a project") $
```

The only thing that I've done is updated the packages to its latest stable from melpa, restarted emacs and keep getting this annoying error.

Any ideas o hints how to avoid this? Thanks!

### Projectile version information
```
Projectile 20171008.135
```

### Emacs version

* 25.2

**Comment by gergelypolonkai** [comment]
I have this, too. My messages buffer is spammed with this error (luckily it gets compacted on 25.2).

This also seems to introduce noticeable delays in Termux (haven’t noticed it on my really strong desktop machine.)

**Comment by bbatsov** [comment]
Ops. I'll fix this right away.

**Comment by kirk86** [comment]
@bbatsov Thank you for fixing that error message! Have you experienced any unresponsive behaviour when `projectile-mode` is on and you're working on a remote file via tramp.
I experience this unresponsive behaviour in scrolling up and down in the file while editing via tramp and `projectile-mode` is on. Whenever I disable `projectile-mode` everything seems to be pretty responsive and there's no slug?
