### ISSUE TITLE
Build Tool Support

### ISSUE THREAD

**Issue by nordlow** [bbatsov/projectile#1185]
Are there any plans on generic build system/tool support for Projectile?

My interest is mainly in system languages such as D (via dub) and Rust (via cargo).

Feature list:

- automatically detect D build roots based on `dub.sdl` or `dub.json` and Rust build roots via `Cargo.toml`.
- standard key-command for building current project using automatic build tool detection (other than make).

If not I would like to contribute this. Where variables are of use in this context?

**Comment by myrgy** [comment]
Nice proposal, but Im intrtested in c++ support.
What if we will be able to keep some value in dir-locals or have some autodetect functions - like if some file is present -then use this build sydtem. Id like to be able to replace/extend make, test and run with some user-defined extensions for the given project type.

**Comment by jethrokuan** [comment]
Issue is a little stale, but does this not do what you want?

https://github.com/bbatsov/projectile/blob/master/projectile.el#L2329-L2331

**Comment by myrgy** [comment]
This thing is good, but I would like to have api to perform some project configuration, for example have debug/release build.
Does this `projectile-register-project-type` api support functions ?

**Comment by bbatsov** [comment]
Yes, it does. I guess we can close this.

**Comment by nordlow** [comment]
If I have a .git repo with sub-trees each containing a build spec such as dub.sdl/json or Cargo.toml, how does that affect Projectile? Does Projectile regard each sub-tree as a separate project or the whole repo as a project?
