### ISSUE TITLE
Bash errors are shown as file names when projectile-find-file is used

### ISSUE THREAD

**Issue by novakboskov** [bbatsov/projectile#1195]
## Expected behavior
Bash errors should not be shown as file names.

## Actual behavior
Bash errors are shown as file names under following settings:
```elisp
(setq shell-file-name "bash")
(setq shell-command-switch "-ic")
```

## Steps to reproduce the problem
- set two variables as they are given upward
- get into a project
- try `projectile-find-file`

### Projectile version information
```
Projectile version: Projectile 20171109.240
```

### Emacs version

GNU Emacs 25.3.1 (x86_64-pc-linux-gnu, GTK+ Version 3.22.19) of 2017-09-16

### Operating system

Arch Linux thinkpad 4.9.61-1-lts #1 SMP Wed Nov 8 17:49:38 CET 2017 x86_64 GNU/Linux

**Comment by valignatev** [comment]
I'm not sure if it should fall here, or be a separate issue: `projectile-find-file` seems to trying local shell in TRAMP buffers, and as a result showing something like `/bin/sh: 693: /usr/bin/fish: not found` as a file name.

For additional info, I didn't customize my `shell-file-name`, emacs took it from system's environment.
