### ISSUE TITLE
Search untracked files with git grep

### ISSUE THREAD

**Issue by hinrik** [bbatsov/projectile#1201]
It would be great if Projectile passed the `--untracked` option to `git grep` when searching. This would find more results (e.g. in newly created files that are a work-in-progress) and would more closely match the results returned by `ag` and `ack` (while still respecting `.gitignore`).

If not by default, then at least having e.g. a `projectile-git-grep-search-untracked` option would be helpful.

**Comment by bbatsov** [comment]
Btw, don't we won't to do this for other git commands as well? E.g. `ls-files`.

**Comment by hinrik** [comment]
That would make `projectile-git-command` inconsistent with `projectile-hg-command`, because `hg locate` doesn't have an option to list untracked files. Probably some of the other VCSs are also missing this option.

Most of my projects use Git and `git grep` has been good enough for me (faster than GNU `grep` due to respecting `.gitignore`), therefore I rarely have `ag` or `ack` installed. However its usefulness in Projectile is limited compared to `ag` or `ack` if it won't search untracked files.

**Comment by bbatsov** [comment]
Got it. Well, I'd certainly accept a PR implementing your suggestion. I see no harm in it.
