### ISSUE TITLE
[Feature request] import projects

### ISSUE THREAD

**Issue by ghost** [bbatsov/projectile#1202]
Add the ability to import projects from:
- An archive
- A version control system (git, hg, etc)
- A folder, with TRAMP support

When a project is imported, open its root folder in dired and his README file if it's exist. With the ability to customize this behaviour.

When importing project from some on-line services (like Github, GNU, Gnome, etc), you can use a shorten url. For exemple `gh:bbatsov/projectile` instead of `https://github.com/bbatsov/projectile`. With the possibility to define your own shorten URL. Useful if you work with projects stored at your own server(s).

It would be nice. ;)

**Comment by bbatsov** [comment]
Hmm, that's an interesting idea. Not sure if I'll have time to work on something like this any time soon, but I'll entertain a PR for it if someone's willing to provide one.

**Comment by bbatsov** [comment]
There hasn't been much activity on this ticket and our Core Team is spread too thin on so many tasks, so I'll just close it for the sake of having a cleaner lists of tasks to focus on. We'd gladly review a PR, but it's unlikely that'd we're going to tackle this ourselves in the foreseeable future.
