### ISSUE TITLE
[Feature request] search and import projects

### ISSUE THREAD

**Issue by ghost** [bbatsov/projectile#1203]
#This feature request depend on the feature request [#1202](https://github.com/bbatsov/projectile/issues/1202).

Add the ability to search a project on some known on-line services and communities. With the ability to define your own "projects provider". Useful if you work with projects stored at your own server(s).

Users should be able to search according to several criteria:
- Project name
- Owner name
- Description
- Language

After searching a project, all found results are shown on a buffer and user can choose one or many project to import. Then Projectile import the selected project(s) like on the feature request [#1202](https://github.com/bbatsov/projectile/issues/1202).

Services and communities it would be cool to support:
- Github
- Gitlab
- GNU Savannah
- git.kernel.org
- Gnome
- KDE

It would be nice. ;)

**Comment by bbatsov** [comment]
There hasn't been much activity on this ticket and our Core Team (aka me) is spread too thin on so many tasks, so I'll just close it for the sake of having a cleaner lists of tasks to focus on. I'd gladly review a PR, but it's unlikely that'd we're going to tackle this ourselves in the foreseeable future.
