### ISSUE TITLE
Match Perl module names as paths

### ISSUE THREAD

**Issue by benlind** [bbatsov/projectile#1206]
When running `M-x projectile-find-file Some::Perl::Module`:

## Expected behavior

Projectile matches lib/Some/Perl/Module.pm

## Actual behavior

Projectile thinks I mean a literal file named `Some::Perl::Module` in the current directory.

### Projectile version information

```
Projectile 20171126.6
```

### Emacs version

```
GNU Emacs 25.3.1 (x86_64-redhat-linux-gnu, GTK+ Version 2.24.23)
```

### Operating system

```
Linux 2.6.32-696.10.3.el6.x86_64
```

**Comment by bbatsov** [comment]
Why not simply use `Module.pm` as the search string? That's generally the idea with Projectile (to type as little as possible).

**Comment by benlind** [comment]
@bbatsov because often I am pasting the full module name from elsewhere.

**Comment by bbatsov** [comment]
Got it. Such project-specific transformations are currently outside the scope of the project. I don't want to hardcode something just for Perl and making this generic will be pretty complex.
