### ISSUE TITLE
projectile-replace-regexp search removed file then failed

### ISSUE THREAD

**Issue by Whiothes** [bbatsov/projectile#1210]
## Expected behavior
replace string match pattern in project's source files
### Message
*next-file: Opening input file: No such file or directory, removed file*

## Steps to reproduce the problem
```
projectile-replace-regexp

regexp string

Scanning file ...
Scanning file ...
Scanning file …
Scanning file ...
next-file: Opening input file: No such file or directory, show removed file path.

rm ~/.emacs.d/.cache/projectile*

Redo
 ```

### Projectile version information
```
Projectile 20171229.1155
```

### Emacs version
*GNU Emacs 25.3.1 (x86_64-apple-darwin13.4.0, NS appkit-1265.21 Version 10.9.5 (Build 13F1911))
 of 2017-09-13*

### Operating system
*OSX 10.13.2*

**Comment by lippirk** [comment]
i am having this issue - 
for me, i'm hitting a symbolic link and then it abandons the renaming process

is there a way i can continue searching through other files after i hit a missing file / symbolic link?

**Comment by Whiothes** [comment]
I found that I got this issue because I still have the file in git repository. 
so, `git rm filepath` is OK
