### ISSUE TITLE
projectile-project-root slow in non-file-backed buffers

### ISSUE THREAD

**Issue by aaronjensen** [bbatsov/projectile#1212]
## Expected behavior

org-capture buffers don't have a `buffer-file-name`, so I'm not sure exactly what `projectile-project-root` needs to do, but it's slow and for some reason spaceline/company-mode call it way too often, so it can make typing laggy.

## Actual behavior

It should be fast, should it just short circuit to nil? When I wrap the body of `projectile-project-root` in a `(when buffer-file-name ...)` it's fast...

## Steps to reproduce the problem

Compare `(benchmark 1000 '(projectile-project-root))` in a file backed buffer to a non-file-backed buffer

```
            - projectile-project-p                                348  13%
             - projectile-project-root                            348  13%
              - cl-some                                           347  13%
               - #<compiled 0x51a9b0a1>                           347  13%
                - projectile-root-bottom-up                       168   6%
                 - cl-some                                        168   6%
                  - #<compiled 0x510a33c1>                        168   6%
                   - projectile-locate-dominating-file                168   6%
                      projectile-file-exists-p                    144   5%
                      abbreviate-file-name                         21   0%
                - file-truename                                   106   4%
                 - file-truename                                   65   2%
                  - file-truename                                  47   1%
                   - file-truename                                 29   1%
                      file-truename                                 9   0%
                - projectile-root-top-down-recurring                 72   2%
                 + cl-some                                         72   2%
                + projectile-root-top-down                          1   0%
                file-remote-p                                       1   0%

```

### Projectile version information

*Include here the version string displayed by `M-x
projectile-version`. Here's an example:*

```
Projectile 20180118.745
```

### Emacs version

26.0.91

### Operating system

macOS 10.13.2

**Comment by aaronjensen** [comment]
I'm using this for now which probably breaks some things:

```elisp
  (with-eval-after-load 'projectile
    (advice-add 'projectile-project-root :before-while 'buffer-file-name))
```

**Comment by bbatsov** [comment]
PRs welcome. IMO in such cases we should just use the `default-directory` of the current buffer. And I actually thought we were doing this, but I don't have time to check the code right now.

**Comment by aaronjensen** [comment]
@bbatsov Yes, it does start in the `default-directory`, so perhaps the problem is only when there is no actual project root, it caches nil, which is the same as no cache so it attempts to cache it every time anew. Perhaps I could change the cache value to be a single item list with the value of the cache, which could be nil. That way, an empty list would represent "empty cache".

**Comment by bbatsov** [comment]
Which caching are you referring to?

**Comment by aaronjensen** [comment]
`projectile-project-root-cache`--I'm not 100% that what I describe is the problem, but it does seem like the root does not actually get cached in this scenario.

**Comment by aaronjensen** [comment]
actually the problem is `projectile-cached-buffer-file-name`, I'm opening a PR.
