### ISSUE TITLE
projectile-idle-timer-hook used to run in backgroun

### ISSUE THREAD

**Issue by To1ne** [bbatsov/projectile#1217]
## Expected behavior

I've set `projectile-enable-idle-timer` to `t` and now `projectile-idle-timer-hook` when emacs is idle for 30 seconds. But I seem to recall it used to do this in the background?

## Actual behavior

It runs in foreground and blocks the UI.

## Steps to reproduce the problem

```elisp
(setq projectile-enable-idle-timer t)
```

### Projectile version information

```
;; Package-Version: 20180128.655
;; Version: 0.15.0-cvs
```

### Emacs version

```
GNU Emacs 27.0.50 (build 4, x86_64-apple-darwin17.3.0, NS appkit-1561.20 Version 10.13.2 (Build 17C88))
 of 2018-01-03
```

### Operating system

macOS High Sierra

**Comment by bbatsov** [comment]
Emacs is a single-threaded app and there's no way to run things in the background unfortunately. :-( Long-running tasks always block the UI (unless you're doing some async IO operation).

**Comment by To1ne** [comment]
Yeah, but I assumed it was running an `async-shell-command` or something like that.

**Comment by bbatsov** [comment]
The shell command to get the files is simple and fast, but what actually slows down things is all the extra processing that happens in Emacs afterwards. If we remove all the post-processing everything would work lightning fast (and I hope that one day I'll add some turbo mode for people who don't care about filtering and so on).
