### ISSUE TITLE
Custom location for `.projectile`

### ISSUE THREAD

**Issue by nickjmeyer** [bbatsov/projectile#1230]
## Custom location of `.projectile`

I have a project that crosses a large of people.  In the root directory, we have a folder `.editor` where you are free to make a folder for `your_editor` and create configuration files.  I'm curious if there is a way to put the `.projectile` folder in a different position than the root directory.  For example, In my case it would be `/path/to/root/.editory/emacs/.projectile`.

Is this possible?  If not, any thoughts on what it might take to make it possible?  If you think it might be reasonable, can you point me in the right direction so I can start taking a look at making that change?

### Projectile version information
```
Projectile 20180227.1743
```

### Emacs version

```
GNU Emacs 25.3.50.2 (x86_64-pc-linux-gnu, GTK+ Version 3.18.9)
```

### Operating system

Ubuntu.  Kernel 4.10

**Comment by bbatsov** [comment]
It's not possible right now. This file was meant to be a root marker, so it can't be placed anywhere else.
