### ISSUE TITLE
Killing all project buffers also kills non-file buffers

### ISSUE THREAD

**Issue by mfiano** [bbatsov/projectile#1233]
## Expected behavior

Using projectile-kill-buffers should not also take out non-file buffers, such as a REPL that is meant to exist for all projects.

## Actual behavior

Using projectile-kill-buffers deletes the SLIME or Sly REPL buffers with Common Lisp projects.

## Steps to reproduce the problem

Open a project file, then open SLIME or Sly. Issue projectile-kill-buffers and both are deleted.
This does not occur if SLIME or Sly is started before visiting a project file.

### Projectile version information

```
Projectile version: MELPA projectile 20180324.2226
```

### Emacs version

25.3

### Operating system

Arch Linux

**Comment by bbatsov** [comment]
This was actually supposed to be a feature - originally it didn't kill such buffers, but someone asked for this. :-) Obviously it's not hard to change and be made configurable.

**Comment by mfiano** [comment]
I would very much like this to be optional behavior :)
