### ISSUE TITLE
Add support for `_test` suffix in Python projects

### ISSUE THREAD

**Issue by jmromer** [bbatsov/projectile#1237]
## Expected behavior

Given a `python-pip` project with a `models.py` and `models_test.py` in the same directory
And a buffer open with the contents of `models.py`
When I issue `:A`
Then I should see emacs open `models_test.py`

## Actual behavior

Emacs opens a buffer with `test_models.py`

## Steps to reproduce the problem

1. Create a python-pip project with a `models.py` and `models_test.py` in the same directory
2. Open `models.py`
3. Issue `projectile-toggle-between-implementation-and-test`
4. Observe that:
    a. no test file is found or:
    b. if `projectile-create-missing-test-files` is non-nil, a `test_models.py` buffer is opened

Environment & Version information
---------------------------------
### Projectile version information
`Projectile 20180507.129`

### Emacs version
```
GNU Emacs 25.3.1 (x86_64-apple-darwin17.5.0, NS appkit-1561.40 Version 10.13.4 (Build 17E199))
 of 2018-05-03
```

### Operating system
MacOS 10.13.4

**Comment by sp3ctum** [comment]
Is the default structure to have the test file in the same directory? Is this supported by projectile?

I don't care which I use, I am new to Python and would just like to use something that's close to a standard.

**Comment by jmromer** [comment]
> Is the default structure to have the test file in the same directory? Is this supported by projectile?

I'm not sure about the default structure — I've seen both co-located test files and test files under a parallel `tests` directory tree. The latter does seem to work as well, based on my testing (so long as your test files are named with a `test_` prefix rather than a `_test` suffix).

**Comment by bbatsov** [comment]
I'm fine with the suggested change.
