### ISSUE TITLE
projectile key options are not shown in the request

### ISSUE THREAD

**Issue by mambolevis** [bbatsov/projectile#1241]
Hi,

I am using the following configuration in projectile:

(use-package projectile
  :ensure t
  :init
  (setq projectile-completion-system 'ivy)
  :bind-keymap
  ("C-c C-p" . projectile-command-map)
  :config
  (projectile-mode 1))
When I press C-c C-p projectile is activated but the key options are not shown.
If I then press C-c C-p the minibuffer shows projectile key options as expected.

Any suggestion?
Thanks

### Projectile version information

projectile-version:

```
Projectile 20180507.129
```

### Emacs version

GNU Emacs 26.1 (build 1, x86_64-w64-mingw32)

### Operating system

*E.g. Windows 10*

**Comment by bbatsov** [comment]
I've noticed this as well, but I haven't had time to debug it. Likely some odd interaction with `package.el`.

**Comment by bbatsov** [comment]
I sorted this out for me like this:

```
(use-package projectile
  :ensure t
  :init
  (setq projectile-completion-system 'ivy)
  :config
  (define-key projectile-mode-map (kbd "s-p") 'projectile-command-map)
  (projectile-mode +1))
```
