### ISSUE TITLE
Cannot customize command for projectile-compile-project

### ISSUE THREAD

**Issue by drrlvn** [bbatsov/projectile#1242]
Project type detection takes precedence over variable set by user.

## Expected behavior
Setting value for `projectile-project-compilation-cmd` should be used by `projectile-compile-project` over predetermined from project type.

## Actual behavior
The command `cmake --build .` is run because the project is detected to be a cmake project.

## Steps to reproduce the problem

I have a `.dir-locals.el` with the following contents:

```elisp
;;; Directory Local Variables
;;; For more information see (info "(emacs) Directory Variables")

((nil .
      ((projectile-project-compilation-cmd . "make"))))
```

Even though the variable value is changed the command `projectile-compile-project` still runs the command `cmake --build .` and not `make`.

### Projectile version information

```
Projectile 20180522.48
```

### Emacs version

*GNU Emacs 26.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.22.30)
 of 2018-05-29*

### Operating system

*Arch Linux*

**Comment by bbatsov** [comment]
Looking at the simple implementation I can't imagine how this can happen:

```
(defun projectile-compilation-command (compile-dir)
  "Retrieve the compilation command for COMPILE-DIR."
  (or (gethash compile-dir projectile-compilation-cmd-map)
      projectile-project-compilation-cmd
      (projectile-default-compilation-command (projectile-project-type))))
```

Guess you can run this with the debugger to see what's going wrong.

**Comment by drrlvn** [comment]
@bbatsov Unless I'm missing something then the `cmake` is in the cmp-map and the `gethash` is called first so `projectile-project-compilation-cmd` is not checked.

**Comment by bbatsov** [comment]
Ouch, you're right.

**Comment by bbatsov** [comment]
Ah, I forgot my own code. The code's written like this for a reason:

* first you check what's the last command you ran on the project
* then you check for something supplied by dir-locals
* then you check of the default command for the particular project type

**Comment by drrlvn** [comment]
I think 2 and 3 are backwards - `cmp-map` (default for project type) is checked before `projectile-project-compilation-cmd` (supplied by dir-locals).

**Comment by rileyrg** [comment]
Is there no fix for this. it's still the case that projectile project compile is "cmake --build ."

**Comment by J-Kappes** [comment]
I also can't configure projectile-project-compilation-cmd.
My .dir-local.el:
```
((nil . ((projectile-project-compilation-cmd . "make"))))
```
When I run projectile-compile-project I get
```
The local variables list in /home/jkappes/Projekte/ctx-DS_Control_UI/
contains values that may not be safe (*).

Do you want to apply it?  You can type
y  -- to apply the local variables list.
n  -- to ignore the local variables list.
!  -- to apply the local variables list, and permanently mark these
      values (*) as safe (in the future, they will be set automatically.)
i  -- to ignore the local variables list, and permanently mark these
      values (*) as ignored

  * projectile-project-compilation-cmd : "make"

```
I assume I'm doing something wrong, but what?
