### ISSUE TITLE
projectile-toggle-between-implementation-and-test difficulty

### ISSUE THREAD

**Issue by dmitry-saritasa** [bbatsov/projectile#1245]
I have an npm / vue project, and my tests files are stored in the same folder as the component, but with a different suffix and extension

![image](https://user-images.githubusercontent.com/1747653/41323581-23208796-6e64-11e8-842a-ba3431cc8054.png)

so if component has a name **aggregated-currency-stats.vue**, then the test of the component (jest) will be stored in **aggregated-currency-stats.unit.js**, i.e. we replace *.vue* with *.unit.js*

I tried to customize the projectile with **.dir-locals.el**

```
((nil . ((setq projectile-project-test-cmd "npm run unit")
         (projectile-register-project-type 'npm '("package.json")
                                           :compile "npm install"
                                           :test "npm test"
                                           :run "npm run start"
                                           :test-suffix "unit.js")
         )))

```

But when I execute **projectile-toggle-between-implementation-and-test difficulty** command I get the following message:

**condition-case: No matching test file found for project type ‘npm’**

## Expected behavior

Switch to a proper test file

## Actual behavior

**condition-case: No matching test file found for project type ‘npm’**

### Projectile version information

Projectile version: Projectile 20180602.2253

### Emacs version

25.3.1 

### Operating system

Linux Fedora 28

**Comment by dmitry-saritasa** [comment]
One more, https://gratipay.com/bbatsov is 404. Is there other way to donate for the great package?

**Comment by bbatsov** [comment]
Can you run the command using edebug and stepping through it, so we can get a better idea what's going wrong?

> One more, https://gratipay.com/bbatsov is 404. Is there other way to donate for the great package?

Unfortunately it was shut down. You can use https://www.patreon.com/bbatsov

**Comment by bbatsov** [comment]
Yeah, probably we should mention this in the manual. Generally project types were meant to be added to your Emacs config, not to .dir-locals.el, as I would assume most of the type those are something generic.

**Comment by akheron** [comment]
OP's use case was to customize test discovery, as was my own use case, too. Maybe it would be better to make customizing this easier than having to restort registering your own project type in `.dir-locals.el`?
