### ISSUE TITLE
`make test` blows away projectile bookmarks

### ISSUE THREAD

**Issue by nickdrozd** [bbatsov/projectile#1246]
After I run `make test` (out of `~/projectile`), my project bookmarks file (`~/.emacs.d/projectile-bookmarks.eld`) ends up rewritten to just `nil`, with no projects in it.

`Projectile 0.15.0snapshot (package: 0.14.0)` (master)

`GNU Emacs 25.2.1 (x86_64-apple-darwin13.4.0, NS appkit-1265.21 Version 10.9.5 (Build 13F1911)) of 2017-04-21`

**Comment by bbatsov** [comment]
Likely some test is doing some test cleanup/setup wrong.
