### ISSUE TITLE
Switching to a remote project does not work

### ISSUE THREAD

**Issue by smaret** [bbatsov/projectile#1252]
## Expected behavior

Switching to a remote project (for example  `/ssh:someserver:/path/to/project`) with `C-c p-p` should bring to that project.

## Actual behavior

An error message "You're not in a project" is displayed.

## Steps to reproduce the problem

1 - Add the remote project to `.emacs.d/projectild-bookmarks.eld`, for example `"/ssh:someserver:/path/to/project"`
2 - Switch to that project with `C-c p-p`

A workaround is to open the project directory with `C-x f /ssh:someserver:/path/to/project`) first. Once this is has been done, switching to that project works as expected.

### Projectile version information

```
Projectile version: 20180621.2239
```

### Emacs version

GNU Emacs 26.1 

### Operating system

MacOS 10.13.5

**Comment by lgmoneda** [comment]
I also can't open a remote project. But if I access one file in the remote directly, then it works! So my turn around was to create a function that opens a certain file there and close it, then `C-c p p` works with all the remote projects in that machine. Not proud of it, but it works...

**Comment by juergenhoetzel** [comment]
>  But if I access one file in the remote directly, then it works! So my turn around was to create a function that opens a certain file there and close it, then C-c p p works with all the remote projects in that machine. Not proud of it, but it works...

`projectile` rejects to check for project root if remote is unconnected:  [https://github.com/bbatsov/projectile/pull/1259](https://github.com/bbatsov/projectile/pull/1259)
