### ISSUE TITLE
C-c C-p prefix conflicts with Cider's cider-pprint-eval-last-sexp

### ISSUE THREAD

**Issue by goodbobk** [bbatsov/projectile#1256]
Not quite sure this is a bug actually. I understand that I can change the prefix to the old one, I just think that out-of-the-box Projectile should work with Cider happily.

## Expected behavior

Projectile works with Cider

## Actual behavior

New Projectile prefix conflicts with Cider's cider-pprint-eval-last-sexp

## Steps to reproduce the problem

Install new Projectile, start Cider. Projectile is no longer accessible.

### Projectile version information

Projectile: 20180721.352
Cider: 0.17.0

### Emacs version

GNU Emacs 26.1 (build 1, x86_64-apple-darwin17.6.0, NS appkit-1561.40 Version 10.13.5 (Build 17F77))  of 2018-06-05

### Operating system

macOS High Sierra 10.13.6

**Comment by mdallastella** [comment]
Same issue here.

## Environment & Version information
### Projectile version information
Projectile: 20180721.352
Cider: 0.18.0snapshot (package: 20180723.47)

### Emacs version
GNU Emacs 26.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.22.30) of 2018-07-05

### Operating system
Arch Linux 4.14.56-1-lts #1 SMP Tue Jul 17 20:11:42 CEST 2018 x86_64 GNU/Linux

**Comment by bbatsov** [comment]
Yeah, unfortunately there's always potential for conflicts between minor modes. I'll address this shortly by updating CIDER's keymap.
