### ISSUE TITLE
Change default prefix to C-c p doesn't work

### ISSUE THREAD

**Issue by beriya** [bbatsov/projectile#1258]
## Expected behavior
After changing default prefix I can use projectile commands using `C-c p` prefix.
## Actual behavior
When I press `C-c p` i see message `C-c p is undefined` in echo area, but prefix `C-c C-p` still works.
## Steps to reproduce the problem
- Run `emacs -Q --load emacsprojectile.el`
- Content of emacsprojectile.el:
```emacs-lisp
(require 'package)
(let* ((no-ssl (and (memq system-type '(windows-nt ms-dos))
                    (not (gnutls-available-p))))
       (url (concat (if no-ssl "http" "https") "://melpa.org/packages/")))
  (add-to-list 'package-archives (cons "melpa" url) t))

(package-initialize)

(unless (package-installed-p 'projectile)
  (package-install 'projectile))

(require 'projectile)
(projectile-mode +1)
(setq projectile-keymap-prefix (kbd "C-c p"))
```
### Projectile version information
```
Projectile version: 20180724.318
```
### Emacs version

*26.1*

### Operating system

*Linux 4.14.56 #2 SMP Wed Jul 18 00:09:15 CDT 2018 x86_64 Intel(R) Core(TM) i7-4790S CPU @ 3.20GHz GenuineIntel GNU/Linux*

![emacs](https://user-images.githubusercontent.com/6093590/43199968-6be6f0f8-901c-11e8-8f29-5b436fb3090e.png)

**Comment by bbatsov** [comment]
You have to set this before loading the mode. If for some reason this doesn't work as well - move the setq before the `require`.

**Comment by beriya** [comment]
It works if I set it before `require` statement. So in case of using `use-package`, should I set it in `:init`?

**Comment by Silex** [comment]
> So in case of using use-package, should I set it in :init?

Yes.

**Comment by beriya** [comment]
I checked and it works:
```emacs-lisp
(use-package projectile
  :init
  (setq projectile-keymap-prefix (kbd "C-c p"))
  :config
  (projectile-mode +1))
```
Thanks, issue solved for me.
