### ISSUE TITLE
projectile-discover-projects-in-directory does not work (for me)

### ISSUE THREAD

**Issue by marcofognog** [bbatsov/projectile#1266]
I am having a similar symptom to https://github.com/bbatsov/projectile/issues/1165, probably for other reasons: 

# Expected behavior
all git repositories are added to my list of projectile projects.

# Actual behavior
No projects are added to my list of projectile projects.
(projectile-discover-projects-in-directory "~/projects/")

## Steps to reproduce the problem
check projectile-bookmarks.eld is empty
check the value of variable projectile-known-projects is empty:

`C-h v projectile-known-projects`

evaluate command (projectile-discover-projects-in-directory "<path to directory with projects not in projectile-known-projects var>")

projectile-bookmarks.eld is still empty ("nil")
projectile-known-projects  var is still empty

## Environment & Version information

No othe lib installed other than projectile.

### Projectile
Package version: 201800808.833
Version: 1.1.0-snapshot

### Emacs version
GNU Emacs 26.1

### Operating system
Linux K42F 4.15.0-30-generic #32-Ubuntu SMP Thu Jul 26 17:42:43 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

### Work around
Copying and pasting the definition of projectile-discover-projects-in-directory to my .emacs makes it work. Maybe that this gives a clue.

**Comment by rogeriopvl** [comment]
I have the same problem, except I'm using spacemacs (emacs 26.1) and OSX.

**Comment by acmnu** [comment]
Have the same trouble too with Emacs 25.2.2
