### ISSUE TITLE
Custom find command for custom projects

### ISSUE THREAD

**Issue by kshenoy** [bbatsov/projectile#1267]
Hi, I use perforce at work and I can define a custom project to suit my needs. However, the default method of searching for files (using find) is quite slow. While searching for an alternative I came across special commands for git, hg and svn. I was wondering if this can be extended for any custom project that are defined.

I also came across https://projectile.readthedocs.io/en/latest/configuration/#adding-custom-project-types in which it says we can specify the compile, run, test etc. commands. Would it be possible to add something like a `:find` command for finding files?

**Comment by bbatsov** [comment]
So far custom projects are based on build tool types, not on VC stuff. Won't it better for your needs to implement perforce support like it's implemented for other VC backends? 

Maybe what we really need is a way to register VC backends...
