### ISSUE TITLE
`projectile-{grep,ripgrep,ag}`: Unify ignored files/directories handling

### ISSUE THREAD

**Issue by the-kenny** [bbatsov/projectile#1277]
*Use the template below when reporting bugs. Please, make sure that
you're running the latest stable Projectile and that the problem you're reporting
hasn't been reported (and potentially fixed) already.*

**Remove all of the placeholder text in your final report!**

## Expected behavior

All `projectile-*grep` (ripgrep, ag, ...) functions should use the same list of ignored files when invoked.

## Actual behavior

`projectile-ripgrep` only concatenates `projectile-globally-ignored-files` and `projectile-globally-ignored-directories`, completely ignoring `.projectile`.

`projectile-ag` uses a different logic to generate the set of ignored stuff, `projectile-grep` uses different logic too.

All `grep`-like functions should strive to use the same set of ignored files, reusing as much code as possible.

## Steps to reproduce the problem

1. `M-x package-install ripgrep RET`
2. `M-x projectile-ripgrep <term> RET`
3. `M-x projectile-grep <term> RET`

Then compare ignored files and directories in the invocation line of both tools.

### Projectile version information

`projectile-1.0.0/` (no relevant changes in current `master`)

### Emacs version

`GNU Emacs 26.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.22.30) of 2018-08-14`

### Operating system

NixOS

**Comment by bbatsov** [comment]
Yeah, that's a good idea. Don't have time to work on this, but I'd gladly review a PR tackling this.
