### ISSUE TITLE
[Feature request] Add default `test-suffix` to `npm` project

### ISSUE THREAD

**Issue by ybiquitous** [bbatsov/projectile#1278]
Hi, this is a suggestion to add default `:test-suffix ".test"` to `npm` project settings (that is `*.test.js`).

This naming convention is adopted by [Jest](https://jestjs.io/), which is a recently most popular JavaScript test framework.

Also it is adopted by another test framework [Mocha](https://mochajs.org/).
(please see [this code example](https://mochajs.org/#detects-multiple-calls-to-done) in getting stareted documentation)

Saying "recently most popular" is based on:

- [The Front-End Tooling Survey 2018 - Results - AshleyNolan.co.uk - Blog and Portfolio for Ashley Nolan](https://ashleynolan.co.uk/blog/frontend-tooling-survey-2018-results#js-testing)
  ![image](https://user-images.githubusercontent.com/473530/45228080-24e11180-b2fd-11e8-9b72-f8a5b0e8d9fc.png)

- [Jest, Mocha, Jasmine - Explore - Google Trends](https://trends.google.com/trends/explore?cat=31&date=today%205-y&q=Jest,Mocha,Jasmine)
  ![image](https://user-images.githubusercontent.com/473530/45228444-2959fa00-b2fe-11e8-9196-8396e28ffd01.png)

## Expected behavior

For example, assume this project structure:
(this example is in ["Getting Started · Jest"](https://jestjs.io/docs/en/getting-started.html) )

```
$ tree -I node_modules
.
├── package.json
├── sum.js
└── sum.test.js
```

1. Open `sum.js` file.
2. Run <kbd>M-x projectile-toggle-between-implementation-and-test</kbd> command.
3. Jump to `sum.test.js` file! 😄

## Actual behavior

In above step 2, this error is raised: 😢 

```
(error "No matching test file found for project type ‘npm’")
```

## Steps to reproduce the problem

Described in above "Expected behavior" section. ⬆️ 

### Projectile version information

*Include here the version string displayed by `M-x
projectile-version`. Here's an example:*

```
Projectile 20180824.2239
```

### Emacs version

```
GNU Emacs 26.1 (build 1, x86_64-apple-darwin14.5.0, NS appkit-1348.17 Version 10.10.5 (Build 14F2511)) of 2018-05-31
```

### Operating system

macOS High Sierra 10.13.6

---

What do you think about this idea?
Thanks.

**Comment by bbatsov** [comment]
I like the idea and I'd accept a PR for this.

**Comment by ybiquitous** [comment]
Thanks a lot! I opened a new pull request #1280
