### ISSUE TITLE
`recompile' functionality

### ISSUE THREAD

**Issue by phillord** [bbatsov/projectile#1279]
I would love to have functionality in Projectile which mimics "recompile". That is, it runs what ever was the last project command -- configure, test, build etc.

This fits with my usage -- I normally have a single build command which I repeat a lot till it's all working, then I move onto the next step (whatever that might be).

**Comment by bbatsov** [comment]
So what you have in mind is basically a non-prompting version the current compile command? (as it already remembers the last command you ran)

**Comment by phillord** [comment]
Yes. But compile, or test, or configure or what ever you ran last. The current `recompile` command works well, for instance but is not project specific. It the last compile command, in the last directory, regardless of current working directory.

Having two commands would probably be best: projectile-command-run-last, projectile-command-run-last-in-project. The first would do as recompile -- run the same command in the same directory -- useful for when I am in a dependent project but want to run, test or compile another. The second would run the last command in the current project, in the current directory.

Personally, I have a non-prompting function that does `save-some-buffer', then `recompile' so that I don't have to answer yes to save all the time. But that's probably a step too far for standard use!
