### ISSUE TITLE
projectile-compile-project: user-error: The value for: compile-command in project-type: generic was neither a function nor a string.

### ISSUE THREAD

**Issue by ttamttam** [bbatsov/projectile#1281]
## Expected behavior

No error, the prompt for the compilation command should appear.

## Actual behavior

`user-error: The value for: compile-command in project-type: generic was neither a function nor a string.`

## Steps to reproduce the problem

It seems to be related to my project. Some are workings, other are failing like described above.
There is certainly a way to `reset` some cache associated with each project that would lead to this error message?

### Projectile version information
```
Projectile 20180824.2239
```
### Emacs version
```
25.1.1 (x86_64-pc-linux-gnu, GTK+ Version 3.22.11)
```
```
0.200.13@25.1.1 (spacemacs)
```
### Operating system
Debian GNU/Linux 9

**Comment by ambihelical** [comment]
Same as #1270 ?

**Comment by bbatsov** [comment]
Yep.
