### ISSUE TITLE
Possible to set src-dir/compile-command per buffer?

### ISSUE THREAD

**Issue by minad** [bbatsov/projectile#1286]
Hi @bbatsov,

at first thank you very much for projectile! 

I have a project with multiple compilation targets which are buffer dependent. Therefore my question - is it possible to use a `:src-dir` and `:compile-command` per buffer? I specified a compile-command in projectile-register-project-type, but it seems to be only called once per project. Basically my projects consists of subprojects with multiple source directories and corresponding compile commands.

Maybe this is out of scope for projectile? 

I am using the most recent projectile version from melpa.

Daniel

**Comment by bbatsov** [comment]
Hey there!

That's the only way to do so currently https://www.gnu.org/software/emacs/manual/html_node/emacs/File-Variables.html

That should work well, if you're fine with adding the emacs metadata. 

> Basically my projects consists of subprojects with multiple source directories and corresponding compile commands.

In this case using `.dir-locals.el` might be an even better approach.

**Comment by minad** [comment]
Thank you for your answer! I don't really like file local variables because of the cluttering. However I went another simpler route now, just using one projectile project per subproject. There are some dependencies between those, but it does not really matter in the common workflow.

**Comment by minad** [comment]
Ok to close this I guess?
