### ISSUE TITLE
The projectile-mode-line-lighter must be set before the projectile is loaded.

### ISSUE THREAD

**Issue by yuzumx** [bbatsov/projectile#1288]
Sorry to bother again. But I think it is necessary to open another issue.

There is still a problem here, only if I set `projectile-mode-line-lighter` before `projectile-mode` is loading, `projectile-mode-line-lighter` will take effect in the non-file buffers and the remote buffers.

I am a lisp rookie... I don't know how to fix it...Sorry.

## Expected behavior
No matter where you set `projectile-mode-lighter`, it will display correctly in all buffers.

## Actual behavior
It can only be displayed correctly in all buffers if it is set before loading `projectile-mode`.

Otherwise, the non-file buffers and remote buffers will display the default value of this variable: `" Projectile"`
## Steps to reproduce the problem

configured like this:
```emacs-lisp
(projectile-mode +1)
(setq projectile-mode-line-lighter " Proj")
```
Then, the non-file buffer and the remote buffer will show `" Projectile"` on the modeline.
The file buffers show the `" Proj[project-name:project-type]"` that I set.
### Projectile version information

```
Projectile 20180922.609
```

### Emacs version

26.1

### Operating system

Arch Linux

**Comment by re-mx** [comment]
It seems that you have solved it. Thank you.

**Comment by re-mx** [comment]
- [ ]

**Comment by bbatsov** [comment]
I think `(setq projectile--mode-line ...)` should do what you want.

**Comment by re-mx** [comment]
This is really hard to implementation...

By the way, use `customize-variable` to set `projectile-mode-line-lighter` can make it work.

In addition, I think you can consider changing the name of `projectile-mode-line-lighter`...because people around me actually think that the name refers to "the whole lihgter (`projectile[project-name:project-type] `)". However, this may also be due to the misunderstanding caused by me and the people around me whose native language is not English. Don't worry about it.

**Comment by bbatsov** [comment]
Yeah, I agree the name is not ideal. I just could not come up with anything better. :-) Maybe I should name this `mode-line-prefix` instead of `lighter`. I'll think about this.

**Comment by re-mx** [comment]
`mode-line-prefix` is good.

**Comment by darkfeline** [comment]
This still affects projectile-mode-line-prefix in 2.0.0.  Can't this be fixed by adding a custom setter to projectile-mode-line-prefix that essentially calls `(setq-default projectile--mode-line ...)`?

**Comment by darkfeline** [comment]
This bug is still relevant, and I again suggest adding a custom setter that does `(setq-default projectile--mode-line projectile-mode-line-prefix)`

**Comment by darkfeline** [comment]
This bug is still present.
