### ISSUE TITLE
How to disable indexing folder any time I open file

### ISSUE THREAD

**Issue by kostafey** [bbatsov/projectile#1294]
After the projectile update, any time I run `find-file` for any project, projectile run indexing  automatically.
How I can disable this behavior?

**Comment by bbatsov** [comment]
There's no such behaviour to my knowledge. What exactly is happening for you?

**Comment by kostafey** [comment]
Steps to reproduce:
```lisp
(projectile-mode)
(setq projectile-indexing-method 'native)
(setq projectile-enable-caching t)
;; Ensure nothing bind to find-file:
(setq find-file-hook nil)
```
`M-x [RET] find-file [RET] C:/blah-blah/my-file.txt`

**Result:**
"Projectile is indexing C:/blah-blah/"
**Expected result:**
A file is opened.

When I disable projectile:
```lisp
(setq projectile-mode nil)
```
The behaviour persists (I see "Projectile is indexing blah-blah" anyway). 
So, I have to reload Emacs with `(setq projectile-mode nil)` in `.emacs` to open files
as expected without indexing starded.

**Comment by bbatsov** [comment]
That's everything projectile does on `find-file`:

```
(defun projectile-find-file-hook-function ()
  "Called by `find-file-hook' when `projectile-mode' is on.

The function does pretty much nothing when triggered on remote files
as all the operations it normally performs are extremely slow over
tramp."
  (unless (file-remote-p default-directory)
    (when projectile-dynamic-mode-line
      (projectile-update-mode-line))
    (projectile-cache-files-find-file-hook)
    (projectile-track-known-projects-find-file-hook)
    (projectile-visit-project-tags-table)))
```

Guess you have to track down which of them is misbehaving for you.

**Comment by kostafey** [comment]
Ok. I see the reason. When no of project definition files listed in `projectile-project-types` found (by `projectile-detect-project-type` fn call), the `projectile-go-project-p` function is called, then `projectile-current-project-files`.
So, it force to indexing the root directory. I think this behavior not expected by default.

**Comment by bbatsov** [comment]
Yeah, that's definitely a bug.

**Comment by kostafey** [comment]
Thank you!
