### ISSUE TITLE
projectile-project-root returns nil (when projectile-require-project-root is nil)

### ISSUE THREAD

**Issue by hlissner** [bbatsov/projectile#1296]
## Expected behavior
The old behavior of `projectile-project-root` was to return `default-directory` when not in a project and `projectile-require-project-root` is `nil`. `projectile-project-root`'s docstring suggests this is still the expected behavior:

```
If DIR is not supplied its set to the current directory by default.
```

As does `projectile-require-project-root`'s:

```
When nil Projectile will consider the current directory the project root.
```

## Actual behavior
Its new behavior, introduced in https://github.com/bbatsov/projectile/commit/4c5e2b7e049d232509e7532848775fd70b5e064d, changes it to return `dir` (its optional argument). If `dir` is omitted, it returns nil instead of `default-directory`.

The breaks [projectile-invalidate-cache](https://github.com/bbatsov/projectile/blob/master/projectile.el#L768-L772) when run from a non-project, because the `project-root` let-var is nil in that case. It causes this [the call to `propertize` in the `message` call](https://github.com/bbatsov/projectile/blob/master/projectile.el#L780) to throw a wrong-type-argument: stringp error.

This also breaks how I've been using projectile-project-root, which expects it to always return a value (or throw an error), but never nil. I can adapt, but I'd like to confirm that this was an intentional change first.

## Steps to reproduce the problem
```elisp
(require 'projectile)
(setq projectile-require-project-root nil)
(projectile-project-root "~/not/a/project")   ; returns nil
```

### Projectile version information
```
Projectile version: 20180927.1728
```

### Emacs version
26.1

### Operating system
Arch Linux

**Comment by bbatsov** [comment]
> This also breaks how I've been using projectile-project-root, which expects it to always return a value (or throw an error), but never nil. I can adapt, but I'd like to confirm that this was an intentional change first.

It's an intentional change, although I guess I didn't update all the places that the change could break something. The idea is that `projectile-project-root` is a low-level function and what to do in the absence of a project should be decided elsewhere (e.g. in the caller or by using the wrapper `projectile-ensure-project`. I completely forgot in the old arrangement we would end up caching any folder and I'll make some adjustments to account for this. Generally it seems to me that non-project dirs should not be cached.

**Comment by hlissner** [comment]
That makes perfect sense to me. In that cause, should I change this issue to target the inconsistency in `projectile-invalidate-cache`, or close it as it is a non-issue?

**Comment by bbatsov** [comment]
> should I change this issue to target the inconsistency in projectile-invalidate-cache

Yes, please. That's definitely an oversight of mine.
