### ISSUE TITLE
Migrate the tests from ERT to Buttercup

### ISSUE THREAD

**Issue by bbatsov** [bbatsov/projectile#1303]
I've decided that I'm done with ERT, as it's really painful to work with it, and I want us to migrate all the tests to [Buttercup](https://github.com/jorgenschaefer/emacs-buttercup/blob/master/docs/writing-tests.md).

I've renamed the old tests to `projectile-legacy-test.el` and `projectile-test.el` already contains a couple of migrated tests. `make test` now runs the new tests and `make ert-test` runs the old ones. 

I'd really appreciate some help in migrating all the tests and generally increasing the code coverage of the project. I think all of you will find it's much easier to work with buttercup (especially if you've ever used something like RSpec or Jasmine).

**Comment by mnuessler** [comment]
Nice, I would like to work on this..

**Comment by bbatsov** [comment]
@mnuessler You've got it. :-)
