### ISSUE TITLE
projectile-project-root returns null when not in project directory.

### ISSUE THREAD

**Issue by tttuuu888** [bbatsov/projectile#1304]
(setq projectile-require-project-root nil) 
and 
(projectile-project-root) 
in home directory. (not projectile project directory) returns nill.
It used to returned value of default-directory.

## Expected behavior
"~/"

## Actual behavior
nil

## Steps to reproduce the problem
(setq projectile-require-project-root nil) 
(projectile-project-root) 

### Projectile version information
```
Projectile 20181001.725
```

### Emacs version
GNU Emacs 26.1

### Operating system
Debian 9

**Comment by bbatsov** [comment]
This behaviour was moved to `projectile-ensure-project`. `projectile-project-root` doesn't consult this variable at all anymore. I decouple the project root detection from what to do in case there's no project root.

**Comment by bbatsov** [comment]
Basically to get the old behaviour you need to use `(projectile-ensure-project (projectile-project-root))`.

**Comment by tttuuu888** [comment]
Oh, thank you for your quick reply. I will use that code usefully. 
I am always thankful for this great package.

**Comment by bbatsov** [comment]
You're welcome!
