### ISSUE TITLE
Handle `nil` project-root case in `projectile-project-buffer-p`

### ISSUE THREAD

**Issue by kaushalmodi** [bbatsov/projectile#1305]
## Expected behavior

No backtrace should appear on running `projectile-kill-buffers`.

## Actual behavior

Getting a backtrace on running `projectile-kill-buffers` if `project-root` is nil.

### Backtrace

```
Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  find-file-name-handler(nil file-remote-p)
  file-remote-p(nil)
  (string-equal (file-remote-p default-directory) (file-remote-p project-root))
  (and (not (string-prefix-p " " (buffer-name buffer))) (not (projectile-ignored-buffer-p buffer)) (string-equal (file-remote-p default-directory) (file-remote-p project-root)) (not (string-match-p "^http\\(s\\)?://" default-directory)) (string-prefix-p project-root (file-truename default-directory) (eq system-type 'windows-nt)))
```

## Steps to reproduce the problem

- Have a buffer open where the projectile project root is nil or unset. I happened to have the `nadvice.el.gz` buffer open from Emacs sources.
- `M-x projectile-kill-buffers`.

I refactored the `projectile-project-buffer-p` to the below:

```el
(defun projectile-project-buffer-p (buffer project-root)
  "Check if BUFFER is under PROJECT-ROOT."
  (message "[projectile-project-buffer-p DBG] buffer = %S" buffer)
  (message "[projectile-project-buffer-p DBG] project-root = %S" project-root)
  (with-current-buffer buffer
    (and (not (string-prefix-p " " (buffer-name buffer)))
         (not (projectile-ignored-buffer-p buffer))
         (string-equal (file-remote-p default-directory)
                       (file-remote-p project-root))
         (not (string-match-p "^http\\(s\\)?://" default-directory))
         (string-prefix-p project-root (file-truename default-directory) (eq system-type 'windows-nt)))))
```

and on recreating the error, I got:

```
[projectile-project-buffer-p DBG] buffer = #<buffer nadvice.el.gz>
[projectile-project-buffer-p DBG] project-root = nil
```

So that function should have returned nil if project-root is nil.

### Projectile version information

```
Projectile 20181001.1033
```

### Emacs version

GNU Emacs 27.0.50 (build 19, x86_64-pc-linux-gnu, GTK+ Version 2.24.23) of 2018-10-01

### Operating system

RHEL 6.8

**Comment by kaushalmodi** [comment]
I believe the root cause of this is a regression in recent projectile refactoring.

Earlier, if projectile-project was nil, the project root defaulted to default-directory. Now it doesn't.

**Comment by bbatsov** [comment]
Yeah, that's the cause of the problem, although this was done intentional. I just didn't have time to go over all the interactive commands and decide which need `projectile-ensure-project`, but I guess that's most of them.

**Comment by kaushalmodi** [comment]
yeah.. `projectile-project-root` has this relic doctring too:

https://github.com/kaushalmodi/projectile/blob/b99f023b3ca48beae9104e81f7466487762e46d4/projectile.el#L1006-L1012

So, `projectile-ensure-project` is kind of the new DWIM `projectile-project-root`?

**Comment by bbatsov** [comment]
Yeah. The point is that only interactive command really cared about tweaking the returned root and many people were annoying it was hard to implement something like "I wan't to be prompted for a project if I'm not in a project before", because of all the non-interactive uses the function had. I wondered to add some flag to it to change it's behaviour, but I decided to actually have a separate function for whoever doesn't want to handle the missing project themselves.

**Comment by kaushalmodi** [comment]
Ok, I can at least continue with this edit in my fork for now, without having to resort to reverting to the much older stable branch:

```el
diff --git a/projectile.el b/projectile.el
index fbb6e02..ac86ae4 100644
--- a/projectile.el
+++ b/projectile.el
@@ -1038,7 +1038,7 @@ will return DIR or the current directory, otherwise it'd raise an error."
                        projectile-project-root-files-functions)))
                   ;; set cached to none so is non-nil so we don't try
                   ;; and look it up again
-                  'none))))
+                  (projectile-ensure-project dir)))))
 
 (defun projectile-ensure-project (dir)
   "Ensure that DIR is non-nil.
```

**Comment by bbatsov** [comment]
Yeah, this will work, unless you enable the new project prompting behaviour which will break things on an epic level. :-) I guess you can just as easily return `dir` as well. 

Anyways, I fixed this particular problem already.
