### ISSUE TITLE
Make operations in Projectile asynchronous

### ISSUE THREAD

**Issue by quicknir** [bbatsov/projectile#1307]
I was very excited for the turbo alien update. Unfortunately for me, it still has very poor performance. Even with caching it takes me 1-2 seconds to start, and without caching longer than that.

```
- command-execute                                                3429  94%
 - call-interactively                                            3429  94%
  - funcall-interactively                                        3429  94%
   - helm-projectile-find-file                                   3421  94%
    - helm                                                       3419  94%
     - apply                                                     3419  94%
      - helm                                                     3419  94%
       - apply                                                   3419  94%
        - helm-internal                                          3419  94%
         - helm-read-pattern-maybe                               3392  93%
          - helm-update                                          3247  89%
           - helm--collect-matches                               3226  88%
            - helm-compute-matches                               3226  88%
             - helm-get-cached-candidates                        3200  88%
              - helm-get-candidates                              3200  88%
               - helm-interpret-value                            3200  88%
                - helm-funcall-with-source                       3200  88%
                 - apply                                         3200  88%
                  - #<compiled 0x2be1d69>                        3166  87%
                   - projectile-current-project-files               1881  51%
                    - projectile-project-files                   1880  51%
                     - projectile-sort-files                     1355  37%
                      + projectile-sort-by-recentf-first               1355  37%
                     + cl-mapcan                                  524  14%
                     + projectile-get-project-directories                  1   0%
                    + projectile-project-root                       1   0%
                   + projectile-project-p                           1   0%
             + helm-process-filtered-candidate-transformer                 26   0%
           + helm--update-move-first-line                          12   0%
           + #<compiled 0xf46c9d>                                   6   0%
           + helm-render-source                                     3   0%
          + read-from-minibuffer                                  138   3%
            helm-get-candidate-number                               1   0%
         + helm-display-buffer                                      9   0%
         + helm-initialize                                          8   0%
         + #<compiled 0x1d4f915>                                    8   0%
         + #<compiled 0x1e4b27d>                                    1   0%
    + projectile-maybe-invalidate-cache                             1   0%
    + projectile-project-name                                       1   0%
   + lazy-helm/profiler-report                                      8   0%
+ timer-event-handler                                             160   4%
+ redisplay_internal (C function)                                  34   0%
+ winner-save-old-configurations                                    1   0%
+ global-spacemacs-whitespace-cleanup-mode-check-buffers                  1   0%
+ which-key--hide-popup                                             1   0%
+ evil-repeat-pre-hook                                              1   0%
+ ...                                                               0   0%
```

What I don't understand is that even though my indexing method says turbo alien, projectile still seems to be doing lots of sorting. Although, it seems like this only accounts for half the time.

I am not sure exactly what projectile is doing that makes it slow, but a couple of thoughts. First, my top level project is not a git directory, rather there are multiple git repos as sub-directories. This means that it can't use git ls-files to get a file list. Second, it seems like projectile runs synchronously. It populates all of the possible file results first, and then lets you search. If this is the case, then this is a rather fundamental limit. I'm working with around 30K files on an SSD and having huge problems.

On the other hand, helm-ag which uses ag to search the *content* of the files asynchronously, is actually more responsive than projectile (which is only searching file names). In fact, my current workaround-hack for projectile being too slow to use, is to actually just pass -g into helm-ag which makes it search file names instead. This doesn't require caching, git ls, or anything else, but is extremely fast and loads instantly.

I'm happy to provide my code that leverages helm-ag's infrastructure to do these extremely fast async searches, if you're interested.

**Comment by bbatsov** [comment]
As you can see, most of the time is spending in sorting the project files, which is a no op by default and you likely enabled yourself. I'm reasonably certain that the default sorting is simply no sorting. 

Take a look at the value of your `projectile-sort-order`. 

> I'm happy to provide my code that leverages helm-ag's infrastructure to do these extremely fast async searches, if you're interested.

I'm always happy to check out solutions that might speed up things even more. Show me the code! :-)

**Comment by bbatsov** [comment]
> Even with caching it takes me 1-2 seconds to start, and without caching longer than that.

Btw, that's also related to your use of sorting on Emacs's. This can't be cached therefore the 1-2 delay. 

> Second, it seems like projectile runs synchronously. It populates all of the possible file results first, and then lets you search.

Yeah, that's pretty much how it works for most things. I don't think you can implement something like find-file-in-project async, but the async approach should work well for grep-like functionality where we can stream the output.

**Comment by quicknir** [comment]
Thanks, seems like spacemacs sets that option :-(. That said, as the perf report implied, even with that option unset, it's still rather slow, I'd say waiting about 1.5 seconds for it to come up before I start typing. And then when I do type, it takes close to a full second after I stop typing for results to actually update. This really kills a lot of the value of interactive search. Updated performance backtrace.

```
- command-execute                                                1373  81%
 - call-interactively                                            1373  81%
  - funcall-interactively                                        1373  81%
   - helm-projectile-find-file                                   1367  81%
    - helm                                                       1365  81%
     - apply                                                     1365  81%
      - helm                                                     1365  81%
       - apply                                                   1365  81%
        - helm-internal                                          1365  81%
         - helm-read-pattern-maybe                               1350  80%
          - helm-update                                          1226  72%
           - helm--collect-matches                               1210  71%
            - helm-compute-matches                               1210  71%
             - helm-get-cached-candidates                        1188  70%
              - helm-get-candidates                              1188  70%
               - helm-interpret-value                            1188  70%
                - helm-funcall-with-source                       1188  70%
                 - apply                                         1188  70%
                  - #<compiled 0x2af9f2d>                        1165  69%
                   - projectile-project-p                           1   0%
                    - projectile-project-root                       1   0%
                     + cl-some                                      1   0%
                   - projectile-current-project-files                  1   0%
                    - projectile-project-root                       1   0%
                     + cl-some                                      1   0%
             + helm-process-filtered-candidate-transformer                 22   1%
           + helm--update-move-first-line                           8   0%
           + #<compiled 0x1687929>                                  5   0%
           + helm-render-source                                     3   0%
          + read-from-minibuffer                                  118   7%
          + thing-at-point                                          1   0%
         + helm-initialize                                          6   0%
         + #<compiled 0x1ad178d>                                    5   0%
         + helm-display-buffer                                      2   0%
           advice-add                                               1   0%
           helm-log-run-hook                                        1   0%
    + projectile-project-p                                          1   0%
    + projectile-project-name                                       1   0%
   + lazy-helm/profiler-report                                      6   0%
+ timer-event-handler                                             279  16%
+ redisplay_internal (C function)                                  31   1%
+ global-page-break-lines-mode-check-buffers                        2   0%
+ ...                                                               0   0%
```

>  I don't think you can implement something like find-file-in-project async, 

I'm curious what feature you have in mind that makes you say this? It works very well for me. If you have helm-ag installed, you can just bring it up, feed the `-g` flag and start typing your query and you'll see it start working.

Here's the code I use. As you can see, it leverages some implementation details of helm-ag considerably because there are some fairly big wheels I didn't want to reinvent (namely, converting the helm arguments into a regex that can be fed into ag, that does the same style of searching that helm does, i.e. conjunction of space separated terms). I called it "worse", which was supposed to be a pun on working sets :-). I had some ideas on how to proceed which I shared in another issue, but ultimately I just got a very fast async find file in project working and then didn't continue. Another thing to note is that as an additional bonus this search accepts all ag arguments. For example, you can pass --python and filter down to only python files... pretty useful feature for a file finder I think!

In the code below, the function I actually use is `worse-faster-projectile-files`.

```
;;; -*- lexical-binding: t -*-

(require 'projectile)
(require 'helm-ag)
(require 'helm)
(require 'helm-help)
(require 'helm-projectile)
(require 'helm-source)

(defvar worse-projectile-files-buffer "*worse files*")
(defvar worse-base-command '("ag" "--nocolor" "--nogroup" "-S" "-g"))

(defun worse--construct-ag-command (pattern)
  (let* ((opt-query (helm-ag--parse-options-and-query pattern))
         (options (car opt-query))
         (query (cdr opt-query))
         (has-query (not (string= query ""))))
    (when (helm-ag--show-result-p options has-query)
      (append worse-base-command
              options
              (and has-query (list (helm-ag--join-patterns query)))))))

(setq worse-helm-source-projectile-files-list
      (helm-build-async-source "Projectile files"
        :candidates-process
        (lambda ()
          (let ((default-directory (projectile-project-root)))
            (apply 'start-process "ag-files" nil (worse--construct-ag-command helm-pattern))))
        :keymap helm-projectile-find-file-map
        :help-message 'helm-ff-help-message
        :mode-line "foo"
        :action helm-projectile-file-actions
        :persistent-action #'helm-projectile-file-persistent-action
        :persistent-help "Preview file"
        :requires-pattern 3))

;;;###autoload
(defun worse-faster-projectile-find-file (input)
  (condition-case nil
      (let* ((default-directory (projectile-project-root))
             (output (apply 'process-lines (worse--construct-ag-command-2 (concat "-Q -g " input)))))
        (if (cdr output)
            (worse-faster-projectile-files-input input)
          (find-file-existing (concat default-directory (car output)))))
    (error (message "No files found or error running process"))))

;;;###autoload
(defun worse-faster-projectile-files ()
 (interactive)
 (let ((default-directory (projectile-project-root)))
   (helm :sources 'worse-helm-source-projectile-files-list
         :buffer "*helm worse files*")))

;;;###autoload
(defun worse-faster-projectile-files-input (input)
  (interactive)
  (let ((default-directory (projectile-project-root)))
    (helm :sources 'worse-helm-source-projectile-files-list
          :buffer "*helm worse files*"
          :input input)))


(provide 'worse)
```

**Comment by bbatsov** [comment]
Ah, now I understand what you mean - we don't wait for the candidates to be returned while you're typing, so you can narrow the search and make it faster by association. Yeah, something like this can be done, but it will also depend on the ability of the completion frontend to support such an async data source. Helm clearly can do this, but I don't think this is the case for `completing-read`, `ivy` and `ido`.  They generally expect just a list of candidates, therefore the current sync design. 

> And then when I do type, it takes close to a full second after I stop typing for results to actually update. This really kills a lot of the value of interactive search.

I'm reasonably certain that's just coming from the fact that Emacs can't handle big lists very well.

**Comment by bbatsov** [comment]
Btw, in your particular case I guess we also need an async source for Helm. I see the currently defined is a sync source, but I don't know anything about Helm, so I can't really do much about this myself. //cc @xiongtx

**Comment by xiongtx** [comment]
Helm definitely supports async sources, but I think the goal here is not only to have `helm-projectile` be async, but Projectile itself, yes?

**Comment by bbatsov** [comment]
Yeah, that's correct. I just called out Helm specifically, given the OP is using Helm.
