### ISSUE TITLE
fix project type detection order

### ISSUE THREAD

**Issue by yydcnjjw** [bbatsov/projectile#1315]
```
;;; Project type registration
;;
;; Project type detection happens in a reverse order with respect to
;; project type registration (invocations of `projectile-register-project-type').
```
project type detection happens in a reverse order in the source code.
But actually, the detection method seems to be positive.
I tried the following code to try to override `make project` registration in the source code.
```
(projectile-register-project-type 'make-override '("Makefile"))
```
Calling `projectile-project-info` in a test project, Still showing `make project`.

**Comment by bbatsov** [comment]
Hmm, seems we really need to adds a few tests for this project order. :-)

I'll take a look. Might be necessary to reverse the resulting list somehow or prepend the project types instead of appending them. Not sure what exactly did we mess up.

**Comment by yydcnjjw** [comment]
The method of detecting the type of project should be `projectile-detect-project-type`.
#1317
