### ISSUE TITLE
user-error: The value for: compile-command in project-type: (npm marker-files (package.json) compilation-dir nil configure-command nil compile-command npm install test-command npm test run-command nil test-suffix .test) was neither a function nor a string.

### ISSUE THREAD

**Issue by TommyX12** [bbatsov/projectile#1318]
(below are using the latest version (as of issue date))

## Steps to reproduce the problem
Call projectile-compile-project in any recognized project (such as Node project)

## Expected behavior
Project compile command should be called successfully.

## Actual behavior
The error below is shown:
`user-error: The value for: compile-command in project-type: (npm marker-files (package.json) compilation-dir nil configure-command nil compile-command npm install test-command npm test run-command nil test-suffix .test) was neither a function nor a string.`

### Projectile version information
Projectile 20181007.939

### Emacs version
26.1

### Operating system
Windows 10

**Comment by TommyX12** [comment]
I suspect it's because project-type is supposed to be a symbol denoting the project type (such as 'npm), but the entire alist cons cell is passed in instead.

**Comment by yydcnjjw** [comment]
This should be a problem caused by changing the `projectile-project-types` to alist. (#1317)
I have a temporary solution.
Overwrite function `projectile-project-type`
``` elisp
(defun projectile-project-type (&optional dir)
  "Determine a project's type based on its structure.
When DIR is specified it checks it, otherwise it acts
on the current project.

The project type is cached for improved performance."
  (if projectile-project-type
      projectile-project-type
    (let* ((dir (or dir default-directory))
           (project-root (projectile-project-root dir)))
      (if project-root
          (first (or (gethash project-root projectile-project-type-cache)
              (projectile-detect-project-type)))
        ;; if we're not in a project we just return nil
        nil))))
```

**Comment by bbatsov** [comment]
Sorry about this. I had made a silly mistake when I was refactoring this yesterday and I didn't have time to test it properly.
