### ISSUE TITLE
Cannot override git ignore using .projectile

### ISSUE THREAD

**Issue by thermopyle** [bbatsov/projectile#1322]
I have the following in .gitignore:

`Dev/Parts/`

I try to make Projectile index and use all files in Dev/Parts by placing the following in .projectile:

`!/Dev/Parts`

Projectile does not include the files and folders in Dev/Parts when searching for files, they are still excluded according to the pattern in .gitignore.

I try to unignore a specific file using the following pattern in .projectile:

`!/Dev/Parts/PluginPackage/VSTPlugIn.cpp`

Projectile does not find this file.

```
Projectile version: 20181008.812
GNU Emacs 26.1 (build 1, x86_64-apple-darwin14.5.0, NS appkit-1348.17 Version 10.10.5 (Build 14F2511)) of 2018-05-31
MacOS 10.14 Mojave 
```

**Comment by bbatsov** [comment]
What's your indexing method?

**Comment by thermopyle** [comment]
I haven't specified this explicitly so I guess it's turbo-alien (?).

**Comment by thermopyle** [comment]
If I switch to native indexing it works. Doesn't alien and turbo-alien indexing take .projectile configuration into account?

**Comment by bbatsov** [comment]
@thermopyle `alien` does, but `turbo-alien` doesn't (that's intentional, as this unignoring is pretty slow). I might have broken it when I introduced the `turbo-alien` mode, as a lot of code was a big mess and I had to do some pretty epic changes with almost no tests. Therefore my effort in #1303 to adopt a better testing library and come up with a proper test suite.

**Comment by bbatsov** [comment]
You can read a little bit more on the subject here http://www.projectile.mx/en/latest/configuration/

**Comment by thermopyle** [comment]
I can confirm that the alien indexing method **does not** take .projectile configuration into account when it comes to including previously git ignored files in the file search.

The only method that makes it possible (without tweeking) to include previously git ignored files in the file search is the native method and it is painfully slow on my system (it's a very large project) so it is not an option.

Instead I installed **fd** and changed the projectile git command by adding the following to my .init.el:

`(setq projectile-git-command "fd . --print0 --no-ignore-vcs --color never")`
`(setq projectile-indexing-method 'alien)`

With this projectile file search is working for me again.

**Comment by ZzAntares** [comment]
I confirm this as an issue, in the mean time for others looking @thermopyle solution does work. Thank you sir.

**Comment by rileyrg** [comment]
This is still an issue. Things are being closed as stale because they're not fixed. Perhaps lengthen the closing period?

**Comment by ZzAntares** [comment]
Yes can confirm, as of today, it does not work. What ever files are listed in `.gitignore` will not be seen by projectile even though they are un-ignored in the `.projectile` file.

**Comment by wminshew** [comment]
based on my reading of the latest [docs](https://docs.projectile.mx/projectile/configuration.html), I suspect this is "working as expected". Setting the indexing method to `native` or `hybrid` seems to fix it, albeit at the cost of slower search (much slower for `native`)
