### ISSUE TITLE
Switching to a remote project does not work (again)

### ISSUE THREAD

**Issue by smaret** [bbatsov/projectile#1328]
This is some resurgence of #1252 that was fixed a few months ago, but shows up again in the latest Projectile version (although with a different error message).

## Expected behavior

Switching to a remote project (for example `/ssh:someserver:/path/to/project`) with C-c p-p should bring to that project.

## Actual behavior

An error message "projectile-switch-project-by-name:  Directory /ssh:someserver:/path/to/project is not a project" is displayed.

## Steps to reproduce the problem

1 - Add the remote project the list of known project, for example "/ssh:someserver:/path/to/project"
2 - Switch to that project with C-c p-p

### Projectile version information

```
Projectile 20181017.710
```

### Emacs version

*26.1*

### Operating system

*macos 10.14*

**Comment by bbatsov** [comment]
Does this work if you set `projectile-require-project-root` to `nil`?

**Comment by bbatsov** [comment]
As some background - I've been doing some heavy refactorings lately and I don't use TRAMP myself, so it's extremely unlikely I'd ever spot something like this myself. I'm assuming this breakage happened when I removed all let-bindings of `projectile-require-project-root`. (which was the fix in the issue you referred to)

**Comment by smaret** [comment]
> Does this work if you set projectile-require-project-root to nil?

No, I get the same error message.

**Comment by dareno** [comment]
This functionality remains broken. Through testing, I've identified this commit as the culprit: https://github.com/bbatsov/projectile/commit/8a424b2d8ec354380294bd88f1c08cf79e7431e7

Can this be re-opened and fixed?
