### ISSUE TITLE
prev/next buffer order issue

### ISSUE THREAD

**Issue by ddovod** [bbatsov/projectile#1338]
## Expected behavior
When I execute projectile-previous/next-project buffer, or builtin previous/next-buffer after projectile-find-file, buffer switches in correct order.

## Actual behavior
Buffers switches in incorrect order.

## Steps to reproduce the problem
Case 1.
1. Open File1
2. projectile-find-file -> File2
3. projectile-find-file -> File3
4. projectile-next-project-buffer -> opens File2 but should open File1 or some buffer after File3 if it is there
5. Now we are in File2
6. projectile-previous-project-buffer -> opens File3 but should open File1

Case 2.
Same steps but instead of projectile-find-file just navigate to the files using C-x C-f. In this case it works like expected.

So looks like projectile-find-file pushes previous buffer in wrong position in the list, so it appears in reversed order (or smth like that).

### Projectile version information
projectile-version doesn't work (Wrong type argument: stringp, package-desc) so projectile 20181024.1707 from melpa (info from package buffer).

### Emacs version
emacs 26.1 from ppa

### Operating system
Ubuntu 18.04

**Comment by mookid** [comment]
I tested your recipe on the projectile repository, with the following values for file{1,2,3}:
```
    .dir-locals.el
    .github/ISSUE_TEMPLATE.md
    .github/PULL_REQUEST_TEMPLATE.md
```

and could not reproduce. From what you describe, it seems that file1 fails to pass `projectile-project-buffer-p`. Can you check that?

**Comment by ddovod** [comment]
Here you can see how it works on my side (I'm on mac now, but on ubuntu it works the same way).
I'm switching buffers back and forth between files. Please pay attention to commands I'm executing.
`projectile-find-file`
![ezgif-4-c7a97e6fe9c5](https://user-images.githubusercontent.com/9406025/47555652-0bc80a80-d915-11e8-919b-07a37721e008.gif)

C-x C-f
![ezgif-4-65696cead75a](https://user-images.githubusercontent.com/9406025/47555688-239f8e80-d915-11e8-8497-484e1e2f7852.gif)

**Comment by ddovod** [comment]
Btw, `projectile-find-other-file` works in the same way, buffers order becomes reversed

**Comment by mookid** [comment]
hello @ddovod,

I already investigated a bit but had trouble understanding the bug.
 I'll take another look at it later today.

**Comment by ddovod** [comment]
Thank you very much @mookid! Let me know if I can help you somehow

**Comment by mookid** [comment]
hello @ddovod,

what is your value for projectile-completion-system?

**Comment by ddovod** [comment]
Hey. The value is `ido`

**Comment by mookid** [comment]
here is my reproduction attempt, which should just be the steps you describe:

```

(defvar bufprefix "*buf*")
(defvar root-dir (concat (expand-file-name "~/src/projectile") "/"))

(setq projectile-completion-system 'ido)

(defun repro-1338 ()
  (list
    (test-ff #'find-file-literally)
    (test-ff #'ff-projectile)))

(defun ff-projectile (filename)
  (cd root-dir)
  (flet ((projectile-completing-read (&rest _) filename))
    (projectile-find-file)))

(defun test-ff (ff)
  (mapc #'kill-buffer (list-project-buffers))
  (let (res)
    (dolist (filename '("projectile.el" "mkdocs.yml" "README.md" "Makefile" "test" ".dir-locals.el"))
      (funcall ff (concat root-dir filename))
      (rename-buffer (concat bufprefix (buffer-name))))
    (setq res (buffer-order))
    (mapc #'kill-buffer (list-temp-buffers))
    res))

(defun list-project-buffers ()
  (remove-if-not (lambda (buf)
                   (and (buffer-file-name buf)
                        (string=
                         (projectile-project-root
                          (file-name-directory
                           (buffer-file-name buf)))
                         root-dir)))
                 (buffer-list)))


(defun list-temp-buffers ()
  (remove-if-not (lambda (buf)
                   (string-prefix-p bufprefix (buffer-name buf)))
                 (buffer-list)))

(defun buffer-order ()
  (let ((start-buffer (current-buffer))
        (buffer nil)
        (results nil))
    (while (or (not buffer) (not (eq (current-buffer) start-buffer)))
      (next-buffer)
      ;; (projectile-next-project-buffer)
      (setq buffer (current-buffer))
      (when (string-prefix-p bufprefix (buffer-name buffer))
        (push (string-remove-prefix bufprefix (buffer-name buffer)) results)))
    (nreverse results)))


```

I could not manage to get 2 different lists.
Do you manage to reproduce using this recipe? (note that you need to set `root-dir` to be the location of a projectile checkout for it to work).

**Comment by ddovod** [comment]
This is what I got by running `(repro-1338)`
```
(
("projectile.el" "mkdocs.yml" "README.md" "Makefile" "test" ".dir-locals.el")
("test" "Makefile" "README.md" "mkdocs.yml" "projectile.el" ".dir-locals.el")
)
```

**Comment by ddovod** [comment]
The thing is I'm using lsp-mode with lsp-ui which has `lsp-ui-peek-find-definitions` which jumps in symbols definition file, and after that I can call `projectile-previous-project-buffer` and it opens the buffer from which I ran find-def command. So if there was something wrong in my emacs configuration, this thing would also broken (not sure about that, but sounds reasonable).
My projectile setup:
```
(require 'projectile)
(projectile-mode 1)
(setq projectile-indexing-method 'alien)
(setq projectile-enable-caching nil)
(define-key projectile-mode-map (kbd "C-c p") 'projectile-command-map)
(define-key projectile-mode-map (kbd "C-c p r") 'projectile-run-project)
(setq projectile-project-compilation-cmd "")
(setq projectile-project-run-cmd "")
```

**Comment by ddovod** [comment]
Sure, I'll try it today later in the evening. Since you cannot reproduce this on your side, probably some weirdness happens in my config. I'll provide you with more info soon

**Comment by ddovod** [comment]
I've managed to find the cause of this issue, it was this line in the most deep part of my config
```
(shackle-mode 1)
```
I don't know what exactly this thing do, but removing this stuff fixes the problem.
I'm sorry for disturbing you, and thank you very much for your help!

**Comment by mookid** [comment]
cool!
