### ISSUE TITLE
Improve advice for `delete-file`

### ISSUE THREAD

**Issue by Silex** [bbatsov/projectile#1351]
Projectile uses this defadvice for `delete-file`:

``` elisp
(defadvice delete-file (before purge-from-projectile-cache (filename &optional trash))
  (if (and projectile-enable-caching (projectile-project-p))
      (let* ((project-root (projectile-project-root))
             (true-filename (file-truename filename))
             (relative-filename (file-relative-name true-filename project-root)))
        (if (projectile-file-cached-p relative-filename project-root)
            (projectile-purge-file-from-cache relative-filename)))))
```

It does the right thing, except it's very annoying when you delete a huge directory through `dired` for example, because it slows down the deletion by an order of magnitude.

There are several options around this problem:

- Add ability to disable the above advice, and let the user deal with cache invalidation.
- Advice `dired-do-delete` so it disables the `delete-file` advice, perform its task then enable the advice and finally invalidate the cache.

Additionnaly, should the old `defadvice` be ported to `advice-add` & friends?

Anyway, tell me what you reckon is the way forward, I might make a PR.

**Comment by bbatsov** [comment]
Yes, this should be ported to the new mechanism.

**Comment by bbatsov** [comment]
> Add ability to disable the above advice, and let the user deal with cache invalidation.

Probably some defcustom like `projectile-auto-update-cache` or something would be best. I assume we have similar advices for creating/renaming files, so this should control all of them. 

I also planned for this to be temporary and to eventually just listen for filesystem notifications, but I never got to doing this.

**Comment by Silex** [comment]
Continuing in #1357
