### ISSUE TITLE
.dir-locals.el not checked when compiling

### ISSUE THREAD

**Issue by spaceotter** [bbatsov/projectile#1366]
## Expected behavior

Using helm-projectile to compile a project loads the command in .dir-locals.el, and builds the project without having to open any project files.

## Actual behavior

helm-projectile let-binds default-directory and runs projectile-compile-project, which does not load the .dir-locals.el if emacs hadn't already done so, e.g. if you opened a file in the project already.

## Steps to reproduce the problem

Create some project with a special build command, for instance:
```
mkdir -p ~/project
touch ~/project/.projectile
touch ~/project/Makefile
echo '((nil . ((projectile-project-compilation-cmd . "make PECULIAR_OPTION=yes"))))' > ~/project/.dir-locals.el
```
In scratch buffer:
```
(let ((default-directory "/home/eric/project")
      (projectile-project-type 'make))
  (projectile-compile-project nil))
```
C-x C-e to execute. This will give a prompt with just "make". Cancel with C-g
Copy the code in the scratch buffer (M-y)
Open the file ~/project/Makefile.
Run the code again in the context of the Makefile: M-: C-y RET
This gives a prompt with the desired "make PECULIAR_OPTION=yes"

Maybe the approach from #413 could be used.

### Projectile version information

Projectile: 20181217.801
Helm-projectile: 20180815.1514

### Emacs version

Emacs: 26.1

### Operating system

Manjaro linux

**Comment by rileyrg** [comment]
Can we see this address please. I am opening another issue. This is critical stuff for a project group package. I need different compile command for different projects.
