### ISSUE TITLE
Trailing slash in project dir (not exclude) causes ctags to break

### ISSUE THREAD

**Issue by emin63** [bbatsov/projectile#1377]
# Summary

I think the trailing slash problem mentioned in #207 for excludes is also causing a problem for me with the project directory. I think ctags version Exuberant Ctags 5.8 on cygwin does stupid things if the target directory has a trailing slash.

I fixed this by changing `default-directory` in the `projectile-regenerate-tags` function in `projectile.el` to be `(string-remove-suffix "/" default-directory)`.

If this makes sense to you, I can submit a pull-request.

## Expected behavior

projectile-regenerate-tags produces a tags file

## Actual behavior

TAGS file is empty

## Steps to reproduce the problem

Run projectile-regenerate-tags on emacs installed on windows system with cygwin and ctags 5.8 installed.

### Projectile version information

Projectile 20190126.1117

### Emacs version

GNU Emacs 25.3.1 (x86_64-w64-mingw32) of 2017-09-12 with ctags 5.8

### Operating system

Windows 10

**Comment by MoHKale** [comment]
Having the same issue. Also using cygwin, and universal ctags. Though in truth, it was working fine earlier today, I then installed ggtags and then uninstalled it and it stopped working properly. I suspect there's a bigger reason behind this, but problem for another time. If anyones still having this issue, this code block should fix it:

```
(defun projectile-ensure-no-trailing-whitespace-in-root (func &rest args)
  (cl-letf* (((symbol-function 'true-projectile-project-root)
              (symbol-function 'projectile-project-root))
             ((symbol-function 'projectile-project-root)
              (lambda (&rest args)
                ;; TODO maybe don't hardcode file name seperator
                (string-remove-suffix "/"
                                      (apply 'true-projectile-project-root args)))))
    (apply func args)))

(advice-add 'projectile-regenerate-tags :around #'projectile-ensure-no-trailing-whitespace-in-root)
```

**Comment by VimIcewind** [comment]
I add this line(setq projectile-tags-command "ctags -Re -f %s %s .")

**Comment by claritystorm** [comment]
This issue affects `MSYS2`.
