### ISSUE TITLE
projectile-find-file throws stty: stdin isn't a terminal error

### ISSUE THREAD

**Issue by ps2931** [bbatsov/projectile#1379]
When I execute projectile-find-file inside a git enabled project, Emacs complained with an error.

## Expected behavior
Projectile should show me list of files as expected.

## Actual behavior
Received error. With debug-on error on I got this:

Debugger entered--Lisp error: (file-missing "Setting current directory" "No such file or directory" "/Users/pankajsharma/Workspace/lxfella/stty: stdin isn't a terminal\n/")
  call-process("/usr/local/bin/fish" nil t nil "-c" "git submodule --quiet foreach 'echo $path' | tr '\\n' '\\0'")
  apply(call-process "/usr/local/bin/fish" nil t nil ("-c" "git submodule --quiet foreach 'echo $path' | tr '\\n' '\\0'"))
  process-file("/usr/local/bin/fish" nil t nil "-c" "git submodule --quiet foreach 'echo $path' | tr '\\n' '\\0'")
  shell-command-to-string("git submodule --quiet foreach 'echo $path' | tr '\\n' '\\0'")
  projectile-files-via-ext-command("/Users/pankajsharma/Workspace/lxfella/stty: stdin isn't a terminal\n/" "git submodule --quiet foreach 'echo $path' | tr '\\n' '\\0'")
  projectile-get-immediate-sub-projects("/Users/pankajsharma/Workspace/lxfella/stty: stdin isn't a terminal\n/")
  projectile-get-all-sub-projects("/Users/pankajsharma/Workspace/lxfella/stty: stdin isn't a terminal\n/")
  #f(compiled-function (s) #<bytecode 0x40a26b19>)("/Users/pankajsharma/Workspace/lxfella/stty: stdin isn't a terminal\n/")
  mapcar(#f(compiled-function (s) #<bytecode 0x40a26b19>) ("/Users/pankajsharma/Workspace/lxfella/stty: stdin isn't a terminal\n/"))
  projectile-get-all-sub-projects("/Users/pankajsharma/Workspace/lxfella/")
  projectile-get-sub-projects-files("/Users/pankajsharma/Workspace/lxfella/" git)
  projectile-dir-files-alien("/Users/pankajsharma/Workspace/lxfella/")
  projectile-project-files("/Users/pankajsharma/Workspace/lxfella/")
  projectile--find-file(nil)
  projectile-find-file(nil)
  funcall-interactively(projectile-find-file nil)
  call-interactively(projectile-find-file nil nil)
  command-execute(projectile-find-file)

## Steps to reproduce the problem

;;;;;;; init.el starts

;; utf-8 everywhere
(set-terminal-coding-system 'utf-8)
(set-keyboard-coding-system 'utf-8)
(set-selection-coding-system 'utf-8)
(prefer-coding-system 'utf-8)

(setq inhibit-splash-screen t
      initial-scratch-message nil
      initial-major-mode 'org-mode)

(when (fboundp 'menu-bar-mode) (menu-bar-mode -1))
(when (fboundp 'tool-bar-mode) (tool-bar-mode -1))
(when (fboundp 'scroll-bar-mode) (scroll-bar-mode -1))

(require 'projectile)
(projectile-mode +1)
(define-key projectile-mode-map (kbd "s-p") 'projectile-command-map)
(define-key projectile-mode-map (kbd "C-c p") 'projectile-command-map)

;;; init.el ends here

cd into a git enabled project, start emacs and do M-x projectile-find-file

### Projectile version information
Projectile 20190126.1117

### Emacs version
Emacs 26.1 (build 1, x86_64-apple-darwin17.5.0, NS appkit-1561.40 Version 10.13.4 (Build 17E202))

### Operating system
MacOS 10.13.6

**Comment by ps2931** [comment]
Another thing I notices is after invoking Emacs from terminal in my home directory when I execute projectile-find-file I got this:

![image](https://user-images.githubusercontent.com/6301789/52517045-e4dedb80-2c5a-11e9-8256-04967fadd6a2.png)

But if I am executing projectile-find-file from a git repo I am receiving error:

Debugger entered--Lisp error: (file-missing "Setting current directory" "No such file or directory" "/Users/pankajsharma/src/ripgrep/stty: stdin isn't a terminal\n/")
  call-process("/usr/local/bin/fish" nil t nil "-c" "git submodule --quiet foreach 'echo $path' | tr '\\n' '\\0'")
  apply(call-process "/usr/local/bin/fish" nil t nil ("-c" "git submodule --quiet foreach 'echo $path' | tr '\\n' '\\0'"))
  process-file("/usr/local/bin/fish" nil t nil "-c" "git submodule --quiet foreach 'echo $path' | tr '\\n' '\\0'")
  shell-command-to-string("git submodule --quiet foreach 'echo $path' | tr '\\n' '\\0'")
  projectile-files-via-ext-command("/Users/pankajsharma/src/ripgrep/stty: stdin isn't a terminal\n/" "git submodule --quiet foreach 'echo $path' | tr '\\n' '\\0'")
  projectile-get-immediate-sub-projects("/Users/pankajsharma/src/ripgrep/stty: stdin isn't a terminal\n/")
  projectile-get-all-sub-projects("/Users/pankajsharma/src/ripgrep/stty: stdin isn't a terminal\n/")
  #f(compiled-function (s) #<bytecode 0x41176665>)("/Users/pankajsharma/src/ripgrep/stty: stdin isn't a terminal\n/")
  mapcar(#f(compiled-function (s) #<bytecode 0x41176665>) ("/Users/pankajsharma/src/ripgrep/stty: stdin isn't a terminal\n/"))
  projectile-get-all-sub-projects("/Users/pankajsharma/src/ripgrep/")
  projectile-get-sub-projects-files("/Users/pankajsharma/src/ripgrep/" git)
  projectile-dir-files-alien("/Users/pankajsharma/src/ripgrep/")
  projectile-project-files("/Users/pankajsharma/src/ripgrep/")
  projectile--find-file(nil)
  projectile-find-file(nil)
  funcall-interactively(projectile-find-file nil)
  call-interactively(projectile-find-file nil nil)
  command-execute(projectile-find-file)

**Comment by ps2931** [comment]
Never mind! 
The issue has been resolve by running brew update.

**Comment by borkdude** [comment]
@ps2931 Can you tell me what you did exactly to fix this? What did you upgrade with brew? I'm running into the exact same issue.

**Comment by ps2931** [comment]
Not able to recollect exactly, but as far as I remember, the issue was due to a missing macOS package. I messed my macOS installation somehow and hence was getting the error. 

Try `brew upgrade`

**Comment by borkdude** [comment]
In my case it was due to a

```
stty icrnl
```

in my .zshrc. I put it there because of some problems with `rlwrap`.
