### ISSUE TITLE
Projectile after switch hook gets old projectile-project-root 

### ISSUE THREAD

**Issue by dcaixinha** [bbatsov/projectile#1397]
## Expected behavior

When hooking into the `projectile-after-switch-project-hook`, I expected `projectile-project-root` to contain the name of the new project (the one we're switching into).

## Actual behavior

It contains the name of the old project (where we switched from)

## Steps to reproduce the problem

Running this snippet:

```
  (defun my-projectile-hook ()
    "My projectile hook."
    (interactive)
    (message (concat "Current project root is " (projectile-project-root))))

  (add-hook 'projectile-after-switch-project-hook #'my-projectile-hook)
```

On the first run (after starting Emacs), after switching to project A I get a blank project root. When I switch from project A to project B, the hook prints the project A root. 

### Projectile version information

```
Projectile version: 2.0.0
```

### Emacs version

```
Emacs version: 26.1
```

### Operating system

```
OS version: Ubuntu LTS 18.04.2
```

**Comment by dcaixinha** [comment]
Bumping this so the stale bot doesn't close it. Am I the only one observing this? :thinking:

**Comment by stardiviner** [comment]
I have this issue too.

**Comment by dcaixinha** [comment]
Bumping this so the stale bot doesn't close it. Apparently I'm not the only one facing this, so I think it's better to leave it open.

**Comment by seijikun** [comment]
I just had a similar problem, and was able to resolve it.
In my case, it was an unfavorable interaction between doom-emacs's workspaces and projectile.
If you are on a managed emacs instance, such as doom-emacs, it might proove useful to look at what they do in the background. (e.g. in my case: [this](https://github.com/hlissner/doom-emacs/blob/220916ae17fe9d561b81e7a5268d2135ec56eac6/modules/ui/workspaces/autoload/workspaces.el#L516))
