### ISSUE TITLE
Behavior of `replace-regexp-read-args` for `projectile-replace-regexp`

### ISSUE THREAD

**Issue by TobiasZawada** [bbatsov/projectile#1399]
See [the question about "Elisp expressions in projectile-replace-regexp" on emacs.stackexchange.com](https://emacs.stackexchange.com/q/48762/2370).

Interactive calls of `projectile-replace-regexp` do not have the features of interactive calls of `replace-regexp`. For an instance evaluating lisp forms with `\,(...)` is not possible.

## Potential solutions

1st) Use `query-replace-read-from` and `query-replace-read-to` instead of `read-string` in `projectile-replace-regexp`.

2nd) If 1st is not an option for any reason then at least apply `query-replace-compile-replacement` to [the `new-string` argument of `tags-query-replace`](https://github.com/bbatsov/projectile/blob/5bd9db6f4b0a9e1c27136561b134a4d119552cdb/projectile.el#L3414). That is still a slight incompatibility to the behavior of `replace-regexp` but maybe more acceptable than the current behavior.

BTW: Note, that I consider it very strange that `projectile-replace-regexp` does not read user input in its interactive form but in its body. But, I am not a user of `projectile`. So it may be that I do not fully comprehend the meaning of such commands.

## Expected behavior
Lisp forms like `\,(downcase \1)` work in interactive calls of `projectile-replace-regexp`.

## Actual behavior
One gets the error

`Invalid use of ‘\’ in replacement text`

## Steps to reproduce the problem

Just a look on the source code is sufficient for diagnosing this problem.

## Environment & Version information

https://github.com/bbatsov/projectile/blob/5bd9db6f4b0a9e1c27136561b134a4d119552cdb/projectile.el#L3389-L3414

### Projectile version information

From master source code on April, 5th 2019.

### Emacs version

26.1

**Comment by sollidsnake** [comment]
I'm the one who posted the question on emacsexchange. The solution provided by @TobiasZawada on his answer worked for me, so that might be a starting point for a fix. If I can help with anything just let me know.
