### ISSUE TITLE
Alien indexing fails for Git repositories with submodules on Windows

### ISSUE THREAD

**Issue by nigredo-tori** [bbatsov/projectile#1411]
## Expected behavior

Projectile indexes git repositories with submodules.

## Actual behavior

Projectile fails to index:
```
Projectile is initializing cache...
In ‘Projectile files’ source: ‘#[0 \301 \205;\0r\302!\203\0\206\0p\211q\210\303 \304 \305\211:\2036\0@\262\306"BB\262A\262\202\0\211\237\266\204)\207 [helm-current-buffer projectile-project-p buffer-live-p projectile-project-root projectile-current-project-files nil expand-file-name] 8]’ 
 (file-missing "Setting current directory" "No such file or directory" "c:/dev/tmp/foo/echo $path: -c: line 0: unexpected EOF while looking for matching `''
echo $path: -c: line 1: syntax error: unexpected end of file
fatal: run_command returned non-zero status for projectile
```

## Steps to reproduce the problem

1. Init the repository and the submodule.
    ```bat
    > git init
    > git submodule add https://github.com/bbatsov/projectile projectile
    ```
1. Enable alien indexing mode.
    ```lisp
    (setq projectile-indexing-method 'alien)
    ```
1. Navigate to the repository.
1. Trigger indexing (`C-c p f`).
1. Indexing fails.

## Environment & Version information

git version 2.19.1.windows.1
[GNU CoreUtils 5.3.0](https://chocolatey.org/packages/gnuwin32-coreutils.install)

### Projectile version information

Projectile 20190416.1458

### Emacs version

GNU Emacs 26.1 (build 1, x86_64-w64-mingw32) of 2018-05-30

### Operating system

Windows 10

### Workaround

This fixes the issue:
```lisp
(setq projectile-git-submodule-command "git submodule --quiet foreach \"echo $sm_path\" | tr '\\n' '\\0'")
```
(note `$sm_path` instead of `$path`, and double quotes instead of the single ones).

**Comment by nigredo-tori** [comment]
Bump.

**Comment by Holt59** [comment]
I have a similar issue with emacs 26.3 on Windows. The error I get when indexing git project with submodules is:

> Projectile is initializing cache for c:/Users/mikael.capelle/.emacs.d/ ...
apply: Setting current directory: No such file or directory, c:/Users/mikael.capelle/.emacs.d/fatal: No url found for submodule path 'site-elisp/aweshell' in .gitmodules

My `projectile` configuration is as follow:

```elisp
(use-package projectile
  :bind
  ("C-c p" . projectile-command-map)
  ("C-z o" . projectile-find-file)
  ("C-z p" . projectile-add-known-project)
  :custom
  (projectile-completion-system 'ivy)
  :config
  (projectile-mode 1)
  (when (and *sys/win32* *tr*)
    (setq projectile-indexing-method 'alien))
  (add-to-list 'projectile-globally-ignored-directories "node_modules"))
```

**Comment by dacap** [comment]
Still an issue, the problem is with the `projectile-git-submodule-command` variable, if you `(setq projectile-git-submodule-command nil)` you will be able to use projectile in the current git repository without listing submodules files. I've tried other possible commands like:

    (setq projectile-git-submodule-command "git submodule--helper list | cut -f2")

but still not working.
