### ISSUE TITLE
Using empty .projectile file to mark a folder a project does not work

### ISSUE THREAD

**Issue by dadinn** [bbatsov/projectile#1416]
## Expected behavior
Target directory has an empty .projectile file placed in it. I would expect projectile to allow me to select any of the files under the target directory. Except files listed in projectile-globally-ignored-files.

## Actual behavior (Steps to reproduce the problem)
Placed a .projectile file inside the target directory, started up Emacs, and opened a file in the directory. On the status line I could see that projectile recognized the directory as project, on the other hand, when trying to use projectile to open other project files, nothing autocompletes (I am using ido-mode for autocompletion).

Once restarting Emacs, and looking up projectile projects (C-c p p), then the target directory is listed. Once selected, and asked to choose a file in the project, no files under the directory are offered, just like earlier.

## Environment & Version information
debian-version 9.9
emacs-version 25.1.1
projectile-version 2.0.0

**Comment by shadowphoton** [comment]
I think I have similar issue as it matches everything you've described, only when I try to select a directory **I get this error**
`[helm-current-buffer projectile-project-p buffer-life-p projectile-project-root projectile-current-project-files nil expand-file-name] 8]'
  (file-missing "Setting current directory" "No such file or directory" "$HOME/projectpath/fatal: not a git repository (or any parent up to mount point /) Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set)./")`

I find that if you **set your indexing method to native** the issue should go away
`(setq projectile-indexing-method 'native)`
**However**, I really don't like native indexing method, so I'm interested in how this issue develops.

**I'm using**
projectile version 20190604.630
helm-projectile 20190408.1508
helm 20190612.713
emacs 26.2-1
and Arch linux

**Comment by legendary-mich** [comment]
A "hybrid" indexing method will also do. It's a new method added in projectile 2.0 which replaced the "alien" one.

https://github.com/bbatsov/projectile/blob/master/CHANGELOG.md#200-2019-01-01
https://projectile.readthedocs.io/en/latest/configuration/#project-indexing-method

```emacs-lisp
(setq projectile-indexing-method 'hybrid)
```

I've also found a note that the contents of .projectile are ignored when using the (new) alien project indexing method. But it does not tell you that if the file is empty its content is also ignored.
https://projectile.readthedocs.io/en/latest/projects/#ignoring-files

**Comment by rileyrg** [comment]
Still not working. Alien indexing. Created a new C project, created a .projectile. Doesn't recognise it. Of all the "root" files this surely should be the one that works at all times.
