### ISSUE TITLE
Using a regexp as project marker

### ISSUE THREAD

**Issue by galdor** [bbatsov/projectile#1428]
I'm trying to add support for Common Lisp projects. They are nowadays based on one or more ASDF systems, which means that a project can be identified by a file matching `.*?\.asd$`. However reading the source code of Projectile, it does not seem possible to use a regexp as marker file. Am I missing something ?

**Comment by Gastove** [comment]
@galdor I was just reading to code to try and answer the same question for a custom mode I wanted to register, and it in fact appears that the marker file lists can instead be functions. Vis:

```
(projectile-register-project-type 'haskell-cabal #'projectile-cabal-project-p
                                  :compile "cabal build"
                                  :test "cabal test"
                                  :test-suffix "Spec")
```

Non-`nil` means "not this kind of project."
