### ISSUE TITLE
projectile can't identity .NET Core project root

### ISSUE THREAD

**Issue by stardiviner** [bbatsov/projectile#1432]
## Actual behavior

I have open a dotnet project file `Program.cs`, omnisharp auto start server.
```
omnisharp: starting server on project root: "/home/stardiviner/"
```
But my Program.cs is under /home/stardiviner/Documents/learning/.NET/myApp/Program.cs

It should identify project root on `/home/stardiviner/Documents/learning/.NET/myApp/`.

I checked out part of projectile source code. Seems does not handle this case. Because .NET Core project doesn't have a static project filename. It's dependent on project name which is `myApp.csproj`. I guess projectile can add an advanced function to detect this and add in custom variable `projectile-project-root-files-functions`.

FOr now, I have to manually add `.projectile` to let projectile works.

### Projectile version information

```
Projectile version: Projectile 20190624.1802
```

### Emacs version

GNU Emacs 27.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.5) of 2019-02-22

### Operating system

Arch Linux

**Comment by bbatsov** [comment]
Something like this is easy to implement with `projectile-verify-file-wildcard`. We basically need the same thing we did for cabal projects. (see `projectile-cabal-project-p`).

**Comment by stardiviner** [comment]
Here is my code, if need, I can create a PR.
```elisp
(defun projectile-dotnet-project-p ()
    (or (projectile-verify-file-wildcard "?*.csproj")
        (projectile-verify-file-wildcard "?*.fsproj")))
  (projectile-register-project-type 'dotnet #'projectile-dotnet-project-p
                                    :compile "dotnet build"
                                    :run "dotnet run"
                                    :test "dotnet test")
```
