### ISSUE TITLE
Projectile menu extremely long - patch to re-organise a bit attached

### ISSUE THREAD

**Issue by jtl5770** [bbatsov/projectile#1447]
Projectiles menu is longer than the height of my emacs frame on a full-hd screen... That is pretty distracting when it starts to hide part of the menubar because it grows upwards... And I think it is also easy to get lost in it.

I attached a patch as a suggestion to put things into sub menus. Maybe the order can be better, I am not yet a pro with projectile and all it has to offer.

(this is with emacs 26.3 on linux, projectile up-to-date from melpa)

[projectile.patch.txt](https://github.com/bbatsov/projectile/files/3644530/projectile.patch.txt)

**Comment by jtl5770** [comment]
OK, this has been auto-closed... reopening it to maybe get it in the spotlight again :-) Just close as wontfix or so if you don't consider this a problem.

**Comment by bbatsov** [comment]
I've missed this ticket and no one else commented on it for quite a while. Can you share a screenshot comparison before/after your proposed changes?

**Comment by bbatsov** [comment]
Just checked the menu myself and it's huge indeed. I'm not sure that "Project", "File" and "Buffer" are good top-level menus, though. E.g. everything in Projectile is related to a project. I was thinking of something like "Find", "Run", "Build". Not sure where to stuff the rest of the commands, though.

**Comment by jtl5770** [comment]
I assume you will know best what categories to choose... In my opinion it could be good to distinguish between actions on something like the current project and stuff that cares about the whole set of projects.. But there are multiple organization principles possible. I just can't stand seeing this huge menu on the screen :-)

**Comment by jtl5770** [comment]
I was about suggest to be able to completely hide the menu via a defcustom on top of reorganising it, but I saw that there is already a issue open about it #1712

**Comment by bbatsov** [comment]
I did a first pass at this. I'll polish the sections more down the road. Thanks for reviving this issue!
