### ISSUE TITLE
How to prefer one project over another?

### ISSUE THREAD

**Issue by grantjenks** [bbatsov/projectile#1449]
Love the project. Thanks much! Not sure if there's a better place for this simple question.

What happens when there are projects in parents and subdirectories? Suppose I have:

```
foo/.git/...  <-- Indicates project "foo"
foo/bar/setup.py  <-- Indicates project "bar"
foo/bar/baz.py  <-- Opened file.
```

When I open baz.py how do I get projectile to associate that with project "bar" rather than with project "foo". How do I control the projectile project-matching order?

**Comment by muradm** [comment]
Same here for complex gradle project with submodules. There is one `build.gradle` file in project root, but submodules get their own projects:
```
~/some/project/build.gradle
~/some/project/module/program/src/main/java/<....>/Main.java
~/some/project/library/src/main/java/<....>/Library.java
```
`build.gradle` opens in project `~/some/project`, `Main.java` opens in project `~/some/project/module/program`, `Library.java` opens in project `~/some/project/library`.
How to set preference? or avoid `sub-projects`?

**Comment by jsoo1** [comment]
I have this too. I have a git repo of org files that lives in $HOME and no subdirectory projects are honored.

**Comment by jsoo1** [comment]
For reference, I found that modifying `projectile-project-root-files-functions` fixed my problem. I haven't used it for long but I added moved `projectile-root-bottom-up` to the last option:

```emacs-lisp
   (setq
     projectile-project-root-files-functions '(projectile-root-local
                                               projectile-root-top-down
                                               projectile-root-top-down-recurring
                                               projectile-root-bottom-up)))
```

**Comment by bbatsov** [comment]
@jsoo1 Yeah, generally that's the way to go - by default the assumption is that closest project match is the one you want, but obviously different use-cases exist. Probably we should cover this in more details in the docs.

**Comment by bbatsov** [comment]
I've added some details to the docs https://docs.projectile.mx/projectile/projects.html#customizing-project-detection I hope this helps.
