### ISSUE TITLE
Can `projectile-find-file` sort completion by recently opened files?

### ISSUE THREAD

**Issue by gamb** [bbatsov/projectile#1453]
Basically want a single key combo that I can use to switch between recent buffers in the project and open new files as required (e.g. in VSCode Cmd+P will popup with recently opened files). Tried updating `projectile-completion-system` to Ivy / Ido without success.

**Comment by gamb** [comment]
Hacking around with the prompt this basically works:
```elisp
(file (projectile-completing-read "Find file: "
    (append (projectile-recentf-files) (projectile-project-files project-root))))
```
Caveat that you need to save a file for it to appear in recentf

**Comment by DanielVartanov** [comment]
Can I re-open this, please? It appears to be the most impeding issue so far, even setting `projectile-sort-order` does not fix the problem, can I have a hint on how do I investigate/fix the issue further?

**Comment by bbatsov** [comment]
@DanielVartanov You noticed that the sort order is not applied by for alien indexing, right? (for performance reasons)

**Comment by DanielVartanov** [comment]
sorry mate! I somehow thought `hybrid` was the default one :facepalm:
