### ISSUE TITLE
Please add "WORKSPACE" as a project marker

### ISSUE THREAD

**Issue by gorakhargosh** [bbatsov/projectile#1465]
Could you please add "WORKSPACE" files as a project marker?
The Bazel build system uses this file to indicate the root directory of a
project.

Thank you for an awesome tool! :)

[Bazel Usage](https://docs.bazel.build/versions/master/build-ref.html)

**Comment by Silex** [comment]
You can modify `projectile-project-root-files` to add WORKSPACE yourself. That or create a `.projectile` file in your root directory.

Try this: `(add-to-list projectile-project-root-files "WORKSPACE")`.
