### ISSUE TITLE
projectile not respecting .projectile file when file searching

### ISSUE THREAD

**Issue by hisnawi** [bbatsov/projectile#1469]
## Expected behavior
When executing projectile-find-file to only show files allowed within .projectile file

# Actual behavior
All filed in project directory are showing

## Steps to reproduce the problem
In my .projectile file I have this format:
+/dir1
+/dir2

But when using projectile-find-file emacs wont only show hits in these directories but in all files in project.

*This is extremely important! Providing us with a reliable way to reproduce
a problem will expedite its solution.*

## Environment & Version information
MacOS Mojave

### Projectile version information
Latest version as of this morning.
(Projectile 20191024.721)

### Emacs version
GNU Emacs 27.0.50 (build 1, x86_64-apple-darwin17.2.0, NS appkit-1561.10 Version 10.13.1 (Build 17B48))

### Operating system
MacOS

**Comment by visortelle** [comment]
@hisnawi how did you solve this issue? I have the same problem.
