### ISSUE TITLE
projectile-find-file not working for .gitignored directories despite them being unignored

### ISSUE THREAD

**Issue by rileyrg** [bbatsov/projectile#1475]
projectile-globally-unignored-directories is a variable defined in ‘projectile.el’.
Its value is ("/vendor/")

(tried vendor/ and vendor too)

vendor is gitignored and I have tried to enable it as a search candidate by using the setting above. Indexing is off and indexing method is, if relevant, set to alien in case its used elsewhere for search algorithms.

So: how do I enable projectile to search gitgnored subdirectories. In this case I want it to search the symfony vendor subdirectory.

**Comment by spaceotter** [comment]
I just ran into this.

It does not seem like unignoring is supposed to work in alien mode. See the documentation for projectile-indexing-method.

However, hybrid mode doesn't work either. There is a mistake in projectile-keep-ignored-directories. I'm working on a pull request.

**Comment by cdarken** [comment]
I can't make this work for the life of me. It's driving me crazy. I'm using projectile with Doom Emacs. I've the variable, I can see that it's set when I inspect vars, but still can't find a file located in my `vendor` directory.
