### ISSUE TITLE
Ability to include git-ignored file

### ISSUE THREAD

**Issue by harob** [bbatsov/projectile#148]
I have several files of personal notes pertaining to a project that I do not want to be checked into the remote repo, so I have them git-ignored (in project_root/.git/info/exclude)

However, I would like these to be accessible via projectile. Is there any way to achieve this? I would be happy to whitelist them in a .projectile file, but that would cause all other files to be excluded.

Thank you for the great work on Projectile, it's a great project!

**Comment by samertm** [comment]
@bbatsov This is can be closed, as it doesn't require any changes.

**Comment by chadhs** [comment]
just to help other folks googling for this; here's an example from my emacs config:

```elisp
(setq projectile-globally-unignored-files
      (append '(
		"profiles.clj"
		)
	      projectile-globally-unignored-files))
```

you can then verify that has been set by placing your cursor on the `projectile-globally-unignored-files` and pressing meta x and typing the command `describe-variable`

cheers!
