### ISSUE TITLE
projectile-find-file displays duplicate files

### ISSUE THREAD

**Issue by anildigital** [bbatsov/projectile#1490]
projectile-find-file displays duplicate files

## Expected behavior
Show only one file 
`config/dev.exs`

## Actual behavior

<img width="321" alt="image" src="https://user-images.githubusercontent.com/266/73268456-fbca6500-4200-11ea-9c67-d9f8a8b37b7e.png">

## Steps to reproduce the problem

Use Projectile with any git-based project. (I also use Treemacs)

## Environment & Version information

Treemacs Version - [Treemacs] v2.7-2020.01.28 @ 26.3

### Projectile version information

*Include here the version string displayed by `M-x
projectile-version`. Here's an example:*

```
Projectile version: Projectile 20200125.1343
```

### Emacs version

GNU Emacs 26.3 (build 1, x86_64-apple-darwin18.2.0, NS appkit-1671.20 Version 10.14.3 (Build 18D109)) of 2019-09-02

### Operating system

macOS Catalina 10.15.2

**Comment by bbatsov** [comment]
Is there something special about your project (e.g. using git submodules)? I can't reproduce this problem in a simple Git repo.

**Comment by pawciobiel** [comment]
I have similar problem.
`GNU Emacs 29.4 (build 1, x86_64-pc-linux-gnu) of 2024-10-31`
```
projectile                     20241022.858   installed
counsel-projectile             20211004.2003  installed
counsel                        20240520.1323  installed
ivy                            20240829.1723  installed
ivy-rich                       20230425.1422  dependency
```

Clearing cache didn't help.
Previous version worked OK with `helm` and `helm-projectile` so I suspect it is more related to `counsel` and `counsel-projectile`
