### ISSUE TITLE
Please provide an offline manual

### ISSUE THREAD

**Issue by brandelune** [bbatsov/projectile#1492]
It does not seem possible to access the manual on an offline machine.

It would be nice to have either a pdf or info manual to refer to.

**Comment by bbatsov** [comment]
The manual is currently build with MkDocs. We'll have to check if it provides some export options.

**Comment by Silex** [comment]
https://github.com/zhaoterryy/mkdocs-pdf-export-plugin

Just a google-fu, no clue how well it works.

**Comment by brandelune** [comment]
It was mentioned in this thread:
[pdf export? #374](https://github.com/mkdocs/mkdocs/issues/374)

**Comment by bbatsov** [comment]
I guess you can try it locally. The problem for me is that I wanted to avoid having to setup some job for generating and publishing the manual, therefore the choice of ReadTheDocs. At some point it provided options to generate automatically epub and pdf versions of the docs, but this didn't work well with MkDocs and got removed. I've short on time for Projectile lately and I hadn't done much on the docs front for a while now. Help is always welcome.

**Comment by brandelune** [comment]
Thank you for your reply. Just providing a 1 page html manual would go a long way. I just need to save the manual offline so that I can check it when I am not connected.

**Comment by spwhitton** [comment]
In Debian distributions you can `apt-get install projectile-doc` to get an offline manual.

**Comment by brandelune** [comment]
Thank you for the reminder. Yet, emacs doesn't run exclusively on debian based distributions so it would be nice to have something from the repository.

**Comment by AndersonTorres** [comment]
Can it be exported for the more standardized Info format? After all, it is an Emacs software.

**Comment by bbatsov** [comment]
I'm afraid there's nothing that can do a decent conversion from Markdown to Texinfo currently. Perhaps someone can play with pandoc? 

I've avoided using Texinfo directly for two reasons:

* most people don't know/like it (I personally don't like it much)
* you can't get with it good web version of the docs
* these days most people look for docs online first anyways; I rarely use the texinfo docs myself even though I've been using Emacs for 15 years now

I have it on my TODO to eventually convert the docs to AsciiDoc, which will solve the export to PDF issue, but I doubt that's going to happen any time soon.

**Comment by AndersonTorres** [comment]
If it is to be converted on Asciidoc, why not Org Mode?

**Comment by bbatsov** [comment]
I'm more comfortable with AsciiDoc, as I use it for other projects, but I'm fine with Org Mode if someone wants to deal with this. I'm not sure how complicated the web publishing pipeline would be with org, but I guess there are some options.

**Comment by AndersonTorres** [comment]
I will do some search on it, then!

**Comment by bbatsov** [comment]
I've recently converted the manual to AsciiDoc and Antora. Seems they are still figuring out PDF exports, but I guess there will be something soon https://gitlab.com/antora/antora/-/issues/349
