### ISSUE TITLE
"Warning: Failed to set locale category LC_TIME to en_JP.UTF-8." when doing 

### ISSUE THREAD

**Issue by brandelune** [bbatsov/projectile#1493]
##  Expected behavior
→ open file

## Actual behavior
→ error message is spit

## Steps to reproduce the problem
→ either call projectile-find-file with M-x or from the assigned shortcut

## Environment & Version information
Running an EN system in Japan. The local is not standard (en_JP) but not illegal.

### Projectile version information
Projectile 20200128.1155

### Emacs version
GNU Emacs 28.0.50 (build 3, x86_64-apple-darwin19.2.0, NS appkit-1894.20 Version 10.15.2 (Build 19C57)) of 2020-02-01

### Operating system
macos 10.15.2

**Comment by bbatsov** [comment]
This warning is generated from the external command that Projectile ran to obtain the list of project files (e.g. `git` or `find`). I'm guessing you should tweak something in your local config to address the warning.

**Comment by brandelune** [comment]
Yes, but I'm only asking projectile to open a file, not to check whether my locale is correct or not, plus it refuses to open the file after the error is spit. git works fine with the locale and all the other commands work fine too. The locale is valid and projectile should ignore such error messages.
