### ISSUE TITLE
.projectile not works

### ISSUE THREAD

**Issue by paopaol** [bbatsov/projectile#1502]
i have a git repo clone from network,in a sub directory, i touched a file named .projectile.
 But the root directory is still the directory where .git is located.

## Expected behavior

Change the root directory from the directory where .git is located to the directory where .projectile is located 

### Projectile version information

```
Projectile version: 2.1.0
```

### Emacs version

27

### Operating system

ubuntu 18.04

**Comment by viocost** [comment]
Observing same issue on version 2.2.0. Any updates on this?

**Comment by czikus** [comment]
Same issue here. How can a project with multiple git repos in it be added?

**Comment by Silex** [comment]
Projectile will find the root of the project to be the first parent directory where it encounters a "root file" (.git, .projectile, etc).

So if you do `projectile-find-file` from the root directory it'll behave as expected. If you do it from within the subfolder where .git it it'll think the project root is the subfolder.

To avoid that the only thing I see is temporarily removing `.git` from the list of project root files.

**Comment by bbatsov** [comment]
As noted in the docs - the list of functions used to identify the project root is configurable - https://docs.projectile.mx/projectile/projects.html#customizing-project-root-files

```
(defcustom projectile-project-root-files-functions
  '(projectile-root-local
    projectile-root-bottom-up
    projectile-root-top-down
    projectile-root-top-down-recurring)
  "A list of functions for finding project roots."
  :group 'projectile
  :type '(repeat function))

```

You can reoder the functions in it or replace them with something that suits your use-cases.
