### ISSUE TITLE
Support for ant / build.xml

### ISSUE THREAD

**Issue by mandarm** [bbatsov/projectile#1506]
I'm probably missing something really obvious, but is there some reason why the following is not in projectile already? Note I'm a Java newbie and am not at all sure about ```src-dir``` and ```test-dir``` below.

```
  (projectile-register-project-type 'ant '("build.xml")
                                    :compile "ant"
                                    :test "ant test"
                                    :src-dir "*/src/java"
                                    :test-dir "*/src/test/")
```

## Environment
Package-Version: 20200206.1749
Version: 2.2.0-snapshot
(projectile-version doesn't seem to be working for me)

### Emacs version
26.3

### Operating system
Linux Mint 19 kernel 4.15.0-20

**Comment by bbatsov** [comment]
I guess `ant` is just not as popular these days. PR welcome! :-)

**Comment by mandarm** [comment]
Sure, sounds fine. Closing.
