### ISSUE TITLE
Any plan for customization of the required ripgrep package?

### ISSUE THREAD

**Issue by condy0919** [bbatsov/projectile#1511]
There are three ripgrep packages in melpa:

- [`rg`](https://github.com/dajva/rg.el/tree/e19c06f4c556bda6457da3d50c14b12cb97679d9)
- [`deadgrep`](https://github.com/Wilfred/deadgrep/tree/3ec95398d09719a9dbdc3a67d29d22ca224516cf)
- [`ripgrep`](https://github.com/nlamirault/ripgrep.el/tree/40e871dcc4519a70981e9f28acea304692a60978)

`ripgrep` is required in `projectile`, but user may use `rg` or `deadgrep`. Installing two ripgrep packages is redundent.

Wish it could be customized. Thanks alot.

**Comment by bbatsov** [comment]
What kind of customization do you have in mind? Projectile already has some integration with the `ripgrep` package.

**Comment by condy0919** [comment]
Let user choose which ripgrep implementation package can be used.

**Comment by bbatsov** [comment]
That's fine by me. PR welcome. :-)
