### ISSUE TITLE
projectile-ag: ignores not in effect

### ISSUE THREAD

**Issue by e-user** [bbatsov/projectile#1514]
## Expected behavior
Running `projectile-ag` honors `projectile-globally-ignored-directories` and `projectile-globally-ignored-files`, so that affected files and directories don't turn up in the resulting `ag` query.

## Actual behavior
`ag` is run without any `--ignore` parameters set and ignored files and directories turn up.

Looking at the code, it's obvious that while `ag-ignore-list` is being bound in `projectile-ag`, it's not passed down to `(funcall ag-command search-term (projectile-project-root)))`.

## Steps to reproduce the problem

1. `mkdir foo; cd foo; git init; mkdir node_modules; echo bar > node_modules/baz`
2. `(add-to-list 'projectile-globally-ignored-directories "node_modules")`
3. `M-x projectile-ag RET bar RET`

### Projectile version information

Projectile 2.0.0

### Emacs version

GNU Emacs 26.3 (build 1, x86_64-redhat-linux-gnu, GTK+ Version 3.24.13) of 2019-12-10

### Operating system

Fedora 31 Silverblue x86_64

**Comment by e-user** [comment]
This is still an issue, unchanged.

**Comment by bbatsov** [comment]
Yeah, it'd be nice to improve this. The required changes are pretty simple.
