### ISSUE TITLE
consider allowing comments in .projectile file

### ISSUE THREAD

**Issue by pipehat** [bbatsov/projectile#1522]
I'd like to be able to add comments in my .projectile file to clarify what some of the ignore patterns are for. Similar to .gitignore. Perhaps, e.g.:

```
-- .projectile ----------------------
# ignore emacs auto save stuff
-*~
-.#
```

Looks like this could be done with another pcase clause in projectile-parse-dirconfig-file.

**Comment by bbatsov** [comment]
Yeah, I think that's a nice idea and something that'd be pretty easy to implement.
