### ISSUE TITLE
Compilation directory gets not set correnctly in Emacs 27

### ISSUE THREAD

**Issue by FlexW** [bbatsov/projectile#1524]
## Expected behavior
Compile project in specified build directory.

## Actual behavior
Compiles project from project root directory.

## Steps to reproduce the problem
I've configured a cmake project in my init.el with
```lisp
(use-package projectile
  :config
  (progn
    (projectile-mode +1)

    ;; Register CMake projects. Projects with CMakeLists.txt file will
    ;; be recognized
    (defun weilbach/cmake-compile-command ()
      "Return a String representing the compile command to run for the given context."
      (cond
       ((and (or (eq major-mode 'c++-mode) (eq major-mode 'c-mode))
             (not (string-match-p (regexp-quote "\\.*/test/\\.*") (buffer-file-name (current-buffer)))))
        "cmake --build .")
       ))

    (defun weilbach/cmake-configure-command ()
      "Return a String representing the configure command to run for the given context."
      (cond
       ((or (eq major-mode 'c++-mode) (eq major-mode 'c-mode))
        "cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=1 -DCMAKE_BUILD_TYPE=Debug -G Ninja ..")
       ))

    (projectile-register-project-type 'cmake '("CMakeLists.txt")
                                      :compilation-dir "build"
                                      :configure 'weilbach/cmake-configure-command
                                      :compile 'weilbach/cmake-compile-command
                                      :src-dir "src"
                                      :test-dir "tests"
                                      )
    )
  :bind
  (("M-p" . projectile-command-map)
   ("C-c p" . projectile-command-map)
   ("<f5>" . projectile-compile-project)
   ("C-<f5>" . projectile-run-project)))
```
If I then open a file from my cmake project and run `projectile-compile-project` then the project starts to compile but it compiles (most of the time) in the wrong directory (compiles in project root). If I run the `projectile-compile-project` a few times behind each other it sometimes runs the compile command from the correct compilation directory.

I'm not an elisp pro but I have debugged this a bit and found out that projectile seems to set `default-directory` for the `compile` function in `projectile--run-project-cmd` to run the compilation in the correct directory. However it seems that `default-directory`gets set in a `let*` binding. If I instead set in `projectile--run-project-cmd` `default-directory` with `setq-default` I get no errors anymore when compiling (it then always compiles in the correct directory). 

### Projectile version information
```
Projectile version: 20200427.1153
```

### Emacs version
GNU Emacs 27.0.90 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.17, cairo version 1.17.3)
 of 2020-04-05

### Operating system
ArchLinux

**Comment by bbatsov** [comment]
> I'm not an elisp pro but I have debugged this a bit and found out that projectile seems to set default-directory for the compile function in projectile--run-project-cmd to run the compilation in the correct directory. However it seems that default-directorygets set in a let* binding.

That's a dynamic variable, so rebinding it temporary in a `let` is usually the way to go. Likely the problem is somewhere else.
