### ISSUE TITLE
cannot register Julia project type

### ISSUE THREAD

**Issue by seregaxvm** [bbatsov/projectile#1529]
After adding custom project type using command
```emacs-lisp
(projectile-register-project-type 'julia '("Project.toml" "src"))
```
projectile does not recognize this project type.

## Expected behavior

Projectile to recognize folder with file `Project.toml` and subfolder `src` as a `julia` project.

## Actual behavior

Folder with files `Project.toml` and subfolder `src` without version control files is not recognized as a project.

#### Generate julia project
```bash
> cd ~
> julia -e 'import Pkg; Pkg.generate("TestProject")'
> tree TestProject
TestProject
├── Project.toml
└── src
    └── TestProject.jl
```
*Note:* Julia does not create version control repo.
#### Add project
File `/tmp/load.el`:
```emacs-lisp
(require 'projectile)
(projectile-register-project-type 'julia '("Project.toml" "src"))
```
Starting Emacs:
```bash
emacs -Q -L ~/.emacs.d/elpa/projectile-* -l /tmp/load.el
```
<kbd>M-x projectile-add-known-project ~/TestProject/</kbd>
<kbd>M-x projectile-switch-project ~/TestProject/</kbd>

Observe error in `*Messages*` buffer:
```
Project ~/TestProject/ removed from the list of known projects.
projectile-switch-project-by-name: Directory ~/TestProject/ is not a project
```

### Projectile version information

```
Projectile version: 20200507.650
```

### Emacs version

```
GNU Emacs 26.3 (build 2, x86_64-pc-linux-gnu, GTK+ Version 3.24.11)
 of 2019-09-22, modified by Debian
```

### Operating system

```
Linux 5.6.0-1-amd64 #1 SMP Debian 5.6.7-1 (2020-04-29) x86_64 GNU/Linux
Debian bullseye
```

**Comment by bbatsov** [comment]
Did you also add `Project.toml` to `projectile-project-root-files`?

**Comment by seregaxvm** [comment]
No. Shouldn't `projectile-register-project-type` do this automatically? I've got the impression [from the manual page](https://docs.projectile.mx/en/latest/projects/#adding-custom-project-types) that `projectile-register-project-type` is all I need.

**Comment by seregaxvm** [comment]
I mean, this is a bit counter intuitive to add marker files in `projectile-register-project-type` and then add the same files in `projectile-project-root-files`.

**Comment by bbatsov** [comment]
No, it doesn't - and it can't really, because you're passing a list of files in some case, and only when they are all present you consider this a project of some type. Generally the assumption is that you probably have some VCS file marker, so this doesn't really matter, but if you don't you're out of luck. I'll update the manual to reflect this.

**Comment by bbatsov** [comment]
> I mean, this is a bit counter intuitive to add marker files in projectile-register-project-type and then add the same files in projectile-project-root-files.

Yeah, I totally get this. Potentially there can be a separate key in the project definition for the root, which would simplify this.
