### ISSUE TITLE
Launch error under -Q from 27_2 GNU win10 binary dist

### ISSUE THREAD

**Issue by mplscorwin** [bbatsov/projectile#1531]
## Expected behavior

Treemacs should open without raising an error.

## Actual behavior

```
Debugger entered--Lisp error: (wrong-type-argument arrayp nil)
  treemacs--init()
  treemacs()
  (progn (toggle-debug-on-error) (load-library "package.elc") (package-initialize) (load-library "treemacs.elc") (treemacs))
  eval((progn (toggle-debug-on-error) (load-library "package.elc") (package-initialize) (load-library "treemacs.elc") (treemacs)) t)
  command-line-1((#("-eval" 0 5 (charset windows-1252)) #("(progn (toggle-debug-on-error) (load-library \"pack..." 0 122 (charset windows-1252))))
  command-line()
  normal-top-level()
```

## Steps to reproduce the problem

```
runemacs -Q -eval "(progn (toggle-debug-on-error) (load-library \"package.elc\") (package-initialize) (load-library \"treemacs.elc\") (treemacs))"
```

## Environment & Version information

Windows 10, 64 Home

### Projectile version information

```
[Treemacs] v2.8 (installed 2020.05.12) @ Emacs 27.0.90
```

### Emacs version

GNU Emacs 27.0.90 (build 1, x86_64-w64-mingw32) of 2020-03-23

Binaries from here:  
  https://alpha.gnu.org/gnu/emacs/pretest/windows/emacs-27/emacs-27.0.90-2-x86_64-installer.exe

### Operating system

Windows 10x64,. Home

**Comment by mplscorwin** [comment]
I'm sure this is obvious, but ... I've deposited this on the wrong project's issue page 😊

**Comment by bbatsov** [comment]
No worries!
