### ISSUE TITLE
alien mode doesn't respect ignores specified in .projectile

### ISSUE THREAD

**Issue by johanatan** [bbatsov/projectile#1534]
hi,

i have an unfortunate situation where i must have projectile ignore a folder which is usually ignored in .gitignore. so i added it to .projectile as an "-" ignore. however, with alien mode, this is not respected & switching to native mode is undesirable as indexing is soooooo slow.

I also tried 'projectile-globally-ignored-directories' but it too is not respected for this situation.

**Comment by bbatsov** [comment]
I'm adding here my reply from our chat in Slack for posterity's sake. 

I think I’ve commented on this many times, as the ticket has been duplicated through the years - it’s not really a bug, it’s a limitation. If we apply postprocessing to the files returned by an external command (alien mode) we’re killing most of the benefits of using it, as this filtering is very expensive in Emacs Lisp.

The native indexing is already slow, so the filtering isn’t that big a deal with it.

Btw, did you try hybrid mode as well? I think it was somewhere in the middle. I haven’t had much time for Projectile lately, so I’m starting to forget what i’ve done there.

**Comment by pipehat** [comment]
> switching to native mode is undesirable as indexing is soooooo slow.

@johanatan - have you retried this (native mode) with the fix from mid May that sped up native indexing performance?

**Comment by jleonard-r7** [comment]
I’m using hybrid mode now (which also relies on native). It’s not as nice as alien mode but it seems at least be usable.

**Comment by johanatan** [comment]
I am using hybrid currently. It's not completely terrible and is based on native but i have no idea whether my projectile had been updated then (or even now).

**Comment by bbatsov** [comment]
I think we can close this ticket.
