### ISSUE TITLE
enhance projectile-find-other-file with complex matching behavior

### ISSUE THREAD

**Issue by zhuoqiang** [bbatsov/projectile#1538]
## Expected behavior

enhance the `projectile-find-other-file` so that it could support complex matching logic, for example:

- `foo.py` <--> `test_foo.py`
- `foo.py` <--> `foo_test.py`

## Actual behavior

right now projectile-find-other-file only support config extension names

## Possible solution

enable regular expression in configuration, and use capture group to reference the source file name part in the target name pattern

`(.+?)\.py` <--> `\1_test\.py`

**Comment by bbatsov** [comment]
There's already different functionality for jumping between test and implementations, so I don't think there's any point in duplicating it here. Isn't the existing test navigation functionality covering your needs?
