### ISSUE TITLE
(setq projectile-enable-caching nil) does not actually disable caching

### ISSUE THREAD

**Issue by johanatan** [bbatsov/projectile#1541]
Due to: https://github.com/bbatsov/projectile/issues/1534 I am searching for a way to make "native" mode work for me. The "indexing" delay is really the killer. Thus, I tried to disable caching with:

`(setq projectile-enable-caching nil)` in my user-config and yet a cursory reading of the projectile source code indicates that this value is not actually considered when an index operation is kicked off (and this is what i'm seeing in practice as well):

https://github.com/bbatsov/projectile/blob/master/projectile.el#L1202

Lines 99 and 100 would seem to indicate that choosing _not_ to use caching (although disadvised) is still an option:
https://github.com/bbatsov/projectile/blob/master/projectile.el#L99-L100

**Comment by bbatsov** [comment]
The place where the configuration value is consulted is actually https://github.com/bbatsov/projectile/blob/master/projectile.el#L1183 If some folder has been cached it will be retrieved from there next time, as indicated by the linked code.

**Comment by johanatan** [comment]
My claim isn’t that the flag is never consulted. It is that the flag doesn’t prevent “indexing”. One can run native mode with the flag set to nil to observe this behavior: we don’t have to rely merely on code inspection.
