### ISSUE TITLE
(projectile-project-root) returns incorrect value

### ISSUE THREAD

**Issue by leoalekseyev** [bbatsov/projectile#1542]
## Expected behavior
Run `(projectile-project-root)` visiting non-project buffer, expect to get nil.

Furthermore, it is expected that `M-x projectile-invalidate-cache` would fix the problem, since one of the issues is that there exists an incorrect entry in `projectile-project-root-cache`.

## Actual behavior
Obtain value of some random project completely unrelated to the buffer being visited.
This results in visible breakage of mode lines that rely on projectile to display buffer path information.

`M-x projectile-invalidate-cache` does not seem to affect the value of `projectile-project-root-cache`, making it impossible to fix this without restarting.

## Steps to reproduce the problem
I do not have a complete repro, but tracing through in edebug makes it clear that somehow the cache gets into a bad state, and `M-x projectile-invalidate-cache` doesn't fix it. The only solution seems to be to restart emacs.

### Projectile version information

```
Projectile version: 2.2.0
```

### Emacs version

27.0.91

### Operating system
Ubuntu

**Comment by bbatsov** [comment]
So, this issue happens only when you enable caching?

**Comment by leoalekseyev** [comment]
> So, this issue happens only when you enable caching?

Not necessarily.  For example, I just set `(setq projectile-enable-caching nil)` and am looking at a non-project buffer that still returns a non-nil value for `(projectile-project-root)`.  As before, `M-x projectile-invalidate-cache` isn't effective.

**Comment by leoalekseyev** [comment]
I cannot repro this using emacs -Q with only projectile loaded, so I'm going to close this and track it in doom-emacs
