### ISSUE TITLE
Dart Custom Project Types not working

### ISSUE THREAD

**Issue by ram535** [bbatsov/projectile#1544]
I expected that dart projects would be detected by adding the following configuration. 

```
(use-package projectile
  :init
  (projectile-mode +1)
  :config

  (projectile-register-project-type
   'dart
   '("pubspec.yaml")
	 :compile "pub get"
	 :test "pub run test"
	 :run "dart"
	 :test-suffix "_test.dart")

  :general
  (:prefix "C-c p"
           :states 'normal
           "f" 'projectile-find-file
           "d" 'projectile-dired
           "p" 'projectile-switch-project
           "b" 'projectile-switch-to-buffer
           "v" 'projectile-run-vterm))
```

But it did not work. Dart projects are not being detected.

When I open a dart project and I do `'projectile-find-file`, projectile prompt to switch project. 

```
Projectile 2.3.0snapshot
GNU Emacs 28.0.50
Ubuntu 18.04 LTS
```

**Comment by ram535** [comment]
When adding `  (add-to-list 'projectile-project-root-files-bottom-up "pubspec.yaml")`, it works.

Is this the way to do it?

My new configuration:

```
(use-package projectile
  :init
  (projectile-mode +1)
  :config
  (add-to-list 'projectile-project-root-files-bottom-up "pubspec.yaml")

  (projectile-register-project-type 'dart '("pubspec.yaml")
	                                  :compile "pub get"
	                                  :test "pub run test"
	                                  :run "dart"
	                                  :test-suffix "_test.dart")
  :general
  (:prefix "C-c p"
           :states 'normal
           "f" 'projectile-find-file
           "d" 'projectile-dired
           "p" 'projectile-switch-project
           "b" 'projectile-switch-to-buffer
           "v" 'projectile-run-vterm))
```

**Comment by bbatsov** [comment]
I'm assuming this project is not under version control, right?

**Comment by ram535** [comment]
It is not under version control. Is that an issue?

**Comment by bbatsov** [comment]
It's not an issue, but it explains why you needed to add `  (add-to-list 'projectile-project-root-files-bottom-up "pubspec.yaml")` to make this work. Typically project roots are identified by VCS markers and then projectile matches there the file markers. 

Probably the project registration should be extended to specify a root marker that gets added to `projectile-project-root-files-bottom-up` automatically to address the confusion in cases without VCS.

**Comment by ram535** [comment]
I see. Thank you.
