### ISSUE TITLE
A lot character are insert in the output buffer when running a test (Dart)

### ISSUE THREAD

**Issue by ram535** [bbatsov/projectile#1546]
When doing `projectile-test-project` the output buffer insert lots of characters, making it difficult to read.
![image](https://user-images.githubusercontent.com/9011002/84702666-db7b1880-af0b-11ea-9acc-227a0b335245.png)

When running from the terminal, it looks like this:
![image](https://user-images.githubusercontent.com/9011002/84702730-f64d8d00-af0b-11ea-8391-33094f9aa160.png)

```
Projectile 2.3.0snapshot
GNU Emacs 28.0.50
Ubuntu 18.04 LTS
```

**Comment by bbatsov** [comment]
Seems to me you'll have to enable ansi-color post-processing for your compilation buffers. Does the suggestion here work for you https://stackoverflow.com/questions/13397737/ansi-coloring-in-compilation-mode ?

**Comment by ram535** [comment]
It worked. Thanks.
This is what I added to my configuration.

```
(use-package ansi-color
  :config
  (defun my-colorize-compilation-buffer ()
    (when (eq major-mode 'compilation-mode)
      (ansi-color-apply-on-region compilation-filter-start (point-max))))
  :hook (compilation-filter . my-colorize-compilation-buffer))

```
![image](https://user-images.githubusercontent.com/9011002/84709571-44b45900-af17-11ea-9ffc-54d9c3ee6e1f.png)
