### ISSUE TITLE
projectile errors out on a corrupted .gitmodules file

### ISSUE THREAD

**Issue by hexmode** [bbatsov/projectile#1548]
## Expected behavior

`projectile-switch-project` works even if `git submodule --quiet foreach 'echo $path'` issues a "fatal" message to stderr

## Actual behavior

An error is raised because stderr and stdout is mixed in the output from the above shell command.

\*Messages\* buffer shows 
```
File is missing: "Setting current directory", "No such file or directory", "/home/mah/client/ge/smw-upgrade/fatal: No url found for submodule path 'conf/skins/MonoBook' in .gitmodules
conf/extensions/AbuseFilter/"
```

## Steps to reproduce the problem

``` shell
$ cd /tmp
$ git init repo
$ cd repo
$ git submodule add https://github.com/itague/hello-world.git 
$ sed -i 's,path.=.hel,path =,' .gitmodules
$ emacsclient --eval '(projectile-get-all-sub-projects "/tmp/repo")'
*ERROR*: Setting current directory: No such file or directory, /tmp/repo/fatal: No url found for submodule path 'hello-world' in .gitmodules
/
$
```

### Projectile version information

```
Projectile 2.3.0snapshot (package: 2.1.0)
```

### Emacs version

GNU Emacs 28.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.5, cairo version 1.16.0)
 of 2020-06-15

### Operating system

Debian Linux

**Comment by bbatsov** [comment]
This was recently fixed by #1438.
