### ISSUE TITLE
projectile-regenerate-tags not working at all with tramp

### ISSUE THREAD

**Issue by teeghee** [bbatsov/projectile#1550]
## Expected behavior

I have a remote C++ project and edit its source by connecting with my local machine using tramp ssh.  Most of the features of projectile work fine under tramp, except for `M-x RET projectile-regenerate-tags`.  Both my local machine and the server have exuberant-ctags. 

## Actual behavior

When I type `M-x RET projectile-regenerate-tags` or its shortcut `C-z R` (`C-z` is my binding for `projectile-command-map`), tramp does some inserting/encoding/decoding stuff, and finally displays 
```
projectile-regenerate-tags: ctags: cannot open tag file : No such file or directory
```
with no output file.

## Steps to reproduce the problem

1. Use tramp(ssh) to connect a remote project (ideally a C/C++ one).
2. `projectile-regenerate-tags`.

### Projectile version information

```
Projectile version: 2.3.0snapshot
```

### Emacs version

GNU Emacs 26.3 (build 1, x86_64-redhat-linux-gnu, GTK+ Version 3.24.13) of 2020-01-29

### Operating system

Local: Fedora 23 GNU/Linux
Remote: Ubuntu 18.04.4 LTS GNU/Linux

**Comment by teeghee** [comment]
I temporarily fix the problem by rewriting `projectile-regenerate-tags` as in the following.

```
  (defun my/projectile-regenerate-tags ()
    (interactive)
    (let* ((projectile-tags-command "ctags -Re -f %s %s . --tag-relative=yes")
           (project-root (projectile-project-root))
           (tags-exclude (projectile-tags-exclude-patterns))
           (default-directory project-root)
           (tags-file (expand-file-name projectile-tags-file-name))
           (command (format projectile-tags-command projectile-tags-file-name tags-exclude)))
      (start-file-process "Regenerate Tags" (current-buffer) "/bin/sh" "-c" command)
      (visit-tags-table tags-file)
      (message "Regenerate %s" tags-file)))
```

As you can see, it is the rewriting of the *ctags* part of the function `projectile-regenerate-tags`.  The points are:

1. To use `start-file-process` instead of `call-process-shell-command` as it seems the correct function to call a shell command in tramp-connected remote machine.
2. To generate relative paths in TAGS in order for the tramp not to confuse the location of the file (local and remote).

**Comment by juergenhoetzel** [comment]
Fixed by  [Make projectile-regenerate-tags tramp-aware](https://github.com/bbatsov/projectile/pull/1681)
