### ISSUE TITLE
Set path of compile command

### ISSUE THREAD

**Issue by deb75** [bbatsov/projectile#1556]
Hello,

I use `projectile` for a `maven` project on Windows 10.

The path to the `maven` executable is howevr not standard : it is not `mvn` but `mvn.xxxx` in a user directory.

How can I configure `projectile` to use my `maven` executable ?

Regards

**Comment by bbatsov** [comment]
I guess you can just update Emacs's `exec-path`, as that's what Projectile uses. See https://www.emacswiki.org/emacs/ExecPath

**Comment by deb75** [comment]
Thanks for your answeer.

I indeed already thought about that and it works well, I can find the right executable with tab-completion.

Even nicer, `projectile` records it for later recall.

However, I wondered if I could also set this directly in `projectile` settings. I read about the `.dir-locals.el` in which you can
redefine some settings.

Here is for example what I found in `projectile.el` : 
```
;; Java & friends
(projectile-register-project-type 'maven '("pom.xml")
                                  :project-file "pom.xml"
                                  :compile "mvn clean install"
                                  :test "mvn test"
                                  :test-suffix "Test"
                                  :src-dir "main/src/"
                                  :test-dir "main/test/")
```

I could create a file `.dir-locals.el` at the root project with this : 
```
;; Java & friends
(projectile-register-project-type 'maven '("pom.xml")
                                  :project-file "pom.xml"
                                  :compile "/abolute/path/to/the/mvn/executable clean install"
                                  :test "/absolute/path/to/the/mvn/executable test"
                                  :test-suffix "Test"
                                  :src-dir "main/src/"
                                  :test-dir "main/test/")
```

Do you think it would work ?

Regards
