### ISSUE TITLE
The documentation is not accessable at the moment

### ISSUE THREAD

**Issue by SimeonEhrig** [bbatsov/projectile#1557]
When I access https://docs.projectile.mx/ , I get the following error:

![image](https://user-images.githubusercontent.com/10682583/86097438-f2e20600-bab4-11ea-91bc-6b2680ad7bb4.png)

I tested it with `Firefox 77.0.1` and `Chromium 83.0` on Linux Mint 19.3

**Comment by bbatsov** [comment]
Works fine for me. I'm guessing your browser might have cached the old certificate when the docs site was hosted at RTD.

**Comment by SimeonEhrig** [comment]
I tried it on our development system (Ubuntu 16.04) where I'm pretty sure I never accessed the site and I get the same error. Maybe it is Linux dependent.

**Comment by bbatsov** [comment]
No idea. I'm on macOS myself.

**Comment by SimeonEhrig** [comment]
On the evening, I have access to a Windows system. I will test it on it and then we will see.

**Comment by SimeonEhrig** [comment]
I have tested it on different PCs with Linux and Windows at different locations. Sometimes it works, sometimes not. I couldn't find out what the reason could be. So I close the issue and hope that it just works in the future.

**Comment by bbatsov** [comment]
Btw, since today I've got a Linux PC and it works fine for me there.

**Comment by SimeonEhrig** [comment]
Maybe it depends on the location and the os. At my work, where we only have Linux PCs, no tested PC worked. At home, on my desktop under Linux it doesn't work and under Windows it works. Later I visited a friend in another city with my working laptop, and the site worked under Linux.

**Comment by SimeonEhrig** [comment]
I think I found the problem. I tried it again at home, and now it works (maybe it was another temporary problem). At work it still doesn't work, but this may be a problem of the company network. Thanks for the feedback.
