### ISSUE TITLE
Project instance specific build rules

### ISSUE THREAD

**Issue by nordlow** [bbatsov/projectile#1558]
I would like to be able to define specific build rules for a single project (instance) not only a type.

My use cases are
- https://github.com/dlang/dmd/
- https://github.com/dlang/druntime
- https://github.com/dlang/phobos

I would be nice if such a build rule could be sensitive to local paths, for instance, `test/run.d` in https://github.com/dlang/dmd/.

Such a build rule typically has a command and project-local subdirectory where the command is to be issued (defaulting to project root directory).

**Comment by bbatsov** [comment]
Did you consider using .dir-locals.el for this?

**Comment by nordlow** [comment]
Ahh, thanks. I'll try that.
