### ISSUE TITLE
echo from .zshenv makes projectile throw file-not-found exception

### ISSUE THREAD

**Issue by jangid** [bbatsov/projectile#1559]
I am using Emacs27 with latest projectile from elpa. I was debugging something on zsh on macos and found following behaviour.

I have created a .zshenv file with just one echo line -
echo "Inside ~/.zshenv"

Then, to switch project I used the common C-c p p command. Until this point it is fine, it shows the list of alternatives. When I completed and selected a project (by typing RETURN after fully resolving the project name), I got an exception - 

/Users/pankaj/Inside ~/.zshenv not found. (See the above echo message. Projectile picked the string from there)

## Expected behavior
After pressing RETURN it should show the list of files to choose/complete from. It is the normal behaviour of Projectile.

## Actual behavior
After pressing RETURN on completion of project name Projectile throws an exception.

## Steps to reproduce the problem
1. Create a file ~/.zshenv on your macos
2. Echo something like this from ~/.zshenv
    echo "Inside ~/.zshenv"
3. Save
4. Try to switch project in emacs under Projectile.

### Projectile version information
Projectile 20200710.947

### Emacs version
27.0.91

### Operating system
macOS Catalina 10.15.5

**Comment by bbatsov** [comment]
It's possible that the shell commands that Projectile runs are spinning new logic shells. I'm not very familiar with the internals there, but I can't think of anything else that would result in the shell config being executed.

**Comment by bbatsov** [comment]
Should be fixed by #1438.
