### ISSUE TITLE
Support for packaging and install project commands

### ISSUE THREAD

**Issue by jehelset** [bbatsov/projectile#1560]
CMake workflow can include install and package commands (with CPack), in addition to build, test, etc. 

Would it be possible to add support for these commands to projectile?

I have tried to add them [here](https://github.com/jehelset/projectile/tree/projectile-install-and-packages-commands) similar to the other commands.

**Comment by bbatsov** [comment]
> Would it be possible to add support for these commands to projectile?

Yeah, definitely. I just never thought of this, as I mostly worked on web app that didn't have such steps (we'd deploy them from source much of the time).

 > I have tried to add them here similar to the other commands.

Looks great! PR welcome!
