### ISSUE TITLE
Odd error initializing cache using TRAMP on remote host

### ISSUE THREAD

**Issue by cartesian-theatrics** [bbatsov/projectile#1561]
Hello, I'm getting strange error initializing the projectile cache on remote

## Expected behavior
Find file works on a remote.

## Actual behavior
```
Projectile is initializing cache for /sshx:<hostname>:/path/to/project/
Not a Tramp file name: "/sshx:<hostname>:/path/to/project/Icon^M
```
Note the `^M` is some unicode character. Doesn't matter what project I'm in, it's always `Icon^M` that's not a tramp filename.

## Steps to reproduce the problem
Visit TRAMP file in a project, then `M-x projectile-find-file`

### Projectile version information
```
20200710.947
```

### Emacs version
GNU Emacs 27.0.90 (build 1, x86_64-pc-linux-gnu, GTK+ Version 2.24.30) of 2020-04-13

### Operating system
Ubuntu 16.04

**Comment by bbatsov** [comment]
That's weird. How come this Icon^M is in all your projects? I don't use TRAMP much, but I'm guessing the actually issue has little to do with TRAMP and more with the filename.
