### ISSUE TITLE
Projectile doesn't override .gitignore with bang-prefixed paths as expected

### ISSUE THREAD

**Issue by angrybacon** [bbatsov/projectile#1564]
## Expected behavior

Using the `hybrid` indexing method, `.projectile` should override only the specified paths.

`.gitignore`
```
elpa/
```
`.projectile`
```
!/elpa/**/*.el
```

I shouldn't see the `.elc` files.

## Actual behavior

![image](https://user-images.githubusercontent.com/5608624/89642742-aad4b100-d8b4-11ea-8fdf-a783d4858395.png)

## Steps to reproduce the problem

```elisp
(use-package projectile
  :defer t
  :hook
  (after-init . projectile-mode)
  :custom
  (projectile-enable-caching t)
  (projectile-indexing-method 'hybrid)
  (projectile-track-known-projects-automatically nil))
```

<kbd>M-x</kbd> `counsel-projectile-find-file`

### Projectile version information

```
Projectile 20200802.1502
```

### Emacs version

```
GNU Emacs 27.0.91 (build 1, x86_64-apple-darwin18.7.0, NS appkit-1671.60 Version 10.14.6 (Build 18G95)) of 2020-07-06
```

### Operating system

```
MacOS Catalina
Version 10.15.5 (19F101)
```

**Comment by rileyrg** [comment]
Where did you find documentation for the .projectile file includes?

**Comment by angrybacon** [comment]
@rileyrg Here: https://github.com/bbatsov/projectile/blob/master/doc/modules/ROOT/pages/projects.adoc#ignoring-files

**Comment by rileyrg** [comment]
Thanks. There's a lot of complexity over what projectile uses with regard
to root files, includes and excludes. I'm losing my hair... 😅

**Comment by angrybacon** [comment]
@rileyrg Well, not too sure why I didn't bother to check but the indexing method default has changed (a long time ago).

```lisp
(setq-default projectile-indexing-method 'hybrid)
```

Thanks for your time nonetheless!
