### ISSUE TITLE
Error when updating projectile, unbalanced parentheses

### ISSUE THREAD

**Issue by Jasagredo** [bbatsov/projectile#1570]
## Expected behavior
Updating the package should succeed.

## Actual behavior
Trying to update the package results in the following error:
```
autoload-generate-file-autoloads: projectile.el:0:0: error: scan-error: (Unbalanced parentheses 13785 213817)
```

## Steps to reproduce the problem

I guess updating from `20200810.1245 (installed)` to `20200820.712` probably should throw the same error.

### Projectile version information
```
Projectile 20200810.1245
```
### Emacs version

```
GNU Emacs 28.0.50
```

### Operating system
```
Ubuntu 20.04
```

**Comment by kondanta** [comment]
Having the same issue on `GNU Emacs 27.1 (build 1, x86_64-apple-darwin18.7.0, NS appkit-1894.60 Version 10.15.6 (Build 19G2021))` as well.

**Comment by bbatsov** [comment]
Fixed by https://github.com/bbatsov/projectile/pull/1569
