### ISSUE TITLE
Change project directory without 2-nd dialog open file

### ISSUE THREAD

**Issue by spavlovich001** [bbatsov/projectile#1578]
1. https://emacs.stackexchange.com/questions/28748/how-do-i-write-a-projectile-switch-action-that-changes-the-current-working-direc

2. https://emacs.stackexchange.com/questions/59423/can-i-make-projectile-open-a-default-file-when-i-switch-to-a-project

this code not working

```elisp
(defun set-main-project (&optional dir)
  "Set the projectile main project based on the current buffer.
When called with argument DIR, make that main project instead."
  (interactive)
  (if dir
      (setq projectile-main-project dir)
      (let ((current-project))
        (let ((projectile-main-project nil))
          (setq current-project (projectile-project-root)))
        (setq projectile-main-project current-project))))

(setq projectile-project-action 'set-main-project)
(setq projectile-switch-project-action 'set-main-project)
(setq projectile-switch-project-action 'set-main-project)
```

default-directory after call projectile-switch-project or helm-projectile-switch-project not changed(permanently path 1-st project). How to fix this? I need switch beetween projects(change default-directory only(I do not need open file in ido orhelm-projectile-find-file or projectile-find-file. I need cd to project directory(change (setq default directory)) and in root directory I need run helm-projectile-find-file-dwim for open project files

**Comment by bbatsov** [comment]
Why don't you simply set `projectile-switch-project-action` to `helm-projectile-find-file-dwim`?

**Comment by a-y-u-s-h** [comment]
@spavlovich001 Did you find any solution to this?

**Comment by spavlovich001** [comment]
@a-y-u-s-h , I'm open project from projectile
