### ISSUE TITLE
.emacs.d directory is ignored while using terminal

### ISSUE THREAD

**Issue by dadinn** [bbatsov/projectile#1579]
## Expected behavior

When starting up a fresh Emacs instance on the terminal, I would expect that `projectile-switch-project` to always offer my `$HOME/.emacs.d` directory (which is under version control using [git](https://github.com/dadinn/.emacs.d)) as a choice.

## Actual behavior

When starting Emacs on the terminal (with command `emacs --no-window-system`), the `$HOME/.emacs.d` directory is somehow missing from the list of choices.

I am using `ido-mode` for selection / completion. I haven't tried the behaviour with other completion engines (e.g. [ivy](https://github.com/abo-abo/swiper)).

If I manually type `.emacs.d` and press Enter, this actually does find the project, and I am offered the choice of files to open as expected.

When running Emacs with GUI, everything works fine, and the `.emacs.d` directory is offered as choice, as expected.

## Steps to reproduce the problem

This is my `init.el` configuration related to `projectile-mode`:

```
(use-package projectile
  :init
  (projectile-mode)
  (defun pop-grep-buffer ()
    (pop-to-buffer next-error-last-buffer))
  :hook
  (projectile-grep-finished . pop-grep-buffer)
  :bind
  (:map projectile-mode-map
   ("C-c p" . projectile-command-map))
  :config
  (add-to-list 'projectile-globally-ignored-directories "node_modules"))
```

As it might be relevant, these are the my configurations related to `ido-mode`:

```
(use-package ido
  :custom
  (ido-enable-flex-matching t)
  (ido-auto-merge-work-directories-length -1)
  (ido-everywhere t)
  (ido-mode t))

(use-package ido-vertical-mode
  :custom
  (ido-vertical-show-count t)
  (ido-vertical-define-keys 'C-n-and-C-p-only)
  :config
  (ido-vertical-mode))

(use-package flx-ido
  :custom
  (ido-enable-flex-matching t)
  (ido-use-faces nil))

(use-package ido-completing-read+
  :config
  (ido-ubiquitous-mode))
```

Additionally, this is how I set up and configure the `use-package` package/macro:

```
(unless (package-installed-p 'use-package)
  (package-refresh-contents)
  (package-install 'use-package))
(require 'use-package)

(custom-set-variables
 '(use-package-always-ensure t)
 '(use-package-always-pin "melpa-stable"))
```

### Projectile version information

`2.2.0`

Installed from [melpa-stable](https://stable.melpa.org/)

### Emacs version

 `26.1`

### Operating system

Linux (Debian 10).

**Comment by bbatsov** [comment]
> When running Emacs with GUI, everything works fine, and the .emacs.d directory is offered as choice, as expected.

That's super weird. I can't think of anything in the code that would behave differently in GUI and terminal mode. I'll try to reproduce this when I have some time.

**Comment by dadinn** [comment]
Is there maybe something in my project directory itself which causes it to be ignored?

I have just migrated my package management onto [straight.el](https://github.com/raxod502/straight.el), and I am still experiencing the issue. My .emacs.d config is [here](https://github.com/dadinn/.emacs.d).

As mentioned, this issue only happens from the terminal, starting Emacs with `emacs -nw`

**Comment by bbatsov** [comment]
Other than some environment variables being different I really can't imagine what could go wrong. I guess you can inspect `projectile-known-projects` and the file it's getting written to and see it's affected in some way.
