### ISSUE TITLE
Consider adding "." root directory to destination of projectile-switch-project

### ISSUE THREAD

**Issue by ianpan870102** [bbatsov/projectile#1582]
This is not a bug per se, but rather a feature request.
When I switch to a project with `projectile-switch-project`, I am forced to open a file in that project. However, sometimes I just want to create a new file within that project and it'd be nice if we could have the `.` option for the destination of projectile-switch-project, so we could *land* in the root directory of the project I wanted to switch to, and start operating from there.
Let me know if the description is unclear, I'll try to explain it better. Cheers!

**Comment by bbatsov** [comment]
I recall this was the original behaviour of the command, but some people complained we showed the current project as well. :laughing: It's hard to please everyone!

**Comment by bbatsov** [comment]
Potentially this can be a configuration option. I'll think about that.

**Comment by ianpan870102** [comment]
> Potentially this can be a configuration option. I'll think about that.

Sounds like a good idea, looking forward to your decision!

**Comment by PQTran** [comment]
Hi @ianpan870102, when I use projectile-switch-project it seems to open up a dired buffer for the project. Does this not happen for you?

**Comment by PQTran** [comment]
I looked into my .emacs init file, and maybe this might be useful for you
```
(setq projectile-switch-project-action 'projectile-dired)
```
@ianpan870102

**Comment by ianpan870102** [comment]
Thanks for the suggestion @PQTran! Sadly, I'm using counsel-projectile as well and that didn't play along well.

**Comment by markgdawson** [comment]
@ianpan870102 for counsel-projectile users, I believe you can use an action to jump to the root directory.

So, with the project highlighted in the ivy `counsel-projectile-switch-project` completion buffer, hit `Meta-o` for actions and `D` for "open with dired".

**Comment by mohkale** [comment]
Alternatively depending on your completion framework you can exit with the empty string and projectile interprets that as the root of the project. In ivy I believe it's `ivy-immeadiate-done`, in selectrum it's `selectrum-submit-exact-input`. I have it bound to `<S-return>` so if I want to jump to the root of the project with dired I run `projectile-find-file` and hit `<S-return>`.

**Comment by ianpan870102** [comment]
> Alternatively depending on your completion framework you can exit with the empty string and projectile interprets that as the root of the project. In ivy I believe it's ivy-immeadiate-done, in selectrum it's selectrum-submit-exact-input. I have it bound to <S-return> so if I want to jump to the root of the project with dired I run projectile-find-file and hit <S-return>.

Great tip. I'm an ivy user too and I didn't know that `ivy-immediate-done` can do that! By default `ivy-immediate-done` is bound to "C-M-j" (ctrl alt j) -- just tried it, and it works great.

Closing issue. Thanks for the tip!
