### ISSUE TITLE
projectile stopped recognizing git repos as projects

### ISSUE THREAD

**Issue by oxddr** [bbatsov/projectile#1583]
## Expected behavior
Git repositories are recognized by projectile as projects without using .projectile file. 

## Actual behavior
Git repositories aren't recognized by projectile as projects. Adding .projectile file to the git root makes projectile to recognize it correctly (both VCS and type, `make` in my case). 

## Steps to reproduce the problem

`cd ~/git/repo`
`emacs`

then 
`projectile-project-info` returns `/path/to/my/home`

another 
`projectile-switch-project` then I select one previously known, git-based projects and I land in `/path/to/my/home` instead.

*This is extremely important! Providing us with a reliable way to reproduce
a problem will expedite its solution.*

### Projectile version information
```
Projectile version: 20200909.650
```

### Emacs version

GNU Emacs 26.3 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.2), modified by Debian

### Operating system

Debian

**Comment by bbatsov** [comment]
Is it possible you've got some project marker in your home dir? Git projects are handled fine for me, but I did notice a similar issue here #1577

**Comment by oxddr** [comment]
Oh, I did actually have `.projectile` file in my home dir. Deleting it solved the problem. However, is it expected behavior, that `.projectile` file in a higher-level directory is preferred over a Git repository in a lower-level dir? (e.g. `/my/home/.projectile` over `/my/home/repo/.git`)

**Comment by bbatsov** [comment]
Yeah, that's by design - file markers have higher precedence than repo markers, although at some point we might make this more flexible.

**Comment by oxddr** [comment]
TIL, thanks for clarifying. 

/close
