### ISSUE TITLE
[Feature Request] Enable projectile-find-other-file and projectile-toggle-between-implementation-and-test on EmberJS

### ISSUE THREAD

**Issue by lljr** [bbatsov/projectile#1586]
```
├── app
│ ├── components
│ ├── controllers
│ ├── helpers
│ ├── models
│ ├── routes
│ ├── styles
│ │   └── app.css
│ ├── templates
│ │   └── application.hbs
│ ├── app.js
│ ├── index.html
│ └── router.js
├── config
│ ├── ember-cli-update.json
│ ├── environment.js
│ ├── optional-features.json
│ └── targets.js
├── public
│ ├── tests
│ ├── helpers
│ ├── integration
│ ├── unit
│ ├── index.html
│ └── test-helper.js
├── vendor
├── .editorconfig
├── .ember-cli
├── .eslintignore
├── .eslintrc.js
├── .gitignore
├── .template-lintrc.js
├── .travis.yml
├── .watchmanconfig
├── README.md
└── app.css
└── application.hbs
└── robots.txt
├── ember-cli-build.js
├── package.json
├── package-lock.json
└── testem.js
15 directories, 24 files
```
This is a EmberJS directory structure. It's created with a command `ember new my_proj`.  Lots of these directories create files with the same name but with different file extensions. For example, `templates` has files with `.hbs` extension and sometimes it comes paired with files with `.js` extension in `routes`. The same thing goes for the `tests` directory, except that they suffixed with `-test.js` and are located in different sub directories in `tests`.

Right now, when I try to use these commands I get : `projectile-find-implementation-or-test: No matching test file found for project type ‘npm’` or `projectile--find-other-file: No other file found`. It would be nice if these commands worked in an EmberJS project. Maybe it would not take much effort to do since EmberJS project structure is standard. I said maybe. Let me know what you think :).

https://guides.emberjs.com/release/getting-started/
### Projectile version information
```
Projectile version: 2.2.0
```

### Emacs version

 27.1

### Operating system

Ubuntu 20.04

**Comment by bbatsov** [comment]
Yeah, that should be easy to change. We can register a new project type that's similar to Ruby on Rails for EmberJS.
