### ISSUE TITLE
[Question] How to open in new window?

### ISSUE THREAD

**Issue by kujohn** [bbatsov/projectile#1593]
When `projectile-find-file` is evoked, how does one open the file in a new window?

**Comment by mattiasb** [comment]
I have projectile mapped to the `C-z p` prefix so for me it's: `C-z p 4 f` (similar to how `C-x 4 f` opens a file in a new window in vanilla Emacs).

Note that what Emacs calles "window" is what other editors tend to call "pane". OS windows are called "frames" in Emacs land and to open a file in a new frame using projectile you do `C-z p 5 f` (again replace `C-z p` with whatever prefix you're using).
