### ISSUE TITLE
compiling a project should only ask to save project files

### ISSUE THREAD

**Issue by jmay** [bbatsov/projectile#1597]
#  Expected behavior
When I execute a compile command inside a projectile project, it should only prompt to save modified buffers related to that project. Alternatively, if `compilation-ask-about-save` (or some new projectile variable) is `nil`, then only auto-save buffers in that project.

## Actual behavior
Compilation triggers the save-buffer notification for every open buffer, not just those associated with the current project. Setting `compilation-ask-about-save` to `nil` auto-saves everything.

## Steps to reproduce the problem
Open a file related to a projectile project, and some other unrelated files (could be other projects, or non-projectile files).

Edit a buffer that is not related to the first project.

Trigger a compilation command in the project. For example, `rspec-verify` in a Ruby on Rails project. That will trigger a buffer save request for the edited buffer, or auto-save that buffer if the global ask-flag is nil.

### Projectile version information
`Projectile 20201030.1132`

### Emacs version
`GNU Emacs 27.1 (build 1, x86_64-apple-darwin18.7.0, NS appkit-1671.60 Version 10.14.6 (Build 18G95))
 of 2020-08-11`

### Operating system
`macOS Catalina version 10.15.6`

**Comment by bbatsov** [comment]
As Projectile simply delegates the compilation to the `compile` package, I'm not sure how easy it's going to be to limit what should be saved. I'm a `super-save` user, that's why I guess I never noticed it, as my buffers are always saved when I'm switching between them.

**Comment by bbatsov** [comment]
This might solve your problem https://github.com/bbatsov/projectile/issues/1517

**Comment by jmay** [comment]
@bbatsov Thanks for the pointer to `projectile-compile`, but that doesn't expose all the environment-specific options such as are available in `projectile-rspec` or alternatives. Standard emacs compilation calls `save-some-buffers`, looks like I'll have to figure out how to hook into that to limit it to project scope. I've gone back and forward with auto-saving all my buffers, I'd like to find a solution that will work regardless of auto-save preference.

**Comment by goldfita** [comment]
Maybe there could be an option to at least save all project files when idle, even if save on compile can't be made to work. Intellij does this by default, and I've gotten used to it.
