### ISSUE TITLE
Cannot find projects or files

### ISSUE THREAD

**Issue by onip** [bbatsov/projectile#1606]
## Expected behavior
<kbd>M-p p</kbd> should display the list of known projects
<kbd>M-p f</kbd> should display the list of files in the projects matching the input characters
## Actual behavior
lists are empty

this is happening since a couple of updates (running from `#master` through melpa). reverting to `projectile-2.2.0` in `melpa-stable` fixes to the usual behaviour.

if this is expected then i probably have missed something in the documentation, sorry.

### Projectile version information

```
Projectile 20201124.1235
```

### Emacs version

```
GNU Emacs 27.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.20, cairo version 1.16.0)
```
### Operating system

```
Ubuntu 20.04
```

**Comment by bbatsov** [comment]
Hmm, that's weird. @minad was working on some small updates, but it didn't seem like any of them could cause such a problem. I guess I should update to master myself. :-)

**Comment by minad** [comment]
@bbatsov For me it works. I am running the lastest version from melpa.

**Comment by onip** [comment]
> Which completion system do you use in Emacs (helm, ivy, ido, default)?

I haven't configured anything, so I guess it is `default`
> If no completion system is used, projectile falls back to the default completion system now instead of ido which it used before.

I am currently working, thus reverted to `2.2.0` and pressing <kbd>TAB</kbd> brings up an `*Ido Completions*` buffer. I will try to upgrade to `#master` and configure projectile to use `ido` and see if the problem is fixed as soon as I have a break.

ps. this will make me spend at least a week digging into completion systems for Emacs, my boss will be glad of my productivity drop :wink:

**Comment by minad** [comment]
Well, working without an improved completion system does not seem very efficient to me, so you should amortize the lost time in a day ;)  Just enable ido in your init.el via `(ido-mode 1)` or enable it via `M-x ido-mode`. And then if you have time to waste, look into ivy, helm or selectrum.

**Comment by bbatsov** [comment]
Ah, got it now.

> I haven't configured anything, so I guess it is default

By default it's not default, but rather `auto` now (it used to be `ido`). So you can either force the old setting or enabled `ido-mode` as suggested by @minad. It never crossed my mind someone might be using Emacs without something like `ido` or `ivy`. :-)

**Comment by onip** [comment]
one have to be aware of `ido`, `ivy` or `helm` :wink: 

anyway, enabling `ido` solved the problem. thank you all for the support.

**Comment by slipset** [comment]
FWIW this bit me the yesterday when I did a package refresh, and projectile "stopped working". Setting `projectile-completion-system` to `ido` fixed it. The default value `auto` did "nothing" for me.

**Comment by bbatsov** [comment]
@slipset Auto does nothing if you've not enabled any global completion mode (e.g. `ido-mode`). Technically, auto does something, but the default completion in Emacs requires you to press TAB to see a list of candidates.
