### ISSUE TITLE
FR: consider version of projectile-vc which avoids magit-status where possible

### ISSUE THREAD

**Issue by aspiers** [bbatsov/projectile#1609]
Hi!

Firstly thanks for your awesome work on projectile and several other projects I've benefited from greatly :-)

Personally I am invoking `projectile-vc` many times per day (actually via `counsel-projectile-switch-project-action-vc` although that isn't really relevant here).  The problem I am experiencing is that ultimately this always calls `magit-status`, which is very often slow for reasons discussed in https://github.com/magit/magit/issues/2982.

While various work is ongoing to speed up `magit-status` as can be seen in that issue, a simple workaround is to use a wrapper around it which checks whether a magit status buffer already exists, and if so, just switch to that.  I have filed [a feature request to magit proposing that this wrapper become part of magit's "official" API](https://github.com/magit/magit/issues/4259).

The purpose of this issue is to propose that projectile offers a corresponding optional optimization for reusing existing status buffers where available.  For example, there could be a `projectile-switch-to-vc-buffer` as a variant of `projectile-vc`, or as a wrapper around it.  This is extremely easy to implement even if my feature request to magit is rejected.  For example here is a quick and dirty hack to my emacs config files which achieves it:

https://github.com/aspiers/emacs/compare/8a0c6769...786b29d4

Thanks for your consideration!

**Comment by bbatsov** [comment]
I'm afraid I don't fully understand the issue you're having with `magit-status`, but I'm open to making the behaviour of the command be configurable via some `defcustom` for instance. My assumption was that this command would never be called that frequently, but I guess I was mistaken.

**Comment by aspiers** [comment]
Thanks for the reply.  The issue is simply that `magit-status` can take several seconds to complete depending on which sections are configured to appear and how long it takes to build their contents.  For me this is especially noticeable when forge is involved - e.g. see https://github.com/magit/forge/issues/300.

Since I am often hacking on multiple related repositories at the same time, I typically invoke `projectile-vc` many times per day, and it can really disturb my flow to have to wait a few seconds each time.

`projectile-switch-project` is already very nicely configurable via `projectile-switch-project-action`, but currently there is no action offered out of the box which is like `projectile-vc` but avoids a rebuild of the magit status buffer.  So this feature request could be implemented very easily by including a new `projectile-switch-to-vc-buffer` function which provides that action.  I've already written such a function called [`as-projectile-switch-project` in my personal emacs config files](https://github.com/aspiers/emacs/compare/8a0c6769...786b29d4#diff-5a2078ad513e128d0638fcd616ebacf50b81ee9cb2338635e27358b644fc298fR45-R57).

**Comment by bbatsov** [comment]
Got it. That makes sense to me, although it seems to me it'd be just as good to control via a defcustom what exactly gets invoked by `projectile-vc`, as it's currently a bit hardcoded. I'm fine with the addition of a new function, though, even it will only be useful to magit users (I guess everyone's a magit user these days).

**Comment by aspiers** [comment]
Thanks. I guess it makes sense to wait a bit to see if I can get https://github.com/magit/magit/issues/4259 resolved - if so then we could take advantage of that new API.

Incidentally I noticed that `projectile-vc` tries to use `magit-status-internal` which has been marked as obsolete since magit 3.0.0.  Maybe we could address that at the same time.

**Comment by aspiers** [comment]
Not stale - still want to fix this as above.

Also (totally unrelated) I realise this is subjective, but please consider the possibility that stale bots are not necessarily always as helpful as they may seem.  Personally I tend to agree with the position stated in [this article](https://www.reddit.com/r/emacs/comments/j9hi9x/an_example_of_why_bug_reports_and_feature/), which happens to use emacs as a good example.

**Comment by aspiers** [comment]
[**@aspiers**](https://github.com/aspiers) commented on [December 1, 2020 11:06 AM](https://github.com/bbatsov/projectile/issues/1609#issuecomment-736427381 "2020-12-01T11:06:23Z - Replied by Github Reply Comments"):
> Thanks. I guess it makes sense to wait a bit to see if I can get https://github.com/magit/magit/issues/4259 resolved - if so then we could take advantage of that new API.

This has now happened.

**Comment by bbatsov** [comment]
Okay, I guess we're now unblocked here, right?

**Comment by aspiers** [comment]
Yes I think so.

**Comment by aspiers** [comment]
So how do we proceed?  As you say, `projectile-vc` is currently a bit hardcoded.

The first thing might be a refactoring to extract the sexps which handle git and hg into two separate functions `projectile-vc-git` and `projectile-vc-hg`.  Then at least anyone could redefine those functions as they saw fit.

The next step could be to add new `defcustom` variables `projectile-vc-git-function` and `projectile-vc-hg-function` which inform `projectile-vc` which functions to call.  They would default to the newly defined functions described above.

Or maybe you can think of a better way to make it flexible?

**Comment by bbatsov** [comment]
The suggest approach is fine by me. It's simple and it will certainly solve the task at hand.

**Comment by aspiers** [comment]
Performance problem with `magit-status` has gone due to new ways of accessing the forge sqlite3 database, so I probably don't need this any more.
