### ISSUE TITLE
M-o no longer showing version-control shortcut

### ISSUE THREAD

**Issue by nickenchev** [bbatsov/projectile#1610]
Hey, I hope I'm not opening this issue in the wrong place as I'm not sure this feature was exactly projectile related. Up until a recent update I've been able to do ```C-c p p``` select a project, then press ```M-o v``` which would open ```magit``` status buffer. Now when I do ```M-o``` I no longer see ```v``` as an option and can't directly go to the VCS status. Any idea how to bring this back? It was very useful when I just want to access the repositories for my projects, rather than having to open a file or dired for that project and then open magit.

## Expected behavior
Expecting to be presented with ```v``` option to open VCS status (magit buffer)

## Actual behavior
No ```v``` option presented for VCS status.

## Steps to reproduce the problem

```C-c p p``` to view project list
```M-o``` to view options for selected project in list
```v``` option is not presented, just o, i, w

### Projectile version information

Projectile 2.3.0

### Emacs version

GNU Emacs 28.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.23, cairo version 1.17.3)

### Operating system

Linux Office-Arch 5.9.11-arch2-1 #1 SMP PREEMPT Sat, 28 Nov 2020 02:07:22 +0000 x86_64 GNU/Linux

**Comment by bbatsov** [comment]
I'd assume you were using a different minibuffer completion system, as nothing relevant has changed in Projectile itself, other than it switch by default to an auto-detected minibuffer completion system.

**Comment by bbatsov** [comment]
> M-o to view options for selected project in list

I have to admit I have no idea where this is coming from, as it's certainly not coming from Projectile. :D It sounds to me like the projectile commander, but if it were it you'd be getting it right after switch the project, not in the list of available projects.

**Comment by nickenchev** [comment]
Hmm, now that I think about it, I had been using ```counsel-projectile``` up until a recent update, I started having some serious slowdowns opening project files. Using ```counsel-projectile's``` version of ```projectile-switch-project``` started behaving VERY laggy after selecting a project and filtering for files. I thought it was projectile, but using ```projectile-switch-project``` didn't have the same behaviour, so I just completely disabled ```counsel-projectile``` and the problem went away. Perhaps that's the package that was providing the ```v``` option.

Since we're on the topic, do you have a recommendation on how I can use projectile to go directly to vcs/magit without opening a project file first?

Thank you!

**Comment by bbatsov** [comment]
I'd just do something like:

```
(setq projectile-switch-project-action #'projectile-commander)
```

**Comment by bbatsov** [comment]
Or you can just type `C-u s-p p` (assuming `projectile-switch-project` is bound to `s-p p`, that is)

**Comment by nickenchev** [comment]
I don't know how recently ```projectile-commander``` came into existence, but this is what I've always needed!

**Comment by bbatsov** [comment]
Try 5+ years. 😆 At least you inspired me to write proper documentation about it today. I'm assuming we can close this ticket, right?
