### ISSUE TITLE
projectile-switch-project-action doesn't open a tramp project unless tramp buffer running

### ISSUE THREAD

**Issue by dareno** [bbatsov/projectile#1611]
## Expected behavior
projectile-switch-project should initiate a tramp session to open a project

## Actual behavior
echo area reports "Directory <my directory> is not a project"

## Steps to reproduce the problem
Stop and start emacs or kill tramp/ssh buffer. Use projectile-switch-project with a tramp connection. This is the same issues as #1328 which was closed due to inactivity (see workaround here though!).

## Workaround
Commenting out these lines makes it work: 
https://github.com/bbatsov/projectile/blob/69a25b110d6be7d3e0822d1ff0a54b91e3ec91aa/projectile.el#L4373-L4375

### Projectile version information
projectile-20201128.1539

```
Projectile 20201128.1539
```

### Emacs version
GNU Emacs 27.1 (build 1, x86_64-apple-darwin18.7.0, NS appkit-1671.60 Version 10.14.6 (Build 18G95)) of 2020-08-12

### Operating system

Mac OS X version 10.15.7

**Comment by bbatsov** [comment]
I'm assuming this is a potential fix for it https://github.com/bbatsov/projectile/pull/1417

**Comment by bbatsov** [comment]
Just merged the fix for this.

**Comment by dareno** [comment]
Tested and confirmed; thanks so much for your time and the quick fix!
Closed by https://github.com/bbatsov/projectile/commit/fcc8b9081d523f88b5705ef220ebcc3b1d7360f6
