### ISSUE TITLE
helm-projectile shows .ccls-cache files

### ISSUE THREAD

**Issue by TheJJ** [bbatsov/projectile#1613]
When invoking helm-projectile, i see .ccls-cache files:

![image](https://user-images.githubusercontent.com/673543/101180162-819e1480-364b-11eb-8a0f-5d23295c265a.png)

`.ccls-cache` is in `projectile-globally-ignored-directories`, so I shouldn't see these files?

Please excuse me if the bug is not actually in projectile, but I hope we can figure it out :)

### Projectile version information

```
20201124.1235
```

### Emacs version

27.1

### Operating system

Gentoo

**Comment by bbatsov** [comment]
Depends on your file indexing method https://docs.projectile.mx/projectile/configuration.html#project-indexing-method

As noted in the docs the `alien` indexing defers entire to the external command it runs to deliver maximum performance.

**Comment by TheJJ** [comment]
`projectile-indexing-method` is `alien` for me, and the project is a git repo, so it should use `git ls-files -zco --exclude-standard`, and this does list the `.ccls-cache` files indeed.

What is your recommended way to filter the files?  :)

Would filtering through `projectile-globally-ignored-directories` really degrade performance so it's not an option to use?

**Comment by TheJJ** [comment]
uh-oh, simply adding that to the `.gitignore` excludes them :D I guess that solves it.

**Comment by bbatsov** [comment]
Yeah, exactly. :-)

**Comment by TheJJ** [comment]
thx :smile:

**Comment by real-or-random** [comment]
I ran into this, too. I think it will be helpful for newcomers to add a note to the docs of `projectile-globally-ignored-directories` (and maybe other functions) that this variable is not honored for `alien` indexing and users should use `.gitignore` etc.

When you look for how to ignore directories, you're likely to find about `projectile-globally-ignored-directories` and not read the entire docs.
