### ISSUE TITLE
Opening remote projects is not working

### ISSUE THREAD

**Issue by swarnendubiswas** [bbatsov/projectile#1615]
## Expected behavior

I have used `projectile` to save known remote projects and accessed them quickly later. Switching to the project allows you to open child project files.

## Actual behavior

The above behavior is broken after recent updates. I can open remote projects, but entering file names either (i) does not bring up the files, or (ii) considers a wrong project location. 

## Steps to reproduce the problem

1. Open a remote folder.
2. Invoke `projectile-add-known-project`
3. Suppose I have a remote project saved as `ssh:/remotepath:/home/swarnendu/Dropbox/`. I save it with `projectile`. Now I access it, the file selection dialog comes up, when I type in names, the files from under `/home/swarnendu` come up. Note that I have a `.projectile` in `/home/swarnendu/Dropbox`. This used to work till a few days before.

In another case, where the project is under Git, I cannot autocomplete or select files even after entering valid file names.

I am able to reproduce this with `emacs -q -l projectile.el`.

```
(require 'package)
(setq package-user-dir (expand-file-name "~/.emacs.d/elpa/")
      package-enable-at-startup nil)
(add-to-list 'package-archives
             '("melpa" . "https://melpa.org/packages/") t)
(package-initialize)

(unless (package-installed-p 'use-package)
  (package-refresh-contents)
  (package-install 'use-package))
(eval-when-compile
  (require 'use-package))

(use-package projectile
  :bind-keymap ("C-c p" . projectile-command-map)
  :custom
  (projectile-auto-discover nil "Do not discover projects")
  (projectile-enable-caching nil "Problematic if you create new files often")
  (projectile-file-exists-remote-cache-expire nil)
  ;; Contents of .projectile are ignored when using the alien or hybrid indexing method
  (projectile-indexing-method 'alien)
  (projectile-mode-line-prefix "")
  (projectile-require-project-root t "Use only in desired directories, too much noise otherwise")
  (projectile-verbose nil)
  :config
  (defun projectile-default-mode-line ()
    "Report project name and type in the modeline."
    (let ((project-name (projectile-project-name)))
      (format " %s [%s] "
              projectile-mode-line-prefix
              (or project-name "-"))))
  (projectile-mode 1)

  (dolist (prjs (list
                 (expand-file-name "/tmp")
                 ))
    (add-to-list 'projectile-ignored-projects prjs))
  (dolist (dirs
           '(".cache" ".clangd" ".dropbox" ".git" ".hg" ".metadata" ".nx" ".recommenders" ".svn" ".vscode" "__pycache__" "auto" "elpa" "node_modules"))
    (add-to-list 'projectile-globally-ignored-directories dirs))
  (dolist (items
           '("GPATH" "GRTAGS" "GTAGS" "GSYMS" "TAGS" "tags" ".dir-locals.el" ".projectile" ".project" ".tags" "__init__.py"))
    (add-to-list 'projectile-globally-ignored-files items))
  (dolist (exts
           '(".a" ".aux" ".bak" ".blg" ".class" ".deb" ".djvu" ".doc" ".docx" ".elc" ".gif" ".jar" ".jpeg" ".jpg" ".o" ".odt" ".out" ".pdf" ".png" ".ppt" ".pptx" ".ps" ".pt" ".pyc" ".rel" ".rip" ".rpm" ".svg" ".tar.gz" ".tar.xz" ".xls" ".xlsx" ".zip" "~$"))
    (add-to-list 'projectile-globally-ignored-file-suffixes exts)))
```

### Projectile version information

20201204.954 from MELPA

### Emacs version

27.1

### Operating system

Local machine: Ubuntu 20.04
Remote machine: Ubuntu 18.04

**Comment by bbatsov** [comment]
Hmm, that's weird. Looking at the recent changes I don't see anything that seems related to your problem. I'll see if I can reproduce it when I have some time.

**Comment by bbatsov** [comment]
Seems this was caused by https://github.com/bbatsov/projectile/commit/351e0c3b430392c73372f4129b1174c088a934b2 See all #1616.
