### ISSUE TITLE
Commit 351e0c3b430392c73372f4129b1174c088a934b2 breaks listing files over TRAMP

### ISSUE THREAD

**Issue by chy-causer** [bbatsov/projectile#1616]
## Expected behavior

```
(projectile-files-via-ext-command "/ssh:$HOSTNAME:/path/to/git/project" "git ls-files -zco")
```
Should return a list of files

## Actual behavior

Always returns nil no matter what I do.

## Steps to reproduce the problem

Fairly straightforward to reproduce: just try accessing a project over TRAMP and run projectile-find-file. There will be no files available.

This looks to have been introduced in commit 351e0c3b430392c73372f4129b1174c088a934b2. Reverting the function projectile-files-via-ext-command fixes the issue for me.

Does the "with-temp-buffer" change the default-directory? I'm sorry I'm just starting out on my Emacs journey.

### Projectile version information

```
Projectile version:  20201204.954
```

### Emacs version

GNU Emacs 26.3 (build 2, x86_64-pc-linux-gnu, GTK+ Version 3.24.14)

### Operating system

Ubuntu 20.10

**Comment by bbatsov** [comment]
@maurelio1234 Can you look into this?

**Comment by bbatsov** [comment]
Looking at the changeset it's not clear to me what's causing the breakage there. Perhaps `call-process-shell-command` doesn't behave properly over TRAMP?

**Comment by maurelio1234** [comment]
Hi, I will take a look at it

**Comment by maurelio1234** [comment]
I confirm it does not work without my commit and that it works when I revert it.

**Comment by bbatsov** [comment]
I guess a simple workaround would be to use `file-remote-p` to make your change condititional, but it'd be best to understand what exactly is misbehaving over TRAMP. My money are on `call-process-shell-command`.

**Comment by maurelio1234** [comment]
Just pushed a PR with a proposal. 

I will take some time tomorrow or after tomorrow to see how tests work now and how/if I can write a test case using a magic file handler.

@bbatsov could you tell me what you think about that?
@chy-causer can you test that?

**Comment by bbatsov** [comment]
The proposed fix seems good to me.

**Comment by chy-causer** [comment]
Can confirm that the patch fixes the issue for me. Many thanks for the speedy response!

**Comment by chy-causer** [comment]
I should probably say that it's not broken as such, but now what happens is that a new buffer pops up at the bottom of the screen, with null delimited filenames, which then get put into the helm projectile buffer. That bit is great. However when the file list is long the buffer at the bottom remains so I'm left with an empty buffer at the bottom of the screen.

This only seems to happen when my Emacs frame is large, basically when I'm on a 4k monitor. As such if I'm not working full screen it doesn't happen.

It's not a showstopper, and I admit I have the luxury of a 4k screen that others may not to test, but I thought I should mention it in case it's an easy fix.

![Temp buffer full of \0 delimited filenames](https://user-images.githubusercontent.com/220105/101474194-b4455700-3942-11eb-8693-1b79cde5fbf3.png)

![Empty buffer at the bottom](https://user-images.githubusercontent.com/220105/101474284-d7700680-3942-11eb-90ae-9d93f318cf01.png)

**Comment by bbatsov** [comment]
I think that the problem is that `shell-command` is an interactive command and it outputs its results to the minibuffer when invoked.

**Comment by maurelio1234** [comment]
> I should probably say that it's not broken as such, but now what happens is that a new buffer pops up at the bottom of the screen, with null delimited filenames, which then get put into the helm projectile buffer. That bit is great. However when the file list is long the buffer at the bottom remains so I'm left with an empty buffer at the bottom of the screen.
> 
> This only seems to happen when my Emacs frame is large, basically when I'm on a 4k monitor. As such if I'm not working full screen it doesn't happen.
> 
> It's not a showstopper, and I admit I have the luxury of a 4k screen that others may not to test, but I thought I should mention it in case it's an easy fix.
> 
> ![Temp buffer full of \0 delimited filenames](https://user-images.githubusercontent.com/220105/101474194-b4455700-3942-11eb-8693-1b79cde5fbf3.png)
> 
> ![Empty buffer at the bottom](https://user-images.githubusercontent.com/220105/101474284-d7700680-3942-11eb-90ae-9d93f318cf01.png)

How to reproduce that?
With your command `(projectile-files-via-ext-command "/ssh:$HOSTNAME:/path/to/git/project" "git ls-files -zco")` ?

**Comment by chy-causer** [comment]
This is reproducible via projectile-find-file (C-p f). Happens 100% of the time, but only when the screen is large enough. I don't know why.

As I say, it's working perfectly when I don't maximize the screen, or if I am happy to ignore the large minibuffer at the bottom. It disappears after I select a file so it's very easy to remove as well.

**Comment by maurelio1234** [comment]
Yes I see why it happens...
`shell-command` basically calls `display-message-or-buffer`when it is finished, which matches the behaviour you see:

> Display MESSAGE in the echo area if possible, otherwise in a pop-up buffer.
MESSAGE may be either a string or a buffer.

We could try to use something like `call-process` directly, the problem is that I think tramp (and other file handlers) won't work well with that.

**Comment by maurelio1234** [comment]
@chy-causer can you test my last commit?

I'm just using the same trick used as `shell-command-to-string` to make it not display the output... just pass `t` as output buffer instead of passing a buffer. Let's see if it works better.

**Comment by chy-causer** [comment]
@maurelio1234 That looks perfect. The buffer at the bottom now no longer displays the list of files with \0 between them. Thanks!

👍
