### ISSUE TITLE
Question about Running Arbitrary Shell Command in Project Root

### ISSUE THREAD

**Issue by husainaloos** [bbatsov/projectile#1619]
This is more of a question than a bug. I did search the website and search for a function in emacs and couldn't find anything helpful.

I am wondering if Projectile supports running an arbitrary shell command in the project root. Suppose for example that I want a shell command such as `git log` or `cat file.txt` and I want to view the output. This is possible interactively via `projectile-run-shell-command-in-root`. But I am wondering if this is possible as a function call so that I can map it in commander.

I am also wondering if it is possible to run commands in the project root that require interaction with the user. (e.g. interactive staging in git). Is this also possible in Projectile (can it be run in term/vterm?)

My use case: I often find myself in projects that I need to run certain pre-defined commands in them that are not for compilation or running tests etc. They are for generating pull request, or for syntax analysis, or other purposes. In such case, I open a terminal within emacs and run them there. But I would like to instead define a command in commander for them. Some of these commands are interactive.

**Comment by bbatsov** [comment]
You can add commands to the commander like this:

```
(def-projectile-commander-method ?f
    "Find file in project."
    (projectile-find-file))
```

You can simply create your own alternatives of `projectile-run-shell-command-in-root` or `projectile-run-async-shell-command-in-root`. E.g.

```
(defun my-run-async-shell-command-in-root ()
  "Invoke `async-shell-command' in the project's root."
  (interactive)
  (projectile-with-default-dir (projectile-acquire-root)
    (async-shell-command "ls -l")))
```

I hope you get the idea.

**Comment by husainaloos** [comment]
Thank you. That gives me an idea of how to set the dir.
