### ISSUE TITLE
Projectile creates second window when switching projects

### ISSUE THREAD

**Issue by thepreacher** [bbatsov/projectile#1624]
## Expected behavior
With projectile installed and configured with the basic config:
```
(use-package projectile
  :ensure t
  :custom ((projectile-completion-system 'ivy))
  :init
  (projectile-mode +1)
  :bind (:map projectile-mode-map
              ("s-p" . projectile-command-map)
              ("C-c p" . projectile-command-map)))
```
When I press `C-c p p`, I expect **projectile** via **ivy** to list the available projects which it does. Now when I move the cursor on a desired project and I press **RET**, I expect projectile to enter root directory for the selected project listing it's content. This it does as well.

In addition I expect the current window prior to pressing `C-c p p` to be the only window visible. Then after I select a file by pressing RET, a new window with the content of the file, replace the previous window as the only one visible.

## Actual behavior
What actually happens is, after I hit `C-c p p`:

<img width="738" alt="Screenshot 2020-12-13 at 08 00 31" src="https://user-images.githubusercontent.com/219075/102006894-6a7eb700-3d1c-11eb-8276-5f17ecba4878.png"> 

and press RET on a desired project, projectile enters and list the content of the project root directory (as expected) BUT in addition, it creates a new window. 

<img width="738" alt="Screenshot 2020-12-13 at 08 00 49" src="https://user-images.githubusercontent.com/219075/102006915-8eda9380-3d1c-11eb-9298-0398fa73ac0e.png">

Then when I select and press RET on a file, it displays the content in this newly created window, leaving me with a second window I don't need.

## Steps to reproduce the problem

The code above is the only projectile code I have in my config.

### Projectile version information

```
Projectile version: 20201210.927
```

### Emacs version

*E.g. 27.1.50* 

### Operating system

*MacOS Big Sur*

**Comment by bbatsov** [comment]
Did this start happening recently? I can't reproduce it locally, but I'm wondering if it's not something to do with recent changes to project switching  we were doing.

**Comment by bbatsov** [comment]
(I'm mostly referring to https://github.com/bbatsov/projectile/pull/1621)

**Comment by thepreacher** [comment]
Unfortunately I can't tell if it's a recent change causing it since I was using **doom emacs** before. I'm not imposing or anything but here is a link to my current [init.el](https://www.apaste.info/wJJq) if you may want to try it. Thanks.

**Comment by thepreacher** [comment]
So I cleared all packages my `.config/emacs/elpa` folder and pinned projectile to `melpa-stable` like so:

```
(use-package projectile
  :ensure t
  :pin melpa-stable
  :custom ((projectile-completion-system 'ivy))
  :init
  (projectile-mode +1)
  :bind (:map projectile-mode-map
              ("s-p" . projectile-command-map)
              ("C-c p" . projectile-command-map)))

```

Then I installed all packages again and now the issue is gone.

**Comment by bbatsov** [comment]
Yeah, I guess it's related to #1621. @Deewiant Any ideas? That's not an issue I can reproduce locally with the latest Projectile, unless it's something to do with the `dired` switch action.

**Comment by Deewiant** [comment]
Doesn't reproduce for me, even with `(setq projectile-project-switch-action #'projectile-dired)`. Perhaps it has something to do with the various `dired`-related packages mentioned in the `init.el`.

Overall it seems strange to me that `with-temp-buffer` and/or `switch-to-buffer` would affect windows... But looking at the help for `switch-to-buffer` there does seem to be a lot more going on there than I anticipated. One could try setting `FORCE-SAME-WINDOW` there for instance, although even if it works I'm not really sure whether it's what we would want.

**Comment by thepreacher** [comment]
I've just reduced my init.el to 

```
;; Initialize package sources
(require 'package)

(setq package-archives '(("melpa" . "https://melpa.org/packages/")
                         ("org" . "https://orgmode.org/elpa/")
                         ("elpa" . "https://elpa.gnu.org/packages/")))

(package-initialize)
(unless package-archive-contents
  (package-refresh-contents))

  ;; Initialize use-package on non-Linux platforms
(unless (package-installed-p 'use-package)
  (package-install 'use-package))

(require 'use-package)
(setq use-package-always-ensure t)

;; Basic UI Configuration

(setq inhibit-startup-message t)

; Projectile
(use-package projectile
  :diminish projectile-mode
  :config (projectile-mode)
  :bind-keymap
  ("C-c p" . projectile-command-map)
  :init
  ;; NOTE: Set this to the folder where you keep your Git repos!
  (when (file-directory-p "~/projects")
    (setq projectile-project-search-path '("~/projects/learn/python/"))))

(provide 'init)
(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(package-selected-packages '(projectile use-package)))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 )

```

and I can still reproduce it. See below

![Screenshot 2020-12-14 at 16 26 04](https://user-images.githubusercontent.com/219075/102107288-7e640f00-3e29-11eb-8c9c-01cfd095c30d.png)

**Comment by Deewiant** [comment]
Tested using `emacs -q` and manually loading that file afterward, still doesn't reproduce.

I also tried using a very small frame since I felt like that could affect it somehow, but no luck.

Could it be Mac-specific somehow? I'm running Emacs 27.1 on Linux (Arch).

**Comment by bbatsov** [comment]
Thanks for testing this further! I'm also on Linux - Emacs 27.1 on Ubuntu 20.04. Still, it seems very unlikely to me that a glitch of this nature can be OS-specific. I'm mostly puzzled how the stable release works, but the master doesn't given I can't find anything but the commit I've suggested that can be related to this. A small mystery.

**Comment by bbatsov** [comment]
It seems that @expez encountered a similar issue in #1625. I have a feeling the problem was actually caused by different changes. (https://github.com/bbatsov/projectile/pull/1618) //cc @maurelio1234
