### ISSUE TITLE
projectile-find-file creates additional windows on Win10

### ISSUE THREAD

**Issue by expez** [bbatsov/projectile#1625]
`projectile-git-submodule-command`, with default value `"git submodule --quiet foreach 'echo $path' | tr '\\n' '\\0'"`, uses `tr` which isn't necessarily available on windows.  The missing `tr` utility causes an error which leaves an additional window open.  Setting `projectile-git-submodule-command` to `nil` resolves the problem for those of us that don't care about submodules.

`Projectile 20201214.839`

**Comment by bbatsov** [comment]
Seems you've just figured out the root cause for #1624. :-) I wonder why the problem started to appear now, though, as the command was the same for ages. Anyways, we'll sort this out.

**Comment by bbatsov** [comment]
My guess would be it's something to do with https://github.com/bbatsov/projectile/pull/1618 //cc @maurelio1234

**Comment by maurelio1234** [comment]
Ok, I can reproduce some weird behaviour in linux too, when we invoke `projectile-files-via-ext-command` with a command that does not exist.

I will investigate that, it will hopefully fix the problems you are seeing.

![newWindow](https://user-images.githubusercontent.com/6065520/102719083-270fe400-42ec-11eb-925b-f6046ebd3764.gif)
