### ISSUE TITLE
Prescient recommendation

### ISSUE THREAD

**Issue by DamienCassou** [bbatsov/projectile#1628]
Hi,

I'm wondering why prescient is less recommended than before. Anything happened?

Best

**Comment by bbatsov** [comment]
I've learned that the ivy-prescient package was unmaintained and was causing issues for some people using it. See https://github.com/raxod502/prescient.el/issues/65 If it works for you - that's great. I don't feel comfortable recommending an unmaintained package.

**Comment by DamienCassou** [comment]
Makes sense, thank you!
