### ISSUE TITLE
In emacs 28 "when" parameter are mandatory in function define-obsolete-variable-alias 

### ISSUE THREAD

**Issue by vpxyz** [bbatsov/projectile#1635]
In emacs 28 (master branch), the "when" parameter are mandatory in functions make-obsolete, define-obsolete-function-alias, make-obsolete-variable and define-obsolete-variable-alias. 
The issue in caused by the line 4878:
```(define-obsolete-variable-alias 'projectile-mode-line-lighter 'projectile-mode-line-prefix)```

## Expected behavior
projectile run as usual

## Actual behavior
emacs are unable to load projectile: 

```Debugger entered--Lisp error: (wrong-number-of-arguments (3 . 4) 2)
  #f(compiled-function (obsolete-name current-name when &optional docstring) "Make OBSOLETE-NAME a variable alias for CURRENT-NAME and mark it obsolete.....)  
(define-obsolete-variable-alias 'projectile-mode-line-lighter 'projectile-mode-line-prefix)
  eval-buffer(#<buffer  *load*-693182> nil "/home/vincenzo/.emacs.d/elpa/projectile-20210104.7..." nil t)  ; Reading at buffer position 208182
````
## Steps to reproduce the problem
Load projectile with emacs 28 (master branch)

### Projectile version information

```Projectile 20210104.700```

### Emacs version
GNU Emacs 28.0.50 (build 31, x86_64-pc-linux-gnu, GTK+ Version 3.24.24, cairo version 1.16.0)
 of 2021-01-04

### Operating system

Fedora 33

**Comment by bbatsov** [comment]
Thanks for reporting this!
