### ISSUE TITLE
Commit 0d52268 has broken storing the compile history between Emacs runs

### ISSUE THREAD

**Issue by Zalewa** [bbatsov/projectile#1637]
The compile history is no longer stored between Emacs runs.
The problem was introduced with commit 0d52268, issue #1601.

## Expected behavior

- `projectile-compile-project` command history should be saved on disk (by default in `~/emacs.d/history`)
- When Emacs is closed and started again, `projectile-compile-project` should load the history back from disk.

## Actual behavior

- The history from `projectile-compile-project` isn't saved.
- Even if there's previous history from before this problem started occurring, this history won't be loaded.
- The plain `compile` command loads/saves history just fine.

## Steps to reproduce the problem

1. Open any .cpp file from a C++ project in Emacs (my file path, for reference: `/mnt/n/dev/4walls/4walls/src/core/ecs/flags.cpp`)
2. `projectile-compile-project`
3. Customize the compile command.
4. Execute it.
5. Close Emacs.
6. Run Emacs again, reopen the same .cpp file.
7. `projectile-compile-project`, try to go back in history.

## Environment & Version information

I use Helm `20210111.1454`.

### Projectile version information

```
Projectile 20210104.1216
```

### Emacs version

```
GNU Emacs 27.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.20)
 of 2020-10-07
```

### Operating system

Kubuntu 20.04

**Comment by TxGVNN** [comment]
Sorry guys to make break your feature. I would like to find a solution to help both issues can be live together.

>  projectile-compile-project command history should be saved on disk (by default in ~/emacs.d/history)

But, I don't know this feature because I don't use it. Could you describe how can I produce it exactly?

Example: I have to run `emacs -Q -l ~/.emacs.d/elpa/projectile-20210125.726/projectile-autoloads.el --eval '(projectile-mode)'`

**Comment by knjmooney** [comment]
I can reproduce this issue by enabling savehist-mode
```
(savehist-mode)
```

**Comment by MetaDark** [comment]
> I can reproduce this issue by enabling savehist-mode

Oh, thanks! I thought this was a general problem, but I just checked my config and I have this enabled.

**Comment by bbatsov** [comment]
I'm leaning towards just reverting the problematic commit, as it seems it['s causing more problems than it solved, unless someone's willing to work out a solution that makes everyone happy.

**Comment by TxGVNN** [comment]
Sure, I totally agree. We should revert it before have a good solution.

I would like to make both features can live together. Could you guys have any idea about that? I will try to take some free time to implement it.

**Comment by knjmooney** [comment]
The obvious hack is to restore the old behaviour when save-hist is enabled.

It sounds like a neat feature to have a compile history per project, but I
haven't seen any history saved since the patch.

**Comment by TxGVNN** [comment]
I found a solution after using savehist-mode. Everyone just need to configure as bellow

```emacs-lisp
  (defvar savehist-additional-variables)
  (add-hook 'savehist-mode-hook
            (lambda nil
              (add-to-list 'savehist-additional-variables 'projectile-project-command-history)))
```
Example with use-package

```emacs-lisp
(use-package projectile
  :ensure t :defer t
  :init
  (defvar savehist-additional-variables)
  (add-hook 'savehist-mode-hook
            (lambda nil
              (add-to-list 'savehist-additional-variables 'projectile-project-command-history)))
...)
```

**Comment by TxGVNN** [comment]
> It sounds like a neat feature to have a compile history per project, but I haven't seen any history saved since the patch.

Could you check again? It works well for me.

**Comment by MetaDark** [comment]
Thanks, @TxGVNN! It works for me too. It looks like `evil-jumps` does the same thing: https://github.com/emacs-evil/evil/blob/1.14.0/evil-jumps.el#L296-L298

**Comment by Zalewa** [comment]
I also confirm @TxGVNN that this works for me. I used the `use-package` variant.
