### ISSUE TITLE
Trying to configure projectile-project gives wrong type argument: stringp, nil error

### ISSUE THREAD

**Issue by Randy1Burrell** [bbatsov/projectile#1642]
When I run projectile configure project I get the following error:
`Wrong type argument: stringp, nil`

## Expected behavior
Able to configure a project.

## Actual behavior
The following errors occur:
`Wrong type argument: stringp, nil`

## Steps to reproduce the problem
All I did was install projectile along with the following helper packager
- treemacs-projectile
- persp-projectile

Here's my configuration:

```emacs-lisp
(when (maybe-require-package 'projectile)
  (add-hook 'after-init-hook 'projectile-mode)

  ;; Shorter modeline
  (setq-default projectile-mode-line-prefix " Proj")

  (when (executable-find "rg")
    (setq-default projectile-generic-command "rg --files --hidden"))

  (with-eval-after-load 'projectile
    (define-key projectile-mode-map (kbd "C-c p") 'projectile-command-map))

  (maybe-require-package 'ibuffer-projectile))

(unless (package-installed-p 'use-package)
  (package-install 'use-package))

(use-package perspective
  :config
  (setq persp-state-default-file "~/.emacs.d/persp-confs/persp-auto-save")
  :init
  (persp-mode)
  :bind (("s-b" . persp-counsel-switch-buffer)
         ("s-M-b" . persp-ivy-switch-buffer)
         ("C-x b" . persp-switch-to-buffer*)
         ("C-x k" . persp-kill-buffer*)))

(add-hook 'kill-emacs-hook #'persp-state-save)

(use-package persp-projectile
  :bind (("s-p" . projectile-persp-switch-project)))
```

### Projectile version information
```
Projectile version: Projectile 20210104.1216
```

### Emacs version
GNU Emacs 27.1 (build 1, x86_64-apple-darwin18.7.0, NS appkit-1671.60 Version 10.14.6 (Build 18G95))
 of 2020-08-12

### Operating system
macOS Big Sur

**Comment by bbatsov** [comment]
If you can post here the full backtrace, it'd be much easier to figure out where exactly the error is happening.

**Comment by Randy1Burrell** [comment]
That's the only output I get when I run this command. It is bound to `C-c p C`. Is there a way I could debug and step through this function when it is called? I can do that then post its output here.

**Comment by bbatsov** [comment]
Just type `M-x toggle-debug-on-error` before running the problematic command. You should get a proper backtrace then.

**Comment by Randy1Burrell** [comment]
Great thanks!

Here's the BackTrace:
```
Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  string-match("\\`\\s *cd\\(?:\\s +\\(\\S +?\\|'[^']*'\\|\"\\(?:[^\"`$\\]\\|\\\\..." nil)
  #f(compiled-function (command &optional mode name-function highlight-regexp) "Run compilation command COMMAND (low level interface).\nIf COMMAND starts with a cd command, that becomes the `default-directory'.\nThe rest of the arguments are optional; for them, nil means use the default.\n\nMODE is the major mode to set in the compilation buffer.  Mode\nmay also be t meaning use `compilation-shell-minor-mode' under `comint-mode'.\n\nIf NAME-FUNCTION is non-nil, call it with one argument (the mode name)\nto determine the buffer name.  Otherwise, the default is to\nreuses the current buffer if it has the proper major mode,\nelse use or create a buffer with name based on the major mode.\n\nIf HIGHLIGHT-REGEXP is non-nil, `next-error' will temporarily highlight\nthe matching section of the visited source line; the default is to use the\nglobal value of `compilation-highlight-regexp'.\n\nReturns the compilation buffer created." #<bytecode 0x1ff35cbb66e1>)(nil nil)
  apply(#f(compiled-function (command &optional mode name-function highlight-regexp) "Run compilation command COMMAND (low level interface).\nIf COMMAND starts with a cd command, that becomes the `default-directory'.\nThe rest of the arguments are optional; for them, nil means use the default.\n\nMODE is the major mode to set in the compilation buffer.  Mode\nmay also be t meaning use `compilation-shell-minor-mode' under `comint-mode'.\n\nIf NAME-FUNCTION is non-nil, call it with one argument (the mode name)\nto determine the buffer name.  Otherwise, the default is to\nreuses the current buffer if it has the proper major mode,\nelse use or create a buffer with name based on the major mode.\n\nIf HIGHLIGHT-REGEXP is non-nil, `next-error' will temporarily highlight\nthe matching section of the visited source line; the default is to use the\nglobal value of `compilation-highlight-regexp'.\n\nReturns the compilation buffer created." #<bytecode 0x1ff35cbb66e1>) (nil nil))
  compilation-start(nil nil)
  compile(nil)
  projectile-run-compilation(nil)
  projectile--run-project-cmd(nil #<hash-table equal 1/65 0x1ff3602ec40d> :show-prompt nil :prompt-prefix "Configure command: " :save-buffers t)
  projectile-configure-project(nil)
  funcall-interactively(projectile-configure-project nil)
  call-interactively(projectile-configure-project nil nil)
  command-execute(projectile-configure-project)
```

**Comment by bbatsov** [comment]
Much better! From the look of it seems that that `string-match` is matching against `nil` which causes the error. I'm guessing that `nil` is the configuration command, but I assume you've entered one manually when you were prompted about it right?

**Comment by bbatsov** [comment]
>   projectile-run-compilation(nil)

That's what bothers me - it seems that `projectile-run-compilation` is passed a `nil`, instead of some command to run (which should come from `projectile-configure-project`.

**Comment by Randy1Burrell** [comment]
> Much better! From the look of it seems that that `string-match` is matching against `nil` which causes the error. I'm guessing that `nil` is the configuration command, but I assume you've entered one manually when you were prompted about it right?

I was never prompted for one. I am wondering if there is another package locally messing with my configuration and automatically passing `nil` to this command without me knowing.

**Comment by Randy1Burrell** [comment]
Reading the docstring for `projectile-configure-project` I noticed that it depends on `compilation-read-command` to be `t` so that it will prompt for command. That made me curious, so I did a little digging and found something interesting.

Here goes `compilation-read-command` current configuration:
<img width="636" alt="image" src="https://user-images.githubusercontent.com/10135939/104871768-f38b9e00-5919-11eb-88f6-88d5ef8d6e4e.png">

And here goes `compile-command` current configuration:
<img width="694" alt="image" src="https://user-images.githubusercontent.com/10135939/104872127-f89d1d00-591a-11eb-95ab-2259eab00f77.png">

Doing a search for the `compile-command` in my emac.d init files, here is the culprit messing with my `compile-command`:
<img width="694" alt="image" src="https://user-images.githubusercontent.com/10135939/104872279-719c7480-591b-11eb-95f0-7b9891476a16.png">

So I updated the culprit to:
<img width="694" alt="image" src="https://user-images.githubusercontent.com/10135939/104873446-89c1c300-591e-11eb-9474-59d71921ed55.png">

And now all the configurations are back to normal:
```
compilation-read-command
```
<img width="694" alt="image" src="https://user-images.githubusercontent.com/10135939/104873526-b70e7100-591e-11eb-8f60-ea8453daa300.png">

```
compile-command
```
<img width="694" alt="image" src="https://user-images.githubusercontent.com/10135939/104874037-ea053480-591f-11eb-8cc7-27c05f05fc03.png">

Now when I run `C-c p C` I get `Configure Command:` prompt and a compilation output:
<img width="694" alt="image" src="https://user-images.githubusercontent.com/10135939/104874198-51bb7f80-5920-11eb-8fcf-34ad00f0d2c6.png">

This serves as a lesson to me to not copy unmodified Emacs configuration code from the net, but then again I should probably not be too hard on myself. After all, I have only been using Emacs for a few months. Smh.

@bbatsov thanks very much for you help 💯

**Comment by Randy1Burrell** [comment]
Closing!
