### ISSUE TITLE
projectile should run maven with "mvn -B"

### ISSUE THREAD

**Issue by steinarb** [bbatsov/projectile#1647]
projectile should use the "-B" command line argument when using maven to compile the project.

This removes all of the text coloring escape characters of the output and results in a lot less clutter in the compile buffer.

I.e. you get
```
mvn -B clean install
[INFO] Scanning for projects...
[INFO] 
...
```
instead of
```
mvn clean install
[^[1;34mINFO^[m] Scanning for projects...
[^[1;34mINFO^[m] 
...
```

**Comment by bbatsov** [comment]
I'm fine with the suggestion. Haven't used `maven` in a while - last time I checked it didn't use ANSI colours. :-)

**Comment by steinarb** [comment]
Created a PR for this, but it wasn't shown here: https://github.com/bbatsov/projectile/pull/1652
