### ISSUE TITLE
Show branch info in dired mode-line

### ISSUE THREAD

**Issue by adamWithF** [bbatsov/projectile#1648]
## Expected behavior

The information about current branch should shows up in Dired buffer mode-line.

## Actual behavior

The information about current branch doesn't show up in Dired buffer mode-line.

## Steps to reproduce the problem

1. Open folder in Dired mode for one of files inside git repo.
2. Current branch name should show up in Dired buffer mode-line.

### Projectile version information

Projectile version: 20201214.839

### Emacs version

GNU Emacs 27.1.90 (build 1, x86_64-apple-darwin19.6.0, NS appkit-1894.60 Version 10.15.7 (Build 19H2)) of 2021-01-11

### Operating system

macOS 10.15.7

**Comment by bbatsov** [comment]
> The information about current branch should shows up in Dired buffer mode-line.

Should it? I've been using dired for ages and this is the first time I hear of this. :-) How is this related to Projectile, btw?

**Comment by farynaio** [comment]
> > The information about current branch should shows up in Dired buffer mode-line.
> 
> Should it? I've been using dired for ages and this is the first time I hear of this. :-) How is this related to Projectile, btw? 

Thanks for prompt reply. Yes, sorry, you are right. It's something that would be nice to have but it's not promised by projectile by itself.

Any hint how to pull branch information while inside Dired buffer?
