### ISSUE TITLE
History in projectile-run-project lists all duplicates

### ISSUE THREAD

**Issue by doctordesh** [bbatsov/projectile#1654]
(disclaimer, I don't know if this is a bug or intentional behaviour, but since this was a bug template I used it)

## Expected behavior

* Given a history of different commands run with `projectile-run-project`, where some commands have been used multiple times in a row (like: `<cmd1>`, `<cmd1>`, `<cmd1>`, `<cmd2>`, `<cmd1>`, `<cmd1>` ...)
* When using `M-p` and `M-n` to move in the history
* Then projectile should only move between "unique" entries and ignores the duplicates

**Informal example**

I made 1 call to do `go mod vendor` then ~15 calls to `go run main.go`. I had to use `M-p` 15 times to get back to `go mod vendor`

## Actual behavior

Projectile keeps all the commands in the history, regardless of uniqueness. 

## Steps to reproduce the problem

* Run `<cmd1>` 1 time
* Run `<cmd2>` 10 times
* Use `M-p` 10 times to move up to <cmd1>

### Projectile version information

```
Projectile version: 20210104.1216
```

### Emacs version

27.1

### Operating system

macOS

**Comment by bbatsov** [comment]
Projectile simply delegates to `complilation-mode` for the command execution. Perhaps there's some way to instruct it to keep only unique commands in its history.
