### ISSUE TITLE
[Proposal] Should projectile-compile-project support comint-mode?

### ISSUE THREAD

**Issue by TxGVNN** [bbatsov/projectile#1669]
Hi @bbatsov,

Today, I ran a command need interactively then I see `projectile-compile-project` doesn't support comint-mode as `compile` command is doing.

Should we support it?

## Expected behavior

`C-u M-x projectile-compile-project` run `(compile cmd t)` as `C-u M-x compile`

## Actual behavior

`C-u M-x projectile-compile-project` has the meaning same with `(setq compilation-read-command t)`.

## Proposal

We had `compilation-read-command` to decide to read the command or not. So I propose use `(C-u) PREFIX` to decide to run `comint-mode` in compilation mode.

If you see that makes sense and agree on this change. I can take time to work on it

**Comment by TxGVNN** [comment]
I switched to use `project-compile` instead, thanks.

**Comment by bbatsov** [comment]
Fair enough.

**Comment by bbatsov** [comment]
Fixed by https://github.com/bbatsov/projectile/pull/1672
