### ISSUE TITLE
CMake configurePresets not  used

### ISSUE THREAD

**Issue by tastytea** [bbatsov/projectile#1673]
## Expected behavior

`projectile-configure-project` lets me select CMake presets.

## Actual behavior

`projectile-configure-project` wants to run `cmake -S . -B build`.

## Steps to reproduce the problem

* Make sure `projectile-enable-cmake-presets` is set to `t`
* Clone https://schlomp.space/tastytea/epubgrep.git
* Open project in Emacs
* Run `projectile-configure-project`

### Minimal init.el

```elisp
(customize-set-variable 'straight-repository-branch "master")
;; Bootstrap straight.
(defvar bootstrap-version)
(let ((bootstrap-file
       (expand-file-name "straight/repos/straight.el/bootstrap.el"
                         user-emacs-directory))
      (bootstrap-version 5))
  (unless (file-exists-p bootstrap-file)
    (with-current-buffer
        (url-retrieve-synchronously
         "https://raw.githubusercontent.com/raxod502/straight.el/develop/install.el"
         'silent 'inhibit-cookies)
      (goto-char (point-max))
      (eval-print-last-sexp)))
  (load bootstrap-file nil 'nomessage))
(require 'straight)

(straight-use-package 'projectile)
(customize-set-variable 'projectile-enable-cmake-presets t)
```

### Projectile version information

```
Projectile 2.4.0
```

### Emacs version

*27.1*

### Operating system

*Gentoo Linux*

## Additional information

`projectile-compile-project` works as expected with this [CMakeUserPresets.json](https://github.com/bbatsov/projectile/files/6592234/CMakeUserPresets.json.txt) – I can select the preset “3jobs”.

CMake version is 3.20.3. `cmake --preset=dev` works from the command line.

**Comment by jehelset** [comment]
It's looking for the wrong file for system presets: https://github.com/bbatsov/projectile/blob/master/projectile.el#L2831

Should be `CMakePreset.json` instead of `CMakeSystemPreset.json`.

**Comment by tastytea** [comment]
Thanks, works fine with patch! 💖
