### ISSUE TITLE
Question: How can I enable "packagejson" to match "package.json"

### ISSUE THREAD

**Issue by SalTor** [bbatsov/projectile#1695]
## Expected
After typing `j` with this screenshow, minibuffer input would be "packagej", I would expect the filtered list to have the same contents
![Screen Shot 2021-07-16 at 4 31 51 PM](https://user-images.githubusercontent.com/3672698/126005407-277bc822-68c4-4f04-9c1b-173e68b280ac.jpg)

## Reality
I have to place a space between `package` and `j` before matches continue because there's no continuous match with `packagej`

I'm coming from fzf and I would love to have this sort of matching available. I'm not sure if it's available with helm-projectile but I'm not using helm

## Environment & Version information
OSX Catalina

### Projectile version information

```
Projectile version 20210503.738
```

### Emacs version

```
GNU Emacs 27.2 (build 1, x86_64-apple-darwin19.6.0, NS appkit-1894.60 Version 10.15.7 (Build 19H524))
 of 2021-06-28
```

### Operating system
OSX

**Comment by bbatsov** [comment]
So, that's a ticket for `helm-projectile`, not projectile itself, right? If so - we should move it to the right repository.

**Comment by SalTor** [comment]
No this isn't for helm-projectile because I'm actually using selectrum. However, since you pointed out that out, my impression is this may specific to the narrowing list tool, or at the very least not to projectile. More specifically, I have recently come across a project that I believe demonstrates my issue is not with projectile nor with [insert narrowing list tool], but instead the completion style being used. Namely, [axelf4/hotfuzz](https://github.com/axelf4/hotfuzz). Now, it doesn't solve the issue I listed above, but I think this shows me where I might put my efforts next. Thanks @bbatsov 👍
