### ISSUE TITLE
`projectile-ripgrep` do not search into hidden files

### ISSUE THREAD

**Issue by pierrelegall** [bbatsov/projectile#1708]
The default behavior of `ripgrep` is to not search into hidden files (files beginning with a dot) by default. As a result, using `projectile-ripgrep` do not search into hidden files. This is from my point of view an unexpected behavior in the context of a project search.

## Expected behavior

`projectile-ripgrep` should search into hidden files by default.

## Actual behavior

`projectile-ripgrep` ignore hidden files.

## Steps to reproduce the problem

Search with `projectile-ripgrep` a patterm you have in a hidden file of your project. You will not found it in the results.

### Projectile version information

Projectile 2.4.0

### Emacs version

Emacs 27.1 (Doom Emacs)

### System info

GNU/Linux, Ubuntu 20.04
ripgrep 11.0.2

**Comment by bbatsov** [comment]
Perhaps it'd be nice to introduce some defcustom controlling this behaviour for all search backends. I'd rather not hardcode this, as I assume different people have different expectations.

**Comment by nordlow** [comment]
Does a hidden file in this case include a `.git` directory?
