### ISSUE TITLE
projectile-switch-buffers with prefix argument plus k also kills current buffer

### ISSUE THREAD

**Issue by NimoTh** [bbatsov/projectile#1709]
## Expected behavior
<kbd>C-u C-c p p Enter k</kbd> (i.e. prefix argument plus `projectile-switch-project`, select project, plus <kbd>k</kbd> for kill) should only kill buffers of the subsequently selected project. In particular, do not kill the current buffer if it is not of that project (otherwise, I wouldn't have to use the prefix command; I could just run `projectile-kill-buffers`).

## Actual behavior
The current buffer is killed, as well, even though it is not part of the selected project.

## Steps to reproduce the problem
Open one or more buffers of project 'a'. Switch to a buffer of project 'b'. Enter prefix <kbd>C-u</kbd> and run `projectile-switch-project` (e.g., via <kbd>C-c p p</kbd>), select a project, and press <kbd>k</kbd> for kill.

### Projectile version information
```
Projectile 2.6.0-snapshot
```

### Emacs version
GNU Emacs 27.2 (build 1, x86_64-apple-darwin18.7.0, Carbon Version 158 AppKit 1671.6) of 2021-03-27

### Operating system
macOS Big Sur Version 11.5.2 (20G95)

**Comment by bbatsov** [comment]
What `k` is for `projectile-commander`, right?

**Comment by NimoTh** [comment]
Correct, and thanks for reminding me about `projectile-commander` :-)
