### ISSUE TITLE
You make it look like I need `<prefix> s g` to use rg or ag?

### ISSUE THREAD

**Issue by x-yuri** [bbatsov/projectile#1710]
> Grep (search for text/regexp) in project (kbd:[s-p s g]) (grep alternatives like ag, pt and rg are also supported)

https://github.com/bbatsov/projectile/blob/v2.5.0/doc/modules/ROOT/pages/usage.adoc#basic-usage

Took me a while to figure out.

On a side note, do you really support `pt`? At first glance, it doesn't look so.

**Comment by bbatsov** [comment]
Not directly - see https://github.com/bbatsov/projectile/issues/355

> Took me a while to figure out.

What exactly was confusing to you?

**Comment by bbatsov** [comment]
> You make it look like I need <prefix> s g to use rg or ag?

Ah, got it. I didn't pay enough attention to the title. Yeah, I can agree that's a bit confusing. I'll reword it.
