### ISSUE TITLE
opening the selected file will create a projectile first.This is troubling.

### ISSUE THREAD

**Issue by e190** [bbatsov/projectile#1711]
*Use the template below when reporting bugs. Please, make sure that
you're running the latest stable Projectile and that the problem you're reporting
hasn't been reported (and potentially fixed) already.*

**Remove all of the placeholder text in your final report!**

## Expected behavior
I use rg.el (https://github.com/dajva/rg.el)

In rg-dwim, opening the selected file (compile-goto-error) will create a projectile first.This is troubling.
`````````````
Projectile is initializing cache for /....../ ...
`````````````
I remember the previous version didn't create pro first.I don't want this feature, I can only simply open the file..
The actual function used is [compile-goto-error]

I tried setting it up

  (setq projectile-auto-update-cache nil)
  (setq projectile-enable-caching nil)
  (setq projectile-auto-discover nil)

It doesn't help, right

## Actual behavior
I don't want to create Projectile when USING compile-goto-error

## Steps to reproduce the problem
1. rg-dwim
2. opening the selected file (compile-goto-error)

*This is extremely important! Providing us with a reliable way to reproduce
a problem will expedite its solution.*

### Projectile version information

*Include here the version string displayed by `M-x
projectile-version`. Here's an example:*

```
Projectile version: 0.14
```

### Emacs version

 27.2

### Operating system

arch linux latest.

**Comment by bbatsov** [comment]
> I remember the previous version didn't create pro first.I don't want this feature, I can only simply open the file..
> The actual function used is [compile-goto-error]

I can't think of any recent changes to this behaviour. I guess you're just visiting a file in a project and that triggers the caching, but it should have always been like this. 

>  (setq projectile-enable-caching nil)

This should definitely work, as without it there's no caching.
