### ISSUE TITLE
Option to disable the projectile menu

### ISSUE THREAD

**Issue by skangas** [bbatsov/projectile#1712]
The "Projectile" menu (in `menu-bar-mode`) is always shown when `projectile-mode` is enabled.

Please consider adding an option to disable (hide) the menu.

**Comment by bbatsov** [comment]
That's easy to do, but I don't think it's very common for Emacs packages. Why does the menu bother you?

**Comment by skangas** [comment]
Because it is enabled globally it makes it harder to debug menu issues in Emacs. I first have to turn off `projectile-mode` so it doesn't clutter my view.

Yasnippet provides the option `yas-use-menu` that I find very helpful.

**Comment by bbatsov** [comment]
Hmm, I thought global menus were fairly common, but I might be mistaken. I'm not opposed to adding a defcustom about this.

**Comment by skangas** [comment]
Thank you!
