### ISSUE TITLE
REQUEST: Consider detects GNUMakefile

### ISSUE THREAD

**Issue by blame2020** [bbatsov/projectile#1718]
## Expected behavior

Projectile detectes a make  file project from GNUMakefile. GNUMakefile is valid file name for GNU Make by default.

cf. https://www.gnu.org/software/make/manual/make.html

## Actual behavior

Projectile doesn't detect GNUMakefile.

Maybe GNUMakefile not registered in projectile.el such as the follow sequences. However I don't know how to fix it correctly. 

```
;; Make & CMake
(projectile-register-project-type 'make '("Makefile")
                                  :project-file "Makefile"
                                  :compile "make"
                                  :test "make test"
                                  :install "make install")
```

## Steps to reproduce the problem

```
make foo
cd foo
touch GNUMakefile
touch main.c
emacs main.c
```

## Environment & Version information
Maybe any platform and any versions.

**Comment by bbatsov** [comment]
Should be an easy fix - we can just register a `gnumake` project type, that's pretty much the same as the `make` one.
