### ISSUE TITLE
Projectile Not Finding Projects Directory 

### ISSUE THREAD

**Issue by artforlife** [bbatsov/projectile#1719]
Having recently built the latest Emacs 29, I have noticed that the projectile is not able to find the projects directory. 

That is, whenever I try to run `projectile-switch-project`, instead of getting a list of projects to choose from in curly brackets, I get nothing. Furthermore, whenever I try to manually switch to any of my projects, I get a message that that directory is not a project.

In the config, I have the following pertaining to Projectile and Magit

```
(global-set-key (kbd "C-x g") 'magit-status)
(put 'upcase-region 'disabled nil)

(require 'projectile)
(define-key projectile-mode-map (kbd "s-p") 'projectile-command-map)
(define-key projectile-mode-map (kbd "C-c p") 'projectile-command-map)
(setq projectile-project-search-path '( "~/sites/" "~/Projects/"))
(projectile-mode +1)
(setq projectile-switch-project-action 'projectile-vc)
(eval-after-load "projectile" 
  '(progn (setq magit-repo-dirs (mapcar (lambda (dir)
                                         (substring dir 0 -1))
                                       (seq-filter (lambda (project)
                                                        (file-directory-p (concat project "/.git/"))) 
                                                      (projectile-relevant-known-projects))))

	  (setq magit-repo-dirs-depth 1)))
```

Emacs version: 
This is GNU Emacs 29.0.50 (build 2, x86_64-pc-linux-gnu, GTK+ Version 3.24.20, cairo version 1.16.0)
 of 2021-11-10

Projectile version (returns nil):
Checking /home/user/.emacs.d/elpa/projectile-20211103.2050...
Done (Total of 1 file compiled, 2 skipped)
Package ‘projectile’ installed.
Making completion list...
Projectile nil
You can run the command ‘projectile-version’ with M-x pr-ve RET
Projectile nil [2 times]

Operating system:
Ubuntu 20.04 LTS

**Comment by bbatsov** [comment]
Probably some temp regression in the development build, but it's hard to be sure. I rarely track the upstream development these days, as things there change very rapidly. If someone figures out what upstream change caused this breakage I'll take a closer look.

**Comment by artforlife** [comment]
I believe this can be closed. I have just gotten everything to work. Something did change on the Emacs side as the directories needed to be specified in the following format `/home/user/projects`.

**Comment by bbatsov** [comment]
Actually I'm fairly certain you just fell victim of Projectile stopping to enable `ido` out-of-the-box https://emacsredux.com/blog/2021/04/19/configuring-minibuffer-completion-in-projectile/
