### ISSUE TITLE
matching with python files takes up to 10 seconds

### ISSUE THREAD

**Issue by rkachach** [bbatsov/projectile#1753]
*Use the template below when reporting bugs. Please, make sure that
you're running the latest stable Projectile and that the problem you're reporting
hasn't been reported (and potentially fixed) already.*

**Remove all of the placeholder text in your final report!**

## Actual behavior
When I start typing a **python file name** it takes 10 seconds to get the match.  This doesn't happen with other extensions. If I type the filename up to ".p" without the y letter then it works (i.e myfile.p  instead of myfile.py)

## Steps to reproduce the problem
open a project and start typing the name of the python file (including the extension **.py**). It takes 10 seconds go get the match highlighted. 

*This is extremely important! Providing us with a reliable way to reproduce
a problem will expedite its solution.*

### Projectile version information

*Include here the version string displayed by `M-x
projectile-version`. Here's an example:*

```
projectile     Projectile 2.6.0-snapshot (20220211.932)
```

### Emacs version

*E.g. 24.5* (use <kbd>C-h C-a</kbd> to see it)
```
spacemacs
emacs 27.2

```
### Operating system
Fedora 35

**Comment by bbatsov** [comment]
Can you get some profiling data from Emacs, so we can get a better idea where exactly this problem occurs? Off the top of my head I don't have any ideas what might be causing `.py` files to be treated differently.
