### ISSUE TITLE
`projectile-toggle-between-implementation-and-test results` in `or: No matching test file found for project type ‘lein-test’` when the corresponding test file doesn't exist

### ISSUE THREAD

**Issue by dklimov-allstreet** [bbatsov/projectile#1765]
## Expected behavior

projectile creates a test file

## Actual behavior

I get an error message `or: No matching test file found for project type ‘lein-test’` when there's no test file 

## Steps to reproduce the problem

- create a clojure project using `lein new` 

- find a new clj file deep inside `src/` dir

- run M-x `projectile-toggle-between-implementation-and-test results`

### Projectile version information
```
Projectile version: 2.6.0-snapshot
```

### Emacs version
```
GNU Emacs 26.3 (build 2, x86_64-pc-linux-gnu, GTK+ Version 3.24.14) of 2020-03-26, modified by Debian
```

### Operating system

Ubuntu 20.04

**Comment by LaurenceWarne** [comment]
I think an error here is right, but the error message is wrong.  Given an impl file without a corresponding test (ie the situation you describe) to determine a test file location we need some way of determining a test file location: so one of `test-dir` (with `src-dir`) and/or `related-files-fn` should be set for that project type.  But none of these are set for the `lein-test` project type:
```elisp
(projectile-register-project-type 'lein-test '("project.clj")
                                  :project-file "project.clj"
                                  :compile "lein compile"
                                  :test "lein test"
                                  :test-suffix "_test")
```

The following for example would string replace `src` for `test` to get the test file name.
```elisp
(projectile-update-project-type 'lein-test
                                :src-dir "src"
                                :test-dir "test")
```
Testing the above locally with `projectile-create-missing-test-files` set inside `foo/src/core.clj` sticks me in `foo/test/foobar_test.clj`.  If this is the standard for `lein` projects (I don't know if it is) the I'd say this should be set (alongside a better error message, something like `'projectile-create-missing-test-files' is set, but cannot determine directory of test file for 'foo.bar', set one of 'foo'/'bar' for this project type to make this explicit`).

But there was a behaviour change in https://github.com/bbatsov/projectile/pull/1734, prior to that PR if a project type didn't have a `src-dir` and `test-dir` property, these were assumed to be `src` and `test` respectively (apologies I don't recall if it was deliberate or if it slipped my mind at the time).  If that's the desired behaviour, I'm happy to PR it back in.

**Comment by dklimov-allstreet** [comment]
> If that's the desired behaviour, I'm happy to PR it back in.

I don't know if it's desired or not, but it worked for me before

**Comment by LaurenceWarne** [comment]
I think reverting to having `src-dir` and `test-dir` use defaults but maybe checking these make sense (e.g. does `foo/path` contain `src`) would solve this - so there'd be backward compat where it's of use.  I'm a bit busy at the moment I can try putting a PR together at the weekend or next week, does the workaround above work for you in the meantime?

**Comment by LaurenceWarne** [comment]
@dklimov-allstreet are you able to pull https://github.com/bbatsov/projectile/pull/1769 and see if it works as you would expect?  fyi test for this case: https://github.com/bbatsov/projectile/blob/e6af68171dcd24d62614a8ce7f2e9df52dfd34aa/test/projectile-test.el#L1333
