### ISSUE TITLE
`projectile-root-bottom-up` doesn’t always find bottom-most file

### ISSUE THREAD

**Issue by sellout** [bbatsov/projectile#1796]
## Expected behavior

Given a directory structure like
```
~/projectile-example
├── .git
└── subdir
    └── .pijul
```
I’d expect `(projectile-root-bottom-up "~/projectile-example/subdir")` to return `"~/projectile-example/subdir/"`.

## Actual behavior

It returns `"~/projectile-example/"`.

## Steps to reproduce the problem

I think that’s covered above. To take out some environmental variability, we can be explicit about the files we’re searching for: `(projectile-root-bottom-up "~/projectile-example/subdir" '(".git" ".pijul"))`.

However, if we reverse the order, `(projectile-root-bottom-up "~/projectile-example/subdir" '(".pijul" ".git"))`, it does the right thing. But if the directory structure is instead 
```
~/projectile-example
├── .pijul
└── subdir
    └── .git
```
the reversed one now returns `~/projectile-example/` and the original returns the correct result.

The problem seems to be that `projectile-root-bottom-up` is actually returning the bottom-most directory _for the first name in the list that it finds at all_. Rather than using `cl-some` here, `projectile-root-bottom-up` should explore the full list and return the longest result.

### Projectile version information

Projectile 20220430.800

### Emacs version

GNU Emacs 28.1 (build 1, aarch64-apple-darwin21.6.0, NS appkit-2113.60 Version 12.6 (Build 21G115))

### Operating system

macOS 12.6 (21G115)

**Comment by sellout** [comment]
For now I am working around this by ordering `projectile-project-root-files-bottom-up` to match the current nestings that exist on my system. I.e., things that are used closer to `/` are later in the list.

**Comment by bbatsov** [comment]
Yeah, I think this detection has been broken for a while (I recall a couple of other reports). Should be fairly easy to fix, but I haven't had much time for Projectile recently.

**Comment by bbatsov** [comment]
Ah, I was actually thinking about different reports https://github.com/bbatsov/projectile/issues/1729
