### ISSUE TITLE
projectile-kill-buffers also kills scratch buffer

### ISSUE THREAD

**Issue by rbarbey** [bbatsov/projectile#1804]
## Expected behavior

When I call `projectile-kill-buffers` only project-related buffers are killed.

## Actual behavior

The `*scratch*` buffer is also killed.

## Steps to reproduce the problem

1. Open a couple of files belonging to the same project
2. Invoke `projectile-kill-buffers`
3. Try to switch to the scratch buffer
4. Observe it not being there

### Projectile version information

```
Projectile 20220804.1530
```

### Emacs version

GNU Emacs 28.2 (build 1, x86_64-apple-darwin18.7.0, NS appkit-1671.60 Version 10.14.6 (Build 18G95))
 of 2022-09-12

### Operating system

macOS 12.6

**Comment by bbatsov** [comment]
Likely this happened because the `default-directory` for `*scratch*` belonged to some project. I guess a simple fix would be to include a list of buffers that should never be killed.
