### ISSUE TITLE
Project Selection After C-c p p Requires Pressing Tab To Get List of Projects

### ISSUE THREAD

**Issue by artforlife** [bbatsov/projectile#1807]
## Expected behavior

They way I would always use Projectile was as follows. I would press C-c p p and see all known projectile projects in the minibuffer through which I could then arrow left and right and press Enter to select.

## Actual behavior

A couple of months ago I turned on automatic updates for Emacs packages. It updated Projectile on my machine. The behavior became as follows. After pressing C-c p p, I get a prompt that says: . I am then forced to press the tab key to get a directory completion. Upon that I type the name of a project directory and press Tab once more.

This could be the intended behavior. In this case, I vote to say that the original behavior was much better, much more useful and even cool! Would love to have it back.

## Steps to reproduce the problem

This happened after an update of some sort. I still have one machine which works the way it always did. It's Projectile version (per directory name) is 20200916. The version that does not work as desired is the newest version.

### Projectile version information
Projectile version (per directory name) is 20200916.

*Include here the version string displayed by `M-x
projectile-version`. Here's an example:*

### Emacs version

*GNU Emacs 28.0.50 (build 1, x86_64-apple-darwin20.6.0, NS appkit-2022.60 Version 11.6 (Build 20G165))
 of 2021-09-29

### Operating system

*MacOS, Ubuntu 22.04 LTS

**Comment by bbatsov** [comment]
Projectile used to force the use of ido in the past, but a year ago left it to the users to decide what completion framework to use. See https://emacsredux.com/blog/2021/04/19/configuring-minibuffer-completion-in-projectile/
