### ISSUE TITLE
The new `project-projectile` in `project-find-functions` caused candidates error

### ISSUE THREAD

**Issue by stardiviner** [bbatsov/projectile#1808]
https://github.com/bbatsov/projectile/blob/306df876d30eef8eb093fe880df9c2a3454d44a5/projectile.el#L6037

When have  the  new `project-projectile` in `project-find-functions`. I do project find file has bellowing candidates:

<img width="886" alt="image" src="https://user-images.githubusercontent.com/378699/198754046-74565651-56cb-4874-a5e9-bba3cb9fee41.png">

When I remove the `project-projectile` from  `project-find-functions`. The error is gone.

**Comment by bbatsov** [comment]
Hmm, it seems that the filename is not appended in the right order - I see the file is first and the folder comes after it. Let me look into this.

**Comment by bbatsov** [comment]
Should be good now - I had made a silly mistake when replacing an `expand-file-name` with `concat`.

**Comment by stardiviner** [comment]
Thanks for quick fixing. @bbatsov
