### ISSUE TITLE
Make projectile-run-vterm open vterm in other window

### ISSUE THREAD

**Issue by sathishmanohar** [bbatsov/projectile#1826]
`projectile-run-vterm` function works as expected but it replaces the existing buffer while opening. If the default behavior is similar to vterm-toggle or magit where vterm opens in the other window. It'll be better user experience.

## Expected behavior
Open Vterm in other window

## Actual behavior
Vterm open in the current buffer

## Steps to reproduce the problem
M-x projectile-run-vterm

## Additional info ( I could be wrong in this part )

libvterm provides and [option](https://github.com/akermu/emacs-libvterm#vterm-other-window) to open vterm with in other window with this function `vterm-other-window`

I believe instead of invoking vterm with the function `vterm` invoking with `vterm-other-window` will provide the desired functionality.

https://github.com/bbatsov/projectile/blob/master/projectile.el#L4480

```
Projectile 20230228.706
```

### Emacs version

28.2

### Operating system

Arch Linux

**Comment by bbatsov** [comment]
PR welcome!

**Comment by bbatsov** [comment]
Fixed by #1827.
