### ISSUE TITLE
Configuration option to open vterm in current window or other window

### ISSUE THREAD

**Issue by sathishmanohar** [bbatsov/projectile#1830]
Recently, `projectile-run-vterm` behavior was [changed](https://github.com/bbatsov/projectile/pull/1827) to open vterm in other window rather than current window. Some users prefer to have vterm open in current window. So having a configuration for this would be great.

**Comment by bbatsov** [comment]
I'll just have to think if this should a `vterm` specific setting or something that applies to most similar commands. I'm leaning towards the more generic option.
