### ISSUE TITLE
`project-projectile` interferes with `project-buffers`.

### ISSUE THREAD

**Issue by joostkremers** [bbatsov/projectile#1831]
## Actual behavior

I use `project.el` because my project needs are so modest that I figured I might as well go with the built-in option. However, Projectile is installed as a dependency of another package ([`python-pytest`](https://github.com/wbolster/emacs-python-pytest)) and I have the impression it interferes with `project.el`.

Specifically,  when I try to kill all project-related buffers with `C-x k p` (`project-kill-buffers`) Emacs tells me there are no buffers to kill. Indeed, `M-: (project-buffers (project-current))` returns `nil`.

If I then remove `project-projectile` from `project-find-functions`, things start working again.

I saw that the `add-hook` that adds `projectile-project` to `project-find-functions` was added fairly recently. I only skimmed the related discussion and I'm sure I missed some key points in it, but if I understand things correctly, this change doesn't take the situation of `python-pytest` into account, which is that it basically uses Projectile as a library. The `add-hook` accommodates users that use Projectile that encounter a package that uses `project.el` exclusively, but my situation is reversed: I use `project.el` and am encountering a package that uses Projectile exclusively.

If that is indeed the case (I may be completely wrong, of course, in which case please enlighten me), would it be possible to make sure Projectile can be used as a library, i.e., in such a way that loading the package doesn't change anything about the user's configuration?

## Steps to reproduce the problem

From `emacs -Q`, load Projectile, open a git-controlled file and do

    M-: (project-buffers (project-current))

This returns `nil`. Then remove `projectile-project` from `project-find-functions` and repeat:

    M-: (project-buffers (project-current))

It now returns a list of buffers with at least the current buffer in it.

### Projectile version information

Projectile 20230312.540

### Emacs version

Emacs 29

### Operating system

Arch Linux

**Comment by bbatsov** [comment]
> If that is indeed the case (I may be completely wrong, of course, in which case please enlighten me), would it be possible to make sure Projectile can be used as a library, i.e., in such a way that loading the package doesn't change anything about the user's configuration?

There's no way to tell how someone is using Projectile and I've opted to hook it into `project.el` by default as this is what most people expect. We can have some config to disable the project.el integration, but someone will have to know to do this and such config should definitely be set before Projectile gets loaded. 

> Specifically, when I try to kill all project-related buffers with C-x k p (project-kill-buffers) Emacs tells me there are no buffers to kill. Indeed, M-: (project-buffers (project-current)) returns nil.

Might be good to look into this specific issue as well. What's the project in which you're trying this? Is projectile failing to detect the project root there?

**Comment by joostkremers** [comment]
I looked into it a bit further. Turns out the problem is the fact that I'm visiting the file through a symlink. `project.el` doesn't expand/canonicalize the path to the project root, so it has `~` and uses the symlink. `projectile-project-root` uses `file-truename`, so we get the expanded path with all symlinks resolved. So basically, what happens is that the file paths of the root and the buffer don't match, so `project-buffers` doesn't return anything. In a project that I visit "directly", i.e., not through a symlink, the problem doesn't occur.

Possibly this can be resolved by overriding `project-buffers`, just like you override `project-files` in `projectile.el` (if I understand things right). But perhaps that's not really the way to go, given that there are more `defgenerics` in `project.el`. You might end up reimplementing `project.el` in terms of `projectile.el`... :wink: 

> There's no way to tell how someone is using Projectile and I've opted to hook it into `project.el` by default as this is what most people expect. 

Presumably everyone that chooses to install Projectile, yes. Unfortunately, I didn't, because it came as a dependency. (Not that I think it's a bad package, quite the contrary! It's just overkill for my needs. `project-kill-buffers` is essentially the only command I use...)

> We can have some config to disable the project.el integration, but someone will have to know to do this and such config should definitely be set before Projectile gets loaded.

That wouldn't stop this bug from occurring, because users in my situation don't necessarily know Projectile was installed, so they won't know they need to disable some option. They just notice that something (specifically, `project-kill-buffers`) that used to work suddenly stopped working, and it won't be immediately obvious (or obvious at all) that this was because of a package that they installed that on the face of it has nothing to do with project management.

Obviously, it's not your "fault" that other package authors use Projectile as a library, so I can understand if you're not immediately inclined to fix this. In any case, I'll update the python-pytest author, so they are aware of the problem as well, and I'll wait and see what you decide. If nothing else, I can always remove `project-projectile` from `project-find-functions` in an `with-eval-after-load`. :slightly_smiling_face:

**Comment by mattiasb** [comment]
Hm. Looking at [these lines](https://github.com/bbatsov/projectile/blob/master/projectile.el#L6153-L6173) it seems that the `project` integration is enabled *on load* which seems fishy to me. Loading a library should generally be side effect free.

Could this be hidden behind a minor mode perhaps?

**Comment by bbatsov** [comment]
That's one option, but the mode is kind of optional and people can use Projectile without it - this would force to enable this integration manually. While I agree that side-effects on load are not great, a ton of Emacs libraries do have side-effects on load. 

Anyways, I'd be fine with moving this to the minor mode setup code.

**Comment by joostkremers** [comment]
> Anyways, I'd be fine with moving this to the minor mode setup code.

Thanks! That looks like a good solution. :slightly_smiling_face:
