### ISSUE TITLE
projectile-find-file returns error fd: No such device or address

### ISSUE THREAD

**Issue by jsobiecki** [bbatsov/projectile#1832]
## Expected behavior

After running `projectile-find-file` I'd like to select project and file within project to open file and create new buffer.

## Actual behavior

The projectile-find-file allows me to switch to new project, but after that, I'm getting "projectile-files-error" buffer with "fd: No such device or address"

## Steps to reproduce the problem

`Open emacs`
`M-x projectile-find-file`
*Select project*
Get error

### Projectile version information

```20230312.540```

### Emacs version

`GNU Emacs 28.2 (build 2, x86_64-pc-linux-gnu, GTK+ Version 3.24.20, cairo version 1.16.0)
 of 2023-03-08`

### Operating system

`OS Ubuntu 22.04 LTS`

**Comment by bbatsov** [comment]
Seems related to #1825. Do you have `fd` installed?

**Comment by jsobiecki** [comment]
Hi @bbatsov 

Thank you for tip. You are right, it was related to this. I had fd installed on my local machine, but it was a completely different program (provided by fdclone package under ubuntu). 

What I did
1. Uninstalled fdclone (at this moment projectile started to work using find)
2. Installed fdfind package (At this moment projectile was able to find fdfind executable and use it).

So generally, it works as expected, problem was on my side. Thank you for your prompt reply and hint!
