### ISSUE TITLE
`C-c p f` doesn't work for symbolic links

### ISSUE THREAD

**Issue by kaushalmodi** [bbatsov/projectile#206]
In our project, we use a revision control system called SOS (like svn). When a file is checked in, its local physical copy is replaced with a symbolic link to its new cache location in a server. `C-c p f` cannot find those files (unlike the `C-x C-f` command).

The `C-x p o` command works with these symbolically linked files very well.

**Comment by stas00** [comment]
> The issue was solved after adding the below to my init. The "-L" ensures that the symbolic links are also searched.
> 
> ```
> (setq projectile-generic-command "find -L . -type f -print0")
> ```

I had the same issue with `projectile-recentf` and the above solved it too. Thank you, @kaushalmodi.

**Comment by kaushalmodi** [comment]
@stas00 I have since switched to an even faster/better method, using **ripgrep** (`rg`) instead of `find`.

- [projectile setup][1]
- [ripgrep setup to include symlinks (`--follow` arg)][2]

[1]: https://github.com/kaushalmodi/.emacs.d/blob/d7a6a6ceb25f57b1179bf65423feae39b38a8a8c/setup-files/setup-projectile.el#L95-L103
[2]: https://github.com/kaushalmodi/.emacs.d/blob/d7a6a6ceb25f57b1179bf65423feae39b38a8a8c/general.el#L108-L116
