### ISSUE TITLE
separate tag ignore

### ISSUE THREAD

**Issue by chalmagean** [bbatsov/projectile#217]
Not 100% sure if this is already covered, but I'd like to be able to have different ignores for my tags file (exclude html, js) and also would be nice to include gems and ruby source indexing in a rails project.

**Comment by bbatsov** [comment]
There hasn't been much activity on this ticket and our Core Team is spread too thin on so many tasks, so I'll just close it for the sake of having a cleaner lists of tasks to focus on. We'd gladly review a PR, but it's unlikely that'd we're going to tackle this ourselves in the foreseeable future.
