### ISSUE TITLE
Fuzzy file matcher matches temp files before normal ones

### ISSUE THREAD

**Issue by banister** [bbatsov/projectile#232]
Even if i type in exactly the name of the file (i.e `survey.rb`) it'll still match things like `#survey.rb#` first. It would be great if 'normal' files were matched first and ones beginning with `#` and so on were later down the list :)

**Comment by bbatsov** [comment]
//cc @lewang

**Comment by lewang** [comment]
I need a flx repro, so far it does not seem to be a problem with flx enabled.

**Comment by bbatsov** [comment]
I've been unable to reproduce this myself. `#....#` files always appear after the regular files.

**Comment by bbatsov** [comment]
Btw, an odd thing. The default `ido` config has this in it:

```
(defcustom ido-ignore-files
  '("\\`CVS/" "\\`#" "\\`.#" "\\`\\.\\./" "\\`\\./")
  "List of regexps or functions matching file names to ignore.
For example, traditional behavior is not to list files whose names begin
with a #, for which the regexp is ‘\\\\=`#’.  See the source file for
example functions that filter filenames."
  :type '(repeat (choice regexp function))
  :group 'ido)
```
How, files starting with `#` clearly are displayed for me.

**Comment by bbatsov** [comment]
There's also some command `ido-toggle-ignore` that seems to do nothing. This is kind of messed up. @dgutov @malabarba @lunaryorn Any ideas how this is supposed to work?

**Comment by lewang** [comment]
@bbatsov `ido-ignore-files` is only for files, I believe you are filtering filenames as strings.  You can apply filter to the file basenames with

    (ido-ignore-item-p base-name ido-ignore-files t)

before passing the collection to ido.

**Comment by lunaryorn** [comment]
@bbatsov I don't know.  I've jumped the Helm train and don't use IDO anymore.  And I never actually looked at its code, or its inner workings.

**Comment by Malabarba** [comment]
What @lewang explains makes sense. Though I've never looked deep into ido either.

**Comment by bbatsov** [comment]
Yeah, guess I'll look into it. @lunaryorn I never liked the bloat and constant changes inside Helm, but with the advent of `helm-core`, I might revisit it some day.

**Comment by lunaryorn** [comment]
@bbatsov Neither do I, nor do I particularly like how Helm is implemented, but it's just this awesome interface… and a great interface compensates a lot of quality issues in the code :)
