### ISSUE TITLE
Projectile should use vc-root-dir in Emacs >= 24.5

### ISSUE THREAD

**Issue by dcolascione** [bbatsov/projectile#323]
I've added a new vc-root-dir vc function to Emacs trunk, which will become 24.5. This function is a new generic interface for finding the root directory of a VC tree, and it'd be nice if Projectile could use it instead of (or at least in addition to) its hardcoded list of VCS root files and directories.

**Comment by bbatsov** [comment]
I'll close this ticket, as now that's a trivial matter of tweaking `projectile-project-root-functions` - https://docs.projectile.mx/projectile/projects.html#customizing-project-detection
