### ISSUE TITLE
projectile-persp-switch-project: Wrong type argument: hash-table-p, nil

### ISSUE THREAD

**Issue by goofansu** [bbatsov/projectile#336]
Emacs version: 
![screenshot of emacs 5-4-14 11 47 38 pm](https://cloud.githubusercontent.com/assets/1143191/2873346/70d8ba0e-d3a3-11e3-8e66-7592e31559e2.png)

Configured as following:

```
(require 'persp-projectile)
(define-key projectile-mode-map (kbd "s-s") 'projectile-persp-switch-project)
```

**Comment by hihozhou** [comment]
add
```
(projectile-mode)
```
to your emacs config file
