### ISSUE TITLE
Command projectile-replace attempting to process bytecode

### ISSUE THREAD

**Issue by spaceotter** [bbatsov/projectile#343]
I am using projectile/Emacs on Windows 7 (with unixy stuff installed) for my python project. The projectile-replace command is matching my query in python bytecode files. This causes the error shown below, which terminates the replace operation. There is no newline between the base path and "Binary file ..." so it seems projectile is just blindly inserting grep output. This is happening in spite of the fact that `__pycache__` and `*.pyc` are both blacklisted in my .projectile.

```
next-file: Opening input file: no such file or directory, e:/Projects/ente/Binary file ./src/ente/gui/__pycache__/_main_window.cpython-33.pyc matches
```
For projectile-files-with-string, you may consider adding the -I option to grep which will exclude binary files. I peeked at the source code and it is not clear that this function is using the .projectile rules.

**Comment by bbatsov** [comment]
I've just correct this today - binary files should now be excluded.
