### ISSUE TITLE
projectile-switch-project doesn't see remote projects

### ISSUE THREAD

**Issue by shevchuk** [bbatsov/projectile#347]
I have a few remote projects on my remote machines but they are invisible for projectil-switch-project
So I have to manually go to /ssh:remotemachine/home/me/src/my_project

/ssh:remotemachine/home/me/src/my_project/.projectile exists there

Though, projectile-find-file / projectile-grep work good.

**Comment by bbatsov** [comment]
The problem is that projects are tracked via a find-file hook, which is pretty slow for remote files and therefore - disabled. Apart from adding remote projects manually, there's not much else that can be done.
