### ISSUE TITLE
helm-projectile error

### ISSUE THREAD

**Issue by tuhdo** [bbatsov/projectile#358]
After updating latest packages today, I cannot use `helm-projectile` anymore:

> Helm issued errors: helm-match-from-candidates in source `Projectile Buffers': void-function (helm-buffer-match-major-mode) [8 times]

Probably it has to do with Helm's latest update, since my previous update was on Thursday.

**Comment by camdez** [comment]
As a quick fix for users still running the version with the issue (e.g. MELPA Stable users—last release was May 27, 2014), add the following to your `.emacs` file:

```elisp
(defalias 'helm-buffer-match-major-mode 'helm-buffers-list--match-fn)
```
