### ISSUE TITLE
Projectile Project File Override

### ISSUE THREAD

**Issue by LukeMauldin** [bbatsov/projectile#359]
I have a directory that is a git repository with a .gitignore file that ignores /vendor.  Projectile correctly reads this file and ignores /vendor.  However, I want Projectile to include /vendor so I created my own .projectile file in the same directory but it appears the Projectile prioritizes .gitignore over its own .projectile file.  Can this behavior be changed?

Emacs: 24.3.1 on Xbunutu 14.04

**Comment by tmccombs** [comment]
I would also like some way to override files ignored from .gitignore. Although I would really like a way to add back in a single file that is ignored, while still respecting the rest of the .gitignore. This would be a little more complicated than simply making .projectile have higher precedence.

**Comment by lwiechec** [comment]
I second that. I have a situation when I have a list of generated Java sources from JAXB that I would like to be able to quickly access using `C-c p f` but they are ignored because I have them in the `.gitignore` file.

**Comment by kostajh** [comment]
I'm running into the same problem with a PHP project, where many important source code files are in `vendor/`, but `vendor/` is in `.gitignore` so they're ignored by Projectile. I've looked through the docs and source a little bit and don't see a way around this issue. Did anyone figure out how to work around this problem?
