### ISSUE TITLE
Create test file when it does not exists

### ISSUE THREAD

**Issue by andrematheus** [bbatsov/projectile#375]
I'm using projectile with clojure. Before, I've used clojure-test-mode.el, and it has a `clojure-jump-to-test` function that works more or less like `projectile-toggle-between-implementation-and-test`.

However, one nice thing about clojure-jump-to-test is that, if there is no test for the current file, it visits a new file where the test file should be, whereas `projectile-toggle-between-implementation-and-test` returns an error **No matching test file found**.

I think it would be nice to have similar functionality in projectile. Right now, I've made a workaround by advising `projectile-toggle-between-implementation-and-test`, but that's not the best solution for sure.

For reference my workaround is:

``` elisp
(defun clojure-test-filename ()
  (concat (projectile-project-root) 
          "test/" 
          (mapconcat #'identity
                     (butlast (split-string (cider-current-ns) "\\.")) "/")
          "/"
          (file-name-nondirectory (file-name-sans-extension (buffer-file-name)))
          "_test.clj"))

(defadvice projectile-toggle-between-implementation-and-test (around create-clojure-test-advice)
  "Visit new file if can't find test"
  (condition-case nil
      ad-do-it
    (error (find-file (clojure-test-filename)))))

(ad-activate 'projectile-toggle-between-implementation-and-test)
```

**Comment by escherize** [comment]
Thanks, @andrematheus this was very helpful.

**Comment by jcf** [comment]
This feature has been added to Projectile, and can be activated like so:

``` emacs-lisp
(setq projectile-create-missing-test-files t)
```

Thanks @bbatsov et al.
