### ISSUE TITLE
You're not in a project

### ISSUE THREAD

**Issue by LouisKottmann** [bbatsov/projectile#376]
I get this error every now and then:

```
projectile-project-root: You're not in a project
Error in post-command-hook (projectile-global-mode-check-buffers): (error Youre not in a project")
```

And then I can't do anything anymore: all commands requiring minibuffer are plagued by this error and can't be used..

The problem is that so far I don't understand what triggers it. 
So for now this is an issue to try and gather other people experiencing the problem so that we can determine the cause (and then I'll try my best to fix it).

**Comment by bbatsov** [comment]
Closing as it's not actually a projectile bug.

**Comment by LouisKottmann** [comment]
Alright so I finally debugged it, and the problem came from my misusing @asok's projectile-rails.

It turns out it uses projectile's hooks to start up, and I was calling the wrong function...

Here's my commit that fixes the issue in my config: https://github.com/LouisKottmann/baboon-emacs/commit/1dc5f0bda7eb4fdc7a515030035ec3bff8510eae

**For people with the same issue:**

You will probably need a different fix than me, and the error given is really not helpful. I suggest you look through your projectile config and make sure you are calling the right functions.

I went through a bisect-style debugging, removing all the packages I use and my config in init.el, then re-adding the packages in bulk, then the config until I had the error again. So comment/uncomment until the culprit is isolated.
Good luck to you guys.

@bbatsov I'm not sure if you can do something about it, but a more helpful message would be.. more helpful ;)

**Comment by cybercode** [comment]
For future reference: This starting hitting me last week. The problem in my case was similar to @LouisKottmann. It was also cause by projectile-rails, but different issues/ causes:

With projectile-global-mode and `(add-hook 'projectile-mode-hook 'projectile-rails-on)`, navigating to a file in a symlinked directory under the rails-root will consistently trigger the problem. E.g:

```
Rails-root
  |_ tmp
     |_ {symlinked dir}
         |_ file.txt
```
opening `file.txt` will trigger the issue

**Comment by asok** [comment]
@cybercode sorry for the late response.
I've tried to reproduce the bug. For me it's working fine.

Maybe you could try to disable caching in projectile `(setq projectile-enable-caching nil)`? Or enable it if it's disabled.

Another thing, you could run emacs with `-q` flag, setup melpa, and install projectile-rails and see if the error persists in the bare Emacs.
