### ISSUE TITLE
Files not found when dired drilled down too far

### ISSUE THREAD

**Issue by mcandre** [bbatsov/projectile#393]
In a project with deep (7+) folder levels, when I drill down in dired too deeply and try to find a file in Projectile by typing the whole path (often pasted in from a bash session), Projectile cannot find the file.

As a workaround, I can back dired up the file tree several times, but I'd prefer that Projectile just work regardless.

Emacs 24 / Ubuntu 14.04.

**Comment by jmckitrick** [comment]
I'd like to take a shot at this. I assume it's as simple as checking for '/' in the path and using that instead of trying to match? Sorry if I'm misunderstanding, I'm just determined to help instead of waiting for someone else to do it, even if it takes me longer ;-)

**Comment by jmckitrick** [comment]
@mcandre @bbatsov Am I on the right track, here?

**Comment by scottjacobsen** [comment]
Checking for a leading `/` wouldn't work on windows. How about using `file-name-absolute-p` https://www.gnu.org/software/emacs/manual/html_node/elisp/Relative-File-Names.html
