### ISSUE TITLE
`projectile-switch-project-action` unsettable by .dir-locals.el

### ISSUE THREAD

**Issue by joelmccracken** [bbatsov/projectile#413]
Recently I tried to use `.dir-locals.el` to set `projectile-switch-project-action` to `magit-status`. However, the dir-locals in that project are not read or enabled until *after* a file/directory within that project has been opened.

I see a few ways of addressing this. The simplest way would be to open dired inside a project *before* invoking `projectile-switch-project-action`. However, a user might not want a dired of their project root.

Another way would be to manually invoke the dir-locals functionality. This seems a little tricky, because it seems as though it would require creating another buffer of some sort. We might be able to directly call the functions that apply dir-local variables, but since these are all buffer-locals, would they then apply to the minibuffer? Maybe a `with-temp-buffer` that has been CD'd into the project directory would be sufficient.

A third and much more drastic solution would be to implement a projectile-specific dir-locals equivalent. I almost don't want to do this, but my hunch is that we will keep running into places where dir-locals is strange/doesn't work.

**Comment by zhongweiy** [comment]
Hi, all, Any progress on this issue?

I also run into similar problem. I usually use `ansi-term` in emacs and just run `cd` in `ansi-term` to project. But `.dir-locals.el` doesn't evaluated until I open some file in this project.

**Comment by joelmccracken** [comment]
@bbatsov wdyt? would you accept something that re-implements dir-locals, specific to projectile? or would it make more sense to extend dir-locals, making the emacs dir-locals feature a first-class part of projectile?

I can clarify anything. At the moment, adding projectile-specific stuff to dir-locals seems easiest by far.

**Comment by joelmccracken** [comment]
Also relevant to this is #479 and #442.

**Comment by ericdanan** [comment]
The following solution works for me: in `projectile-switch-project-by-name`, simply replace

```
(funcall switch-project-action)
```

with

```
(with-temp-buffer
  (setq default-directory project-to-switch)
  (hack-dir-local-variables-non-file-buffer)
  (funcall switch-project-action))
```

I have tested that this behaves reliably even when switching project recursively, aborting the switch project action with <kbd>C-g</kbd>, or changing `default-directory` in `projectile-before-switch-project-hook`: it always loads the correct dir-locals and nevers leaves an internal temp buffer behind. I didn't notice that it makes switching project slower.

If some users may still prefer this not to be done for some reason that I don't think of, a solution could be to introduce a new custom variable, say `projectile-load-dir-locals-before-switch-project`, and replace the above with

```
(if projectile-load-dir-locals-before-switch-project
    (with-temp-buffer
      (setq default-directory project-to-switch)
      (hack-dir-local-variables-non-file-buffer)
      (funcall switch-project-action))
  (funcall switch-project-action))
```

I can make a PR if @bbatsov wants.

**Comment by joelmccracken** [comment]
I think this is a great solution, is pretty much what I was imagining.

Is there anywhere else projectile that this should exist? It might be worth
having a macro, something like "with-dir-locals" that does this.

**Comment by ketbra** [comment]
Thanks for this fix!  As a temporary fix I just overrode my switch project action using your technique.  Glorious!

```elisp
(defun ketbra/projectile-switch-project-action ()
  "Run projectile-find-file with dir-locals properly set."
  (with-temp-buffer
    (hack-dir-local-variables-non-file-buffer)
    (projectile-find-file)))

(setq projectile-switch-project-action #'ketbra/projectile-switch-project-action)

```
