### ISSUE TITLE
file-relative-name and expand-file-name calls in projectile-dir-files-external are very slow

### ISSUE THREAD

**Issue by sqs** [bbatsov/projectile#420]
I noticed that projectile-dir-files-external was very slow on one of my large repositories (6,100 files), but most of the time was not in the `projectile-get-repo-files` call:

```
projectile-global-mode-enable-in-buffers               16          1.307117903   0.0816948689
projectile-mode                                        6           1.306882017   0.2178136695
projectile-go                                          6           1.300657849   0.2167763081
projectile-current-project-files                       6           1.3000586669  0.2166764444
projectile-dir-files                                   6           1.291248086   0.2152080143
projectile-dir-files-external                          6           1.1220830910  0.1870138485
projectile-get-repo-files                              6           0.273677106   0.045612851
projectile-files-via-ext-command                       6           0.269172659   0.0448621098
projectile-remove-ignored                              6           0.164833454   0.0274722423
projectile-project-root                                156         0.0861857369  0.0005524726
```

It appears that relativizing the file paths returned from `projectile-get-repo-files` was taking 140msec per invocation (compared to 45msec for the `git ls-files ...` command).

Since the paths returned by `projectile-get-repo-files` are already relative, it is necessary to relativize the paths again? I think it's unnecessary for git, but I assume there are other cases where the file paths would not be relative. In that case, we could optimize this operation (by caching path prefix resolutions, etc.).

**Workaround:** This should work for people using git and probably other VCSes (that return relative paths). I changed the definition from [the previous definition of projectile-dir-files-external](https://github.com/bbatsov/projectile/blob/c8e93ba2d50f26e3ffd6f19681ca25592ca01be8/projectile.el#L696-L703) to: 

```lisp
(defun projectile-dir-files-external (root directory)
  "Get the files for ROOT under DIRECTORY using external tools."
  (let ((default-directory directory)
        (files-list nil))
    (setq files-list (projectile-get-repo-files))
    files-list))
```

**Comment by bbatsov** [comment]
I think @vspinu recently changed this. Reopen it if I'm mistaken.
