### ISSUE TITLE
Unable to ignore files ending with tilda (~)

### ISSUE THREAD

**Issue by rags** [bbatsov/projectile#425]
I have tried using all these in .projectile
-*_/\_.*~
-.*~
-*.*~
-*~
But the files ending with ~ just show up
I also tried adding to projectile-globally-ignored-files, but it doesnt help.

**Comment by bbatsov** [comment]
@it3ration Adding some filtering on top of the file lists received by an external command would counter much of the benefits of using the external command (as filtering many files in Emacs would be pretty slow). Ideally we should translate ignore patterns into some params we pass to the underlying tools, but this hasn't been implemented yet. 

Generally I just ignore everything I want to ignore with git and I just get the right list of files from git with no performance overhead.
