### ISSUE TITLE
Associating key-bindings and command with projects?

### ISSUE THREAD

**Issue by abingham** [bbatsov/projectile#442]
When I open a project I'd like to set up some keybindings which are specific to that project. What's the recommended way to do that? Should I be using .dir-locals.el to do this and, if so, how would you go about doing this?

**Comment by bbatsov** [comment]
I want us to switch to a more flexible configuration scheme (e.g. an Elisp file, that controls a lot more than ignores), but before we get there it'd be very painful to introduce something like this via configuration.

**Comment by jmjones5** [comment]
Has this had any further thought?
