### ISSUE TITLE
helm-projectile-find-other-file should work with nested extensions

### ISSUE THREAD

**Issue by vkz** [bbatsov/projectile#454]
There must be a way to make it work with multiple extensions not just the outer most. Unfortunately my elisp foo is so rudimental that it'd take me ages to figure out the fix. 

;; ;; This currently doesn't work because `projectile-get-other-files'
;; ;; uses (file-name-base current-file) which strips only the outer
;; ;; most extension
;; (add-to-list 'projectile-other-file-alist '("bemhtml" "bh.js"))
;; (add-to-list 'projectile-other-file-alist '("bh.js" "bemhtml"))

**Comment by sunesimonsen** [comment]
I would really like to see this implemented too. Thanks for the nice plugin by the way, it is extremely useful.

**Comment by tuhdo** [comment]
Now this feature is officially supported.

**Comment by sunesimonsen** [comment]
Thank you so much, this is extremely useful.
