### ISSUE TITLE
[Improvement] Change the behaviour of projectile-ibuffer

### ISSUE THREAD

**Issue by tuhdo** [bbatsov/projectile#478]
@bbatsov There's [a question on Emacs StackExchange](http://emacs.stackexchange.com/questions/2181/ibuffer-how-to-automatically-create-groups-per-project) with an interesting answer. I think the solution is more suitable with `projectile-ibuffer`, as currently the command is redundant with `projectile-switch-buffer`, and `ibuffer` is meant for managing a large number of buffers. Doing it the way the answer suggested makes `projectile-ibuffer` serves different purpose: to be a cross-project buffer manager. It gives an overview of all working projects and make it easily to work cross-projects. It can also replace `ibuffer-vc` due to how Projectile works.

**Comment by bbatsov** [comment]
I'd love to see this improved, but I don't have time to work on it myself. 

If anyone ever wraps what was started in #499 I'd be happy to pull this in.

**Comment by seagle0128** [comment]
I am using https://github.com/purcell/ibuffer-projectile , which is a a cross-project buffer manager.
