### ISSUE TITLE
Should be able to specify a name for projects

### ISSUE THREAD

**Issue by angrybacon** [bbatsov/projectile#479]
Recently went to Web development, here is my folder hierarchy:

```
.
├── documentation/
├── locale/
├── showcase/
├── sources/
├── toolbox/
└── readme.md
```

I've set up my project root at sources/ since this is where I want to work (I don't want other files to pollute the auto-completion when searching for a file).

With a set up like above, [`projectile-project-name`](https://github.com/bbatsov/projectile/blob/master/projectile.el#L685) returns `sources`, when _in that particular case_ it should returns parent's folder.

Most flexible way I can think of now is setting a string for the project name in `projectile-bookmarks.eld`.

Thanks : ]

**Comment by 501st-alpha1** [comment]
The `defadvice` works for me, but I agree that it would be more convenient if I could define names some other way, such as in the `.projectile` file.

**Comment by bbatsov** [comment]
I think we should handle this with a dir-local variable (it will be simple and effective).

**Comment by jaseemabid** [comment]
@bbatsov That would do. +1
