### ISSUE TITLE
[Improvement] Projectile + desktop-save

### ISSUE THREAD

**Issue by csantosb** [bbatsov/projectile#485]
Please, consider this as a possible future feature.

Coupling projectile to persp-mode is really useful. Now, it would be great to have support for desktop-save, which now includes frameset too. 

In this way, when one leaves a project (closes a persp) or when the user decides to, a new desktop file is created locally, storing the last project state including open buffers (desktop-save) and window layout (frameset). When the project is open back again, the desktop file is auto loaded.

Regards,

**Comment by fatlazycat** [comment]
+1

**Comment by TheoAndersen** [comment]
+1

**Comment by bbatsov** [comment]
I'll take a PR for this, but this is not something I have time to work on myself.
