### ISSUE TITLE
Symlinks under project-root lose project when visiting link files

### ISSUE THREAD

**Issue by scubacabra** [bbatsov/projectile#491]
Hi,

I have a directory that I use as the `~/myproj/` that has two children that are soft links to two folders that are dynamically mounted off of the root path
- `symlink1 -> /dynamic/mounted/folder1`
- `symlink2-> /dynamic/mounted/folder2`

I'm trying to do this so that I can generate tag files once and update them as I change different views, the same with the projectile cache.

Everything works if I start from `~/myproj/`, but after visiting a file and trying `projectile-find-file` or `projectile-find-other-file` I get the "You're not in a project".

This makes sense to me, as either of the mounted paths have no `.projectile` file anywhere before it hits `/`.

Is there a way to set `projectile-project-root` in the mounted folders to point back to the `~/myproj/` so that it will work as if the projectile project was somewhere on the dynamic mounted path?

**Comment by JasZhe** [comment]
Kind of an old thread, but just for anyone stumbling upon this like me, this also worked for me using `.dir-locals.el` in the project containing the symlink. My use case was just wanting to include some iCloud files with the rest of my org notes. 
i.e. 

`~/org` was where my regular notes were contained 
but I had some mobile notes on iCloud symlinked via  
```ln -s ~/org/iCloudOrg ~/Library/Mobile\ Documents/com~apple~CloudDocs/org```

The parentheses are slightly incorrect in the current version of emacs I'm using (28.2 with Doom) 

What I have in `~/org/.dir-locals.el` following the above example: 
```
((nil . ((eval . (progn
                 (defun file-symlink-p (FILENAME)
                    nil))))))
```
