### ISSUE TITLE
(wrong-type-argument hash-table-p nil) when running projectile-current-project-files

### ISSUE THREAD

**Issue by rpdillon** [bbatsov/projectile#496]
Debugged a bit.
Line 1193 of projectile.el:

``` elisp
(gethash (projectile-project-root) projectile-projects-cache))))
```

where, in my project, `projectile-projects-cache` is `nil` (and I have caching enabled).

`gethash` doesn't appear to accept `nil` for the hashtable, as is the default (line 353).

Emacs 24.4, Arch Linux, latest packages from Melpa (as of this morning).

Update:
`(setq projectile-projects-cache (make-hash-table))`
seems to solve the issue until restart, when it defaults back to `nil`.

**Comment by cjauvin** [comment]
I don't know much about the projectile internals, but I've been bit by this "problem": I was using helm-projectile and everything was working great, except that newly visited projects never got added to the list/cache (and no `.emacs.d/projectile-bookmarks.eld` was ever created). I caught the `hash-table-p` error, googled it, and stumbled here, so perhaps my experience could be useful to some: `(projectile-global-mode)` indeed solves this problem.

**Comment by cjauvin** [comment]
I don't know much about the projectile internals by I've been bit by this "problem": I was using helm-projectile and everything was working fine, except that newly visited projects never got added to the list/cache (and no `.emacs.d/projectile_bookmarks.eld` was ever created). I eventually caught the `hash-table-p` error, googled it and stumbled here. And indeed `(projectile-global-mode)` is the solution.
