### ISSUE TITLE
Local only projectile-find-file with SVN

### ISSUE THREAD

**Issue by codygman** [bbatsov/projectile#520]
My work svn server is inaccessible and projectile-find-file tries to contact the remote server, failing. How can I easily tell projectile to not try and find the file on the remote server and instead search locally?

I got around this by renaming my .svn directory and creating a .projectile file in that folder for now.

**Comment by falood** [comment]
I have the same problem and this config works for me.
```
(setq projectile-svn-command "find . -type f -not -iwholename '*.svn/*' -print0")
```

**Comment by bbatsov** [comment]
@falood's solution seems like the best option.

**Comment by tuxayo** [comment]
Is there any doc where this could fit? I was also bothered to have to wait more than 3 long seconds of network queries when doing projectile-find-file. And it was only by luck that I've found this.
