### ISSUE TITLE
helm-projectile-grep does not work

### ISSUE THREAD

**Issue by zxcvbn97** [bbatsov/projectile#537]
`helm-projectile-grep` does not show any search result. I am using Emacs 24.4 on OS X Yosemite, latest version of bbatsov/projectile and helm. Other grep and helm commands (such as helm-do-grep) run perfectly. Please help. Thanks

@tuhdo @bbatsov

**Comment by microamp** [comment]
@tuhdo,

I'm experiencing the same problem here. Using `grep` (also, doesn't work with `ack` either).

Versions installed (all latest, as far as I can tell):
- projectile: 20150108.957
- helm-projectile: 20150109.54
- grep: grep (BSD grep) 2.5.1-FreeBSD
- ack: ack 2.14

With `grep`, it works with the first 5, 6 letters, and then I get the following error message as reported earlier.

```
Error during redisplay: (eval (helm-show-candidate-number (car-safe helm-mode-line-string))) signaled (wrong-type-argument integer-or-marker-p nil) [3 times]
```

Not experiencing it on my Arch laptop. Only on OS X Yosemite.

**Comment by tuhdo** [comment]
@microamp Could you try it again? After this PR: https://github.com/bbatsov/projectile/pull/606, it should work with either GNU Grep or the built-in BSD grep of OS X. A demo screenshot is in there.

**Comment by microamp** [comment]
@tuhdo, 

I'm getting a different error now when I try ``helm-projectile-grep``,

```
Error during redisplay: (eval (helm-show-candidate-number (car-safe helm-mode-line-string))) signaled (wrong-type-argument integer-or-marker-p nil)
```

Versions:
* helm: 20150119.723
* helm-projectile: 20150117.1007
* projectile: 20150108.957

The version of ``grep`` is same as before (grep (BSD grep) 2.5.1-FreeBSD).

**Comment by tuhdo** [comment]
@microamp Could you try if stock `helm-ff-do-grep` work find? 

- First, run `helm-find-files`.
- Then, press `C-s` to start grep search in current directory.
- Type something.

**Comment by microamp** [comment]
@tuhdo,

It works fine when I do `C-x C-f` (`helm-find-files`), choose the current directory (i.e. `.`), then `C-s` with a keyword.

Odd, let me know if there's anything else that I can try out in the meantime.

**Comment by thegeorgeous** [comment]
@microamp, what worked for me was installing GNU grep as a replacement for BSD grep and then using       `exec-path-from-shell` to force Emacs to use my zsh path. I think ditching BSD grep is the best way to solve this issue

**Comment by kirk86** [comment]
This problem is still apparent in OSX with emacs 25.
Whenever I start emacs I see the following error in the messages buffer
```
Error during redisplay: (eval (format " Projectile[%s(%s)]" (projectile-project-name) (projectile-project-type))) signaled (error "You’re not in a project")
```
