### ISSUE TITLE
projectile-find-file and projectile-switch-to-buffer should match switch-buffer behavior

### ISSUE THREAD

**Issue by jgarvin** [bbatsov/projectile#555]
By default in emacs, if you C-x b and hit enter without pressing any other keys, emacs goes back to visiting the most recent buffer. You can do this repeatedly to conveniently toggle between two files. Projectile doesn't duplicate this behavior, if you don't press anything and you're already in the file that would be picked by default you just stay there.

I think projectile-switch-to-buffer matching switch-buffer would be good for consistency. I think projectile-find-file matching the behavior would be nice because if it did I could just get rid of my binding to switch-buffer and stop having to think about whether a file already has a buffer or not -- I could just always use projectile-find-file and trust it to create one if necessary. Which I could do now, except I'm reminded that the behavior is different everytime I try to use the toggle feature.

Edit: should note I've only tried with ido, no idea if this is the behavior with helm.

**Comment by samertm** [comment]
I believe this can be closed @bbatsov
