### ISSUE TITLE
projectile-switch-project shouldn't require being in a project

### ISSUE THREAD

**Issue by jgarvin** [bbatsov/projectile#556]
If I'm not in a particular project, and I want to be, it seems reasonable I should be able to press C-c p p to get a list of projects to switch to as documented. But it only works when you're already visiting a buffer that's part of a project.

**Comment by samertm** [comment]
@bbatsov This bug doesn't exist in the latest version of projectile, so this issue can be closed.
@jgarvin If you still hit this bug on the latest version of projectile, please reopen this issue.
