### ISSUE TITLE
alien mode indexing not working on Mac OS X

### ISSUE THREAD

**Issue by smolyn** [bbatsov/projectile#579]
When using alien indexing mode in Mac OS X, nothing happens.
Mac OS X 10.9.5, Emacs 24.4, projectile-20141208.716

When I switch to native, it works fine (albeit slowly).

Is this spawning a shell?  I'm using zsh w/ oh-my-zsh... could it be confusing some piped output parsing?

How can I help debug this?

**Comment by smolyn** [comment]
I had a .projectile and I called projectile-invalidate-cache. Still the same problem.  The only thing that worked was the commenting.  For whatever reason it thinks bar is in a git repository, and it calls projectile-git-command, instead of projectile-generic-command.

**Comment by tuhdo** [comment]
What's your Git version?

**Comment by smolyn** [comment]
➜  ~  git --version
git version 2.2.1

**Comment by smolyn** [comment]
Ok, so the problem looks like it's in projectile-project-vcs.
Perhaps this is a misunderstanding of how I should think it should work, but in my case I want the .projectile to override any .git in a parent directory.  However, projectile-project-vcs does a projectile-locate-dominating-file, which doesn't take into account the .projectile file.  

Adding 
((projectile-locate-dominating-file project-root ".projectile") 'none)
before
((projectile-locate-dominating-file project-root ".git") 'git)

makes everything work.

**Comment by halbtuerke** [comment]
@smolyn Thanks for this fix. I also ran into this problem today.

It would be nice if this feature could be incorporated into projectile.

**Comment by tuhdo** [comment]
@smolyn You should make a PR.

**Comment by smolyn** [comment]
Done. 
https://github.com/bbatsov/projectile/pull/636
