### ISSUE TITLE
idea for ignoring file extensions in alien mode

### ISSUE THREAD

**Issue by it3ration** [bbatsov/projectile#580]
I have a `.projectile` file in my project root with the following ignores:

https://gist.github.com/it3ration/ab8620156e16c6c72121

Directories are ignored, but none of the file extensions are.  From reading the lisp code it appears that file extensions are only ignored if you enable native indexing.  This isn't fast enough on large projects.  It seems like you could ignore file extensions using the native `find` command in the following way:

`find . -not -name "*.exe" -not -name "*.dll"`

In this way you could still use the `find` command for speed, but apply extension ignores in your `.projectile` file.  Is this possible?

Thanks so much!

-Kevin

**Comment by tolchz** [comment]
Try this:

         (setq projectile-globally-ignored-file-extensions '(".o" ".d" ".pyc"))
         (defun projectile-remove-ignored (files)
           "Remove ignored files and folders from FILES.
    Operates on filenames relative to the project root."
           (let ((ignored (append (projectile-ignored-files-rel)
                                  (projectile-ignored-directories-rel))))
             (-remove (lambda (file)
                        (or (--any-p (s-starts-with-p it file) ignored)
                            (--any-p (s-ends-with-p it file) projectile-globally-ignored-file-extensions)))
                      files)))

**Comment by it3ration** [comment]
Hey bbatsov,

Are .projectile + .gitignore files not processed in alien mode?  I'm still having issues, really hoping it will be possible eventually to process ignores when using alien mode as I have a project with about 20k files.

If not, should I fork things and try to set that up?

Best,
-Kevin
