### ISSUE TITLE
Command projectile-replace cannot find next file

### ISSUE THREAD

**Issue by angrybakon** [bbatsov/projectile#583]
Tried to replace a string within a project with `C-c p r` and got:

```text
next-file: Opening input file: no such file or directory, /path/to/project/bin/bash: ag: command not found
```

Let me know if I can provide anything more to help debug : )

**Comment by bbatsov** [comment]
Seems that `ag` is not in your exec-path.

**Comment by angrybakon** [comment]
Through moving onto another computer (and possibly Projectile updates), it got further and I now get these messages:

delete-backward-char: Text is read-only [2 times]
next-file: Opening input file: no such file or directory, /Users/angrybacon/Workspace/labadens/labadens/
+

**Comment by samertm** [comment]
@angrybakon I couldn't reproduce your issue with the latest version of projectile. Are you still seeing this issue?

**Comment by angrybakon** [comment]
@samertm I can't reproduce this particular issue, `projectile-replace` seems to work just fine. I am now using [railwaycat's last build](https://github.com/railwaycat/homebrew-emacsmacport/releases).

Thanks : )
