### ISSUE TITLE
projectile doesn't seem to work with perspective

### ISSUE THREAD

**Issue by vkz** [bbatsov/projectile#586]
Hi. Trying this with everything freshly installed from MELPA: projectile, helm-projectile, perspective, persp-projectile. Encountered the following two issues:

* `projectile-persp-switch-project` does the switch but fails to create a perspective. Nothing suspicious in Messages
* switch to a fresh perspective, then `helm-projectile-switch-project` to some project. Select files in `helm-projectile` and bulk open them. Buffers will show up in `helm-projectile` but not in `helm-mini` i.e. they aren't added to perspective

@bbatsov I understand you don't use perspective so I'm taking the liberty of tagging people who appear on earlier persp-related patches. Hope it's ok. @bastianbeischer @danielwuz @dawuwgen 

I'm not an active user of perspective but was checking it out and trying to marry it with `helm-projectile-switch-project` when noticed the above. Speaking of switching projects. I couldn't for the love of me figure out how `helm-projectile-switch-project` is defined. It is added to the keymap in **helm-projectile.el** alright but where's the definition? :-)

**Comment by rsenna** [comment]
I was having the same problem, but with ido instead of helm.

After taking a look at the elisp code, I found out that implementation of `projectile-persp-switch-project` was not according its documentation string: for instance, `persp-switch` should be called either if the perspective does NOT exist, OR if the perspective does exist but it is not current.

I made a fix, which seems to work as expected, but since I've never made a pull request through github before, I'll send the new version of `projectile-persp-switch-project` below. If this is not acceptable (for any reason) please let me know.

```lisp
(defun projectile-persp-switch-project (project-to-switch)
  "Switch to a project or perspective we have visited before.
If the perspective of corresponding project does not exist, this
function will call `persp-switch' to create one and switch to
that before `projectile-switch-project' invokes
`projectile-switch-project-action'.

Otherwise, this function calls `persp-switch' to switch to an
existing perspective of the project unless we're already in that
perspective in which case `projectile-switch-project' is called."
  (interactive (list (projectile-completing-read
                      "Switch to project: "
                      (projectile-relevant-known-projects))))
  (let* ((name (file-name-nondirectory (directory-file-name project-to-switch)))
         (persp (gethash name perspectives-hash))
         (is-curr (and persp (equal persp persp-curr))))
    (when (or (not persp) (not is-curr))
      (persp-switch name))
    (when (or (not persp) is-curr)
      (projectile-switch-project-by-name project-to-switch))))
```

**Comment by arichiardi** [comment]
I was having problems too, came here, pasted in @rsenna's code and everything was working.
If nobody can pull it in I will do it. Tnx @rsenna !

**Comment by favadi** [comment]
The PR is merged, is it fixed?

**Comment by samertm** [comment]
@bbatsov Since the PR addresses this issue directly, I assume this can be closed

**Comment by arichiardi** [comment]
Works here.
