### ISSUE TITLE
.projectile shouldn't add itself to the project cache

### ISSUE THREAD

**Issue by ahyatt** [bbatsov/projectile#593]
For very large repositories, I use .projectile to first just define the directories to include.  However, merely adding .projectile will attempt to add it to the cache, which then attempts to find all the files, which is an excessively slow operation for very large projects.

So, .projectile needs to be treated specially here, and ignored.

**Comment by ahyatt** [comment]
Yes, well using find is reasonable.  But it isn't reasonable to do so before I can even edit the .projectile file so as to make "find" usable, though, which is what this bug is about. 

As far as the number of files in the project, I actually don't have that information.  Let's just say it's large enough that you definitely wouldn't want to use any sort of recursive file operation on it.

**Comment by tuhdo** [comment]
@ahyatt did it fix your problem? The latest commit should fix it.

> Yes, well using find is reasonable. But it isn't reasonable to do so before I can even edit the .projectile file so as to make "find" usable, though, which is what this bug is about.

The issue is, the content you put in `.projectile` has no effect on `find` or any external command used to retrieve the file list. Projectile only uses `.projectile` after finishing the external command.

**Comment by ahyatt** [comment]
@tuhdo, thanks, I just tested it out, and indeed creating the .projectile file didn't start off a long find operation.  Everything was fast and nice.  Thanks, @tuhdo and @bbatsov!
