### ISSUE TITLE
Consider removing 'build' from projectile-globally-ignored-directories

### ISSUE THREAD

**Issue by Wilfred** [bbatsov/projectile#604]
I was caught by surprise when I couldn't find some files with `projectile-find-file`. It turned out that my files were in `build/`, which is explicitly ignored by `projectile-globally-ignored-directories`.

Given that this directory isn't in my .gitignore, I'd prefer projectile to still list files within it. So, I suggest that either `build` is removed from `projectile-globally-ignored-directories`, or `projectile-globally-ignored-directories` isn't used when projectile is in a folder managed by VCS.

Does that sound reasonable, or should I just customize `projectile-globally-ignored-directories` locally?

**Comment by bbatsov** [comment]
Yeah, guess it'd be best if this variable was nil by default.

**Comment by bbatsov** [comment]
Scratch that - not nil, but only containing VCS & project related dirs.

**Comment by Wilfred** [comment]
Thank you! :)
