### ISSUE TITLE
Option to whitelist files?

### ISSUE THREAD

**Issue by mkleehammer** [bbatsov/projectile#605]
When I'm working on a project, there are a small number of extensions I'm really interested in.  An option to just use those would be easier to maintain and should speed up indexing.

In my example there are various binary files like exe, dll, and pdf which are not useful.  Using a global blacklist would work for these.  But I also have a lot of 3rd party EDI-type files with all kinds of extensions.

Not a huge deal - just a nice-to-have.

Thanks for the great project.

**Comment by tuhdo** [comment]
You can customize `projectile-globally-ignored-files` to ignore files with extension you don't want projectile to include. For example, add `*.pdf` and you will never see pdf files again.

**Comment by chadhs** [comment]
@mkleehammer @tuhdo see my example here:
https://github.com/bbatsov/projectile/issues/148#issuecomment-257592878
