### ISSUE TITLE
Old minibuffer input appears in helm completion system.

### ISSUE THREAD

**Issue by proofit404** [bbatsov/projectile#607]
Hello. Here is my projectile config:
```
(projectile-global-mode)
(setq projectile-completion-system 'helm)
```
I press `C-c p p`, type some string, press `RET`, match some file name with random input for example `tnh th`, press `RET`. Then I press `C-c p f` and see `tnh th` (previous input) as first completion candidate. I press `C-g` and then `C-c p f` second time. `tnh th` line disappears from candidates.

**Comment by tuhdo** [comment]
Use the proper [helm-projectile](http://tuhdo.github.io/helm-projectile.html) version, with more features (as you can see in the link). Just add

```elisp
(helm-projectile-on)`
```

and you will be able to use proper Helm Projectile commands with actual action menu.

**Comment by proofit404** [comment]
I don't need `helm-projectile`. Personally I don't like its fuzzy matching and aditional resources. I just want projectile use `helm` as its completion system without this glitch.

**Comment by tuhdo** [comment]
You can disable fuzzy matching with:

```elisp
(setq helm-projectile-fuzzy-match nil)
```

before loading `helm-projectile`. Otherwise, this bug persists. For the same input it does not happen using Ido. Probably because Projectile uses `helm-comp-read` directly rather than using `helm` and create a source for it.

**Comment by proofit404** [comment]
Seems like its indead `helm-comp-read` behaviour. Maybe @thierryvolpiatto can help.

**Comment by thierryvolpiatto** [comment]
Malyshev Artem <notifications@github.com> writes:

> Seems like its indead helm-comp-read behaviour. Maybe @thierryvolpiatto can help.

If I have a link to the issue...

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by proofit404** [comment]
Hmm, but I can't reproduce this without projectile. I try following code:
```lisp
(setq prompt "A: ")

(setq choices '("This" "buffer" "is" "for" "notes" "you" "don't" "want" "to" "save," "and" "for" "Lisp" "evaluation"))

(helm-comp-read prompt choices
                :must-match 'confirm)
```

**Comment by tuhdo** [comment]
@thierryvolpiatto @proofit404 I can reproduce the issue now, using the same example above, except for one thing:

```elisp
(setq prompt "A: ")

(setq choices '("This" "buffer" "is" "for" "notes" "you" "don't" "want" "to" "save," "and" "for" "Lisp" "evaluation"))

(helm-comp-read prompt choices
                :candidates-in-buffer t
                :must-match 'confirm)
```

Add `:candidates-in-buffer t` makes the old minibuffer input appear in the candidate list.

**Comment by proofit404** [comment]
@thierryvolpiatto Is that behavior right?

**Comment by thierryvolpiatto** [comment]
Tu Do <notifications@github.com> writes:

> @thierryvolpiatto @proofit404 I can reproduce the issue now, using the
> same example above, except for one thing:

Thanks, great report, I think I know what is happening, will try to look
into this ASAP.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by thierryvolpiatto** [comment]
Should be fixed now.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by proofit404** [comment]
I'll test after melpa build.

**Comment by proofit404** [comment]
Yes, this help. Thanks!
