### ISSUE TITLE
helm-projectile project-level tag search

### ISSUE THREAD

**Issue by lawremi** [bbatsov/projectile#610]
Would be nice to have an action for helm-source-projectile-projects to search tags, including both etags and gtags if helm-gtags is available. Or if there is an easy way for me to add this through customization, please let me know. Couldn't find one, but I'm an elisp noob.

**Comment by tuhdo** [comment]
Well, if you have `helm-gtags` and generate the tags at the root directory, it automatically searches the tags starting from project root. So, there's no need for integration with `helm-projectile`.

If you use `etags`, there's already a built-in command: `helm-etags-select`. Just load the TAGS file into Emacs and `helm-etags-select` automatically uses it.

**Comment by lawremi** [comment]
Here is the use case: I want to find a symbol in a project that is not the current one. I can use helm-projectile to find the project, and then I want a shortcut for doing the helm-gtags search on it. The quickest way I've found so far is to open the project in dired and then run the tags search. But that leaves a dired buffer behind. Perhaps someone knows of a more clever, existing shortcut.

**Comment by lawremi** [comment]
Just to restate this, I think we need a "Find tag definition" acion on `helm-source-projectile-projects`. I have tried to implement one that calls `projectile-find-tag`. I think this is a relatively simple task, but I can't figure it out. The main obstacle now is that it is thowing an error about running helm from within helm. Here is my current implementation of the action:

```
(defun helm-projectile-find-tags-action (project)
  "Find tag definitions `helm-projectile-source-projects'."
  (interactive)
  (let* ((default-directory project))
    (run-hooks 'projectile-switch-project-hook)
      (helm-quit-and-execute-action 'projectile-find-tag)))
```

Presumably one would also want to ensure that `ggtags-mode` is active, as well. Any help is appreciated, thanks!

**Comment by bbatsov** [comment]
Move this ticket to https://github.com/bbatsov/helm-projectile if you're still interested in it.
