### ISSUE TITLE
Ignoring directories when helm-projectile-grep

### ISSUE THREAD

**Issue by vkz** [bbatsov/projectile#628]
`helm-projectile-grep` behaviour unfortunately differs from `projectile-grep` in that it recursively searches in the directories that are explicitly ignored in **.projectile**. One possible solution to force ignore directories when grepping [had been discussed](https://github.com/bbatsov/projectile/issues/184#issuecomment-62940053). I submit to you that since `projectile-grep` already respects per-project ignores the need to effectively add directories to `grep-find-ignored-directories` which is not project-specific but rather global is somewhat disconcerting albeit a reasonable solution when grep is invoked from `helm-find-files` which is project agnostic. Not a bug but rather a missing feature here, I think. *Not being surprised* by our tools is a powerful thing. When I invoke `projectile-...` commands my mind is in the project frame of mind else I'd be invoking non-project specific commands.

**Comment by aguynamedben** [comment]
+1 to this, I think. I can't seem to get get helm-projectile-ack to respect my project's .projectile file.

**Comment by angrybakon** [comment]
Same for `helm-projectile-ag`.

**Comment by bbatsov** [comment]
Submit this ticket to the helm-projectile project https://github.com/bbatsov/helm-projectile

**Comment by haroldcarr** [comment]
search that respects ignored dirs/files:

1. install `ack` (An alternative to grep.  I install via homebrew.)

2. put `--ignore-case` in your `~.ackrc` file (assuming you want to ignore case)

3. bind `helm-projectile-ack` to a key.  I do this in my emacs init via:

```
(use-package helm
  ...
  :bind (...
         ("C-c p s a" . helm-projectile-ack)
        )
  ...
)
```

4. create a `.projectile` file.  E.g.,

```
-.dot
-.jcs
-.svg
-.txt
```

use

    C-c p s a     ;; search that respects .projectile ignore

or

    C-c s p g     ;; search everything
