### ISSUE TITLE
projectile-find-file-in-directory seems broken

### ISSUE THREAD

**Issue by vkz** [bbatsov/projectile#629]
Here's the contents of my `emacs.candidate` project and directory with `themes` subdirectory:
![emacs_candidate](https://cloud.githubusercontent.com/assets/917220/5999792/8f209f52-aae6-11e4-959e-b661d8ab2d1c.png)

Here're the candidates I get from `projectile-find-file-in-directory` when choosing themes directory (same for any other directory):
![_minibuf-1_](https://cloud.githubusercontent.com/assets/917220/5999814/d73cde54-aae6-11e4-8b66-61ade8cc36a5.png)

I don't actually know what the command intended behaviour is, but it's unlikely to be that. I'm using `helm` for completions but switching to `ido` doesn't make a difference. I'm using a fork of 
```
origin (https://github.com/bbatsov/projectile.git):
          origin/HEAD -> master
7335b48   origin/gh-pages
74afdbb   origin/master
```
which has a couple of my local commits but those are only for **perspective** support and don't touch anything else.

**Comment by tuhdo** [comment]
What's the problem here? `projectile-find-file-in-directory` is similar to `projectile-find-file`, but it first asks you for a directory and then list all files in that directory and sub-directories.

**Comment by vkz** [comment]
@tuhdo have another at both pictures. Do you see any of the candidate files (2nd pic) inside **themes/** directory (bottom entry of the 1st pic)? Yet `projectile-find-file-in-directory` insists they are there. In fact it simply puts all projectile-files inside whatever directory you choose

**Comment by tuhdo** [comment]
I thought that those are in **themes/** directory as well. But it's better to have a precise description with pictures to support than just pictures alone. It works for me in Linux and Windows. Maybe you should delete `.projectile` file, invalidate the cache and try again to see if that's the root cause, so we can investigate from there.

**Comment by vkz** [comment]
trashed **.projectile**, invalidated cache - didn't help. `projectile-find-file-in-directory` recursively expands all paths in your project and puts them inside the directory you choose, just like in the 2nd pic. Have you tried **master** branch? Essentially that's what I'm running

**Comment by bbatsov** [comment]
Might be related to #633.

**Comment by tuhdo** [comment]
Hmm after updating to latest Projectile, this does happen. Probably related to the issue @bbatsov  suggested.
