### ISSUE TITLE
(projectile-global-mode) not activating projectile

### ISSUE THREAD

**Issue by codygman** [bbatsov/projectile#631]
This is what I have in my custom.el file (called by init.el).
```eshell
(require 'projectile)
(projectile-global-mode)
(setq projectile-enable-caching t)
(global-set-key (kbd "C-c p .") 'helm-projectile-find-file-dwim)
```

I tried opening a projectile project, didn't see the usual projectile indicator in the status bar, then did C-h m and don't see projectile in the list of enabled minor modes.

**Comment by bbatsov** [comment]
Try using `(projectile-global-mode +1)`.
