### ISSUE TITLE
Change compilation command via dir locals

### ISSUE THREAD

**Issue by lunaryorn** [bbatsov/projectile#640]
How can I change the command used by `projectile-compile` via directory variables?  There doesn't seem to be a `projectile-compilation-command` variable or something like that.

**Comment by bbatsov** [comment]
You have to override the variable for your project type. If the project type is something projectile doesn't recognize overriding the `projectile-make-compile-cmd` should do (although it might make sense to use another variable for such project types).

**Comment by lunaryorn** [comment]
How do I find out the project type that projectile assumes?

**Comment by bbatsov** [comment]
You can try the command `projectile-project-info` that I just added. :-)

**Comment by lunaryorn** [comment]
:) Thanks!
