### ISSUE TITLE
projectile-replace crashes on .projectile marked directory (spurious newline)

### ISSUE THREAD

**Issue by Mekk** [bbatsov/projectile#641]
I elpa-updated projectile to 20150201.1134. Since then, projectile-replace stopped to work on repositories marked with .projectile file (in mercurial repositories it still works) - it properly prompts for term and replacement, then immediately fails.

Here is the backtrace (note spurious newline on the end of directory name). The text "nie ma takiego pliku ani katalogu" is "no such file or directory" in my locale, there is empty .projectile in /home/marcink/GSS/wspolne/makeutil

```
Debugger entered--Lisp error: (file-error "Opening input file" "nie ma takiego pliku ani katalogu" "/home/marcink/GSS/wspolne/makeutil/
+")
  insert-file-contents("/home/marcink/GSS/wspolne/makeutil/\n+" nil)
  next-file((list "/home/marcink/GSS/wspolne/makeutil/\n+") t)
  tags-loop-continue((list "/home/marcink/GSS/wspolne/makeutil/\n+"))
  tags-query-replace("CMDLIST" "CMD_LIST" nil (list "/home/marcink/GSS/wspolne/makeutil/\n+"))
  projectile-replace(nil)
  call-interactively(projectile-replace nil nil)
```

**Comment by bbatsov** [comment]
Likely related to #633.
