### ISSUE TITLE
Mechanically create test files

### ISSUE THREAD

**Issue by expez** [bbatsov/projectile#642]
Often there are strong conventions in the community on the name and location of test files.  It would be nice if `projectile-toggle-between-implementation-and-test` created test files in the event they are missing.

I wrote some code for doing this in clojure projects [here](https://github.com/clojure-emacs/clj-refactor.el/issues/113). 

To guard against mavericks, not following the conventional project structure, the functionality should be toggled with `projectile-create-missing-test-files` or some such setting.

**Comment by arichiardi** [comment]
:+1:

**Comment by arichiardi** [comment]
@expez @bbatsov 

I have created the following, works quite well here on 24.3.1 and combined with arichiardi/projectile@fb02c9eb32eae984bf21402a3cd5aa64b482a240 could be a real improvement. For example, I am using ```midje``` and the below code correctly generates ```t_``` tests in my test folder (note that I have not handled other cases then @expez's code in the linked issue above)
I have two problem to handle before a PR as I am not a proper ```elisper```:
- How to set options as the above ```projectile-create-missing-test-files```.
- How to handle the fact that ```cljr--add-ns-if-blank-clj-file``` might be missing.

```co
    (defun projectile--testify-impl-name (impl-file-name)
      (let* ((project-type (projectile-project-type))
             (test-prefix (funcall projectile-test-prefix-function project-type))
             (test-suffix (funcall projectile-test-suffix-function project-type)))
        (cond
         (test-prefix (concat test-prefix impl-file-name))
         (test-suffix (concat impl-file-name test-suffix))
         (t (error "Project type not supported!")))))
    
    (defun projectile-create-test-file-for (impl-file)
      (let* ((test-file (projectile--testify-impl-name (file-name-nondirectory impl-file)))
             (test-dir (replace-regexp-in-string "src/" "test/" (file-name-directory impl-file))))
        (unless (file-exists-p (expand-file-name test-file test-dir))
          (progn (unless (file-exists-p test-dir)
                   (make-directory test-dir :create-parents))
                 (find-file-other-window test-file)
                 ;; (cljr--add-ns-if-blank-clj-file)
                 ;; (save-buffer)
                 ))))
    
    (defadvice projectile-toggle-between-implementation-and-test
      (around expez--create-missing-test-file)
      "Creates a test file if not found in the test/ folder of the project."
      (message "here")
      (let ((file-name (buffer-file-name)))
        (if (projectile-test-file-p file-name)
            ad-do-it
          (progn (save-window-excursion (projectile-create-test-file-for file-name))
                 ad-do-it))))
    
    (ad-activate 'projectile-toggle-between-implementation-and-test)```

**Comment by arichiardi** [comment]
There is a little bug I am going to fix it, the questions are still valid of course :+1:

**Comment by expez** [comment]
> How to set options as the above `projectile-create-missing-test-files`

You can create customizations points with [defcustom](http://www.gnu.org/software/emacs/manual/html_node/eintr/defcustom.html)

> How to handle the fact that cljr--add-ns-if-blank-clj-file might be missing.

You can use [fboundb](http://www.gnu.org/software/emacs/manual/html_node/elisp/Function-Cells.html) to check if a function is bound.

I'll also add that one generally does not advice one's own functions.  The use of advice in my first implementation is why I opened a ticket instead of a pull-request.  I just never got around to doing it 'properly'  because the advice hack has served me quite well :)

**Comment by arichiardi** [comment]
Added ```when``` above...if @bbatsov gives me the nod, I can prepare a PR, add ```defcustom``` and of course embed everything in ```projectile-toggle-between-implementation-and-test```

**Comment by arichiardi** [comment]
I also noticed that ```cljr--add-ns-if-blank-clj-file``` adds a ```require``` to himself, which is not what we want at all :smile:

**Comment by arichiardi** [comment]
From what I see in clj-refactor.el@7f4555556a7d9420a6063e75bf6707f85f623237, they added a hook (but still, need some help from some elisper):
```(add-hook 'find-file-hook 'cljr--add-ns-if-blank-clj-file)```

**Comment by expez** [comment]
Yeah, I think you can safely leave the line with `cljr--add-ns-if-blank-clj-file` out because the `find-file-hook` takes care of it.

**Comment by arichiardi** [comment]
Testing now right about how...

**Comment by arichiardi** [comment]
Yep working, final version modified above.

**Comment by arichiardi** [comment]
A problem with custom suffix/prefix is that the following does not work anymore in ```clj-refactor``` as it just chops ```-test```. It looks like our functionality stays in between ```projectile``` and ```clj-refactor```.

```elisp
(defun cljr--add-test-use-declarations ()
  (save-excursion
    (let ((ns (clojure-find-ns)))
      (message ns)
      (cljr--insert-in-ns ":require")
      (insert "[" (s-chop-suffix "-test" ns) " :refer :all]")
      (cljr--insert-in-ns ":require")
      (insert "[" (cond
                   ((cljr--project-depends-on-p "midje") "midje.sweet")
                   ((cljr--project-depends-on-p "expectations") "expectations")
                   (t "clojure.test"))
              " :refer :all]"))))
```

**Comment by expez** [comment]
What's the problem?  We should chop `-test`.  We want to refer the ns under test, which doesn't have a `-test` suffix.

**Comment by expez** [comment]
Is the problem that we can't generate an ns declaration for arbitrary suffixes?  That's not an issue `projectile` should concern itself with.

If you want this functionality you can open an issue over at `clj-refactor`, but I can tell you right away that you'll have to write the code that closes that issue yourself :)

**Comment by arichiardi** [comment]
This is what happens now, the wrong namespace is imported:
![wrong-import](https://cloud.githubusercontent.com/assets/1724788/7939254/591c2bb6-094a-11e5-9b86-eb555391c02c.gif)

Yes I think there is no clean solution about that.  As you can see [here](https://github.com/arichiardi/projectile/commit/f2a1167390949df3b91eac299d1069aa87a8dc7f#diff-e350afa47840c07f4dbf92840e4f8cfaR1585) ```projectile``` actually carries prefix/suffix with each project type.
That is why I am able to generate ```t_impl.clj``` files when I am using midje instead of ```impl-test.clj```.

The only idea that comes to mind is when ```cljr--add-test-use-declarations``` in ```clj-refactor``` is called, take the dir of same namespace and for each ```.clj``` in there try to find the one that is substring of the test ```clj```. That is stop when ```t_impl``` is contains ```impl```. Then use that ```impl``` in the require...that now it is correct.

**Comment by expez** [comment]
@arichiardi why not just name your files with the `-test` suffix even though you're using midje?

Anyway, this problem should be fixed in `clj-refactor` (if t all) and shouldn't prevent us from closing the issue at hand :)

**Comment by arichiardi** [comment]
@expez Hi hi of course I could do it and completely abandon the issue, but then where is the fun :smile: I think I might embark in the ```clj-refactor``` issue, but this one should still be open at least until we won't solve the situation in [758](https://github.com/bbatsov/projectile/pull/758)...

**Comment by expez** [comment]
This is fixed now and can be closed, right @arichiardi ?

**Comment by arichiardi** [comment]
Yes, fixed both PRs merged.

**Comment by perkss** [comment]
@arichiardi Is this fixed in clj-refactor or proejctile? If so what is the command to run this?
