### ISSUE TITLE
helm-projectile-on error

### ISSUE THREAD

**Issue by wolfand11** [bbatsov/projectile#643]
can't find helm-projectile-on   my helm-projectile version is MELPA Stable v0.11.0

**Comment by tuhdo** [comment]
That versions is more than a year ago and is very outdated. You won't even find other Helm Projectile commands.

**Comment by wolfand11** [comment]
thank you for your replay
but the latest stable version is v0.11.0    where i can find the latest stable version

**Comment by tuhdo** [comment]
You should use MELPA, not MELPA stable if you want latest Helm Projectile.  The instructions for using MELPA is [here](http://melpa.org/#/getting-started).
