### ISSUE TITLE
grep not great in git project

### ISSUE THREAD

**Issue by fommil** [bbatsov/projectile#645]
I have just started using projectile and it is great for finding files!

However, the projectile-grep was not as good as I was hoping... it echoed the git command (very long) and found lots of binary files that I'm pretty sure were in the gitignore file.

Couldn't you make use of git-grep when in a git repo?

I use this command for grepping in git repos, and it would be awesome if I could replace it with a more general projectile-grep

```elisp
(defun git-grep (search)
  ;; https://www.ogre.com/node/447
  "Git grep the entire current repository for SEARCH."
  (interactive (list (completing-read
                      "Search for: " nil nil nil (current-word))))
  (grep-find (concat "git --no-pager grep -P -n \""
                     search
                     "\" `git rev-parse --show-toplevel`"))
  (other-window 1))
```

**Comment by bbatsov** [comment]
There's an option to use `vc-git-grep` even now - `projectile-use-git-grep`.

**Comment by fommil** [comment]
aaah! Thankyou. I actually needed to install `vc-git` for this to appear. I don't think you do a `require` anywhere. Shall I leave open for that? I also believe this should be the default... much better than find!

**Comment by bbatsov** [comment]
Guess we should add an autoload for it (I assumed it was autoloaded by default).
