### ISSUE TITLE
Obey core.excludesfile

### ISSUE THREAD

**Issue by prettynatty** [bbatsov/projectile#646]
In some projects it is not good to add some ide-specific ignores to the project `.gitignore`. Instead they are placed to the global gitignore `~/.gitignore` for example and the global gitignore is set in `~/.gitconfig` as `core.excludesfile = /path/to/global/.gitignore`.

**Comment by mikegolod** [comment]
having same problem, definetely want projectile to honor global vcs ignore patterns

**Comment by bbatsov** [comment]
Not sure what needs to be done - projectile actually shells out the to the VC commands, so this should be working out the box. And this is too complex to do for the `native` indexing method, so I'm not interesting in pursuing it there.
