### ISSUE TITLE
Open eshell Open magit failed

### ISSUE THREAD

**Issue by wolfand11** [bbatsov/projectile#649]
after helm-projectile-switch-project, M-e or M-g failed

**Comment by tuhdo** [comment]
Could you post the error messages?

**Comment by wolfand11** [comment]
there isn't any error messages. in switch-project buffer, i pressed TAB,but there is only one item, it's "[f1] Sole action (Identity)"

**Comment by wolfand11** [comment]
projectile version is 20150209.542˙
helm-projectile version is 20150207.237

**Comment by tuhdo** [comment]
You are not using Helm Projectile, You are using stock Projectile with Helm completion interface. To use Helm Projectile, put this code after you enable Projectile:

```elisp
;; (setq helm-projectile-fuzzy-match nil)
(require 'helm-projectile)
(helm-projectile-on)
```

It is documented in [this section](https://github.com/bbatsov/projectile#helm-integration).

**Comment by wolfand11** [comment]
oh! it's ok , thanks
