### ISSUE TITLE
projectile-replace no longer works

### ISSUE THREAD

**Issue by nloyola** [bbatsov/projectile#650]
I'm using 8335791 (with date 2015-02-09) and projectile-replace no longer works. Here is the backtrace:

```
Debugger entered--Lisp error: (void-function s-present\?)
  s-present\?("\n+")
  -filter(s-present\? ("\n+"))
  projectile-files-from-cmd("ag --literal --nocolor --noheading -- getApiAnnotation" "/home/nelson/src/cbsr/scala/bbweb/")
  projectile-files-with-string("getApiAnnotation" "/home/nelson/src/cbsr/scala/bbweb/")
  projectile-replace(nil)
  call-interactively(projectile-replace nil nil)
  command-execute(projectile-replace)
```

It seems that commit 5e46193ed2c34028c7ee1ff65c5d2a16149131fe may have broken it by removing this line:

```lisp
(require 's)
```

Thanks for all the hard work on this great package.

**Comment by dgutov** [comment]
FWIW, even after adding the require, it doesn't work for me anymore:

```
Debugger entered--Lisp error: (file-error "Opening input file" "No such file or directory" "/home/gutov/project/name/
+")
  insert-file-contents("/home/gutov/project/name/\n+" nil)
  next-file((list "/home/gutov/project/name/\n+") t)
  tags-loop-continue((list "/home/gutov/project/name/\n+"))
  tags-query-replace("all_ips" "all_ids" nil (list "/home/gutov/project/name/\n+"))
  projectile-replace(nil)
```

**Comment by bbatsov** [comment]
I think someone broke replace about a month ago, but I've been crazy busy lately and I had no time to debug the problem.

**Comment by dgutov** [comment]
That someone was @tarsius, in the same commit. `s-split` and `split-string` have arguments in different order.

Wait for a pull request from me, soon.

**Comment by nloyola** [comment]
Thanks for fixing this.
