### ISSUE TITLE
Use last project or default instead of "You're not in a project"

### ISSUE THREAD

**Issue by ahonnecke** [bbatsov/projectile#664]
Occasionally I will be in a scratch buffer or something and attempt to run projectile-find-file or some such and get "You're not in a project".  It seems more useful to have projectile use the most recent project, or have a projectile-default-project that would get used when I run projectile not in a project and global mode is off.

**Comment by bbatsov** [comment]
That's definitely debatable. I think it such situations one should simply run `projectile-switch-project`.

**Comment by ahonnecke** [comment]
I agree.  Thank you!  That addresses projectile-find-file for me.
