### ISSUE TITLE
Ability to whitelist files that would otherwise be ignored.

### ISSUE THREAD

**Issue by tmccombs** [bbatsov/projectile#665]
I would like a way to specify to a file (or directory) should be included if it would otherwise be ignored. For example if a file is in .gitignore or blacklisted by a pattern in .projectile, I would like to a way to add back in more specific examples.

For example, suppose my .gitignore ignores a generated source file, but I would still like to be able to easily navigate and search it with projectile. As far as I know there is no easy solution to get this behaviour. It is possible to use a custom non-vcs project, but then I have to keep my .projectile and .gitignore files in sync (with the exception of that one file). 

Another, perhaps more common example would be a configuration file containing secrets and keys which should not be kept on git.

**Comment by chadhs** [comment]
@tmccombs 
see my example here, hope it helps:
https://github.com/bbatsov/projectile/issues/148#issuecomment-257592878
