### ISSUE TITLE
persp-projectile with persp-mode

### ISSUE THREAD

**Issue by tmccombs** [bbatsov/projectile#666]
[persp-mode](https://github.com/Bad-ptr/persp-mode.el) is compatible with perspective, but currently persp-projectile doesn't work with it, because it require 'perspective isntead of 'persp-mode. 

Please change so that persp-projectile will work for both projectile and persp-mode

**Comment by bbatsov** [comment]
I don't use perspective and don't really understand what you mean. If you know what has to be changed - PRs are welcome!
