### ISSUE TITLE
projectile-find-tag very slow

### ISSUE THREAD

**Issue by fommil** [bbatsov/projectile#668]
Even just hacking in my `.emacs.d` the `TAGS` file is about 8MB, which is fine, and `find-tags` is pretty instant.

However, when using `projectile-find-tags` there is a couple second delay every time. It looks like it's rebuilding the table every time, is that correct? Is there no better way to do this?

**Comment by fommil** [comment]
btw, in elisp code it would also be amazing to drop down to find-function-at-point if the TAGS table returns negative.

**Comment by fommil** [comment]
```elisp
(defun elisp-find-tag-or-find-func ()
  ;;; Could be a lot smarter for non-function symbols (variables, faces, packages, etc)
  "Use `find-tag' to find symbol at point, falling back to `find-func' features."
  (interactive)
  (let* ((fun (function-called-at-point)))
    (if (find-function-noselect fun 'no-c-sources)
        (find-function-do-it fun nil 'switch-to-buffer)
      (find-tag (symbol-name (symbol-at-point))))))
```

**Comment by fommil** [comment]
In response to my own comment, I cooked this up for elisp

```elisp
(defun elisp-find-tag-or-find-func ()
  ;;; Could be a lot smarter for non-function symbols (variables, faces, packages, etc)
  "Use `find-tag' to find symbol at point, falling back to `find-func' features."
  (interactive)
  (let* ((fun (function-called-at-point)))
    (if (find-function-noselect fun 'no-c-sources)
        (find-function-do-it fun nil 'switch-to-buffer)
      (find-tag (symbol-name (symbol-at-point))))))
```

**Comment by jpkotta** [comment]
If you're using etags, it's probably rebuilding the completion table (https://github.com/bbatsov/projectile/blob/master/projectile.el#L1796).  I commented out those lines and it sped up a lot.  I don't know why it needs to do that; maybe it could be cached for each project.  BTW, I'm using ido for completion.

**Comment by fommil** [comment]
I'm using exuberant ctags and it's also rebuilding the completion table every time... which is very wasteful. I almost prefer emacs' basic `find-tag`.

**Comment by colegleason** [comment]
This is really hurting. I have a large TAGS file and it sucks to wait for it to build every time. Any good way to speed it up?

**Comment by fommil** [comment]
I replace it with built in find-tag

**Comment by fommil** [comment]
I actually found out that my `ctags` was adding a bunch of junk to the `TAGS` file from build report files, so I added a filter and now my `TAGS` file is manageable and there is no noticeable bad performance anymore.
