### ISSUE TITLE
TAB should tab complete filenames, not insert a tab literal

### ISSUE THREAD

**Issue by mcandre** [bbatsov/projectile#670]
When I press TAB while performing a projectile search, I want Projectile to finish typing the rest of the selected result.

Currently, pressing TAB in this context inserts a literal TAB key in the search term, which messes up the results.

**Comment by bbatsov** [comment]
I have no idea what you're talking about. Please, add some repro steps.

**Comment by tuhdo** [comment]
The problem is, why do you need to press <kbd>TAB</kbd> in the first place? As you type, projectile automatically narrows down for you, regardless of completion interface (ido or helm or grizzl). You don't need to narrow down to a single result to select it.

**Comment by mcandre** [comment]
Some more context:

As a former dired user, I often press TAB instinctively to autocomplete filenames. I want projectile to discard/ignore TAB key presses, because they mess up Projectile search results.

Steps to reproduce:

```
$ touch README.md
$ emacs <dir>
Ctrl+p
read[TAB]
```

Expected:

Projectile either sets the current search term to the full 'README.md' filename, or simply drops the TAB key altogether.

Observed:

Projectile tries to add a literal `\t` tab character to the search term, which then fails to match on any files, making the search results become empty.

**Comment by tuhdo** [comment]
You can simply stop hitting TAB key and it won't happen. Using Ido or Helm, it basically presses TAB for you automatically. And TAB is a needed key in Helm Projectile to open action menu.

**Comment by tuhdo** [comment]
Anyway, when in `projectile-find-file`, TAB should give a list of filename in a separate buffer even if you use Ido mode.
