### ISSUE TITLE
Any new release ?

### ISSUE THREAD

**Issue by nlamirault** [bbatsov/projectile#671]
The latest version is on May 27, 2014.

**Comment by bbatsov** [comment]
Yeah, yeah. Have been planning to do a new release for at least half an year. Hopefully this will happen soon...

**Comment by nlamirault** [comment]
Great :)

**Comment by zilvinasu** [comment]
The latest package version date in MELPA is 20150301.213, but it lacks fixes form helm-projectile project buffers and etc, any ideas when are you planning to release fixed version?

**Comment by bbatsov** [comment]
0.12 is out!

**Comment by nlamirault** [comment]
Great !
