### ISSUE TITLE
helm-projectile-find-file-dwim doesn't work in the 1 candidate case

### ISSUE THREAD

**Issue by rootzlevel** [bbatsov/projectile#672]
When using `helm-projectile-find-file-dwim` such that the filename at point has only one possible match, the following happens:

The matched file is opened in one buffer, but helm still prompts me for a filename with an empty \*helm projectile\* buffer open. Since that buffer is empty, I can't select any canditate and C-g jumps back to the file I started `helm-projectile-find-file-dwim` in.

**Comment by tuhdo** [comment]
Thanks for your report. It should be fixed in the above commit.
