### ISSUE TITLE
Indexing files (native) with a .projectile + a few patterns is extremely slow

### ISSUE THREAD

**Issue by sandos** [bbatsov/projectile#675]
I tried with this .projectile file:

> -vx55-num01
> -vx67-cpu02
> -vx63-cpu01
> -670Debug
> -650Debug
> -bcout.cg
> -$tf
> -Debug

It even has no wildcards, but it is still so slow, with native indexing, in windows that I never got to see it finish. I am not able to debug this further, sadly. It looks, in procmon, like its reindexing the same folder over and over, likely trying to expand file patterns in the same folder which is crazy. It should not need to expand the pattern for every filename.

I tried slightly smaller example with the same configuration as above. The folder structure was:

> .projectile
> build.proj
> downloadAllTFS.bat
> tfstatus
> typetest/.tfignore
> typetest/DMR typetest SW.doc
> typetest/wintms/ABOUT.DFM

Logs from process monitor for this sample directory: https://gist.github.com/sandos/f19bca2d1d8ff0180665

**Comment by tuhdo** [comment]
You should use alien. It will use external program to provide the file list. Much much faster.

**Comment by sandos** [comment]
I actually tried that, with no luck. Did not investigate much though.
