### ISSUE TITLE
Feature request: "C-d" should open dired when in projectile-find-file

### ISSUE THREAD

**Issue by samertm** [bbatsov/projectile#676]
...similar to how ido does it. I have projectile-switch-project-action set to the following because I prefer to be in the dired of the root directory of a project 70% of the time:

```
(setq projectile-switch-project-action (lambda () (dired (projectile-project-root))))
```

but the other 30% of the time I want to select a file directly from projectile-find-file. It would be nice if projectile-find-file supported the "C-d" dired backdoor that ido has, so hitting "C-d" would instantly take you to the dired view, and I could get rid of my custom binding.

ido-mode accomplishes this by binding "C-d" to ido-magic-delete-char

```
(define-key map "\C-d" 'ido-magic-delete-char)
```

https://github.com/emacs-mirror/emacs/blob/master/lisp/ido.el#L1008
And ido-magic-delete-char deletes a char if given an arg, or if the point isn't at the end of the line. Otherwise, if ido-cur-item is a file or directory (I believe this is only the case when "ido-find-file" is active, and this check is here to prevent this branch from running during other ido actions), dired is entered.

```
(defun ido-magic-delete-char (arg)
  "Delete following char in user input or perform magic action.
If at end of user input, perform magic actions:
C-x C-f ... C-d enter `dired' on current directory."
  (interactive "P")
  (cond
   ((or arg (not (eobp)))
    (delete-char (min (prefix-numeric-value arg)
                      (- (point-max) (point)))))
   (ido-context-switch-command
    nil)
   ((memq ido-cur-item '(file dir))
    (ido-enter-dired))))
```

https://github.com/emacs-mirror/emacs/blob/master/lisp/ido.el#L2693
Would projectile-mode accept a pull request with this feature added? If so, what's the best place to start?

**Comment by tuhdo** [comment]
If you don't mind Helm, have a look at [helm projectile](http://tuhdo.github.io/helm-projectile.html). It has everything you want and more.

**Comment by samertm** [comment]
Helm is impressive, and I want to check it out at some point, tho I can't say how soon. I don't know if it makes sense for projectile proper to take the same approach as helm projectile (not sure how helm-build-in-buffer-source works), but I can look into it.

**Comment by bbatsov** [comment]
Yeah, I'd take a PR implementing this. I'm guessing you should in `projectile-completing-read` and see what we're missing there.

**Comment by joonoro** [comment]
Just a note: C-j seems to do that you want, though it would still be nice if someone fixed this because that would enable the other file-oriented Ido keybinds like C-k in to work as well. You could then use projectile-find-file to delete files anywhere in your project directory.

**Comment by Silex** [comment]
+1 good idea, I always had the exact same idea but never thought of simply requesting it :-)
