### ISSUE TITLE
How do i ignore paths with "node_modules" not being the first directory from project root?

### ISSUE THREAD

**Issue by TheoAndersen** [bbatsov/projectile#680]
```
(add-to-list 'projectile-globally-ignored-directories "node_modules")
```

makes projectile ignore any paths from root beginning with the folder "node_modules" but how do i ignore any path with the "node_modules" folder not begin the first from root?

**Comment by pronobis** [comment]
Same question here regarding '.git' folder which appears in projectile if the project has git submodules.

**Comment by markdaws** [comment]
Same question, I want to be able to ignore folders with specific names at any level in the directory structure when indexing, I tried various regexes in .projetile but couldn't make it work. So given:

a/foo
b/c/foo
c/foo
d/xyz/pqr/foo

I want to not index any files in any folder called foo.

**Comment by TheoAndersen** [comment]
you need to ad a dash-char in front of paths you want to exclude in .projectile.

My question was with the global ignore setup, but i have achieved what i wanted (sort of) by adding the following line to my .projectile

    -/spikes/*/node_modules

**Comment by cjauvin** [comment]
If anyone has an idea how to solve (or a workaround) the problem at the origin of this thread, I'd be interested to know, as this issue is annoying (i.e. I'd like to be able to globally ignore directories, even if they are not found at the root of a project).

**Comment by tutysara** [comment]
Got the same issue, wanted to ignore node_modules, added```-/*/node_modules``` in .projectile, ran ```M-x projectile-invalidate-cache``` then ran ```projectile-find-files``` I can still see the files from node_modules.

**Comment by ambihelical** [comment]
This seems similar to #733, #1119 and #1041
