### ISSUE TITLE
helm-source-projectile-buffer broken after helm updates

### ISSUE THREAD

**Issue by bsuh** [bbatsov/projectile#682]
https://github.com/emacs-helm/helm/commit/6613f82aa3e56ee9adc62abc4537dbd5b4335f9d removes `helm-buffers-list--match-fn`

**Comment by PythonNut** [comment]
I can confirm and reproduce this.

**Comment by bbatsov** [comment]
Fixed.

**Comment by camdez** [comment]
Quick fix for users running the version with the issue (e.g. MELPA Stable users—last release was May 27, 2014) who are seeing this error:

```
Helm issued errors: helm-match-from-candidates in source `Projectile Buffers': void-function (helm-buffer-match-major-mode)
```

Add the following to your `.emacs` file:

```elisp
(defalias 'helm-buffer-match-major-mode 'helm-buffers-match-function)
```

If that doesn't work, you may be running an older version of Helm with a similar problem. See https://github.com/bbatsov/projectile/issues/358
