### ISSUE TITLE
Feature request: Delete non-existing projects

### ISSUE THREAD

**Issue by pronobis** [bbatsov/projectile#686]
It would be great if projectile realized that a project folder was removed and deleted it from known projects cache. The projects list currently gets cluttered with old projects.

**Comment by Silex** [comment]
<kbd>M-x projectile-cleanup-known-projects</kbd>

**Comment by pronobis** [comment]
Awesome! Couldn't find it. Thanks!

**Comment by Silex** [comment]
You're welcome :)
