### ISSUE TITLE
No completion for rake/gulp/etc tasks

### ISSUE THREAD

**Issue by chillum** [bbatsov/projectile#694]
Hi,

I'm running 20150327 from MELPA. I've tried to install Projectile a month ago and I remember, there was a completion for rake/gulp/etc. tasks. That is: I run `projectile-compile-project`, enter `rake` and press tab -- and I get a completable list of tasks. For some reason, this feature has gone.

How should I discover, where's the problem: on my side (I'm using the same system and Emacs) or in Projectile?

**Comment by bbatsov** [comment]
> I've tried to install Projectile a month ago and I remember, there was a completion for rake/gulp/etc. tasks.

Pretty sure such feature never existed. :-)

**Comment by chillum** [comment]
Hm. Then it seems, we definitely want it. :-) It's a really nice and handy feature.

Rinari does this in Emacs+Rake world. For Rake and Gulp the case is in parsing `rake -T`/`gulp -T` output and caching it until gulpfule/rakefile has changed.

**Comment by bbatsov** [comment]
I don't really want to deal with this, as compile/test commands are usually something static/well-known and it seems this will be a lot of work (which has to be done for every tool) for pretty no benefit. If you want to implement this, however, it's fine by me.
