### ISSUE TITLE
If ignored directory doesn't have proper permissions, projectile-find-file displays "find: 'foldername': permission denied"

### ISSUE THREAD

**Issue by hhnr** [bbatsov/projectile#695]
Project structure : 
-----------------------
.projectile
-- folder_1 [doesn't have permission to access directory]
-- folder_2
    --- test1.c
    --- test2.c
    --- test3.c

.projectile:
-------------
-/folder_1

launch emacs and invoke projectile-find-file
![screenshot from 2015-03-28 19 36 47](https://cloud.githubusercontent.com/assets/3027568/6881350/f7d3072c-d581-11e4-9f5e-864290979a4a.png)

**Comment by dibenede** [comment]
The merged fix breaks projectile on OS X. It doesn't look like the included find has a -readable option:

    $ find . -readable
    find: -readable: unknown primary or operator

**Comment by bbatsov** [comment]
Guess we should see what's the equivalent command there and make the default conditional.

**Comment by dibenede** [comment]
I just found this: http://stackoverflow.com/questions/762348/how-can-i-exclude-all-permission-denied-messages-from-find

**Comment by glucas** [comment]
On Windows, the test for `-readable` support isn't accurate because `find /dev/null` will always fail regardless of what options you specify. You could use `find NUL -readable` on Windows?

**Comment by bbatsov** [comment]
Probably it'd be simpler to replace this with a `pcase` for the different operating systems.

**Comment by dibenede** [comment]
One concern I had with that approach was someone installing an unexpected find version. For example, homebrew on OS X appears to allow installing GNU find as "find" rather than "gfind". Is it ok to ignore this corner case?

Does elisp OS detection have any other corner cases I should be aware of? (Sorry, brand new to elisp in general).

Also, I'm not sure what the underlying problem is in the pull request thread with respect to CentOS.

**Comment by kaushalmodi** [comment]
See if this solution ( https://github.com/bbatsov/projectile/pull/811#issuecomment-124223339 ) works for you; works for me on RHEL 5.10.

**Comment by dibenede** [comment]
Older versions of findutils, like on CentOS 5.10, seem to lack -readable. Is OS detection limited to `system-type`? (http://stackoverflow.com/questions/1817257/how-to-determine-operating-system-in-elisp) .

**Comment by kaushalmodi** [comment]
Note that my above referenced code needs to be enabled before you require projectile. If you use use-package, that goes in :init.

**Comment by kaushalmodi** [comment]
Sorry, am on phone, I meant eval'ed, not enabled.

**Comment by dibenede** [comment]
@glucas: Can you please describe your setup a bit? I just threw Cygwin on a Windows 7 VM and it has /dev/null. Also, find NUL (or even nul) -readable results in "no such file or directory".

It looks like Windows has a built in find command, but the semantics are completely different: http://www.howtogeek.com/206097/how-to-use-find-from-the-windows-command-prompt/

**Comment by glucas** [comment]
Interesting -- perhaps Cygwin has special handling for /dev/null, because in the Windows cmd shell the null device is NUL. 

I'm on Windows 8.1, using GNU find from [ezwinports](http://sourceforge.net/projects/ezwinports/files/):

    C:\> find --version
    GNU find version 4.2.30

    C:\> find /dev/null
    find: /dev: No such file or directory

    C:\> find nul
    nul

    C:\> dir > nul
    C:\>

**Comment by dibenede** [comment]
Please give this a try. It's based off of @kaushalmodi's comments.

I have also deferred the find detection until it's needed, so hopefully it doesn't impact emacs startup time.

**Comment by dibenede** [comment]
Updated the commit to included the latest upstream changes. An amend was involved, so you will probably have to force any local copies.
