### ISSUE TITLE
Projectile has issues opening files on remote system

### ISSUE THREAD

**Issue by bgvianyc** [bbatsov/projectile#698]
After installing tern, projectile stopped being able to open remote file directly. Even as of yesterday I could connect to a project on remote file system using projectile, now I have to first connect using TRAMP only then can I open using projectile.

The error message I get is: 
Tramp: Waiting for prompts from remote shell...failed
Tramp: Opening connection for XXX@XXXX.com using ssh...failed
byte-code: Selecting deleted buffer

What could be the issue, how can this be debugged?

**Comment by Silex** [comment]
See #523
