### ISSUE TITLE
Improve ctags support

### ISSUE THREAD

**Issue by marcinant** [bbatsov/projectile#718]
1. 'ctags' command on Ubuntu is 'ctags-exuberant'. As Ubuntu and Debian based distributions are most popular distros then default value for ctags-function could be 'ctags-exuberant'.
2. This command should be called asynchronously. There is no reason to lock Emacs and wait for rebuild.

**Comment by bbatsov** [comment]
> 'ctags' command on Ubuntu is 'ctags-exuberant'. As Ubuntu and Debian based distributions are most popular distros then default value for ctags-function could be 'ctags-exuberant'.

We can simply check and see which binary is available.

PRs welcome.

**Comment by tejasbubane** [comment]
I have both `ctags` and `ctags-exuberant` on my Ubuntu. `ctags` does not accept `-e` option and throws an error.

**Comment by marcinant** [comment]
There is pretty good package called: (ctags-update)[https://github.com/jixiuf/helm-etags-plus].
It has function to rebuild tags asynchronously. It's a bit annoying because user has to revisit TAGS file and confirm it after each change (I'm going to fork and provide code to revisit tags automatically on change). However IMHO it's the way to go.

Projectile could use 'update-tags' function from 'ctags-update' package to rebuild TAGS file.

**Comment by ReneFroger** [comment]
I agree with this one. I get bothered with the message

    Tags file a:/foobar/TAGS has changed, read new contents? (y or n) n

every time after calling `(projectile-regenate-tags)`, which is quite cumbersome.
