### ISSUE TITLE
helm-projectile-grep not work?

### ISSUE THREAD

**Issue by ambjlon** [bbatsov/projectile#720]
I installed helm-projectile through elap. When I use helm-projectile-grep, it seems doesn't work, I just get a hint "Helm Projectile Grep (C-c ? Help)" , as shown in the figure below:
![ww20150420004243](https://cloud.githubusercontent.com/assets/4489822/7220344/31b0e362-e6f6-11e4-87bc-08fb7bfd3e58.png)
something should be 'greped', but nothing.
Then I attempt to use helm-do-grep, it works fine.

**Comment by tuhdo** [comment]
Are you won Windows? If so, use Cygwin `grep`. If you are on OS X, use GNU Grep, not the one that comes with OS X.

**Comment by ambjlon** [comment]
I work in Linux, the grep version:
grep (GNU grep) 2.5.1.

p.s. when the file path is too long, helm-do-grep also don't work.

**Comment by bbatsov** [comment]
Is this still an issue? No one else seems to be experiencing it.

**Comment by ambjlon** [comment]
Unintentionally, I updated grep. Then it worked well. So, it seems my grep's version is low.
Thank you for your participation!
