### ISSUE TITLE
Remove current buffer from helm-projectile-switch-project

### ISSUE THREAD

**Issue by dsdshcym** [bbatsov/projectile#721]
Every time I use ```helm-projectile-switch-project```, I find that the current buffer is in the ```Project buffers``` section.

This behavior is really odd most of the time. Cause if I use ```helm-projectile-switch-project``` instead of ```helm-projectile-find-file```, the current buffer is clearly not the file of the Project I want.

And I also find that the current buffer's path is changed to the chosen project path.

Like this:
![screen shot 2015-04-20 at 14 43 44](https://cloud.githubusercontent.com/assets/4723751/7224987/d70d80e8-e76b-11e4-94be-6d6789216546.png)

But the original path of ```ics.org``` is:
![screen shot 2015-04-20 at 14 46 15](https://cloud.githubusercontent.com/assets/4723751/7225001/14880cfe-e76c-11e4-836f-a0ce4514ba6a.png)

(Original posted in syl20bnr/spacemacs#1275)

**Comment by bbatsov** [comment]
//cc @tuhdo

**Comment by tuhdo** [comment]
Actually, `helm-projectile-switch-project` reuses (and thus, display) the same buffer list as `projectile-switch-project`. So, if you want to exclude it, simply `cdr` the current list.

**Comment by dsdshcym** [comment]
@tuhdo I still don't understand.

I looked into ```projectile```'s source file. And I didn't find which list I should ```cdr```.

**Comment by tuhdo** [comment]
@dsdshcym You can replace [this line](https://github.com/bbatsov/projectile/blob/master/helm-projectile.el#L513) with this line:

```elisp
(candidates :initform (cdr helm-buffers-list-cache))
```

**Comment by dsdshcym** [comment]
@tuhdo Thank you!
I'm wondering why this is not default behavior. Are there some other concerns?

**Comment by tuhdo** [comment]
Probably no one notices it. You should make a PR.

**Comment by hlissner** [comment]
This fix seemed to break helm-projectile-switch-to-buffer for me for some reason, causing it to yield an empty buffer list without any error.

Curiously, by doing the cdr earlier, on [line 500](https://github.com/bbatsov/projectile/blob/master/helm-projectile.el#L500) instead like so:

`(setq helm-buffers-list-cache (cdr (projectile-project-buffer-names)))`

The problem magically disappears (with the current buffer omitted from the list).

Anyone else getting this?

**Comment by tuhdo** [comment]
@hlissner yea I fixed it with this PR: https://github.com/bbatsov/projectile/pull/742

**Comment by hlissner** [comment]
Awesome, thanks!
