### ISSUE TITLE
helm-projectile shouldn't override helm-buffer-max-length

### ISSUE THREAD

**Issue by mikecrowe** [bbatsov/projectile#723]
I have helm-buffer-max-length set to nil so that filenames are not truncated in helm-buffer-list etc.

Unfortunately helm-projectile's helm-source-projectile-buffer class contains:

                       (unless helm-buffer-max-length
                         (setq helm-buffer-max-length (car result)))

which overrides my setting, not only for helm-projectile, but for everything else as well.

I don't believe that helm-projectile should be affecting this global setting.

**Comment by bbatsov** [comment]
Probably you're right. @tuhdo Why did you decide to do so?

**Comment by tuhdo** [comment]
@bbatsov the original code was always like that.

**Comment by bbatsov** [comment]
Guess we can drop this.

**Comment by tuhdo** [comment]
If we drop it, it produces an error `apply: Wrong type argument: number-or-marker-p, nil`. We can wrap it around a let. However, I don't think it is related to Projectile, since if I execte `helm-mini`, the value is reset to `31` in my case.

**Comment by tuhdo** [comment]
Actually, [helm-source-buffers does it](https://github.com/emacs-helm/helm/blob/master/helm-buffers.el#L181) as well. Helm Projectile only follows the example. You can reproduce this bug by simply executing `helm-mini` or `helm-buffers-list`.

**Comment by mikecrowe** [comment]
It seems that the fix for https://github.com/emacs-helm/helm/issues/810 has fixed this problem for me too despite the offending code (as quoted in my original report) still being present in helm-projectile. I suspect this means that the code in helm-projectile is never executing and wasn't causing the problem in the first place. I still believe that the code is incorrect given the documented behaviour of helm-buffer-max-length being nil though.

Thanks to everyone who narrowed this down.
