### ISSUE TITLE
"Save results in buffer" action missing for `helm-projectile-ag`

### ISSUE THREAD

**Issue by jonathanj** [bbatsov/projectile#724]
It would be useful if it were possible to save the results of `helm-projectile-ag` into a buffer, as one can do with `helm-projectile-grep`. Enabling next/previous results, open, open in other window, etc. functionality in a side window.

**Comment by tuhdo** [comment]
Please close it. I opened in here: https://github.com/syohex/emacs-helm-ag/issues/102
