### ISSUE TITLE
No known projects for SBT/Scala

### ISSUE THREAD

**Issue by adelbertc** [bbatsov/projectile#725]
Installed `projectile` and have the following config:

```
(setq projectile-enable-caching nil)
(require 'projectile)
(projectile-global-mode +1)
```

I'm currently working in an SBT multi-project that looks similar to:

```
umbrellaProject/
    .git
    scala/
        project1/
            build.sbt
        project2/
            build.sbt
```

When I'm in the `scala` directory and open a random file in it (just to get `projectile` mode enabled, and I do see it in the status bar) and hit `C-c p p` I get "There are no known projects." However, when I do `C-c p f` I do get what appears to be a valid/filtered list of files.

I haven't changed any of the settings via `customize-group`, but some relevant bits:

* Projectile Project Root Files shows `build.sbt` in the list
* Projectile Project Root Files Bottom Up shows `.git` in the list

At one point I tried adding `build.sbt` to the "Projectile Project Root Files Bottom Up" list and then visited some directories with `build.sbt` in them. Then when I went back up to the root directory (`scala/`) and hit `C-c p p` it would list those directories I've visited.

The behavior I'm hoping to achieve is to be able to just be in the root project directory (`scala/`), hit `C-c p p` and have it traverse the directory tree figuring out subprojects (`project1/` and `project2/`) and let me jump to them.

**Comment by bbatsov** [comment]
> When I'm in the scala directory and open a random file in it (just to get projectile mode enabled, and I do see it in the status bar) and hit C-c p p I get "There are no known projects."

You should see all the files in umbrella project at this point. What OS are you using?

**Comment by adelbertc** [comment]
I can see all files when I do `'projectile-find-file` but I also expected to see all the different projects in `'projectile-switch-project` - they only appear if I had visited that project prior. Perhaps that is simply by design though.. no worries :-)

**Comment by bbatsov** [comment]
Yep, this is by design. Projectile doesn't search for nested projects, only for the project (the root directory) of the file you're currently visiting.

**Comment by adelbertc** [comment]
What is the best way to be able to treat the top-level project (the one rooted at `.git`) as well as the sub-projects (rooted at `build.sbt`) as separate projects so I can switch between them?
