### ISSUE TITLE
projectile-rename-in-project doesn't respect ignored dirs

### ISSUE THREAD

**Issue by expez** [bbatsov/projectile#732]
When working on a javascript app at work I noticed that `bower_components` and `npm_modules` were being searched.  I've listed these directories in `projectile-globally-ignored-directories` so I expected them to be excluded.

If it makes a difference this is on a windows machine.

**Comment by joonro** [comment]
I have the same problem - projectile keeps including `.git` even though it is in `projectile-globally-ignored-directories`. I use Emacs in Windows as well.
