### ISSUE TITLE
[bug] helm-projectile outside of project no longer "displays list of projects"

### ISSUE THREAD

**Issue by jinnovation** [bbatsov/projectile#743]
Documented behavior for `helm-projectile` is such that, if called outside of a project, it "displays a list of known projects to jump [to]."

This was the behavior up until about roughly a week ago, and is no longer the case; calling outside of a project now simply prints to minibuffer "You're not in a project"

**Comment by tuhdo** [comment]
It should be callable outside of a project. Otherwise, this is a bug.

**Comment by jinnovation** [comment]
Agreed.

I can look into performing a bisection later today, time permitting.

**Comment by tuhdo** [comment]
I'm making the PR to fix this bug.

**Comment by tuhdo** [comment]
The fix is there. Please wait for @bbatsov to merge it.
