### ISSUE TITLE
Mention 'projectile-add-known-project' in README.md

### ISSUE THREAD

**Issue by kevinushey** [bbatsov/projectile#746]
Motivation: I wanted `projectile-switch-project` to 'know' projects that I had not yet even visited / opened / used in Emacs. It turns out `projectile-add-known-project` is what I was looking for, but it is not mentioned prominently anywhere in any documentation.

I feel like I must be crazy or something since Googling 'projectile add new project' doesn't turn up anything relevant so either I'm doing something odd or completely missing out in something else re: how projectile adds / caches new projects -- I have `projectile-enable-caching` set to `t` but even then new projects don't seem to get 'automagically' added by `projectile` even as I visit files / folders within.

Is `projectile-add-known-project` worth documenting in `README.md`? Or, is there an alternative flow (e.g. a hook) that could automagically add new projects as files are visited?

**Comment by shackra** [comment]
Actually, I don't see my projects since few new updates of projectile... is weird because I used to see them...

**Comment by arichiardi** [comment]
:+1: Same here, the ```project``` display sometimes is confusing, especially with submodules. I did not know about ```projectile-add-known-project```, thanks.

**Comment by shackra** [comment]
Weird, I don't have the command `projectile-add-known-project`

**Comment by bbatsov** [comment]
It's not a command, it's just an internal function. Every time you visit a project file, projectile will remember the project that contains it. No need for manual user intervention.
