### ISSUE TITLE
README should list currently understood project types

### ISSUE THREAD

**Issue by FranklinChen** [bbatsov/projectile#747]
I was curious about which projects are implicitly supported out of the box and the README lists somel, but this information is buried and incomplete ("lein, maven..."). I had to look at the source code `projectile.el` to find the complete list of information of what is currently supported. Maybe this list should be generated into a section in the README for ease of reference for those new to Projectile.

**Comment by bbatsov** [comment]
Maybe there should be some command about this, although we should also make registering new project types easier. The current approach doesn't really scale very well.

**Comment by stardiviner** [comment]
+1

**Comment by marcinant** [comment]
> Maybe there should be some command about this, although we should also make registering new project types easier. The current approach doesn't really scale very well. 

It's a great idea. While you don't accept some patches providing support for additional project types, then maybe `projectile-project-type` should be customizable with list of functions editable by user and fallback to generic?

**Comment by bbatsov** [comment]
See https://github.com/bbatsov/projectile/commit/e8b7b54449c645c764c928d7d1cfa29113230f05
