### ISSUE TITLE
Searching for program: is a directory

### ISSUE THREAD

**Issue by alissonperez** [bbatsov/projectile#749]
People,

I'm using version **24.5.1 (x86_64-unknown-linux-gnu, GTK+ Version 2.24.23)** and when I try to use `C-c p f` I receive the message bellow:

**Searching for program: is a directory**.

I've not found anything on internet. Someone has some ideia what is happening?

Let me know if you need more information about my environment.

Thanks in advance.

**Comment by tuhdo** [comment]
What is your shell and which VCS are you using? If you use Projectile in a VCS project, you need to make sure Emacs see the path to the binary of such VCS.

**Comment by alissonperez** [comment]
I'm using zsh with oh-my-zsh. The VCS is git.

**Comment by alissonperez** [comment]
@tuhdo I set `projectile-indexing-method` as `'native` and `C-c p f` now works, before its value was `'alien`.

<kbd>M</kbd>-<kbd>:</kbd> `(setq projectile-indexing-method 'native)`

**Comment by bbatsov** [comment]
Seems that `git` isn't on Emac's `load-path` or something like this.

**Comment by kolen** [comment]
The same occured for me, the cause was that I have ``shell-file-name`` set to ``nil``, so ``shell-command-to-string`` not worked at all. According to Emacs documentation, it can be set by setting ``SHELL`` environment variable:

> The above commands use the shell specified by the variable shell-file-name. Its default value is determined by the SHELL environment variable when Emacs is started. If the file name is relative, Emacs searches the directories listed in exec-path (see Shell).

After setting ``shell-file-name``, ``C-C p f`` works.

**Comment by alissonperez** [comment]
Thanks a lot @kolen. Your solution worked for me!!
