### ISSUE TITLE
[Feature request] Option to avoid remote projects in projectile-known-projects list

### ISSUE THREAD

**Issue by marcinant** [bbatsov/projectile#753]
Projectile adds remote projects to `projectile-bookmarks.eld` file.
Then if remote system is unreachable emacs hangs on boot.

Is this possible to add switch to avoid adding these projects to bookmarks?

**Comment by teaforthecat** [comment]
I second this. I'd like to not see remote projects at all. Is there a way to do this already?

**Comment by bbatsov** [comment]
That has been in projectile for a while - see `projectile-ignored-project-function`.

**Comment by teaforthecat** [comment]
I don't see `projectile-ignored-project-function`, but I see `projectile-ignored-projects`.  I tried this shot in the dark with no luck:  `(setq projectile-ignored-projects (list "/ssh:" "/sudo:"))`

**Comment by bbatsov** [comment]
It doesn't work like this. Read the description of the `projectile-ignored-project-function`.

**Comment by teaforthecat** [comment]
Ha, ok so it was added 24 days ago. I guess that is kind of a while :) Thank you.
