### ISSUE TITLE
Editing results from `helm-projectile-ag' saves all files on commit action

### ISSUE THREAD

**Issue by holtzermann17** [bbatsov/projectile#756]
I ran `M-x helm-projectile-ag RET ^%% C-c C-e` inside of a Git repo containing tex files, and changed one line.  I pressed `C-c C-c` and then saw this appear in the `*Messages*` buffer (edited to remove duplicates).  The numbers exactly match the corresponding number of lines in the `*helm-ag-edit*` buffer. This behavior is not desirable; only the lines corresponding to an actual edit should be saved (and these files should only be saved once).

```
Saving file /home/joe/feedback/NOTES/notes.tex...
Wrote /home/joe/feedback/NOTES/notes.tex
(... 41 times...)
Saving file /home/joe/feedback/apacite.sty...
Wrote /home/joe/feedback/apacite.sty
(... 84 times...)
Saving file /home/joe/feedback/biblio.bib...
Wrote /home/joe/feedback/biblio.bib
(... 4 times ...)
Saving file /home/joe/feedback/background.tex...
Wrote /home/joe/feedback/background.tex
(... 2 times ...)
Saving file /home/joe/feedback/ijcai15.tex...
Wrote /home/joe/feedback/ijcai15.tex
(... 2 times ...)
Saving file /home/joe/feedback/ijcai15.sty...
Wrote /home/joe/feedback/ijcai15.sty
(... 3 times ...)
Saving file /home/joe/feedback/llncs.cls...
Wrote /home/joe/feedback/llncs.cls
(... 20 times)
```

**Comment by bbatsov** [comment]
Submit this ticket to the helm-projectile project https://github.com/bbatsov/helm-projectile
