### ISSUE TITLE
Enable fuzzy matching for projectile-completing-read

### ISSUE THREAD

**Issue by aronasorman** [bbatsov/projectile#759]
Helm just got fuzzy matching recently, and it would be nice if there's a setting that would enable fuzzy matching wherever helm can be used. I think it's as simple as adding the `:fuzzy` keyword parameter here: https://github.com/bbatsov/projectile/blob/master/projectile.el#L1112-L1115

**Comment by tuhdo** [comment]
It's already in Helm Projectile. You must install Helm Projectile to get real Helm interface to Projectile, with fuzzy matching and actions. First, you must install Helm Projectile then add the following configuration:

```elisp
(setq helm-projectile-fuzzy-match t) ;; must place here before loading helm-projectile
(require 'helm-projectile)
(helm-projectile-on)
```

See [Helm integration](https://github.com/bbatsov/projectile#helm-integration). Finally, Helm got fuzzy matching on Jan so it's not recently.

**Comment by aronasorman** [comment]
Good to know, thanks!

**Comment by aronasorman** [comment]
Strange, it doesn't seem to be working with `projectile-persp-switch-project`. I keep getting the default matching for that. Would you know if `helm-projectile` works with that @tuhdo?

**Comment by tuhdo** [comment]
have you changed projectile-switch-project-action to helm-projectile-find-file?

**Comment by aronasorman** [comment]
@tuhdo It's set to `projectile-dired` right now. 

Playing around it looks like `helm-projectile-switch-project` does have fuzzy matching now, but `projectile-persp-switch-project` doesn't. Looks like `helm-projectile-switch-project` also switches the perspective too, so just switching to that works for me.
