### ISSUE TITLE
helm-projectile-grep fails to respect projectile-use-git-grep variable

### ISSUE THREAD

**Issue by tko** [bbatsov/projectile#763]
In a git project setting `projectile-use-git-grep` significantly increases the performance of `projectile-grep` but that does not seem to have any effect on `helm-projectile-grep`.

From: syl20bnr/spacemacs#1835

**Comment by yatesco** [comment]
I can confirm the same.

I have `(setq projectile-use-git-grep 1)` in my `.emacs.d/personal/personal.el` yet when I do `C-c p s g` it is showing me results from files that are ignored in my .gitignore. If I manually call `vc-git-grep` for `*` files and navigate to my project root then I only see results in non-ignored files.

In addition, `helm-git-grep` works as expected.

(Thanks for projectile and prelude though - they are brill!, little issues like this not-withstanding ;-)).
