### ISSUE TITLE
helm-projectile-ag buffer resumed by helm-resume does not work properly

### ISSUE THREAD

**Issue by greenrd** [bbatsov/projectile#764]
helm-projectile-ag works fine for me, but when I use helm-resume to resume a previous search, I experience a couple of issues. Firstly, navigating to a file does not always work - sometimes the filename is incorrectly constructed based on the current directory of the buffer I was in instead of the root directory of the projectile project. Secondly, editing the search causes no results to be displayed (I suspect the same fundamental cause - searching in the subdirectory instead of the projectile root directory).

**Comment by bbatsov** [comment]
Submit this ticket to the helm-projectile project https://github.com/bbatsov/helm-projectile
