### ISSUE TITLE
Strange characters in "Find file" prompt

### ISSUE THREAD

**Issue by honza** [bbatsov/projectile#765]
Using latest prelude or bare config with only projectile, invoking <kbd>C-c p f</kbd> I get

![screen shot 2015-06-06 at 22 33 15](https://cloud.githubusercontent.com/assets/206357/8022258/6d41bb74-0c9c-11e5-8e9c-82eb3cc393b0.png)

**Comment by ReneFroger** [comment]
Do you get the same issue with an empty configuration, with Projectile only?

**Comment by ReneFroger** [comment]
To solve this, you could consider integration of Projectile into Helm. 

(setq helm-for-files-preferred-list
      '(
        helm-source-projectile-files-list
        helm-source-projectile-recentf-list
        helm-source-buffers-list
        helm-source-recentf
        helm-source-projectile-directories-list
        helm-source-projectile-projects
        ;; helm-source-bookmarks
        ;; helm-source-file-cache
        helm-source-files-in-current-dir
        helm-source-moccur
        helm-source-locate
        ))         

Then `C-c p-f` is integrated into your Helm. When there are no files available, Projectile will not displaying the source. You can call `helm-for-files` with a keybinding: http://tuhdo.github.io/helm-projectile.html

**Comment by honza** [comment]
Yes, this happens for me even with a bare config with only projectile installed.

**Comment by bbatsov** [comment]
Seems there are some colour codes in your filenames. I can't reproduce this.

**Comment by shangsunset** [comment]
same here.
<img width="1102" alt="screen shot 2017-03-31 at 9 59 00 pm" src="https://cloud.githubusercontent.com/assets/3700269/24574251/8e251ff8-165d-11e7-9376-96da3f1eb7a8.png">
