### ISSUE TITLE
helm-projectile-find-file ignores multiples of search strings

### ISSUE THREAD

**Issue by tko** [bbatsov/projectile#768]
Given a directory hierarchy such as:
```
abc.ext
abc/abc.ext
```
one would expect that typing `a a` in the helm-projectile-find-file prompt would filter out the first entry since it does not contain two a's but it appears entering the same string multiple times has no effect.

**Comment by bbatsov** [comment]
Submit this ticket to the helm-projectile project https://github.com/bbatsov/helm-projectile
