### ISSUE TITLE
helm-projectile-ag doesn't work on Windows 8.1 (helm-ag works).

### ISSUE THREAD

**Issue by mpielikis** [bbatsov/projectile#770]
I installed emacs 24.4.1 on Windows 8.1 and emacs 24.3.1 on Ubuntu. The minimum installed packages are the same on both OS'es helm, helm-ag, projectile, helm-projectile. The helm-ag works on both emacs but helm-projectile-ag works only in Ubuntu. helm-projectile-ag command on Windows opens empty helm window and after entered pattern it closes.

The ag version on Windows - 0.18.1 (via choco install ag) on Ubuntu - 0.19.2.

The same situation is with helm-projectile-ack.

**Comment by syohex** [comment]
It's my fault. I suppose this issue was fixed by https://github.com/syohex/emacs-helm-ag/pull/114 .
Please update `helm-ag` to latest version. (If you use package.el, you need to wait some hours until MELPA update).

**Comment by mpielikis** [comment]
aha it works now! thanks :)
