### ISSUE TITLE
Is it possible to compile in a subdirectory?

### ISSUE THREAD

**Issue by cbilson** [bbatsov/projectile#773]
Context: working in a large project. Compiling from the top of the tree may take several minutes. If I make a small change deep down in a subdirectory, it would be nice if I could run make there instead of from the root.

Is there a way to make projectile do this? Looking at projectile.el it's not obvious to me how to do it. I tried using .dir-locals.el and setting compile-command, but it still build from the project root.

Thanks in advance for any help!

**Comment by bbatsov** [comment]
It's not possible right now, but we can tweak `projectile-compile-project` to prompt for the directory in which to do the compilation.
