### ISSUE TITLE
projectile considers HOME to be a project root although projectile-require-project-root in t

### ISSUE THREAD

**Issue by tsdh** [bbatsov/projectile#777]
Since a very recent MELPA upgrade of helm-projectile (currently version 20150610.253), it starts up very slowly when invoked from a buffer which is not associated with a project file.  It takes about 5 seconds until the prompt and candidate list appears.

Recipe:

1. `emacs -Q`
2. `M-: (package-initialize) RET`
3. `M-x helm-projectile RET` in `*scratch*` takes about 5 secs until prompt/candidates appear
4. `C-x C-f /path/to/project/file.el RET`, `M-x helm-projectile RET` appears instantly

The slowness seems to appear only with buffers which either aren't associated with a file at all (like `*scratch*`) or are not associated at least with a file in a project (like `/tmp/foo`).

**Comment by tuhdo** [comment]
I do not have this issue. What OS and Emacs version are you using? Is your project large? If you visit a large project, it takes a few seconds to retrieve the file list but if you enable caching, the next time you run the command, `helm-projectile` should be instant to show the file list. Try again with `projectile-find-file` to see if the issue occurs, but it's likely since both Helm Projectile and Projectile use the same function to retrieve the file list.

**Comment by tsdh** [comment]
I'm on Arch Linux with the current HEAD of emacs.

As said, `helm-projectile` shows the candidates instantaneously if the current buffer is associated with a file in some project.  It is slow only if the current buffer is not associated with some project file.

Anyway, now I tested `projectile-find-file` and indeed there's the same issue.  It seems that when the current buffer is not associated with a projectile file, then `~/` is considered to be the project.  Well, and my HOME contains more than 300.000 files, so its no wonder that it's slow.

I edebugged `projectile-project-root`, and the `projectile-project-root-files-functions` function `projectile-root-top-down` suggests `/home/horn` as being the project root (I pruned the project root cache before to make sure).

```
Result: projectile-root-top-down
Result: "/home/horn/.emacs.d/elpa/projectile-20150610.2247/"
Result: "projectile-root-top-down-/home/horn/.emacs.d/elpa/projectile-20150610.2247/"
Result: "projectile-root-top-down-/home/horn/.emacs.d/elpa/projectile-20150610.2247/"
Result: #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8 data ("projectile-root-bottom-up-~/" no-project-root "projectile-root-top-down-~/" "/home/horn/" "projectile-root-bottom-up-~/.emacs.d/" no-project-root "projectile-root-top-down-~/.emacs.d/" "/home/horn/" "projectile-root-bottom-up-/home/horn/.gnus.d/" no-project-root "projectile-root-top-down-/home/horn/.gnus.d/" "/home/horn/" "projectile-root-bottom-up-/home/horn/" no-project-root "projectile-root-top-down-/home/horn/" "/home/horn/" "projectile-root-bottom-up-/home/horn/.emacs.d/elpa/projectile-20150610.2247/" no-project-root "projectile-root-top-down-/home/horn/.emacs.d/elpa/projectile-20150610.2247/" "/home/horn/" ...))
Result: "/home/horn/"
Result: "/home/horn/"
```

After a bit more debugging, I found out that `projectile-locate-dominating-file` will be 7 times during `(projectile-project-root)` with empty cache.  The first 6 times it returns nil, but the last call which receives a closure returns `/home/horn`.

```
projectile-locate-dominating-file: /home/horn/.emacs.d/elpa/projectile-20150610.2247/ .projectile
projectile-locate-dominating-file: /home/horn/.emacs.d/elpa/projectile-20150610.2247/ .git
projectile-locate-dominating-file: /home/horn/.emacs.d/elpa/projectile-20150610.2247/ .hg
projectile-locate-dominating-file: /home/horn/.emacs.d/elpa/projectile-20150610.2247/ .fslckout
projectile-locate-dominating-file: /home/horn/.emacs.d/elpa/projectile-20150610.2247/ .bzr
projectile-locate-dominating-file: /home/horn/.emacs.d/elpa/projectile-20150610.2247/ _darcs
projectile-locate-dominating-file: /home/horn/.emacs.d/elpa/projectile-20150610.2247/ (closure ((list) (dir . /home/horn/.emacs.d/elpa/projectile-20150610.2247/) t) (dir) (let (#:needle) (let ((#:list (or list projectile-project-root-files)) (#:continue t) (it-index 0)) (while (and #:list #:continue) (let ((it (car #:list))) (if (not (not #:needle)) (setq #:continue nil) (if (projectile-file-exists-p (expand-file-name it dir)) (progn (setq #:needle it))))) (setq it-index (1+ it-index)) (setq #:list (cdr #:list)))) #:needle))
```

**Comment by tuhdo** [comment]
Arch on Emacs has an issue with Helm and even Magit. You should take a look [at this reddit thread](http://www.reddit.com/r/emacs/comments/3a8ovf/magit_and_helm_became_unusably_slow/) and the linked Helm issue.

**Comment by tsdh** [comment]
As already said, I don't use the emacs provided by Arch.  This is a different issue.  The issue here is that projectile considers my HOME directory to be a project which it is not.

**Comment by tuhdo** [comment]
May I have a look at your Projectile ocnfiguration? What's the value of `projectile-require-project-root`?

**Comment by tsdh** [comment]
My complete config is

```elisp
(setq projectile-completion-system 'default
      projectile-switch-project-action 'projectile-find-file-dwim)
(setq helm-projectile-fuzzy-match nil)
(require 'helm-projectile)
(setq helm-locate-command "locate %s --basename --existing -r %s"
      helm-ff-transformer-show-only-basename nil)
```
`projectile-require-project-root` is at its default value, i.e., `t`.

**Comment by tuhdo** [comment]
Try enabling cache and it should be fast the second time you run Projectile on a project:

```elisp
(setq projectile-enable-caching t)
```

As for your other issue, I tried `helm-projectile-find-file` at my home directory but it gives me this error:

```text
helm-projectile-find-file: You're not in a project
```

Maybe somehow home dir got into the project list. Try removing it with `helm-projectile-switch-project`. Also, try setting `projectile-switch-project-action` to something else, since `projectile-find-file-dwim` gets the symbol at point and filter files that match the symbol, so it will be slow on large projects i.e. with 300k files like you said above.

**Comment by tsdh** [comment]
I don't want projectile to consider my HOME as a project in the first place.  I can reproduce that even with emacs -Q and  projectile-20150610.2247 from MELPA.

```
cd ~
emacs -Q
;; in *scratch*
(package-initialize)
(require 'projectile)
(projectile-project-root) ;=> /home/horn
M-x projectile-find-file ;; takes 5 seconds until I get the completion prompt considering all 300.000 files in my home
```

So that's actually not a helm-projectile but a plain projectile issue.  I'll adapt the summary.

**Comment by tuhdo** [comment]
By default, anything not a project recognized by Projectile, an error "You're not in a project" is returned immediately on most commands. Do you have some `.git` or `.projectile` find in your home directory? If not, `projectile-find-file` or most commands should not be usable there.

**Comment by tsdh** [comment]
No, just `.gitk` and `.gitconfig`, `.hgk` and `.hgrc`, and `.bzr.log`.

**Comment by tsdh** [comment]
Gosh, that put me in the right direction.  I had indeed a `project.clj` laying around there which someone emailed me and I've saved there for inspection...

**Comment by miltonio94** [comment]
Hello, I'm having the same issue as described above but I have no project folder in my home directory nor any .git  files
