### ISSUE TITLE
projectile-current-project-files freezes windows emacs

### ISSUE THREAD

**Issue by iamdionysus** [bbatsov/projectile#778]
windows emacs version: 24.4, 24.5 as in [https://ftp.gnu.org/gnu/emacs/windows/]

### observation
It does not happen to all projects. Certain project has this issue always. Other projects are always fine. I have to shut down emacs in windows task manager processes. While doing this every time, I just found that there is zombie git.exe *32 process with 128K memory is always there as well. So this time, I didn't shutdown the emacs and only kill the git.exe *32 with 128K memory one. Suddenly, I found that the projectile window pops up in the emacs and it's working again!

### tracking
I just found that (projectile-current-project-files) is the cause of this problem in those project. I'm figuring out what's going on here now.

If you know this issue already or know how to fix this, please enlighten me. I'll try my best to debug if possible. But I'm not that expert as you guys.

**Comment by tuhdo** [comment]
Try setting to `'alien` [indexing method](https://github.com/bbatsov/projectile#indexing-method):

```elisp
(setq projectile-indexing-method 'alien)
```

By default, on Windows, Projectile won't use external command to retrieve the file list but Emacs itself, which causes a long blocking on slightly large repository.

If the above method works, you should also comment on this issue: https://github.com/bbatsov/projectile/issues/581

**Comment by iamdionysus** [comment]
I've been using (setq projectile-indexing-method 'alien) I got a bit more now.

(-mapcat 'projectile-dir-files (projectile-get-project-directories)) makes the emacs freeze.

**Comment by tsdh** [comment]
Just to rule out this is related to #777, what does `M-: (projectile-project-root)` in the *scratch* buffer return?

**Comment by iamdionysus** [comment]
It's getting collect project root for each project like "c:/../../"

**Comment by iamdionysus** [comment]
Please check this out. I dig into the code and found projectile-remove-ignored is causing this.

```elisp
(defun test-bug-not-freezing ()
    (let ((root (projectile-project-root))
	  (directory "C:/my-project/"))
      (projectile-dir-files-external root directory)))

(defun test-bug-freezing ()
    (let ((root (projectile-project-root))
	  (directory "C:/my-project/"))
      (projectile-remove-ignored (projectile-dir-files-external root directory))))
```

**Comment by iamdionysus** [comment]
I tested this by making projectile-remove-ignored returns the files without removing. Just commented remove logic. It works. I don't experience frozen windows emacs anymore. I'll try to find out solution which can make windows emacs happy as well when I get some time.

```elisp
(defun projectile-remove-ignored (files)
  "Remove ignored files and folders from FILES.

Operates on filenames relative to the project root."
;;  (let ((ignored (append (projectile-ignored-files-rel)
;;                         (projectile-ignored-directories-rel))))
;;    (-remove (lambda (file)
;;               (or (--any-p (string-prefix-p it file) ignored)
;;                   (--any-p (string-suffix-p it file) projectile-globally-ignored-file-suffixes)))
;;             files)))
  files)
```

**Comment by iamdionysus** [comment]
I ran edebug on this function and I found that the code below runs extremely slow on certain project. 

```elisp
    (setq files-list (-map (lambda (f)
                             (file-relative-name (expand-file-name f directory) root))
                           (projectile-get-repo-files)))
```

When I use `(setq projectile-indexing-method 'native)` the indexing is not the fastest but it does not freeze. So I compared `projectile-dir-files-native` to `projectile-dir-files-external`. 

```elisp
(defun projectile-dir-files-native (root directory)
  "Get the files for ROOT under DIRECTORY using just Emacs Lisp."
  (let ((progress-reporter
         (make-progress-reporter
          (format "Projectile is indexing %s"
                  (propertize directory 'face 'font-lock-keyword-face)))))
    ;; we need the files with paths relative to the project root
    (-map (lambda (file) (file-relative-name file root))
          (projectile-index-directory directory (projectile-patterns-to-ignore)
                                      progress-reporter))))

(defun projectile-dir-files-external (root directory)
  "Get the files for ROOT under DIRECTORY using external tools."
  (let ((default-directory directory)
        (files-list nil))
    (setq files-list (-map (lambda (f)
                             (file-relative-name (expand-file-name f directory) root))
                           (projectile-get-repo-files)))
    files-list))
```

From looking at the `projectile-dir-files-native` , 

* it looks like `(setq files-list ... )` is redundant
* `(file-relative-name (expand-file-name f directory) root))` can be shortened to `(file-relative-name f root)`

I changed the `projectile-dir-files-external` to this and it work fine for every projects now.

```elisp
;; original
(defun projectile-dir-files-external (root directory)
  "Get the files for ROOT under DIRECTORY using external tools."
  (let ((default-directory directory)
        (files-list nil))
    (setq files-list (-map (lambda (f)
                             (file-relative-name (expand-file-name f directory) root))
                           (projectile-get-repo-files)))
    files-list))

;; changes
(defun projectile-dir-files-external (root directory)
  "Get the files for ROOT under DIRECTORY using external tools."
  (-map (lambda (file) (file-relative-name file root))
                           (projectile-get-repo-files)))
```

Can you guys take a look at this? I'll test more in my side and if it's working fine, I can open pull request. But if you guys can just update this, I'll appreciate it as well.

**Comment by bbatsov** [comment]
> it looks like (setq files-list ... ) is redundant

Seems this is some leftover from the past.

> (file-relative-name (expand-file-name f directory) root)) can be shortened to (file-relative-name f root)

Good observation.

> Can you guys take a look at this? I'll test more in my side and if it's working fine, I can open pull request. But if you guys can just update this, I'll appreciate it as well.

Fire up that PR!

**Comment by iamdionysus** [comment]
I open the pull request https://github.com/bbatsov/projectile/pull/781. Please check it out.
