### ISSUE TITLE
projectile-helm-ag not working with tramp

### ISSUE THREAD

**Issue by dab** [bbatsov/projectile#779]
I'd like to work on my dev server from local machine, and most of `projectile` functionality working well, but `projectile-helm-ag` — it's still searching locally even when project directory set to ssh. I'd like to use it remotely as well. Will make my workflow better. Thanks.

**Comment by tuhdo** [comment]
`helm-ag` or Helm-based search in general does not work over ssh. For that, you need to use [ag](https://github.com/Wilfred/ag.el).

Or you can request the feature on [helm-ag](https://github.com/syohex/emacs-helm-ag), not here since Projectile only reuses `helm-ag` when available.

**Comment by dab** [comment]
Thanks, will request the feature. You already told me about the using `ag`, just want to use more user friendly solution.

**Comment by syohex** [comment]
`helm-do-ag` works with tramp by https://github.com/syohex/emacs-helm-ag/pull/149 changes. `helm-projectile-ag` also works. Please upgrade `helm-ag` version and try again.
