### ISSUE TITLE
Projectile cannot find project root - (void-variable it) in projectile-project-root

### ISSUE THREAD

**Issue by t-jones** [bbatsov/projectile#780]
It was working great yesterday and today, after upgrading to the latest projectile and helm, it's not working.  If I run 'C-c p p', it prompts for the project root and then fails with:

    Debugger entered--Lisp error: (void-variable it)
      projectile-project-root()
      projectile-dirconfig-file()
      projectile-maybe-invalidate-cache(nil)
      projectile-find-file()
      projectile-switch-project-by-name("~/develop/code/pmsync/" nil)
      projectile-switch-project(nil)
      call-interactively(projectile-switch-project nil nil)
      command-execute(projectile-switch-project)

Please let me know how I can provide more information.

**Comment by bbatsov** [comment]
See the comments here https://github.com/bbatsov/projectile/commit/53d2e4b9d58688b6cd0c9cc00bae58dd3c4abff2

I'm pretty sure this commit caused the problem for you.

**Comment by t-jones** [comment]
That's it!  Thanks for the pointer.  Is there any way to prevent these sort of compile-time dependency problems when upgrading via package.el?  Thanks also for the great work on projectile.

**Comment by bbatsov** [comment]
Not sure. @Malabarba mentioned this won't be an issue in Emacs 25. Guess we'll just have to wait. :-)

> Thanks also for the great work on projectile.

You're welcome!

**Comment by Malabarba** [comment]
The user can reduce the chances of running into problems like this by upgrading often. You can also completely get rid of it with a clever advice, but I wouldn't recommend that.

As for the package, there's no correct way to prevent this. There are a couple of ugly, hacky ways, but this is fixed in Emacs 25 anyway.

**Comment by t-jones** [comment]
Thanks for the extra info.  Recompiled and it's good to go.
