### ISSUE TITLE
Support for multiple tag generators

### ISSUE THREAD

**Issue by JSmith-BitFlipper** [bbatsov/projectile#786]
Tag generators such as ctags or etags do not have support for some "less" commonly used languages such as Haskell. For Haskell, there exists hasktags which can generate ctag format TAGS, however I cannot seem to find a good way to change projectile-tags-command based on the type of project I am in. 

Is there something I am missing?

**Comment by stardiviner** [comment]
Could add a sub-keymap for helm-projectile- tags-generate, cscope, catgs, etags, hasktags etc.

**Comment by cydparser** [comment]
It would be nice to be able to easily override the tag generator for specific projects types. E.g. I use `codex update` with Haskell projects, but the only way that I found to do this is:
```emacs-lisp
(make-variable-buffer-local 'projectile-tags-command)
;; In a haskell-mode-hook
(setq projectile-tags-command "codex update")
```

**Comment by 23Skidoo** [comment]
+1 from me, this'd be nice to have.

**Comment by bbatsov** [comment]
There hasn't been much activity on this ticket and I'm spread too thin on so many tasks, so I'll just close it for the sake of having a cleaner lists of tasks to focus on. 

To be perfectly clear - I think that's a good idea in general and I'll gladly review a PR, but it's unlikely that I'll tackle this myself in the foreseeable future. Hopefully my response is going to inspire someone else to work on this! 😉
