### ISSUE TITLE
Shortcut for find file in subdirectory

### ISSUE THREAD

**Issue by duff** [bbatsov/projectile#787]
Hi,

I have a keyboard shortcut setup to run `projectile-find-file` and it works wonderfully.  I was wondering if there might be a way to setup a few other shortcuts such that I can easily search over a subset of the files in a project rather than across the entire project.  So, for example, I'd love a shortcut to `projectile-find-file` that only looks in the `lib/` directory.  I'd love another one to only look in the `tests/` directory.

I know about `projectile-find-file-in-directory`, but that prompts me for a directory.  I'd like to be able to hookup some shortcuts to hard coded locations since I know before I'm going to find a file if it's a model, a test, a lib file, etc.

When I used to use Ctrl-P in Vim, I could setup shortcuts like this:

```
nnoremap <leader><leader>m :CtrlP app/models<cr>
nnoremap <leader><leader>v :CtrlP app/views<cr>
nnoremap <leader><leader>c :CtrlP app/controllers<cr>
nnoremap <leader><leader>l :CtrlP lib<cr>
nnoremap <leader><leader>u :CtrlP test<cr>
```

Might there be some way to do something similar in Projectile?  I thought I'd check here in case there was an ability I might be missing.  I've even tried creating a function in which I attempted to call `projectile-find-file` and then send keys to the minibuffer containing the directory prefix, but I haven't been successful as of yet in getting that to work.

Might you have any ideas as to where I might look to do something like this?

Thanks so much for projectile!  I'm loving it.

**Comment by bbatsov** [comment]
I'm assuming you're using `ido`, so you can just bind such commands in its completion keymap as described here http://emacs.stackexchange.com/questions/3729/how-do-i-bind-keys-in-ido

Perhaps we should make something like this easier to setup, but I'm not sure how many people are interested in such a feature.

**Comment by bbatsov** [comment]
Btw, there's also https://github.com/asok/projectile-rails

**Comment by duff** [comment]
Thanks @bbatsov!  Here's where I ended up:

https://github.com/duff/emacs.d/commit/522d7796054aa868cf2966815f94cb6738abe209

It basically lets me pass that last parameter to `projectile-completing-read`.  I agree with you in that I'm also unsure as to how many people are interested in such a feature.  I figure I'll close this for now since I may be the only human interested! :smile:
