### ISSUE TITLE
Symbols value as a variable is void: it

### ISSUE THREAD

**Issue by Kungi** [bbatsov/projectile#788]
When I try to run any projectile related command I get this error:

    Symbols value as a variable is void: it

This seems to happen in `projectile-project-root` at this point:

    (cache-key (format "%s-%s" it dir))

Can you please help me debugging this?

**Comment by bbatsov** [comment]
I'm guessing you have to update your `dash.el`.

**Comment by Kungi** [comment]
`package-list-packages` tells me I’m at version `20150611.922`. This seems
to be the newest version available.

**Comment by bbatsov** [comment]
Ah, yeah - it's actually this https://github.com/bbatsov/projectile/issues/780

**Comment by diiq** [comment]
Also having this issue. 

The projectile comment block still says that you only require dash 1.5

    ;; Package-Requires: ((dash "1.5.0") (pkg-info "0.4"))

and --some (the offending function) isn't *in* dash 1.5.0 . This may be some part of the problem with installing from the package manager.

**Comment by bbatsov** [comment]
Ops. I use only MELPA all the time and failed to notice this. The problem of living on the edge...

**Comment by Kungi** [comment]
I am using Cask with the following sources:

﻿﻿    (source gnu)
    (source melpa)
    (source org)

and recompiled all .el files with `(byte-recompile-directory (expand-file-name "~/.emacs.d/.cask") nil t)` but the problem still persists.

**Comment by dl1ely** [comment]
In the same situation here, do not know what would be the right steps to fix this. Reinstalling dash and projectile from melpa didn't help.

**Comment by bbatsov** [comment]
Did you try removing the old compiled files?

**Comment by Kungi** [comment]
Yes I tried that as well.

**Comment by bbatsov** [comment]
I'm at a loss here - the function is definitely in `dash.el` and this seems to work for most people (myself included). What's your Emacs version, btw?

**Comment by Kungi** [comment]
GNU Emacs 24.4.50.1

Can I somehow check which dash.el is loaded by emacs. Maybe I load the wrong one?

**Comment by bbatsov** [comment]
`M-x list-load-path-shadows`

You can also check the source of the loaded `dash.el` - `C-h l RET dash RET`.

**Comment by Kungi** [comment]
C-h l is bound to (view-lossage) which does not seem
to do what you intendet.

What is the function behind C-h l RET?

**Comment by bbatsov** [comment]
Ops. Use `M-x find-library`. Me and my bindings...

**Comment by Kungi** [comment]
Ok now I am stumped.

When I run M-x find-library dash I find it shows me:

dash Version 2.10.0 which should be recent enough.

**Comment by bbatsov** [comment]
If `--some` is there you should be covered.

**Comment by Kungi** [comment]
So I found this --some in my dash.el:
```
(defmacro --some (form list)
  "Anaphoric form of `-some'."
  (declare (debug (form form)))
  (let ((n (make-symbol "needle")))
    `(let (,n)
       (--each-while ,list (not ,n)
         (setq ,n ,form))
       ,n)))
```
I recompiled everything with:
`(byte-recompile-directory (expand-file-name "~/.emacs.d/.cask/24.4.50.1/elpa") 0 t)`

But I still get this error. What else could I have done wrong?

**Comment by bbatsov** [comment]
I'm out of ideas. //cc @vspinu @magnars

**Comment by magnars** [comment]
This `Symbols value as a variable is void: it` happens when the usage of an anaphoric macro (like `--some`) is byte compiled before Emacs is aware that it is a macro, ie before it is evaluated. Emacs assumes it is a function that will be defined later, and the macro is never expanded. 

So, from what I can tell, projectile.el is compiled before dash.el. Does `byte-recompile-directory` take into account take into account `Package-Requires`? Could you try evaluating `dash.el` first, and the byte compiling `projectile.el`?

**Comment by vspinu** [comment]
I guess `byte-recompile-directory` just relies on whatever is loaded in the emacs at that moment. So you are likely still compiled your projectile with the old dash. 

This is not a bug for sure. One anaphoric macro was replaced with another. It used to work for you before; it should be working now. You just have to figure out it locally.

**Comment by Kungi** [comment]
@magnars Thanks for the explanation. That seems to fit. I deleted all `.elc` files and it works fine. I will try your solution now.

**Comment by Kungi** [comment]
Thank you! I first compiled everything and then recompiled `projectile` and `helm-projectile` separately.

**Comment by base698** [comment]
How do you recompile everything?  I'm getting this error.

**Comment by liuzhishan** [comment]
I finally solved this problem by deleting cedet-1.1 that I installed. Just remove the line "(add-to-list 'load-path "~/.emacs.d/cedet-1.1)".

Recompiling doesn't work for me. So I think there maybe some conflict with projectile and cedet.
There also maybe other packages conflict too.

You can try my methods as follows:
1. Comment out all other packages except for melpa in your init file(init.el, custom.el, or .emacs.d). We need melpa to install helm and projectile.
2. Try install helm, projectile, helm-projectile. It should work.
3. Then use binary search to romove comment from your init.el. You may find one package that made projectile not working. That's the cause. Remove that package and restart emacs, or load init file again, It should work.

**Comment by map7** [comment]
I've got this issue under Emacs 24.4.1 on Debian. I'm using Cask to compile my emacs packages, I've removed all of the packages and just installed projectile like so
    
    Cask file
    : (source gnu)
    : (source marmalade)
    : (source melpa)
    : 
    : (depends-on "projectile")
    
    Remove and re-compile
    : cd ~/.emacs.d
    : rm -fr .cask/24.4.1/elpa
    : cask
     
    Start and try and run 'projectile-find-file' and still get the error
    : projectile-dirconfig-file: Symbol's value as variable is void: it

**Comment by diiq** [comment]
@map7 I suspect that you, like most of us in this thread, may have a version of dash hanging around somewhere that was not package-installed. Find and destroy it :)

**Comment by map7** [comment]
You're right there was an old dash in .emacs.d/.cask/24.4.1/bootstrap once I removed this I didn't need the dodgy hack anymore and projectile works :).

**Comment by aspiers** [comment]
Same problem here - as with others I had to not only upgrade / recompile / reload both dash and projectile but ensure that I did them in that order - it didn't work when I did projectile first.  Thanks @magnars @vspinu and others!
