### ISSUE TITLE
Adding properties functionality

### ISSUE THREAD

**Issue by sabof** [bbatsov/projectile#79]
Might it be possible to make .projectile store a plist? I was thinking about a
structure similar to this:

```
### properties ###
(:prop1 "val1"
 :prop2 "val2")
### ignored-files ###
/old format
/ignored-folder1
/ignored-folder2
```

If no headers are present it could assume that all lines represent ignored
files.

These values would be available through a function such as
(projectile-project-property :prop1), and could be used by extensions.
Additionally, projectile could use some properties itself to provide per-project
overrides for functions like the following:

```
:projectile-project-files-function
:projectile-compile-project-function
:projectile-test-project-function
```

It's common for such variables to require a "security clearance". I don't think
it's very useful, but I suppose you could reuse some find-file code to implement it.

**Comment by bbatsov** [comment]
@dakrone Just use a dir-local config for the project in question.
