### ISSUE TITLE
void-variable it

### ISSUE THREAD

**Issue by treydavis** [bbatsov/projectile#792]
I get an exception from this line:

https://github.com/bbatsov/projectile/blob/master/projectile.el#L685

I don't seem to have the  `--some` macro. I'm using 25.5.1.

**Comment by treydavis** [comment]
Figured it out from this discussion: https://github.com/bbatsov/projectile/commit/53d2e4b9d58688b6cd0c9cc00bae58dd3c4abff2#comments

`--some` is difficult to google to figure out where it comes from. I updated dash and reinstalled projectile to resolve the problem.

**Comment by Silex** [comment]
NIce that you find out the solution yourself, another related issue is https://github.com/bbatsov/projectile/issues/788

I guess you can close this one now.
