### ISSUE TITLE
helm-projectile-hack-actions: (wrong-type-argument listp helm-find-files-actions)

### ISSUE THREAD

**Issue by sewkokot** [bbatsov/projectile#794]
After today's helm upgrade from melpa I got the error as in title.
Perhaps helm-projectile must be fixed to adapt new helm changes

https://github.com/emacs-helm/helm/issues/1088

**Comment by catesandrew** [comment]
+1 ditto

**Comment by zachlatta** [comment]
Running into this as well. It also breaks projects in Spacemacs stable (I'm on 0.103.2)

syl20bnr/spacemacs#/2282

**Comment by sewkokot** [comment]
The fix done by Thierry [1] removes the error at startup but still there is an issue since helm-projectile-find-file does not work correctly e.g. opens dired buffer instead visiting a file.
[1] https://github.com/emacs-helm/helm/issues/1088

**Comment by kovrik** [comment]
Also encountered the same error after today's helm upgrade.

**Comment by YorkZ** [comment]
This should have been addressed in commit 134748a. Please see issue #796 for details.

**Comment by rranelli** [comment]
seeing the same problem over here.
