### ISSUE TITLE
Files in unversioned subdirectories no longer listed for navigation

### ISSUE THREAD

**Issue by ryan-maus** [bbatsov/projectile#801]
After the most recent update, I no longer see any files listed for unversioned subdirectories of my project root.  The folders checked into SVN appear normally in projectile, but a dozen other directories pulled in by svn-externals are not.

Is there a configuration to get projectile to recognize all files in all subdirectories of the project root?

Thanks,
REM

Config:
```lisp
(require 'projectile)
(projectile-global-mode)
(setq projectile-enable-caching t)
(setq projectile-indexing-method 'alien)

(require 'helm-projectile)
(helm-projectile-on)
(setq projectile-completion-system 'helm)
```

emacs 24.5.1
projectile 20150712.1329
helm-projectile 20150713.137

**Comment by bbatsov** [comment]
Nothing related to this functionality has been changed recently. Guess you'll have to adjust the SVN command you're using. Modify `projectile-svn-command`.

**Comment by ryan-maus** [comment]
Not entirely sure why this broke the way it did (possibly related to the projectile cache?), but clearing the cache and modifying that command resolved the issue.  Thank you.
