### ISSUE TITLE
helm-projectile-grep doesn't ignore files per directory

### ISSUE THREAD

**Issue by yeminzhang** [bbatsov/projectile#807]
Hi,

helm-projectile-grep and projectile-grep behave differently. projectile-grep can ignore files per directory by setting something such as "-/out" in .projectile. But helm-projectile-grep doesn't support this. It only have a global ignored file list. I hope helm-projectile-grep could function the same way as projectile-grep does. Thanks!

**Comment by maximvl** [comment]
`helm-projectile-grep` doesn't support ignoring, at least the code doesn't do it. But `helm-projectile-ack` does respect `.projectile` settings, except there is a problem with patterns, they are not included into `projectile-ignored-files`:

```
(with-current-buffer ".projectile"
  (list 
   (projectile-patterns-to-ignore)
   (projectile-ignored-files)))
(("*.beam" "*.log*") ("/home/maxvel/dev/gunfleet/TAGS"))
```

with `.projectile` content:

```
-/.git
-/Unity
-/CSharpCLI
-*.beam
-*.log*
```

@bbatsov is there a reason for that or should patterns be treated specially?

**Comment by bbatsov** [comment]
Submit this ticket to the helm-projectile project https://github.com/bbatsov/helm-projectile
