### ISSUE TITLE
helm-projectile-vc stopped working

### ISSUE THREAD

**Issue by kostya-sh** [bbatsov/projectile#809]
Pressing `M-g` in helm-projectile popup doesn't show magit status window any more. Instead the following error is displayed: `magit-status-internal: Wrong type argument: arrayp, nil`

I believe this is caused by the following change in magit: https://github.com/magit/magit/commit/01cf031f0ba54a3860571794f12195ddaf3f7323

I am using magit 20150720.1617, helm-projectile 20150714.842

**Comment by bbatsov** [comment]
Probably true. @tarsius Any advice on how to alter the implementation in projectile?

**Comment by noorul** [comment]
When I am trying to switch to a project and use Alt-g to see magit buffer, it is not switching and I also get the following message in *Messages* buffer.

user-error: Not inside a Git repository

**Comment by kostya-sh** [comment]
`M-g` seems to be working again with magit 20150726.1805 and projectile 20150724.1312

**Comment by kostya-sh** [comment]
Since this is fixed now I am closing the issue.
