### ISSUE TITLE
Projectile thinks I have a file named after a git error message

### ISSUE THREAD

**Issue by jgarvin** [bbatsov/projectile#813]
I accidentally invalidated my cache recently, and now when I visit a file in my git project to try and repopulate it, the repopulation seems to silently fail. I can't tell it's failed until I try `C-c p f` and see the only ido candidate is a file allegedly named:

```
fatal: Not a git repository: /home/vagrant/repos/numpy/.git/modules/doc/scipy-sphinx-theme
```

My sandbox contains a _file_ (not a directory) named `scripts/prod/foo/build/numpy/doc/scipy-sphinx-theme/.git` -- I can't tell if it's checked in or not, it's possible a coworker accidentally checked it in but it doesn't show up in `git ls-files` and there aren't any git submodules in our tree so I don't know how it ended up in my sandbox. Its contents is:

```
gitdir: /home/vagrant/repos/numpy/.git/modules/doc/scipy-sphinx-theme
```

If you try to run `git status scripts/prod/foo/build/numpy/doc/scipy-sphinx-theme/.git` you get the error exactly. `/home/vagrant` has never been a path on my machine, I assume it's something checked into this scipy thing for some reason. To top it all off I have "-/scripts" in my .projectile file. So there appear to be multiple bugs here:
- projectile is invoking git on a file and presumably not checking the error code, leading to it thinking there is a file named after an error
- projectile does this even though that subdirectory is supposed to be ignored
- after getting an error projectile doesn't populate the cache with any other files

Here are the projectile settings I use:

```
(projectile-global-mode)
(setq projectile-indexing-method 'alien)
(setq projectile-switch-project-action 'projectile-dired)
(setq projectile-enable-caching t)
(setq projectile-mode-line " Projectile")
```

This is with melpa 20150722.2202.

**Comment by bbatsov** [comment]
> projectile is invoking git on a file and presumably not checking the error code, leading to it thinking there is a file named after an error

It seems this is the problem we should focus on. It's true there's not much error checking for the results of shell commands - we're just optimistic they are going to work out fine. :-)
