### ISSUE TITLE
C-c p T hangs the whole emacs

### ISSUE THREAD

**Issue by Kukunin** [bbatsov/projectile#814]
Hello. I've got the the bug with projectile, when `C-c p T` keystroke hangs all emacs. It becomes totally unresponsible. It takes about a minute or two to unfreeze the UI.

I use Mac OS X Yosemite, emacs installed from `brew`, almost empty configuration, Ruby on Rails project folder. I use latest version of projectile from repository.

I think, any resourceful action shouldn't hang the UI of emacs.
I'd like you to give any debug information about my system to help you to troubleshoot the bug.

**Comment by bbatsov** [comment]
Seems I've introduced some performance regression, which made the test file filtering ridiculously slow. I'll investigate.
