### ISSUE TITLE
C-u helm-projectile-ag gots error

### ISSUE THREAD

**Issue by demon386** [bbatsov/projectile#819]
I want to specify options to helm-projectile-ag, so I uses C-u helm-projectile-ag.

But after providing options ("--cpp"), I got error:

> Wrong type argument: listp, "--cpp"

**Comment by syohex** [comment]
@demon386 I fixed this issue at https://github.com/syohex/emacs-helm-ag/pull/143. Please upgrade helm-ag version.

**Comment by demon386** [comment]
@syohex Great. It works.

BTW: Is it possible to provide the latest option as default when calling this?

**Comment by syohex** [comment]
> BTW: Is it possible to provide the latest option as default when calling this?

I suppose there is no way. We need some fix to `helm-projectile` or `helm-ag` for implementing its feature.
