### ISSUE TITLE
C-c p s g report error after update just now

### ISSUE THREAD

**Issue by YuleiXiao** [bbatsov/projectile#821]
error look like this:
Error running timer `helm-projectile-grep-or-ack': (void-variable grep-find-ignored-files)

**Comment by askreet** [comment]
I just hit this error as well, and resolved it by explicitly requiring grep before loading helm-projectile.
```
(require 'grep)
```

**Comment by lvh** [comment]
Same problem, same fix -- worked even by requiring it *after* loading helm-*.

**Comment by bbatsov** [comment]
Can't reproduce this.
