### ISSUE TITLE
Generate Tags and Search Doesn't Respect Ignore Rules in .projectile (Spacemacs)

### ISSUE THREAD

**Issue by jophde** [bbatsov/projectile#824]
I am working on a huge project.  It has a lot of generated code and binaries etc.  I don't want this to be indexed.  My .projectile looks like this:

+/src/www/frontend/src/js/optly
+/src/www/frontend/src/js/optly_jstest
+/src/www/frontend/src/scss

However, whenever I generate tags all of the directories in the project are used resulting in a > 10G TAGS file.  Also, whenever I do a search results are shown from directories that shouldn't be included.

**Comment by hmgibson23** [comment]
:+1: - would be to have this
