### ISSUE TITLE
Trouble finding files in Windows 10

### ISSUE THREAD

**Issue by rschuetzler** [bbatsov/projectile#827]
Initially I received an error that `FIND: Parameter format not correct`. I'm not sure what changed, but now when I look at `*Messages*` all it tells me is: `Aborting an helm session running in background` (I'm using helm-projectile). This happens even when I run helm-projectile immediately after opening Emacs.

**Comment by bbatsov** [comment]
What's your repo type? Do you have gnu find installed?

**Comment by pizzooid** [comment]
Had the same Problem you need to install [gnu findutils](http://gnuwin32.sourceforge.net/packages/findutils.htm) and put C:\Program Files (x86)\GnuWin32\bin at the **top** of your PATH variable. And then of course close emacs and start it again (no restart) to get the new PATH in emacs.

**Comment by jeeger** [comment]
A better fix for this would be using the value of the `find-program` variable in `projectile-generic-command`, this way, you can customize the find program that's used for all emacs find calls at once.
