### ISSUE TITLE
Error: helm-projectile-ag (void-variable grep-find-ignored-files)

### ISSUE THREAD

**Issue by nomosyn** [bbatsov/projectile#830]
`Projectile version: 20150728.2141`

Calling `helm-projectile-ag` leads to:
```
Debugger entered--Lisp error: (void-variable grep-find-ignored-files)
  helm-projectile-ag()
  call-interactively(helm-projectile-ag nil nil)
  command-execute(helm-projectile-ag)
```
Seems like `grep-find-ignored-files` is not correctly initialized.

Putting `(setq grep-find-ignored-files nil)` somewhere obviously solves that. 

More knowledgeable people may know what the `somewhere` should be (`defcustom` something like that maybe)

**Comment by mijoharas** [comment]
So I had a glance at this, inspecting `grep-find-ignored-files` on my machine gives:

```
grep-find-ignored-files is a variable defined in `grep.el'.
Its value is
(".#*" "*.cmti" "*.cmt" "*.annot" "*.cmi" "*.cmxa" "*.cma" "*.cmx" "*.cmo" "*.hi" "*.o" "*~" "*.bin" "*.lbin" "*.so" "*.a" "*.ln" "*.blg" "*.bbl" "*.elc" "*.lof" "*.glo" "*.idx" "*.lot" "*.fmt" "*.tfm" "*.class" "*.fas" "*.lib" "*.mem" "*.x86f" "*.sparcf" "*.dfsl" "*.pfsl" "*.d64fsl" "*.p64fsl" "*.lx64fsl" "*.lx32fsl" "*.dx64fsl" "*.dx32fsl" "*.fx64fsl" "*.fx32fsl" "*.sx64fsl" "*.sx32fsl" "*.wx64fsl" "*.wx32fsl" "*.fasl" "*.ufsl" "*.fsl" "*.dxl" "*.lo" "*.la" "*.gmo" "*.mo" "*.toc" "*.aux" "*.cp" "*.fn" "*.ky" "*.pg" "*.tp" "*.vr" "*.cps" "*.fns" "*.kys" "*.pgs" "*.tps" "*.vrs" "*.pyc" "*.pyo")


Documentation:
List of file names which `rgrep' and `lgrep' shall exclude.
If an element is a cons cell, the car is called on the search directory
to determine whether cdr should not be excluded.
```

`grep.el` appears to be part of normal emacs for me. I have it at:

```
/usr/share/emacs/24.5/lisp/cedet/semantic/symref/grep.el.gz
/usr/share/emacs/24.5/lisp/cedet/semantic/symref/grep.elc
/usr/share/emacs/24.5/lisp/progmodes/grep.el.gz
/usr/share/emacs/24.5/lisp/progmodes/grep.elc
```

**Comment by nomosyn** [comment]
well, yes: adding `(require 'grep)` did the trick for me.
I cannot see why it works for you, not for me.
Here is my [emacs.d](https://github.com/nomosyn/emacs.d)

Well, I guess this issue is closed then!

**Comment by mijoharas** [comment]
It's kind of weird. I don't know why it wouldn't be loaded for you by default. I suppose projectile should `(require 'grep)` if there's a chance that it can't be required already. You should reopen this issue and see about adding that line.

**Comment by nomosyn** [comment]
Well, there is not a single `(require _)` in the project.
I guess it's a way to make it self contained.
Maybe @bbatsov could give direction on this.

**Comment by goofansu** [comment]
+1 meet same problem

**Comment by gguimaraesbr** [comment]
+1

**Comment by correl** [comment]
I'm seeing this as well. `helm-projectile-ag` fails with this error, but `helm-projectile-grep` works fine, and seems to trigger `grep` getting loaded, as calls to `helm-projectile-ag` following a `helm-projectile-grep` succeed.

**Comment by microamp** [comment]
There does exist `(require 'grep)` under `helm-projectile-grep-or-ack` which is what `helm-projectile-grep` and `helm-projectile-ack` call under the hood.

It makes sense to include `(require 'grep)` under `helm-projectile-ag` as well. It's just odd that it wasn't happening before. Anyway, alternatively, we can have a single `(require 'grep)` where other `require`'s are (near the top of the file).

**Comment by alf** [comment]
This is probably related to [this commit](https://github.com/emacs-helm/helm/commit/81216449833dd0a28bf337bd423cec819c53c2e4) in helm.

**Comment by ejheil** [comment]
Same problem here.

**Comment by microamp** [comment]
For anyone blocked by this, I'd suggest using `helm-pt` in the meantime. It supports Projectile under the hood. It's `pt`, the Platinum Searcher, written in Go, just as fast as `ag`. I actually find it slightly slower, but not by much, and is still _much_ faster than `ack` or `grep`.

**Comment by nomosyn** [comment]
:+1:
