### ISSUE TITLE
using TRAMP with /sudo:: fails, if projectile-global-mode is on

### ISSUE THREAD

**Issue by 2mc** [bbatsov/projectile#835]
If 

```
(projectile-global-mode t)
```

is on, then TRAMP

```
/sudo:: 
```

will fail. 

Further conditions to reproduce:
- enable projectile caching 
  
   (setq projectile-enable-caching t)
- setup a auth-source file (even an empty one will do) e.g.: 
  
    (setq auth-sources '((:source "~/authinfo.gpg")))

Description:

When typing:

```
 C-x C-f /sudo::
```

gpg will start to ask for the passphrase of the above mentioned auth-source file.
After entering the passphrase, we'll get the following approval in the Messages buffer:

```
 Decrypting ... authinfo.gpg...done
```

But then emacs starts to hang and you have to force to stop the issued find-files command by typing C-g.

This failure will not happen, if projectile-global-mode is disabled or if projectile caching is disabled.
However, if you have once disabled one of the above, proceeded with C-x C-f /sudo:: successfully and re-enable the before disabled again, then everything works as expected.

```
 So, in order to reproduce the issues, make sure to always restart emacs for testing.
```

**Comment by IvanMalison** [comment]
I have this issue as well

**Comment by spaceotter** [comment]
Can confirm this issue. It's really annoying when combined with prelude automatically reopening files as root! Open the wrong file and emacs is fubar'ed. Opening as root for everything you don't have write permission on is a bad idea imo anyway so I turned it off. Maybe as an intermediate: is there a way to just entirely disable projectile on remote systems?

**Comment by stardiviner** [comment]
I have this issue too.

**Comment by puffnfresh** [comment]
Hit this and updated Projectile - seems to work with master! :fireworks:

**Comment by spaceotter** [comment]
I updated to the latest, still having this problem.
```
Error during redisplay: (eval (format " ¶" (projectile-project-name))) signaled (quit)
QuitError during redisplay: (eval (format " ¶" (projectile-project-name))) signaled (quit)
```
I press C-g over and over because it freezes.

**Comment by spaceotter** [comment]
Setting the mode line to a fixed string helps, but (projectile-project-name) should not hang.

**Comment by 2mc** [comment]
Must confirm that after updating the problem is still there, just as described above at the initial report.

**Comment by seagle0128** [comment]
I have the same issue without .authinfo.gpg.
I am using Emacs 24.5 on Ubuntu 16.04.
My workaround:
`    
(add-hook 'text-mode-hook 'projectile-mode)
`

**Comment by bhrgunatha** [comment]
Yesterday I updated my packages - including projectile (0.14.0) - the package in installed in folder projectile-20160723.622.  Started to encounter this problem too. I can;t use sudo:// to open files.

emacs --version gives 24.5.1 - installed from the [arch repos](https://www.archlinux.org/packages/extra/x86_64/emacs/) 

seagle0128 's text-mode hook workaround is also working (thanks!)

**Comment by binarin** [comment]
Another workaround for .authinfo.gpp problem:

    (defun disable-delete-file-advice (orig-fun &rest args)
      (let ((was-active (and (ad-is-active 'delete-file)
                             (ad-deactivate 'delete-file))))
        (unwind-protect
            (apply orig-fun args)
          (when was-active (ad-activate 'delete-file)))))

     (advice-add 'epg-delete-output-file :around #'disable-delete-file-advice)

**Comment by tangxinfa** [comment]
Encounter this issue in emacs 27 today, in ibuffer, if `ibuffer-auto-mode` and
`projectile-mode` both enabled, `M-x /sudo::/` will freeze emacs until you kill sudo
process, a workaround is set `projectile-dynamic-mode-line` to `nil`.
