### ISSUE TITLE
Symbol's value as variable is void: helm-ff-mode-line-string

### ISSUE THREAD

**Issue by sometimesfood** [bbatsov/projectile#836]
When using helm 1.7.5, loading helm-projectile 0.12.0 produces the following error message:

    Symbol's value as variable is void: helm-ff-mode-line-string

This seems to be fixed by b29b9a3bfe8861f4bc53c749e2758845c0e56e2f.

However, so far there is no released version that contains this fix. Could you please push a release?

**Comment by jeaye** [comment]
I'm seeing this issue as well.

**Comment by jeaye** [comment]
I've resolved this by sourcing `melpa` instead of `melpa-stable`, @sometimesfood. Hopefully this lands in a stable version soon.

**Comment by sometimesfood** [comment]
@jeaye Thanks, I know that this is fixed in the current Git master and therefore in melpa. I should have been more clear in the original bug report. Of course using the melpa version is a perfectly suitable workaround until a stable version is released. :+1:

**Comment by camdez** [comment]
:+1: 

You can work around this with:

```elisp
(defvaralias 'helm-ff-mode-line-string 'helm-read-file-name-mode-line-string)
```

...but you'll likely just run into another issue:

```
(wrong-type-argument listp helm-find-files-actions)
```

**Comment by jwr** [comment]
Is a release planned anytime soon? I also ran into the same problem. Switching from melpa-stable to melpa isn't really an option, too many things break.

I have projectile+helm-projectile 0.12.0, helm-core 1.7.9.

**Comment by bbatsov** [comment]
Remind me about a release during the upcoming or next week. I've been crazy busy lately, but I'll try to find some time to do a release.

**Comment by sometimesfood** [comment]
@bbatsov Since you asked for a reminder:

https://www.youtube.com/watch?v=6S9ecXWCBCc

**Comment by jitendranair** [comment]
Hoping for the fix to arrive on melpa-stable soon.

**Comment by bbatsov** [comment]
Haven't forgotten about this - there are a few outstanding PRs I want to merge, before releasing 0.13 (e.g. the 4 newest or something like this).

**Comment by favadi** [comment]
I still have this error, can someone tells me how to workaround it?

**Comment by sometimesfood** [comment]
@favadi This is fixed in the git master, so if you can use the version in melpa instead of melpa-stable you should be ok.

If you absolutely can't use the unstable version you'll have to wait until @bbatsov releases a new stable version.

**Comment by bbatsov** [comment]
The stable version was released last week.

On 27 October 2015 at 12:41, Sebastian Boehm <notifications@github.com>
wrote:

> @favadi <https://github.com/favadi> This is fixed in the git master, so
> if you can use the version in melpa instead of melpa-stable you should be
> ok.
>
> If you absolutely can't use the unstable version you'll have to wait until
> @bbatsov <https://github.com/bbatsov> releases a new stable version.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bbatsov/projectile/issues/836#issuecomment-151452172>.
>



-- 
Best Regards,
Bozhidar Batsov

http://www.batsov.com

**Comment by sometimesfood** [comment]
@bbatsov Sorry, my bad. Thanks a lot for a great new release!

@favadi If you are still having problems try removing both projectile, helm and helm-projectile manually before upgrading to the new packages.
