### ISSUE TITLE
Projectile-ag runs fine on Windows, but Helm-projectile-ag doesn't run? 

### ISSUE THREAD

**Issue by ReneFroger** [bbatsov/projectile#837]
## Setup:
GNU Emacs GUI version 24.4.51.1 (x86_64-w64-mingw32) 
[Compiled from Harroogan Emacs.](https://bitbucket.org/Haroogan/emacs-for-windows/)
Projectile, using the latest version of Projectile from MELPA
Helm-projectile, using the latest version of Helm-Projectile from MELPA
Windows 7 x64 bit.

## Situation:
Earlier it worked fine in my Emacs setup. But my Emacs configuration was such a huge mess. I decided to start again with a brand new configuration. 

When I do `projectile-ag` and type my input, it runs fine, I get results.

When I call `helm-projectile-ag`, I get the following message:

    funcall-interactively: Symbol's value as variable is void: grep-find-ignored-files

Earlier `helm-projectile-ag` ran fine on my Windows. I'm not sure what to do with this. Any search on the internet on this message didn't gives me any results.

Any suggestion?

**Comment by andschwa** [comment]
I'm running into this as well on OS X.

**Comment by andschwa** [comment]
This probably needs to be fixed in [Helm](https://github.com/emacs-helm/helm/wiki#grep) itself, but if you declare the variable yourself the problem goes away.

```elisp
(setq grep-find-ignored-files nil)
```

**Comment by andschwa** [comment]
Nevermind, now I can't repro my fix. Grr.

**Comment by andschwa** [comment]
Workaround for now (actually can repro this fix):

```elisp
(setq grep-find-ignored-files nil
      grep-find-ignored-directories nil)
```

`helm-projectile` needs to check if they're defined before using them, and if not, either skip the use or define them. I'm not sure what is supposed to define them originally.

**Comment by ReneFroger** [comment]
@andschwa Andy, thanks for solving my issue. I'm wondering the same as you, I'm puzzled why @bbatsov decides to define them originally. At least I know that this bug didn't appeared in the earlier versions of helm-projectile.

**Comment by bbatsov** [comment]
> I'm puzzled why @bbatsov decided to define them originally.

I didn't. I don't really use `helm-projectile` and it's development is fuelled mostly by other contributors.
