### ISSUE TITLE
The actions in `helm-source-projectile-projects` that again use helm ought to be wrapped in `helm-run-after-quit`

### ISSUE THREAD

**Issue by IvanMalison** [bbatsov/projectile#839]
The issue described in https://github.com/emacs-helm/helm/issues/1084 afflicts the selection of a custom action.

I suppose the only actions that can actually currently do this is the "Switch to project" (assuming that the default action uses helm) and `helm-find-files-grep`. The latter of these seems to copy the solution of `helm-run-after-quit` (which is, in my opinion a pretty bad one). However, if the solution there is ever fixed, `helm-find-files-grep` would stand to benefit if it were appropriately wrapped with `helm-run-after-quit`.

**Comment by bbatsov** [comment]
Submit this ticket to the helm-projectile project https://github.com/bbatsov/helm-projectile
