### ISSUE TITLE
projectile-tags-command is not getting any values. 

### ISSUE THREAD

**Issue by ReneFroger** [bbatsov/projectile#841]
With the package `projectile`, I use `projectile-regenate-tags`. At the name already says, it regenates the TAGS-table of the current project on the project root.

It works likke a charm. However, I noticed not all files are included, the files with `.inc`-extension. I would make it so.

A good command for this could be the following:

    ctags -f TAGS -e -R --langmap=php:+.inc.foo.bar --list-maps=php

I would like that `projectile-regenate-tags` use these parameters. When looking up the source code of `projectile-regenate-tags`, I found the following:

    (defun projectile-regenerate-tags ()
    "Regenerate the project's [e|g]tags."
    (interactive)
    (if (boundp 'ggtags-mode)
        (progn
            (let* ((ggtags-project-root (projectile-project-root))
                (default-directory ggtags-project-root))
            (ggtags-ensure-project)
            (ggtags-update-tags t)))
        (let* ((project-root (projectile-project-root))
            (tags-exclude (projectile-tags-exclude-patterns))
            (default-directory project-root)
            (tags-file (expand-file-name projectile-tags-file-name))
            (command (format projectile-tags-command tags-file tags-exclude))
            shell-output exit-code)
        (with-temp-buffer
            (setq exit-code
                (call-process-shell-command command nil (current-buffer))
                shell-output (projectile-trim-string
                                (buffer-substring (point-min) (point-max)))))
        (unless (zerop exit-code)
            (error shell-output))
        (visit-tags-table tags-file))))

Aha, then look up what `projectile-tags-command` consists of. 

    (defcustom projectile-tags-command "ctags -Re -f \"%s\" %s"
    "The command Projectile's going to use to generate a TAGS file."
    :group 'projectile
    :type 'string)

So in my `init.el`, I setted the variable `projectile-tags-command` to the following:

    (setq projectile-tags-command "ctags -Re -f \"%s\" %s --langmap=php:+.inc.foo.bar --list-maps=php")

Evaluated it, and calling `projectile-regenate-tags`, I still don't get any relevant files with the extension `.inc`. So perhaps Projectile is not getting he value of setted variable `projectile-tags-command`. 

Any suggestion to do in order to debug this?

**Comment by fommil** [comment]
put your custom parameters to `ctags` in a `.ctags` file at the root of your project (or your home directory if global). Vote to close.

**Comment by ReneFroger** [comment]
I'm suprised I got an answer on this nearly a half year later. Thanks for your reply. However, I couldn't figure out what I exactly need to put in the `.ctags` file?

**Comment by fommil** [comment]
Have a look at my dotfiles project on github for how I do this. It's reasonably well documented in `man ctags`

**Comment by fommil** [comment]
https://github.com/fommil/dotfiles/blob/master/.ctags

This is needed for any language that isn't supported by default. BTW, I use exuberant-ctags not the etags that came with Emacs.
