### ISSUE TITLE
helm-projectile-ag yields too many results when query includes space characters

### ISSUE THREAD

**Issue by angrybakon** [bbatsov/projectile#843]
Looks like it is performing an OR on tokens, but even then I still don't understand those results:

![screen shot 2015-08-13 at 10 50 17](https://cloud.githubusercontent.com/assets/5608624/9246139/ca544fec-41a9-11e5-8b89-39a1af74844f.png)
![screen shot 2015-08-13 at 10 50 22](https://cloud.githubusercontent.com/assets/5608624/9246141/d038b286-41a9-11e5-84c5-fdb615eea128.png)

Does anyone else experience this behavior? I have this issue for quite some time now.

**Comment by syohex** [comment]
Which ag version do you use ? Old ag has issue about OR pattern. Please upgrade ag and retry if possible.

**Comment by angrybakon** [comment]
I was using ag 0.27.0.

Even though it worked in the past, upgrading to 0.30.0 worked for me, thanks :).
