### ISSUE TITLE
helm-projectile-find-file is extremely slow with long strings in a large project

### ISSUE THREAD

**Issue by Nephyrin** [bbatsov/projectile#844]
I am working with a project that has 200k+ files. Pulling up `helm-projectile-find-file` and searching for a file with a 13-character string takes 10+ seconds, seemingly exponential per additional character added. However, even with `projectile-completion-system 'helm`, `projectile-find-file` is nearly instant on the same search.

**Comment by rymndhng** [comment]
I find it helps to disable `helm-projectile-fuzzy-match`.

**Comment by Nephyrin** [comment]
Good call -- disabling `helm-projectile-fuzzy-match` is a good workaround for me, and explains the difference between the stock command and the helm command.
