### ISSUE TITLE
failing to create Dired buffer from files via Virtual directory manager (helm-projectile)

### ISSUE THREAD

**Issue by oracleyue** [bbatsov/projectile#845]
It is my first time to learn to use projectile + helm-projectile. However, I couldn't manage to create Dired buffer from files by "virtual directory manager", as in http://tuhdo.github.io/helm-projectile.html (**a perfect tutorial!** by @tuhdo )

**Could someone please check or confirm this problem/bug?** Is it possible to fix by configurations? Thanks a lot!

Here is my procedure to create a buffer for "virtual directory manager":
1. `C-c p f` (`helm-projectile-find-file`) to find file via helm, mark files:
<img width="722" alt="screen shot 2015-08-15 at 22 07 00" src="https://cloud.githubusercontent.com/assets/5046605/9290662/466c4d76-439b-11e5-9317-583da9a659a4.png">
2. `C-c f` to create a Dired buffer for "virtual directory manager". Unfortunately, **only one file is added in the buffer**. Most times in other tests, there is no entry in the buffer.
<img width="727" alt="screen shot 2015-08-15 at 22 07 23" src="https://cloud.githubusercontent.com/assets/5046605/9290666/aa8d29f6-439b-11e5-8a5b-364768d7ed01.png">
3.  `C-c a` to add files in the Dired buffer of "virtual directory manager", which works well. However, **there is a bug in alignment.**
<img width="732" alt="screen shot 2015-08-15 at 22 08 14" src="https://cloud.githubusercontent.com/assets/5046605/9290678/ddca82f0-439b-11e5-9ea4-483915ee7299.png">

### Version:
Emacs: 24.4.1
Helm: 20150815
Helm-projectile: 20150731
Projectile:20150807

### Configuration:
```elisp
(projectile-global-mode)
(setq projectile-completion-system 'helm)
(helm-projectile-on)
(setq projectile-switch-project-action 'helm-projectile)
```

**Comment by xuchunyang** [comment]
You have to disable `helm-mode` while using this feature (i.e., `C-p f <mark some files> C-c f`) because the `C-c f` (almost `helm-projectile-dired-files-new-action`) calls `completing-read` within itself, and at this time, if `helm-mode` is enabled, the old marked files information will be overrode/cleared (I guess), `C-c a` should have the same problem.  IMO, it should be considered as a bug.

**Comment by oracleyue** [comment]
@xuchunyang Thanks a lot! Yes, you are right! When I disable `helm` globally, it works well. However, I use `helm` a lot. 
Is there a way to fix it by configuration (e.g. disable helm temporarily, or disable small features in helm when using helm-projectile) when I use `helm-projectile`? I will make a try using my poor elisp knowledge :-D.

**Comment by oracleyue** [comment]
Confirm that it has been fixed by @xuchunyang patch.
Thanks a lot for your patch!
