### ISSUE TITLE
Ability to add a custom Project name? 

### ISSUE THREAD

**Issue by ReneFroger** [bbatsov/projectile#848]
I use Yasnippet in pair with Projectile. Is there any way to prefer custom project names above the current project names? 

For example in this Yasnippet: 

    #include <iostream>

    int main () {
    try  {
    }
    catch (int e)  {
            cout << "The `(buffer-name)` from `(project-name)`) encountered an error. Exception Nr. " << e << '\n';
        }
    return 0;
    }
   
Sometimes a project does have a unclear name, e.g. ws_project_fooBAR12. So I get unclear snippets. Is it possible to have any ability in Projectile to define custom project names?

**Comment by glucas** [comment]
+1, I have some projects for which I'd like to have a more meaningful name without having to change my directory structure.

**Comment by EHartC** [comment]
You could easily create your own function for that, e.g:

    (defun my-own-project-name ()
    ;; Checks if Projectile is currently active, or this will once run into undefinable errors.
    (when (featurep 'projectile)
        ;; Checks if the file ".custom-project-name" is currently located in the project root. 
        (if (file-exists-p (concat (expand-file-name (projectile-project-root)) ".custom-project-name"))
            ;; If that's the case, write their contents into the buffer. 
            (with-temp-buffer
            (insert-file-contents (concat (expand-file-name (projectile-project-root)) ".custom-project-name"))
            (buffer-string))
        ;; If not, then extract the projectname.
        (replace-regexp-in-string "/proj/\\(.*?\\)/.*"
                                    "\\1"
                                    (projectile-project-name)))))

After evaluating the function above, create the file `.custom-name`, which contains your own projectname and located in the current project root. If that file doesn't exist (yet), it will use the current projectname instead.

**Comment by glucas** [comment]
Thanks for the suggestion, but it looks at least a bit more involved than that.

In addition to replacing (with advice, I guess) the default implementation of `projectile-project-name` with a function like what the one suggested, it looks like there are a number of places where projectile assumes the project name is actually a directory path and uses it that way -- lots of functions that let-bind `default-directory` to the project name.

**Comment by bbatsov** [comment]
The best way to implement this functionality would be simply to augment the existing project tracking. Basically there should be some function which allows you to name a project and it will be saved in the list of known projects as name + folder. All the code dealing with known projects should be updated to reflect this as well. Not a lot of work, but as usual - I'm pretty low on free time.

**Comment by dustinpaluch** [comment]
+1. I work on WordPress websites, and the convention at my company is to use wp-content as the git root directory, so regardless of the project I'm working on, my mode line always says `Projectile[wp-content]`, which isn't very helpful.

**Comment by ReneFroger** [comment]
Any update on this?

**Comment by bbatsov** [comment]
See https://github.com/bbatsov/projectile/pull/928
