### ISSUE TITLE
remove perspective when removing project

### ISSUE THREAD

**Issue by blaenk** [bbatsov/projectile#849]
I'm not sure how exactly to remove a project from my emacs instance, meaning I want to remove the perspective and kill all of the project's associated buffers, which is probably implicit in the former. I tried `projectile-remove-known-project` but it doesn't seem to kill every buffer associated with its perspective, so perhaps it'd be nice if that function ran `persp-kill` as well or something? Not sure.

**Comment by bbatsov** [comment]
The perspective support now lives here https://github.com/bbatsov/persp-projectile
