### ISSUE TITLE
Idea: instead of showing "You're not in a project", it can instead trigger projectile-switch-project

### ISSUE THREAD

**Issue by robert-stuttaford** [bbatsov/projectile#850]
I'll often be in a scratch buffer or similar and want to open a file, and I keep having to butt my head against this warning and then do switch-project anyway.

**Comment by offby1** [comment]
+1

**Comment by bbatsov** [comment]
Guess we have the message prompt you for the next action (switch to project) or make this configurable. I'm fine with changing the existing behavior.

**Comment by arichiardi** [comment]
+1
