### ISSUE TITLE
projectile-switch-project-action with use-package

### ISSUE THREAD

**Issue by floli** [bbatsov/projectile#851]
I use use-package for package configuration
```
(use-package projectile
  :ensure t
  :config (progn
            (projectile-global-mode)
            (setq projectile-switch-project-action 'projectile-vc)
))
```
but the variable assignment is simply ignored. The variable retains the 
original value. I have tried variations of that like putting setq before the 
activaction or put in the iniit section, which is executed before the 
package load.

What is the right way? Why that?

**Comment by bbatsov** [comment]
No idea. I've never used `use-package`.

**Comment by codeitagile** [comment]
I had the same issue @floli, setting the variable elsewhere was my work-around. 

As a `helm` user, the following seemed sensible place to put the config: 

```emacs-lisp
    (use-package helm-projectile
      :ensure    helm-projectile
      :config
      (progn
        (setq projectile-switch-project-action 'projectile-dired)
        (setq projectile-completion-system 'helm)))
```

**Comment by floli** [comment]
I think helm-projectile is the cause of that issue. ```helm-projectile-toggle``` does a ```(setq projectile-switch-project-action #'helm-projectile-find-file)``` and thus resets the default actions if set before calling  ``` (helm-projectile-on)```.
