### ISSUE TITLE
helm-projectile is changing helm-buffer-max-length when that is set to nil

### ISSUE THREAD

**Issue by el-lute** [bbatsov/projectile#853]
Hello,

I'm using GNU Emacs (25.0.50) with helm (20150901.833 from MELPA) and configured:

  (setq helm-buffer-max-length nil)

so buffer names are not truncated.

I recently started using projectile (20150831.1127 from MELPA) with helm-projectile (20150831.1127 from MELPA).  I noticed that after I use the command helm-projectile for the first time in an Emacs session, helm-buffer-max-length is set to an integer value.  Thus causing truncation of long buffer names.  

Could you change helm-projectile so it does not change helm-buffer-max-length when that is set to nil?

Best regards,

  Eleuterio Sánchez

**Comment by chalmagean** [comment]
+1

**Comment by chalmagean** [comment]
@el-lute you could try adding this to your init file:

```elisp
(with-eval-after-load 'helm-projectile
  (setq helm-buffer-max-length nil))
```

**Comment by bbatsov** [comment]
Submit this ticket to the helm-projectile project https://github.com/bbatsov/helm-projectile

**Comment by el-lute** [comment]
@chalmagean Thanks, that worked.
