### ISSUE TITLE
[request] Add GTAGS as a file marking project root.

### ISSUE THREAD

**Issue by Fuco1** [bbatsov/projectile#861]
Anyone has some idea when this might not be appropriate?  I always keep my tags in the root.

**Comment by bbatsov** [comment]
Guess the same might apply for just TAGS as well.

**Comment by Fuco1** [comment]
Oh, right.  I usually use GNU global so I don't know how the other taggers name their files. maybe `*TAGS`? :P

**Comment by Fuco1** [comment]
Thanks!
