### ISSUE TITLE
Determining root in nested VCSs is incorrectly handled

### ISSUE THREAD

**Issue by Fuco1** [bbatsov/projectile#862]
I have my `~` under `.git`.  I have `~/dev/` where I keep my projects.  I have an svn project inside `~/dev/php/foo`.  When I am inside `foo/bar` my project root is reported as `~` instead of `~/dev/php/foo/`.  I am using the old-style svn layout with `.svn` in every directory.

**Comment by Pitometsu** [comment]
Looks like you need to change `projectile-project-root-files-functions`. Not yet sure how yet, I'm stuck with similar problem.

**Comment by Pitometsu** [comment]
Or customize `projectile-project-root-files-bottom-up` by adding `.svn`…

**Comment by bbatsov** [comment]
@Fuco1 Sorry about the extremely slow reply - basically the problem is the order in which the vc checks are happening. The ones looking for top-level files happen first, so you need to reorder the root functions as suggested by @Pitometsu. 

> I am using the old-style svn layout with .svn in every directory.

What's the new one, btw?

**Comment by Fuco1** [comment]
Newer versions of svn have one `.svn` in the root of the project same as `.git`.

Wouldn't a good strategy be to get all the functions return whatever they think and then get the most-nested path?  I can't think of a counter-example now where this would not be what I want.

**Comment by Pitometsu** [comment]
I have
```elisp
 '(projectile-project-root-files-functions
   (quote
    (projectile-root-local projectile-root-top-down projectile-root-bottom-up projectile-root-top-down-recurring)))
```
as personal setup.

**Comment by clawoflight** [comment]
I have my home in git and would like to be able to still use nested projects correctly.
For my use-case, it might be enough to not recurse higher, despite finding .git there, if the current folder is ignored in the level above?
