### ISSUE TITLE
Projectile is clearing other advices for compilation-find-file

### ISSUE THREAD

**Issue by caioaao** [bbatsov/projectile#871]
I have the following advice for the compilation-find-file:
```
(advice-add 'compilation-find-file  :around
              (lambda (oldfun &rest args)
                (destructuring-bind
                    (marker filename directory &rest formats) args
                  (apply oldfun marker
                         (w32utils-expand-subst filename)
                         (w32utils-expand-subst directory)
                         formats))))
```
All it does is expanding the path when I'm in Windows and using subst (more about it [here](https://www.microsoft.com/resources/documentation/windows/xp/all/proddocs/en-us/subst.mspx)), but when i have `projectile-mode` enabled in compilation directory, this advice is not being called. I'm a newbie on advising functions, but it looks like the way projectile does it's own advising breaks the other advices for this function. I've also read on [Emacs Lisp Reference](https://www.gnu.org/software/emacs/manual/html_node/elisp/Porting-old-advices.html#Porting-old-advices) is obsolete. Could this error be related to some compatibility issues between `defadvice` and `advice-add`?

**Comment by bbatsov** [comment]
I was under the impression you can have multiple advices for the same command. `advice-add` was added just recently and we can't leverage it in Projectile just yet.

**Comment by caioaao** [comment]
You can, but since the projectile advices apparently overrides the `find-file` / `compilation-find-file` implementations (sometimes it doesn't call `ad-do-it`), the other advices may have no effect.

**Comment by caioaao** [comment]
[This patch](https://github.com/caioaao/projectile/commit/e7f96c6e901d23af20e2088610e96c2ec0ebcc42) seems to have fixed it, but I couldn't make cask work in Windows. I'll try running the tests later today and create the PR if successful.
