### ISSUE TITLE
How to find files which isn't in repository?

### ISSUE THREAD

**Issue by yoihito** [bbatsov/projectile#876]
I started to use spacemacs for development. I can't open config files in my rails project, for example database.yml. I didn't put database.yml to git repository. How can I open config files with projectile? helm-projectile-find-file doesn't see such files.

**Comment by TheSeldonPlan** [comment]
Create a `.projectile` file and use native indexing. 

``` elisp
(setq projectile-indexing-method 'native)
```

Consult the [README](https://github.com/bbatsov/projectile#ignoring-files) for how to write the `.projectile` file.
