### ISSUE TITLE
How to "un-ignore" files from .gitignore

### ISSUE THREAD

**Issue by aiguofer** [bbatsov/projectile#892]
I have a few files that are part of my project but not part of the git repo (node_modules and some local config files). Is there a way to re-include these files into my projectile project?

**Comment by bbatsov** [comment]
Unfortunately there's nothing right now, although we can certain add support for such functionality down the line.

**Comment by aiguofer** [comment]
that would be awesome! feature request please? :)

**Comment by jwalton512** [comment]
agreed, this would be a great feature

**Comment by lionel-** [comment]
yup, totally need this

**Comment by aiguofer** [comment]
This is working great for me. Thanks a lot!!
