### ISSUE TITLE
Easy way to add a project without opening a file in that project

### ISSUE THREAD

**Issue by lethjakman** [bbatsov/projectile#895]
I think it'd be nice to have an easy way to add a project without opening a file in said project. That way it's easy to use something like perspective to switch to that project.

**Comment by pheaver** [comment]
I also would like to be able to configure the list of projects in elisp. Maybe a quick solution would be to list all .projectile files and automatically open them, which would enable each project?

**Comment by pheaver** [comment]
@lethjakman Actually i just discovered `projectile-known-projects-file`, which contains a list of all known projects. That sounds like what we want.

**Comment by bbatsov** [comment]
Just use `M-x projectile-add-known-project`. It will prompt you for the name of the project to add.
