### ISSUE TITLE
Cycle through current project's buffer's only

### ISSUE THREAD

**Issue by tonycpsu** [bbatsov/projectile#896]
Is there a way to cycle through buffers like with next-buffer/previous-buffer but limited only to buffers associated with the current project?  If not, this would be great -- perhaps projectile could add [buffer ring](http://www.emacswiki.org/emacs/BufferRing) integration to achieve this?

**Comment by bbatsov** [comment]
There's already a command that returns the list of project buffers, so implementing something like next-project-buffer should be trivial.
