### ISSUE TITLE
Ag search output looks noisy and makes difficult to read the results

### ISSUE THREAD

**Issue by mkaschenko** [bbatsov/projectile#897]
The 'ag' command includes 'ignore' option which is quite long. 
If a few buffers are open in the same time it's uncomfortable to see the results.
<img width="1440" alt="screen shot 2015-10-30 at 22 15 07" src="https://cloud.githubusercontent.com/assets/130269/10847828/b392364c-7f53-11e5-8032-68461fb85f57.png">

**Comment by ryankask** [comment]
I've recently noticed this as well.

It appears to be related to this change: https://github.com/bbatsov/projectile/commit/6b5c0ab3b7a081e001192a6ff38e61c13812c219

An option to abbreviate or hide the ag command would be nice but that probably belongs here: https://github.com/Wilfred/ag.el

**Comment by mkaschenko** [comment]
I was thinking about folding the command by default.

**Comment by mkaschenko** [comment]
As suggested there https://github.com/Wilfred/ag.el/issues/99 `toggle-truncate-lines` may help.
```
(add-hook 'ag-mode-hook 'toggle-truncate-lines)
```

**Comment by bbatsov** [comment]
Seems to be outside the scope of Projectile.
