### ISSUE TITLE
Shell echo shows up in projectile-find-file

### ISSUE THREAD

**Issue by ccann** [bbatsov/projectile#902]
Apologies if this is a duplicate.

I use `fish` and I have my config set up so that whenever I open a new shell it `echo`s "Setting Docker host...". For some reason this shows up as a directory (I think) in the output when I invoke `projectile-find-file`.

<img width="313" alt="screen shot 2015-11-08 at 2 01 15 pm" src="https://cloud.githubusercontent.com/assets/2650566/11022072/92b78900-8623-11e5-860e-890c4f332ba3.png">

I worked around the issue by removing the `echo`, but seems like a bug, no? Thank you! Let me know if I can provide more info.

**Comment by bbatsov** [comment]
Projectile invokes some shell commands behind the scenes, so this might be the cause of your issue. However, it seems odd to me that the Elisp shelling-out command would spin new shells every time. This has to be investigated in greater detail.

**Comment by ccann** [comment]
I don't think it's related but I'm using https://github.com/purcell/exec-path-from-shell in [my config](https://github.com/ccann/emacs/blob/master/init.el) in case it is
