### ISSUE TITLE
Init-time-only customization consistently bites users' ankles. Look at my ankle. LOOK.

### ISSUE THREAD

**Issue by Fabricationatorishnicatorist** [bbatsov/projectile#903]
This has been annoying me in various ways for months.

Today, I'd like to override `projectile-project-test-cmd` by changing the value of the variable, in fact I'd like to toggle it between a few  alternatives while I'm working.

Projectile provides a nice hook for me to override but then proceeds to ignore the changes I make. This is well documented behavior, the docstring warns me that:

```
[this] Should be set via .dir-locals.el.
```

... but I just don't understand why Projectile chooses to do things this way.

Why can't I customize a variable by setting its value, the way I do in every other emacs package?

**Comment by Fabricationatorishnicatorist** [comment]
@bbatsov, why does projectile ignore customizations?

**Comment by bbatsov** [comment]
It simply doesn't make sense to set this globally. It's meaningful only in the context of a project. There are different commands for different project types, but if someone wants to use an alternative commands this exists as an easy configuration option.

**Comment by bbatsov** [comment]
> @bbatsov, why does projectile ignore customizations?

It doesn't.

**Comment by Fabricationatorishnicatorist** [comment]
I assumed it was buffer-local. Ok, then how do I change the setting for a loaded project?

**Comment by Fabricationatorishnicatorist** [comment]
@bbatsov, I have a loaded project and I want to change the value of a cider var for a buffer temporarily. Projectile ignores `(setq projectile-foo 'bar)`. 

If not that way, how?

**Comment by bbatsov** [comment]
The easiest way to reload dir-locals is to just close and open some buffer and they'll be reloaded for it. I assume the code you mentioned in the context of the right buffer should work just fine as well.
