### ISSUE TITLE
Project name, global variables, root project dir, file types including

### ISSUE THREAD

**Issue by CybGen** [bbatsov/projectile#904]
Hi, just a few ideas and issues:

##### Could you add feature to define project name, lets say into .projectile file for example? Like 

-/binaries
project name: "myproject"
-/\*.exe
-/\*.bin
....

##### And some global definitions for c/c++ coding into .projectile file like:

#define MY_VAR
#define DEBUG
etc...

##### Another issue but a bit smaller I've tried to describe here http://emacs.stackexchange.com/questions/17976/projectile-how-to-work-with-multiple-projects-and-builds 
Basically, if you have the same root directory for 2 or more projects you cannot divide sources from one project and other project in one opened .projectile instance.
For example you have dirs like:

/CommSystem/common
/CommSystem/common/src
/CommSystem/common/inc
/CommSystem/TX
/CommSystem/TX/build
/CommSystem/TX/src
/CommSystem/TX/inc
/CommSystem/RX
/CommSystem/RX/build
/CommSystem/RX/src
/CommSystem/RX/inc

As you see a global project CommSystem have two projects for transmitter(TX) and receiver(RX) and they both share some files in "common" dir. So you have to put .projectile file to /CommSystem but you'll have to work with all source files simultaneously what is not good if you have hundreds of files in both projects.

The probable solution could be to create some another files in /CommSystem like mytargetTX.projectile and mytargetRX.projectile and define what you want to include or exclude in these files and put some reference to .projectile about it.

##### Could you add a possibility to include file types to .projectile, like if you want to include just some directory you do: +/mydir/inc but could you do the same with file types? Like 
+/\*.cpp
+/\*.c
+/\*.h
and all other files will be excluded.
Thanks.

**Comment by bbatsov** [comment]
I'm not opposed to something like this, but I don't intend to ever work on it. My strategy is to allow similar customisations mostly via `.dir-locals.el`.
