### ISSUE TITLE
Ability to run custom elisp code for run / test / compile actions?

### ISSUE THREAD

**Issue by maximvl** [bbatsov/projectile#907]
Hi, I'm an Erlang developer and my workflow with Emacs is usually to connect to remote Erlang node and work with it's repl. I would like to run this repl from `projectile-run-project` command, but now it accepts only strings to run with `compilation-start`.

It seems to me, that checking the type of `project-run-command`, and if it is a symbol - make a funcall of it can be a nice solution. What do you think?

**Comment by bbatsov** [comment]
Yeah, seems reasonable. We're already doing something similar with project root detection code (as you can pass either a list or a symbol there).

**Comment by maximvl** [comment]
Ok, great, my pull request is here: #908
