### ISSUE TITLE
support for etags-select

### ISSUE THREAD

**Issue by fommil** [bbatsov/projectile#910]
I recently discovered etags-select, which is the best way yet that I've seen to search etags without installing a large framework like helm.

I've found that the following is enough to get the support integrated with the tag table built by projectile, incase anybody wants to do similar:

```elisp
(defun projectile-etags-select-find-tag ()
  "Run `etags-select-find-tag' in the current projectile context."
  (interactive)
  (projectile-visit-project-tags-table)
  (etags-select-find-tag))
```

of course it would be great if this was the default behaviour for `C-c p j`

**Comment by bbatsov** [comment]
PR welcome. :-0

**Comment by fommil** [comment]
would you be happy for me to remove the current implementation and add this (tiny) dependency?

The current find-tags is very broken https://github.com/bbatsov/projectile/issues/683 https://github.com/bbatsov/projectile/issues/668 and there are a lot of other issues too https://github.com/bbatsov/projectile/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+tag
