### ISSUE TITLE
helm-projectile-ag uses a deprecated history variable !?

### ISSUE THREAD

**Issue by edurante** [bbatsov/projectile#914]
Hi

helm-projectile-ag is referencing a wrong history variable !?

Looking at the package helm-ag.el, helm-ag-command-history is not defined and seems to be replaced
by helm-ag--command-history.
  
Thanks for this great package

Ernesto

**Comment by syohex** [comment]
Hi, I'm author of helm-ag. I suppose `helm-ag--extra-options` is better than `helm-ag--command-history` in this case. I sent PR #915. Please check it.
