### ISSUE TITLE
Add relation between `cxx` and `h` files.

### ISSUE THREAD

**Issue by StreakyCobra** [bbatsov/projectile#918]
A spacemacs user reported in https://github.com/syl20bnr/spacemacs/issues/3480 that he wants `.cxx` files to be associated with `.h` headers, and vice-versa. I'm not used to C/C++ development so I don't know if it make sense or not to do it in general.

The lines related to this issue: https://github.com/bbatsov/projectile/blob/master/projectile.el#L1216-L1229

Does this has any chance to be merged in `projectile`? If yes I can make a PR if needed, if not you can freely close this issue, we will just document it on our side :smile:

**Comment by bbatsov** [comment]
PR welcome.

**Comment by StreakyCobra** [comment]
PR: #934
