### ISSUE TITLE
Projectile won't ignore anything, shows all files at all times

### ISSUE THREAD

**Issue by imfranklin** [bbatsov/projectile#92]
In Emacs 24.2, 24.3, or recent source build on Mac OS X with latest projectile.el I am unable to have any files ignored. Have tried `projectile-use-native-indexing` set to `t` or `nil`, in a git repository or a testing project with a `.projectile` file containing simply "-*.txt" (without quotes, of course). No matter what, when invoking `projectile-find-file` I am presented with everything git is ignoring and everything listed for ignoring in my `.projectile`.

The projectile-related portion of my init.el:

```
(require 'projectile)
(setq projectile-use-native-indexing t)
(setq projectile-enable-caching t)
```

Is there something I'm not doing right? I've also tried adding `(setq projectile-globally-ignored-files (append '("*.txt" "*.o" "*.so") projectile-globally-ignored-files))` to my init.el, have invalidated project cache and reindexed numerous times, with no luck.

**Comment by blak3mill3r** [comment]
I cannot get projectile to ignore any files. I have tried every method in these comments and I've not been able to get it to ignore any file.

    (setq projectile-globally-ignored-files '( "TAGS" "*.txt" " *.~undo-tree~ " ))

does nothing, and adding a `.projectile` file does nothing

I tried the MELPA version and git master as of just now

If anyone has any ideas, I'd appreciate it. I would really like to use projectile but right now it is very frequently offering me undo-tree files and such.

**Comment by fommil** [comment]
actually its native indexing that breaks things for me on Windows... the `'alien` indexing takes `.gitignore` into account but native doesn't.

**Comment by philiparvidsson** [comment]
I don't see why this is closed - I still have this problem using native (projectile's own) indexing on Windows 10.

**Comment by et2010** [comment]
I'm having this issue on Linux using `alien` indexing. Neither `.projectile` nor `.gitignore` works

**Comment by williamJmelton** [comment]
I am having this problem as well on OSX High Sierra. I've tried using the customize interface, using ag, even switching my default completion engine to ivy and NOTHING works. It's very annoying to get results back from node_modules when searching through my projects.

**Comment by TPLinux** [comment]
I solved this problem by deleteing `~/.emacs.d/projectile.cache`

and add node_modules to ignored directories and to .gitignore

and it will works

**Comment by RodrigoLeiteF** [comment]
Make sure you're actually in a git repository. With the `alien` method, projectile runs `git ls-files -zco --exclude-standard` to figure out which files to show. Running that in the shell can help you narrow down where the issue lies.

**Comment by abbaswasim** [comment]
Looking at current documentation on this https://docs.projectile.mx/projectile/projects.html#ignoring-files. There is a warning saying: 

```
The contents of .projectile are ignored when using the alien project indexing method.
```

I struggled to read that for a while. I still read it as if the `.projectile` file is only read if using 'alien' method. which is the default. But I think it means that the .projectile file is ignore. If the 'contents' are ignored then the warning doesn't make sense. This is why I can't make it work.
