### ISSUE TITLE
/bin/bash not found when using TRAMP

### ISSUE THREAD

**Issue by dtreiter** [bbatsov/projectile#921]
When using projectile over TRAMP it seems to look for bash at `/bin/bash`. However, I have a remote machine where bash is located at `/usr/local/bin/bash`.

The error I'm seeing is `/bin/bash: not found` being displayed as the only file to choose from. If you choose it it tries to create a new buffer with that name.

Is there a variable I should set to specify that bash is located elsewhere?

**Comment by syohex** [comment]
> Is there a variable I should set to specify that bash is located elsewhere?

`shell-file-name`. You should set it as remote host name in some hooks like `find-file-hook` as below.

```lisp
(defun my/shell-set-hook ()
  (when (file-remote-p (buffer-file-name))
    (let ((vec (tramp-dissect-file-name (buffer-file-name))))
     ;; Please change "some-hostname" to your remote hostname
      (when (string-match-p "some-hostname" (tramp-file-name-host vec))
        (setq-local shell-file-name "/usr/local/bin/bash")))))

(add-hook 'find-file-hook #'my/shell-set-hook)
```
