### ISSUE TITLE
Not using helm faces properly?

### ISSUE THREAD

**Issue by it3ration** [bbatsov/projectile#922]
The `projectile-completing-read` method calls into helm via `helm-comp-read`, as strings, which causes all of helm's faces to be ignored:

`helm-ff-directory`
`helm-ff-dotted-directory` 
`helm-ff-dotted-symlink-directory` 
`helm-ff-executable` 
`helm-ff-file` 
`helm-ff-invalid-symlink` 
`helm-ff-prefix` 
`helm-ff-symlink`

I'm not sure if this is possible, but perhaps there is another method that could be used to populate the helm buffer so the context of all the strings (files / directories / etc.) is retained?

Best,
-Kevin

**Comment by bbatsov** [comment]
PR welcome. I don't use Heml anymore and I don't do any work on `helm-projectile` myself.

**Comment by it3ration** [comment]
Ok thanks, I'll see if I can't look for a fix. <3
