### ISSUE TITLE
grep file in project's specific directory

### ISSUE THREAD

**Issue by zhongweiy** [bbatsov/projectile#923]
Hi, is there any function that can do grep on files under specific directory in projectile?

**Comment by dpathakj** [comment]
With ag.el (probably also ack.el) this is possible by default; simply `M-x ag` and choose your directory. It's pre-filled by default.

**Comment by bbatsov** [comment]
You simply use `rgrep` or something like it.

**Comment by eRedekopp** [comment]
I wrote myself a little utility function that accomplishes this task a little more cleanly. Basically, it prompts for a directory using `read-directory-name`, then runs `rg` with a glob pattern matching only files in that directory automatically inserted into the arguments. Feel free to copy this function for your own purposes, but note that you'll have to change the ripgrep function name if you don't use counsel-projectile. 

Ignore my unusual indentation preferences, I'm just too Java-brained to parse regular Lisp code.

@bbatsov if you would like to add this function to projectile I'd be happy to submit a PR with this same logic but cleaned up a little bit and expanded to work with all 3 of grep, rg, and ag.

```
(defun my/counsel-projectile-rg-subdir ()
  "Prompt for a subdirectory, then run `counsel-projectile-rg' in it."
  (interactive)
  (let*
    (
     (project-root (projectile-project-root))
     (buffer-dir
      (if buffer-file-name
        (file-name-directory buffer-file-name)
        project-root
      )
     )
     (relative-dir
      (directory-file-name
       (file-relative-name
        (read-directory-name
         "grep in subdir: "
         buffer-dir
         nil
         t
        )
        project-root
       )
      )
     )
    )
    (counsel-projectile-rg (format "-g '%s/**/*' " relative-dir))
  )
)
```
