### ISSUE TITLE
Keeping track of last file associated with a project.

### ISSUE THREAD

**Issue by wusticality** [bbatsov/projectile#924]
Hey `bbatsov`,

If you open emacs on the terminal under a supported repo (say git or whatever), `default-directory` is set to that directory and becomes buffer-local for all new buffers, which causes `projectile-find-file` to succeed, even if you are not in a buffer belonging to a project (say, the _scratch_ buffer).  This is incredibly useful behavior; it's quite tedious to first navigate to a buffer that is associated with a project before running `projectile-find-file` (or to first navigate to the project, then to the buffer via `projectile-switch-project`).

This is really a feature request (or maybe I could try to code it up) - would it be possible to track the last buffer we were in that was associated with a projectile project, and to use that as the starting point to search for a project if `default-directory` ends up not resolving to a project?  This would be oh-so useful.

Thanks in advance!

Best,
-Kevin

**Comment by bbatsov** [comment]
We can certainly do this, but it seems to me it'd be a bit confusing for people not expecting such a behaviour.

**Comment by it3ration** [comment]
Perhaps it could be added and disabled by default, unless an option is set?
