### ISSUE TITLE
ignoring .git directory

### ISSUE THREAD

**Issue by incandescentman** [bbatsov/projectile#926]
I created a .projectile file and specified directories to ignore:

    -/.git
    -/emacs-pastebin-master
    -/archive

But `projectile-find-file` is still pulling up all the files in my .git directory.

**Comment by bbatsov** [comment]
You don't need ignore `.git` as it's globally ignored by Projectile when you're using caching and irrelevant otherwise - https://github.com/bbatsov/projectile/blob/master/projectile.el#L284
