### ISSUE TITLE
How to switch among "opened" projects?

### ISSUE THREAD

**Issue by lazywei** [bbatsov/projectile#927]
Hi,

I know I can use `projectile-switch-project` to list all projects I have worked on and switch between them.
However, I'm wondering if it is possible to have a function similar to this but only display projects that has file opened? For example, say I have 5 projects A, B, C, D, E. And I have opened two files for editing: a, which is contained in A, and b, which is contained in B.
Now, `projectile-switch-project` will show all 5 projects. And what I'd like to have is showing only A and B.

Is it possible?

Thanks.

**Comment by bbatsov** [comment]
It's possible, but it's not implemented yet. Add such functionality would be trivial - you just have to go through all open buffers and check if they are part of some project.

**Comment by lazywei** [comment]
awesome! thanks for your hard work!!
