### ISSUE TITLE
neewb question: bind a key for projectile find file to a specific project?

### ISSUE THREAD

**Issue by zeltak** [bbatsov/projectile#939]
Hi guys

i know this is probably super trivial , but how does one bind a key for projectile find file to a specific project?
for example i want C-c p 0 to start the projectile-find-file for the project under ~/org/

thx!

Z

**Comment by bbatsov** [comment]
You need to define some wrapper command like:

**Comment by zeltak** [comment]
thx so much!

i did try that but get the following error when i launch it:
```projectile-current-project-files: Wrong type argument: hash-table-p, nil```

i did add the (interactive) part so that it can appear in my M-x. this is the code:

```
(defun projectile-find-file-in-project-org ()
(interactive)                                
(let ((default-directory "/home/zeltak/org/files/"))
(projectile-find-file)))
```
even when i take out the interactive part i get an error when i bind to a key

```command-execute: Wrong type argument: commandp, projectile-find-file-in-project-org [2 times]```
                               
thx so much !

z
