### ISSUE TITLE
projectile-grep completion hook

### ISSUE THREAD

**Issue by fommil** [bbatsov/projectile#942]
It would be great if there was a hook that ran when a search finished.

In `ag` there is the possibility to do this, because such a hook exists

```elisp
(add-hook 'ag-search-finished-hook (lambda () (pop-to-buffer next-error-last-buffer)))
```

which jumps to the first search result.

**Comment by bbatsov** [comment]
That'd be trivial to add.

**Comment by fommil** [comment]
:smile:
