### ISSUE TITLE
projectile-shell command

### ISSUE THREAD

**Issue by jamienicol** [bbatsov/projectile#943]
I find it really useful having a command to open a shell in the root dir of a project, or if a shell is already open for the project, jump to it. I quickly threw this together and it works, though I'm no elisp expert so I'm sure it could be improved:

    (defun projectile-shell ()
      (interactive)
      (when (projectile-project-root)
        (let* ((default-directory (projectile-project-root))
               (buffer-name (format "*shell*<%s>" (projectile-project-name)))
               (buffer (or (get-buffer buffer-name)
                           (shell buffer-name))))
          (switch-to-buffer buffer))))

**Comment by Silex** [comment]
:+1: 

This could be later improved to support `eshell` and `term`, similar to like the search interface supports `grep` and `ag`.

**Comment by bbatsov** [comment]
This can be simplified using `projectile-with-default-dir`.

**Comment by bbatsov** [comment]
Fixed by #973.
