### ISSUE TITLE
allow specifying test file patterns when registering project types

### ISSUE THREAD

**Issue by yarray** [bbatsov/projectile#945]
First thanks for the awesome plugin.

I saw that e8b7b54449c645c764c928d7d1cfa29113230f05 enabled users to extend supported project type easily. Will it be a good idea that jumping to test/implementation files also follow similar mechanism? Currently the code handling this is:

``` elisp
(defun projectile-test-prefix (project-type)
  "Find default test files prefix based on PROJECT-TYPE."
  (cond
   ((member project-type '(django python-pip python-pkg python-tox)) "test_")
   ((member project-type '(emacs-cask)) "test-")
   ((member project-type '(lein-midje)) "t_")))
```

It seems not scale well. Also users sometimes get "project type not supported" when try jumping to test files even if the project type is (partially) supported, which is a bit confusing.

**Comment by bbatsov** [comment]
Yes, this has to be done for sure. I was pretty busy (and I still am) and I didn't finish the dynamic registration. Obviously test stuff should be part of it, and not be hardcoded as it is right now. That's rather trivial, but I can't promise you when I'll have time to fix it.

**Comment by yarray** [comment]
Thanks for your reply. I am glad that the feature is on your road map. I will try to improve this part and make a pull request, but it may take some time since I am still new to emacs lisp.

**Comment by bbatsov** [comment]
Let me know if you need any help.

**Comment by Fuco1** [comment]
I might look at it because our project at work now uses some ridiculous structure and this is annoying me greatly :D  Good to see I'm not the only one.

**Comment by maksimr** [comment]
@bbatsov what about progress on this issue?

**Comment by cydparser** [comment]
Is anyone actively working on this? If not, I might take a stab at it, but I suspect that it will require decoupling the concept of project type from chosen test framework. I.e. detect the project type first, then detect the test framework. E.g. instead of having four possible project types for a ruby project, there should be only two project types  and two test types. The test type should affect how _projectile-create-test-file-for_ behaves as well.

**Comment by bbatsov** [comment]
To my knowledge no one is working on this, so we could definitely use a volunteer. :-)
