### ISSUE TITLE
Keybinding Prefix

### ISSUE THREAD

**Issue by xin-jin** [bbatsov/projectile#948]
Could you add the ability to change keybinding prefix, so that I can change bindings like `C-c p I` to `C-. p l` for instance.

[helm-gtags](https://github.com/syohex/emacs-helm-gtags) has this kind of feature with `helm-gtags-prefix-key`.

Thanks!

**Comment by bbatsov** [comment]
Search for `projectile-keymap-prefix` in the readme.
