### ISSUE TITLE
Allow editing projectile-known-projects

### ISSUE THREAD

**Issue by Wilfred** [bbatsov/projectile#950]
I use `projectile-switch-project` heavily, but it eventually accumulates test copies of projects that I don't want to reuse.

Poking through the code, I can there's `projectile-ignored-projects` and `projectile-ignored-project-function`. These only seem to apply before a project is added to `projectile-known-projects`.

However, I can't see any interactive way of saying 'forget about project foo_copy'. Ideally projectile would offer something similar to `recentf-edit-list` for interactive removal of old projects from `projectile-known-projects`.

Have I missed some clever way of doing this? Would you be interested in such a feature?

**Comment by bbatsov** [comment]
> Have I missed some clever way of doing this? Would you be interested in such a feature?

Yeah, that'd be nice to have. PR welcome! :-)

**Comment by sandor-juhasz** [comment]
I also agree that a feature similar to `recentf-edit-list` would be useful. I played with `widget.el` this weekend, I think I can port the feature to Projectile fairly easily. I should have some time in the upcoming week to code the feature.
