### ISSUE TITLE
helm-projectile-grep does not respect ignored entries in .projectile file

### ISSUE THREAD

**Issue by daudelin** [bbatsov/projectile#959]
I apologize if this is a duplicate.

**Environment:**
OS: OS X Yosemite 10.10.5
Emacs: 24.5.1
projectile: 20160130.457
helm-projectile: 20151220.221

I am using vanilla [Prelude](https://github.com/bbatsov/prelude) to configure projectile and helm-projectile.

**Setup:**

1. Create a project compatible with projectile
2. Create a `.projectile` file and add an entry to be ignored
3. Create a file that should be ignored by the entry created in step 2 with some content
4. Use `helm-projectile-grep` to search for the content in the file created by step 3

**Expected Result:**
The file should not show in the `helm-projectile-grep` results

**Actual Result:**
The file is shown.

**Comments:**
I am finding that `helm-projectile-grep` does not respect ignored directories or files in my `.projectile` file. Oddly enough, `projectile-grep` does seem to respect them. I created a simple projectile project to test this, see screenshot:
![emacs_prelude_-___minibuf-1_](https://cloud.githubusercontent.com/assets/7882033/12795263/f3403d60-ca6d-11e5-8eef-e88341abc6f5.png)

`file-to-be-ignored.txt` is inside of the `/ignore-dir` and `file-to-be-shown.txt` is inside of the `src` dir. The buffer in the lower left shows the results of `helm-projectile-grep` and the lower right buffer shows the results of `projectile-grep` which correctly ignore the file.

**Comment by gdanov** [comment]
hi, I can't give you pointers, but my memory is that the original grep coming with os X does not support the ignore flag, so you have to install "real" grep via brew and symlink to it so that emacs can use it

**Comment by bbatsov** [comment]
This should be reported to https://github.com/bbatsov/helm-projectile

**Comment by haroldcarr** [comment]
search that respects ignored dirs/files:

1. install `ack` (An alternative to grep.  I install via homebrew.)

2. put `--ignore-case` in your `~.ackrc` file (assuming you want to ignore case)

3. bind `helm-projectile-ack` to a key.  I do this in my emacs init via:

```
(use-package helm
  ...
  :bind (...
         ("C-c p s a" . helm-projectile-ack)
        )
  ...
)
```

4. create a `.projectile` file.  E.g.,

```
-.dot
-.jcs
-.svg
-.txt
```

use

    C-c p s a     ;; search that respects .projectile ignore

or

    C-c s p g     ;; search everything

**Comment by rileyrg** [comment]
Doesn't work today. Being able to include directories that are NOT in git is really really important.
