### ISSUE TITLE
Elisp projectile-project-compiliation-cmd

### ISSUE THREAD

**Issue by justmytwospence** [bbatsov/projectile#960]
The README says I should be able to set projectile-project-compilation-cmd to an elisp function in .dir-locals.el, but when I do, I get

```
Wrong type argument: stringp, (function ensime-sbt-do-compile)
```

when I run projectile-compile-project.

Here is my .dir-locals.el:

```
((nil . ((projectile-project-compilation-cmd . #'ensime-sbt-do-compile)
         (projectile-project-run-cmd . "sbt package && scp core/target/foo-0.1.jar baz:~/spark-bin"))))
```

**Comment by syohex** [comment]
Did you call `M-x ensime` before using this command ?

**Comment by justmytwospence** [comment]
yes

**Comment by syohex** [comment]
Please retry after removing hash-mark(`#'`). `#'ensime-sbt-do-compile` is expanded to `(quote (function ensime-sbt-do-compile))`.

**Comment by justmytwospence** [comment]
Slightly different error now:

```
Wrong type argument: stringp, ensime-sbt-do-compile
```

**Comment by syohex** [comment]
Could you check whether `M-x ensime-sbt-do-compile` is successful ? If you get error, I suppose your environment is wrong.

**Comment by justmytwospence** [comment]
ensime-sbt-do-compile works by itself.

**Comment by syohex** [comment]
Could you check value of `(functionp 'ensime-sbt-do-compile)` when you fail calling `projectile-compile-project` ?  That is code of [here](https://github.com/bbatsov/projectile/blob/f39d7492ffffa5b61ec54a30845928c971593618/projectile.el#L2260)

**Comment by justmytwospence** [comment]
Uninstalling and reinstalling projectile seems to have fixed whatever wasn't working; sorry for the false alarm.
