### ISSUE TITLE
Adding directory to projectile-ignored-projects does not have desired effect

### ISSUE THREAD

**Issue by Spauldo** [bbatsov/projectile#962]
I'm a student, and I keep all my classwork in one directory tree.  I use git to synchronize it between three machines.

Inside this directory tree I have multiple unrelated source trees, along with a lot of files that aren't code at all.

I added this directory to projectile-ignored-projects (via customization), ran the command projectile-remove-current-project-from-known-projects, and invalidated the cache via the menu.  It doesn't seem to do any good; if I visit a file inside there, go to 'tools->projectile->project info' it tells me I'm using the project I've been trying to ignore.

I've tried both with and without the ending slash on the directory.  The variable is being set according to C-h v.  Am I misunderstanding the purpose of this variable?  My eventual goal is to use .projectile files to mark each separate project in the tree.

I'm using emacs 24.5.1 on Kubuntu 15.10 and projectile 0.13.0 (installed via el-get about a week or two ago).  The only projectile-related commands in my init, other than customizing that one variable, are (require 'projectile) and (projectile-global-mode).

**Comment by karljs** [comment]
I am having the same problem in trying to ignore `.cabal-sandbox` directories when working in Haskell.  I have not been able to find a setting in the corresponding `.projectile` that actually works.

**Comment by bbatsov** [comment]
Ignored project won't be added to the list of known projects, but will still be treated as project while your interacting with files belonging to them.

**Comment by Spauldo** [comment]
Any way to get it to not see that directory as a project?  That's what I'm actually trying to accomplish.

**Comment by ChoppinBlockParty** [comment]
I see this discussion is quite old, thought I have just hit a practical issue related to this behavior. Please, see [the issue mentioned above](https://github.com/ericdanan/counsel-projectile/issues/105). Could you suggest any solution to this problem? The question is basically how to block projectile from considering a particular directory to be a project? Or (may be even better) how to tell projectile that a specific file/directory path (to Makefile, yarn.lock, .git, etc.), that hints this directory to be a project directory, being blocked?
