### ISSUE TITLE
Feature request: List of projects

### ISSUE THREAD

**Issue by chris-martin** [bbatsov/projectile#967]
I'd like to replace the Emacs welcome screen (the `initial-buffer-choice` setting) with something lists recently-used projects.

For illustration of the concept, this is what the IntelliJ splash screen looks like:

![idea](https://cloud.githubusercontent.com/assets/399718/13101860/bd41191e-d4fe-11e5-9c50-f42e643766fa.png)

All the stuff on the right can be ignored - the crux is just the project list.

**Comment by dougm** [comment]
I had started on something similar but abandoned it (my .emacs.d repo is dead since I switched to prelude a while back).  In my case, I wanted to get a list of projects that hadn't pushed all git changes: https://github.com/dougm/.emacs.d/blob/master/custom/git.el#L81
Maybe this could be a starting point for you.  A more generic project list with links could be done for example:

```lisp
(defun projectile-project-list ()
  "List all projectile projects."
  (interactive)
  (let (project)
    (with-current-buffer (get-buffer-create "*projectile-project-list*")
      (setq buffer-read-only nil)
      (erase-buffer)
      (dolist (project (projectile-relevant-known-projects))
        (let ((default-directory (expand-file-name project)))
          (when (file-exists-p default-directory)
            (lexical-let ((name project))
              (insert-text-button name
                                  'action (lambda (button)
                                            (projectile-switch-project-by-name name))
                                  'follow-link t))
            (insert "\n\n"))))
      (let ((w (display-buffer (current-buffer))))
        (balance-windows)
        (shrink-window-if-larger-than-buffer w)
        (set-window-point w (point-min)))
      (setq buffer-read-only t))))
```

**Comment by dougm** [comment]
Actually, I suggest ignoring this old hack.  It would probably be much cleaner and useful to implement such a feature using tabulated-list-mode.

**Comment by chris-martin** [comment]
I just discovered helm-projectile - `helm-projectile-switch-project` is pretty close to what I'm after.

**Comment by a13ph** [comment]
Spacemacs does something of sorts in it's home (starting) buffer

![](http://spacemacs.org/img/screenshots/ss1.png)

In the bottom left corner of the screenshot you can see part of it

Code for it is there: https://github.com/syl20bnr/spacemacs/blob/master/core/core-spacemacs-buffer.el#L550
