### ISSUE TITLE
Feature request: toggle-project-read-only

### ISSUE THREAD

**Issue by xin-jin** [bbatsov/projectile#972]
Hi,

`ggtags` has a very handy feature `ggtags-toggle-project-read-only` (but I don't use `ggtags`). Could you add it to projectile? 

Thanks!

**Comment by bbatsov** [comment]
What does it do?

**Comment by xin-jin** [comment]
As the name suggests, it basically toggles between
```
((nil
  (buffer-read-only . t)))
```

and 

```
((nil
  (buffer-read-only)))
```

in `.dir-locals.el` in the project root.

**Comment by xin-jin** [comment]
It also makes all current buffers associated with files of the project read-only. Not sure how it is done. I am not familiar with elisp.

**Comment by Qquanwei** [comment]
I need too, when I reading git project source code without modify it.
