### ISSUE TITLE
[request] Add heuristic for projectile-find-matching-test

### ISSUE THREAD

**Issue by Fuco1** [bbatsov/projectile#982]
My project has 48554 files.  The function `projectile-find-matching-test` calls `(projectile-current-project-files)` internally which I let run forever and it never finished.

Most of the time, tests follow some conventions, like:
- same structure as the project is replicated in `./test`
- tests are right next to the files
- all tests are thrown into `test` directory
- ...

I'm not sure yet how this would work, probably on a per-project basis.

I know this probably isn't typical use and I'm happy to hack my own one-time solution.  Has anyone ever had similar problems with performance?

**Comment by bbatsov** [comment]
I think the simple solution for this is to register custom test-finding functions for the different project types. The current solution is a bit messy mostly because it aims to be generic. There's certainly a lot of room for improvement.

**Comment by Fuco1** [comment]
During the years I've created this package https://github.com/Fuco1/find-test It has some configuration but generic enough that it worked fine on all projects I've been working on (php, js, elisp...).

Maybe it could be integrated somehow.  It's a small package so it can even be rewritten in a better way.

Custom functions are a good solution and very flexible, but some sort of pre-built "common cases" would definitely give better UX.

**Comment by bbatsov** [comment]
@Fuco1 No arguments from me. PRs welcome! :-)

**Comment by bbatsov** [comment]
Btw, a bit part of the reason for the current design of Projectile is that I normally use in pretty homogenous projects (e.g. a Rails app, some Clojure library, etc) and there usually the mapping between the source and the tests is crystal clear. I just didn't think of any other usecases, because they weren't common in my day-to-day work. :-)
