### ISSUE TITLE
Find other file doesn't find a file with multiple matches

### ISSUE THREAD

**Issue by dmh43** [bbatsov/projectile#985]
## Expected behavior

When in a project containing three files in the same directory, each with the same name but different extentions, I run `projectile-find-other-file` (or the helm version) and expect to see a list of the files with the same name.
## Actual behavior

Instead I get 'No other file found' as a notification in the minibuffer
## Steps to reproduce the problem
1. Create a projectile project
2. Inside a folder create three files: "hello.ts", "hello.jade" and "hello.styl"
3. Run `projectile-find-other-file`
## Environment & Version information

Prelude
### Projectile version information

```
Projectile version:  20160228.8
```
### Emacs version

24.5.1
### Operating system

Mac OS X 10.11.3

**Comment by edoloughlin** [comment]
Any movement on this? It makes navigating in Angulat2+ projects cumbersome because there are can be up to 3 matches for any particular file.

**Comment by bbatsov** [comment]
Is this the same as https://github.com/bbatsov/projectile/pull/1284?

**Comment by dmh43** [comment]
Yup this looks like the same issue
