### ISSUE TITLE
Change Directory

### ISSUE THREAD

**Issue by nickenchev** [bbatsov/projectile#986]
Hey, can you please add a shortcut to CD into a project's root folder. I'm currently using CTRL-C P P to switch projects, but I'm always forced to pick a file in the root, when I only want to CD.

### Projectile version information
20160320.2

### Emacs version
24.5.1

### Operating system
OS X 10.10.5

**Comment by bbatsov** [comment]
Have you read this section of the README - https://github.com/bbatsov/projectile#switching-projects ?

Basically you can set whatever action you want to be executed after switching to a project.

**Comment by nickenchev** [comment]
Hadn't seen been that, thanks! Looks like this will take care of my need.

**Comment by nickenchev** [comment]
My first instinct was to try doing something like:
(setq projectile-switch-project-action 'cd)

But that complains that I'm passing the wrong number of arguments. So projectile doesn't call the action and pass the project directory. What can I use to retrieve the project root path after selecting it with projectile?

**Comment by lepieru** [comment]
What you want seems to be this:

```elisp
(setq projectile-switch-project-action
      (lambda ()
        (message "Switching to: %s" (projectile-project-root))
        (projectile-switch-project-by-name (projectile-project-root))))
```

However, it will change the project of the current buffer! Projectile is not design to be used like this.

May dired is a good choice for a project root buffer, so this is an alternative:

```elisp
(setq projectile-switch-project-action 'projectile-dired)
```

**Comment by bbatsov** [comment]
I'd suggest simply invoking `projectile-dired` after `C-u C-c p p`. As mentioned before, doing `cd` will change the `default-directory` of the current buffer, which is definitely not desirable.
