### ISSUE TITLE
projectile-ag ignores ag-ignore-list when projectile-project-vcs is git

### ISSUE THREAD

**Issue by squid-lee** [bbatsov/projectile#987]
## Expected behavior

`M-x projectile-ag query` ignores files that match ag-ignore-list
## Actual behavior

When the vcs for the project is git, `M-x projectile-ag query` ignores the ag-ignore-list
## Steps to reproduce the problem

```
mkdir /tmp/foo
cd /tmp/foo
git init
echo waffle > waffle
echo waffle > waffle.min.js
```

in emacs - go /tmp/foo; eval (setq ag-ignore-list "*.min.js"); run projectile-ag waffle
get two results, one of which is waffle.min.js. 

to contrast

```
mkdir /tmp/bar
cd /tmp/bar
hg init
echo waffle > waffle
echo waffle > waffle.min.js
```

here, opening /tmp/bar, with the same ag-ignore-list "*.min.js"
only has one result
## Environment & Version information

Projectile version: 20160321.2307
GNU Emacs 25.1.50.2 (x86_64-pc-linux-gnu, GTK+ Version 3.10.8) of 2016-03-13
## Suggested fix

The problem is in projectile-ag
`ag-ignore-list` is let-bound to nil by `(unless (eq (projectile-project-vcs) 'git)`, which is the problem.
Instead, in the function `projectile-ag` in `projectile.el`  (~ line 1970)

```
(let (ag-ignore-list (unless (eq (projectile-project-vcs) 'git)
                              ;; ag supports git ignore files
                              (-union ag-ignore-list
                                      (append
                                       (projectile-ignored-files-rel) (projectile-ignored-directories-rel)
                                       (projectile--globally-ignored-file-suffixes-glob)
                                       grep-find-ignored-files grep-find-ignored-directories)))))
```

should probably be something like

```
(ag-ignore-list      (-union ag-ignore-list
                                      (append
                                       (projectile-get-ignored-vcs-files-if-such-a-thing-exists)
                                       (projectile-ignored-files-rel) (projectile-ignored-directories-rel)
                                       (projectile--globally-ignored-file-suffixes-glob)
                                       grep-find-ignored-files grep-find-ignored-directories)))
```

**Comment by laz2** [comment]
From commit a200f12736904e30c8a0da8333c3a924f0e32585

> A benefit of this change is that the command output buffer is much
cleaner. A potential regression that that files the user is ignoring in
projectile, but not ignoring in git (corner case?), will be searched.

This is not corner case for all web developers. When someone have npm modules and bower components. This files under version control, but i don't want to see it in output result.

**Comment by fommil** [comment]
Why don't you put together a PR?

**Comment by laz2** [comment]
I can revert commit changes, but may be you can provide better solution (for you or for all).

**Comment by fommil** [comment]
well as long as you can provide me with a mechanism to fall back to the "just use git" behaviour. On one of my projects, the full ignore list can be tens of thousands of lines long and even printing that can cause Emacs to hang, nevermind the fact that it is just noise.

**Comment by Fykec** [comment]
projectile-grep and projectile-grep is ok， but the projectile-ag cannot work with the ignore rules.

**Comment by ReneFroger** [comment]
Any update on this?

**Comment by fommil** [comment]
@ReneFroger I think we're waiting for somebody to submit a PR that adds the user's ignore list to `projectile` if it is defined (in addition to letting `ag` use its standard behaviour for git repos without printing this to the screen).

**Comment by ReneFroger** [comment]
@fommil clear enough.

I'm not sure if my issue is related to this issue. I have `foobar.txt` in my `.agingore` file, but I see it back in my `helm-projectile-ag` window when I'm calling that function inside my project. I don't use VCS in my project directory, only a `.projectile` file is created.

**Comment by fommil** [comment]
this is really annoying me because somebody added lots of `.js` files to my repo. I'll put together a PR that does this:

- if we're in git, preserve `ag-ignore-list`, `projectile-ignored-files-rel`, `projectile-ignored-directories-rel`, projectile--globally-ignored-file-suffixes-glob`, 
- if we're not in git, preserve the above but also add `grep-find-ignored-files` `grep-find-ignored-directories` (which are better handled directly by `ag` if we're in a git repo)

**Comment by fommil** [comment]
@squid-lee @laz2 @Fykec @ReneFroger please comment on the proposed PR with a fix.

I'm using stable projectile locally and overriding this function with this slightly different version.

```lisp
(setq ag-ignore-list '("*.js"))

(defun projectile-ag (search-term &optional arg)
  "Run an ag search with SEARCH-TERM in the project.

With an optional prefix argument ARG SEARCH-TERM is interpreted as a
regular expression."
  (interactive
   (list (read-from-minibuffer
          (projectile-prepend-project-name (format "Ag %ssearch for: " (if current-prefix-arg "regexp " "")))
          (projectile-symbol-or-selection-at-point))
         current-prefix-arg))
  (if (require 'ag nil 'noerror)
      (let ((ag-command (if arg 'ag-regexp 'ag))
            (ag-ignore-list (cl-union ag-ignore-list
                                      (projectile--globally-ignored-file-suffixes-glob)
                                      ;; ag supports git ignore files directly
                                      (unless (eq (projectile-project-vcs) 'git)
                                        (append
                                         (projectile-ignored-files-rel)
                                         (projectile-ignored-directories-rel)
                                         grep-find-ignored-files
                                         grep-find-ignored-directories))))
            ;; reset the prefix arg, otherwise it will affect the ag-command
            (current-prefix-arg nil))
        (funcall ag-command search-term (projectile-project-root)))
    (error "Package 'ag' is not available")))
```

**Comment by ReneFroger** [comment]
Thanks for your reply, @fommil I will test it soon

I found another way to exclude JS files in projectile.  For example:
```

  (add-to-list 'projectile-globally-ignored-directories "*templates/cache")  
  (add-to-list 'projectile-globally-ignored-directories "templates/cache") 
  (add-to-list 'projectile-globally-ignored-directories "templates/cache/") 
  (add-to-list 'projectile-globally-ignored-directories "*templates/cache/")

  (add-to-list 'projectile-globally-ignored-files "*.js")
  (add-to-list 'projectile-globally-ignored-files "jquery.js")
  (add-to-list 'projectile-globally-ignored-files "*.min.js")
  (add-to-list 'projectile-globally-ignored-files "**.min.js")
  (add-to-list 'projectile-globally-ignored-files "*/**.min.js")
  (add-to-list 'projectile-globally-ignored-files "**/*.min.js")

```
And for those who use Projectile Ag in combination with Helm:

 

>  ;; Use agignore in home directory when filteirng results.
>   (setq helm-ag-command-option " -U" )
>

**Comment by fommil** [comment]
oh, of course. `~/.agignore`. I forgot all about that.

**Comment by fommil** [comment]
arguably `ag` shouldn't bother with `ag-ignore`... a redundant flag. At least my PR will make `ag` respect the projectile glob patterns.
