### ISSUE TITLE
strange behavior when I put `projectile-bookmarks.eld` in a different dir.

### ISSUE THREAD

**Issue by doctorate** [bbatsov/projectile#989]
_when `projectile-bookmarks.eld` is in `~/.emacs.d/` everything is fine. The strange behavior happens only when I set a different dir in my `.init.el` file like this:
`(setq projectile-known-projects-file "~/.emacs.d/misc/projectile-bookmarks.eld")`_
## Expected behavior

once I fire up emacs I press `C-c p p` and I get a list of my projects in helm buffer, when `projectile-bookmarks.eld` is in `~/.emacs.d/` folder (default).
## Actual behavior

once I fire up emacs I press `C-c p p` from the _scratch_ buffer and I get nothing, but once I visit any other buffer and then press  `C-c p p` it works like expected. This strange behavior happens only when I set a different directory for it in my `init.el` file:
`(setq projectile-known-projects-file "~/.emacs.d/misc/projectile-bookmarks.eld")`
once I comment this line, everything works like before.
### Projectile version information

```
Projectile version: 20160326.2220
```
### Emacs version

```
GNU Emacs 25.1.50.2 (x86_64-pc-linux-gnu, GTK+ Version 3.14.13) of 2015-12-02
```
### Operating system

```
Ubuntu 15.10 Linux
```

**Comment by geoffmacintosh** [comment]
I get exactly the same problem with
Projectile 20160526.832
Emacs 24.5.1
OS X 10.11.5

**Comment by bridgeofstraws** [comment]
In case anyone has a similar problem, I found for projectile you must set variables before (use-package projectile) or before (require 'projectile).  May or may not be directly related to the original poster's problem.

**Comment by bbatsov** [comment]
I think I just fixed this https://github.com/bbatsov/projectile/commit/f5863127c33f26013f885e182dacb64372f34114

The problem was before `(require 'projectile)` would have loaded the known projects, and I assume most people put their config after such a require.
