### ISSUE TITLE
projectile-keymap-prefix is not respected

### ISSUE THREAD

**Issue by anderspapitto** [bbatsov/projectile#991]
## Expected behavior

after setting projectile-keymap-prefix, that prefix now launches projectile commands and the default prefix no longer does.
## Actual behavior

setting projectile-keymap-prefix has no effect whatsoever.
## Steps to reproduce the problem

set projectile-keymap-prefix, either with `setq` as described in the README, or via customize. Currently I have the following like in my init.el, produced by customize

 '(projectile-keymap-prefix (kbd "M-p"))

I've also tried a couple other variants - `(kbd "C-c C-p")`, `"M-p"`, `"C-c C-p"`. None have any effect

This is what I see when I run `C-h v projectile-keymap-prefix`

```
projectile-keymap-prefix is a variable defined in `projectile.el'.
Its value is (kbd "M-p")
Original value was "p"

Documentation:
Projectile keymap prefix.

You can customize this variable.

[back]
```
## Environment & Version information

Projectile version: 0.13.0
GNU Emacs 24.5.2 (x86_64-unknown-linux-gnu, GTK+ Version 2.24.29)
### Operating system

Linux, distro is NixOS

**Comment by Denommus** [comment]
Same problem here.

**Comment by stunpix** [comment]
For me example from project's README also doesn't work, so after numerous attempts I'm using a workaround:

    (define-key projectile-mode-map (kbd "s-p") 'projectile-command-map)

And this does what `projectile-keymap-prefix` should do: now I can use Projectile like `s-p f` and `s-p s g`

**Comment by bbatsov** [comment]
> cc @bbatsov if my reasoning is correct, can you add a note to the docs which clears this issue?

Your reasoning is correct. Doc improvement PRs are always welcome. :-)

**Comment by IanQS** [comment]
I'm still facing problems with this even after the fix suggested above.

This is what I see when I run ```C-h v projectile-keymap-prefix```
```
projectile-keymap-prefix is a variable defined in ‘projectile.el’.
Its value is "C-c C-p"
Original value was "p"

Documentation:
Projectile keymap prefix.

You can customize this variable.
```
Everything in my init.el related to projectile

```
(require 'projectile)
(define-key projectile-mode-map projectile-keymap-prefix nil)
(define-key projectile-mode-map (kbd "C-c C-p") #'projectile-command-map)
(setq projectile-switch-project-action 'venv-projectile-auto-workon)

(require 'helm-projectile)
(helm-projectile-on)
```
