### ISSUE TITLE
global-projectile-mode breaks compilation-directory-matcher

### ISSUE THREAD

**Issue by bjackman** [bbatsov/projectile#994]
When `--print-directory` is in a `make` command for Emacs' `compile`, `compile`
should parse the "Make: Entering directory..." message, to know the location of
files to visit when the are clicked on in error messages.  Enabling
`global-projectile-mode` appears to break this behaviour. 

Steps to reproduce:

```
$ cat ~/.emacs
(require 'package)

(push '("melpa-stable" . "http://stable.melpa.org/packages/")
       package-archives)

(setq package-list '(projectile))
(package-initialize)

(unless package-archive-contents
  (package-refresh-contents))
(dolist (package package-list)
  (unless (package-installed-p package)
    (package-install package)))

(projectile-global-mode)
$ rm -rf ~/.emacs.d/
$ cat demo.sh 
mkdir /tmp/repro
mkdir /tmp/repro/a
mkdir /tmp/repro/b

cd /tmp/repro

cat << EOF >Makefile
all: a_target b_target

a_target:
    \$(MAKE) -C a file.o
b_target:
    \$(MAKE) -C b file.o

EOF

cat << EOF > a/file.c
int main() {
  if you like it and you know it, syntax error
}

EOF

cat << EOF >b/file.c
int main() {
  return 0;
}

EOF
$ ./demo.sh 
$ emacs /tmp/repro
```

(Note that the `$(MAKE)` lines in the `Makefile` must be indented with tabs,
I'm not sure if copying to/pasting from Github will clobber that. I guess y'all are familar with Make etc. but let me know if not and I'll explain what's going on in that script.)

... Then visit /tmp/repro and `M-x compile`, set the command to `make -wB`. The
compilation window will show the syntax error. When you click on `file.c`,
Emacs visits `b/file.c` instead of `a/file.c`. This behaviour goes away (i.e. it visits the file that produced the error) if you
remove `(projectile-global-mode)` from ~/.emacs.

Versions:
Emacs 24.4.2 
Ubuntu 15.10
Projectile: projectile-version shows 0.13.0. This is the version from melpa-stable.
  Have also repro'd withe the version from melpa (20160331.2219)

Thanks

**Comment by bjackman** [comment]
OK, I finally got some time to take a look at this, it took me a while because I haven't got my hands dirty with Emacs before. 

So, this is due to the `advice` wrapped around `compilation-find-file` , which AFAICT replaces the argument to `compilation-find-file` with the full path of the first file found in the Projectile project. Indeed when I remove that `advice`, the problem goes away. 

I *think* that the functionality provided by the `advice` can just be handled by setting `compilation-search-path` to hold the expansion of all of `(projectile-current-project-dirs)`, I'm going to try that. Please tell me if you know of a reason this won't work.

So, this is due to the `advice` wrapped around `compilation-find-file` , which AFAICT replaces the argument to `compilation-find-file` with the full path of the first file found in the Projectile project. Indeed when I remove that `advice`, the problem goes away. 

I *think* that the functionality provided by the `advice` can just be handled by setting `compilation-search-path` to hold the expansion of all of `(projectile-current-project-dirs)`, I'm going to try that. Please tell me if you know of a reason this won't work.

**Comment by bjackman** [comment]
Ugh, looks this is a duplicate of [#871](https://github.com/bbatsov/projectile/issues/871) (Not sure how I didn't spot that) which has apparently been fixed.. I'm going to leave this open for the moment until I can investigate why it

**Comment by bjackman** [comment]
OK [here](https://github.com/bjackman/projectile/commit/5326fe0f2305fb622a089ac8032df13d45f1d7d3)'s a fix.. but like I said I have a feeling there's gotta be something else broken by removing the advice, any thoughts? If not I'll just submit a PR I guess.

**Comment by bjackman** [comment]
(Sorry, not sure how I closed the issue, I can't Github)

**Comment by bjackman** [comment]
Turns out my solution above indeed doesn't work, will get back in here when I have some time to come up with a better one.

**Comment by anderspapitto** [comment]
I've hit this as well

**Comment by anderspapitto** [comment]
for now I'm trying to work around it with


(ad-deactivate 'compilation-find-file)
