### ISSUE TITLE
not found error in melpa

### ISSUE THREAD

**Issue by futurist** [bbatsov/projectile#998]
## Expected behavior
Install projectile by M-x package-install RET projectile

## Actual behavior

*Backtrace* as below

Debugger entered--Lisp error: (file-error "https://melpa.org/packages/projectile-20160326.2220.el" "Not found")
  signal(file-error ("https://melpa.org/packages/projectile-20160326.2220.el" "Not found"))

### Emacs version

24.5

### Operating system

Windows XP 32bit

**Comment by syohex** [comment]
Your package archive file is too old. Please update it by `M-x package-refresh-contents`

**Comment by futurist** [comment]
solved the problem. thank you very much
