### ISSUE TITLE
test command with emacs function

### ISSUE THREAD

**Issue by futurist** [bbatsov/projectile#999]
## Expected behavior

Test html5 project in browser

## Actual behavior

Cannot specify in .dir-locals.el file

## Steps to reproduce the problem

Below is my .dir-locals.el file:
````
((nil . ((projectile-project-test-cmd . (browse-url-of-file "http://my-url.com/index.html"))
         )))
````

The project contains js/css files, and once I've make to some file and want to open test url in browser, using `C-c p t`,  message is:
````
projectile-find-implementation-or-test: No matching test file found
````

## Environment & Version information

Web project

### Projectile version information

```
Projectile version: 20160404.2251

```

### Emacs version

24.5

### Operating system

Windows XP 32bit

**Comment by bbatsov** [comment]
Two things:

1. The test command has to be a lambda in your case.
2. The proper keybinding for `projectile-test-project` is `C-c p P`.
